import {test} from 'node:test';
import assert from 'node:assert/strict';
import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import {PGlite} from '@electric-sql/pglite';
import {migrateCore} from '../src/migrate.js';
import {prepareKnowledgeBase,installKnowledgeBase} from '../src/knowledge-base.js';

test('knowledge base is role-safe, versioned and linked to real diagnostics',async()=>{
 const db=await PGlite.create(),query=(sql,p=[])=>p.length?db.query(sql,p):db.exec(sql).then(r=>r.at(-1));let chain=Promise.resolve();const pool={query,connect:async()=>{const before=chain;let release;chain=new Promise(r=>release=r);await before;return{query,release}},end:async()=>{}};await migrateCore(pool);
 await query(`CREATE TABLE IF NOT EXISTS request_diagnostics(id SERIAL PRIMARY KEY,request_id INT UNIQUE REFERENCES requests(id) ON DELETE CASCADE,symptoms TEXT,diagnosis TEXT,recommendation TEXT,engineer_id INT REFERENCES users(id),updated_at TIMESTAMPTZ DEFAULT now())`);await prepareKnowledgeBase(pool);
 const branch=(await query("SELECT id FROM branches WHERE code='KST'")).rows[0].id;await query("INSERT INTO users(name,email,password_hash,role,primary_branch_id) VALUES('KB Owner','kb-owner@test','x','OWNER',$1),('KB Supervisor','kb-supervisor@test','x','SUPERVISOR',$1),('KB Manager','kb-manager@test','x','MANAGER',$1),('KB Engineer','kb-engineer@test','x','ENGINEER',$1),('KB Trainee','kb-trainee@test','x','TRAINEE',$1),('KB Accountant','kb-accountant@test','x','ACCOUNTANT',$1)",[branch]);const users=(await query("SELECT id,email FROM users WHERE email LIKE 'kb-%@test'" )).rows,uid=email=>Number(users.find(x=>x.email===email).id),owner=uid('kb-owner@test'),sup=uid('kb-supervisor@test'),mgr=uid('kb-manager@test'),eng=uid('kb-engineer@test'),acc=uid('kb-accountant@test');
 await query("INSERT INTO customers(name,phone) VALUES('Knowledge Client','77000000991')");const customer=(await query("SELECT id FROM customers WHERE phone='77000000991'")).rows[0].id;await query("INSERT INTO equipment(customer_id,category,brand,model,serial_number) VALUES($1,'Посудомоечная машина','Abat','МПТ-2000Л','KB-SN')",[customer]);const equipment=(await query("SELECT id FROM equipment WHERE serial_number='KB-SN'")).rows[0].id;const request=(await query("INSERT INTO requests(number,customer_id,equipment_id,manager_id,engineer_id,branch_id,status,complaint) VALUES('KB-T1',$1,$2,$3,$4,$5,'DIAGNOSTICS','Горит остановка конвейера, ошибка H21') RETURNING id",[customer,equipment,mgr,eng,branch])).rows[0].id;await query("INSERT INTO request_diagnostics(request_id,symptoms,diagnosis,recommendation,engineer_id) VALUES($1,'Остановка конвейера, код H21','','',$2)",[request,eng]);
 const app=Fastify({logger:false});await app.register(jwt,{secret:'k'.repeat(64)});installKnowledgeBase(app,pool);await app.ready();const token=role=>app.jwt.sign({id:role==='OWNER'?owner:role==='SUPERVISOR'?sup:role==='MANAGER'?mgr:role==='ENGINEER'?eng:acc,role}),call=async(method,url,payload,t=token('OWNER'))=>{const r=await app.inject({method,url,payload,headers:{authorization:'Bearer '+t}});return{status:r.statusCode,...r.json()}};
 let r=await call('POST','/api/v1/articles',{title:'Abat МПТ-2000Л — H21, остановка конвейера',category:'Посудомоечная машина',brand:'Abat',model:'МПТ-2000Л',error_code:'H21',tags:'конвейер, привод, датчик',symptoms:'Конвейер остановлен, на панели H21',cause:'Нет подтверждения движения конвейера или сработала защита привода',solution:'Проверить механическое заклинивание, цепь привода, мотор-редуктор и цепь контроля движения. После устранения причины сбросить аварию.',verification:'Запустить конвейер без посуды и проверить стабильное движение не менее 3 минут.',safety_notes:'Перед механической проверкой обесточить машину.'});assert.equal(r.status,201);const article=r.data;assert.equal(article.status,'DRAFT');assert.equal(article.version,1);
 r=await call('GET','/api/v1/articles',undefined,token('ENGINEER'));assert.equal(r.status,200);assert.equal(r.data.length,0);assert.equal((await call('GET','/api/v1/articles',undefined,token('ACCOUNTANT'))).status,403);assert.equal((await call('POST','/api/v1/articles',{title:'Forbidden',solution:'x'},token('ENGINEER'))).status,403);
 r=await call('POST',`/api/v1/articles/${article.id}/publish`,{},token('SUPERVISOR'));assert.equal(r.status,200);assert.equal(r.data.status,'PUBLISHED');assert.equal(r.data.version,2);
 r=await call('PATCH',`/api/v1/articles/${article.id}`,{verification:'После ремонта выполнить 5 минут холостого прогона конвейера.'});assert.equal(r.status,200);assert.equal(r.data.version,3);
 r=await call('GET',`/api/v1/suggest?request_id=${request}&q=${encodeURIComponent('H21 конвейер')}`,undefined,token('ENGINEER'));assert.equal(r.status,200);assert.ok(r.data.articles.length>=1);assert.equal(Number(r.data.articles[0].id),Number(article.id));assert.ok(Number(r.data.articles[0].match_score)>40);const shown=r.data.articles[0];assert.equal(Number(shown.version),3);
 r=await call('PATCH',`/api/v1/articles/${article.id}`,{solution:'Новая редакция решения после того, как инженер уже открыл подсказку.'});assert.equal(r.status,200);assert.equal(r.data.version,4);
 r=await call('POST',`/api/v1/articles/${article.id}/use`,{request_id:request,action:'APPLIED',article_version:shown.version},token('ENGINEER'));assert.equal(r.status,201);assert.equal(r.data.version,3);assert.ok(String(r.data.article?.solution||'').includes('мотор-редуктор'));assert.ok(!String(r.data.article?.solution||'').includes('Новая редакция'));assert.equal(Number((await query("SELECT article_version FROM knowledge_use_events WHERE request_id=$1 AND action='APPLIED' ORDER BY id DESC LIMIT 1",[request])).rows[0].article_version),3);const history=(await query("SELECT details FROM request_history WHERE request_id=$1 AND action='KNOWLEDGE_APPLIED' ORDER BY id DESC LIMIT 1",[request])).rows[0];assert.equal(Number(history.details.article_version),3);
 r=await call('POST',`/api/v1/articles/${article.id}/feedback`,{request_id:request,helpful:true,note:'Подтвердилось по приводу'},token('ENGINEER'));assert.equal(r.status,200);assert.equal(Number(r.data.helpful_count),1);r=await call('GET','/api/v1/articles',undefined,token('MANAGER'));assert.equal(r.status,200);assert.equal(r.data.length,1);
 r=await call('GET',`/api/v1/articles/${article.id}/versions`,undefined,token('OWNER'));assert.equal(r.status,200);assert.equal(r.data.length,4);const versionId=r.data[0].id;await assert.rejects(()=>query("UPDATE knowledge_article_versions SET version=99 WHERE id=$1",[versionId]));
 r=await call('POST',`/api/v1/articles/${article.id}/archive`,{},token('OWNER'));assert.equal(r.status,200);assert.equal(r.data.status,'ARCHIVED');assert.equal(r.data.version,5);assert.equal((await call('GET',`/api/v1/articles/${article.id}`,undefined,token('ENGINEER'))).status,404);assert.equal((await call('GET',`/api/v1/suggest?request_id=${request}&q=H21`,undefined,token('ENGINEER'))).data.articles.length,0);
 await app.close();await db.close();
});
