import {test} from 'node:test';
import assert from 'node:assert/strict';
import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import {PGlite} from '@electric-sql/pglite';
import {migrateCore} from '../src/migrate.js';
import {authenticate} from '../src/access.js';
import {roleAllowed} from '../src/rbac.js';
import {installServiceContracts} from '../src/service-contracts.js';
const dateOnly=v=>v instanceof Date?v.toISOString().slice(0,10):String(v||'').slice(0,10);

test('service contract creates reminders, respects branches and advances only after closed maintenance order',async()=>{
 const db=await PGlite.create(),query=(sql,p=[])=>p.length?db.query(sql,p):db.exec(sql).then(r=>r.at(-1));let chain=Promise.resolve();
 const pool={query,connect:async()=>{const before=chain;let release;chain=new Promise(r=>release=r);await before;return{query,release}},end:async()=>{}};await migrateCore(pool);
 await query("INSERT INTO users(name,email,password_hash,role) VALUES('Owner','owner@sc.test','x','OWNER'),('Supervisor','supervisor@sc.test','x','SUPERVISOR'),('Manager','manager@sc.test','x','MANAGER'),('Engineer','engineer@sc.test','x','ENGINEER'),('Other Manager','other@sc.test','x','MANAGER')");
 const kst=(await query("SELECT id FROM branches WHERE code='KST'")).rows[0].id;await query("INSERT INTO branches(code,name,address) VALUES('ALT','Другой филиал','Другой адрес')");const alt=(await query("SELECT id FROM branches WHERE code='ALT'")).rows[0].id;
 await query('UPDATE users SET primary_branch_id=$1 WHERE id=5',[alt]);await query('DELETE FROM user_branches WHERE user_id=5 AND branch_id<>$1',[alt]);
 await query("INSERT INTO customers(name,phone) VALUES('Contract Client','77000000202')");await query("INSERT INTO equipment(customer_id,category,brand,model,serial_number) VALUES(1,'Кондиционер','Daikin','FTX','SN-1')");
 const app=Fastify({logger:false});await app.register(jwt,{secret:'z'.repeat(64)});const auth=async(req,reply)=>{if(!await authenticate(req,reply,pool))return},roles=(...allowed)=>async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!roleAllowed(req.user.role,allowed))return reply.code(403).send({data:null,error:{code:'FORBIDDEN',message:'Недостаточно прав'}})};
 const messages=[],enqueue=async x=>{if(messages.some(m=>m.dedupe_key===x.dedupe_key))return null;const m={id:messages.length+1,status:'QUEUED',...x};messages.push(m);return m};const flow=await installServiceContracts(app,pool,{enqueue,roles});await app.ready();
 const tokens={owner:app.jwt.sign({id:1,role:'OWNER'}),manager:app.jwt.sign({id:3,role:'MANAGER'}),other:app.jwt.sign({id:5,role:'MANAGER'})};const call=async(method,url,payload,token)=>{const r=await app.inject({method,url,payload,headers:{authorization:'Bearer '+token}});return{status:r.statusCode,...r.json()}};
 const today=new Date().toISOString().slice(0,10);let r=await call('POST','/api/v1/service-contracts',{customer_id:1,branch_id:kst,responsible_id:2,start_date:today,reminder_days_before:7,assets:[{equipment_id:1,interval_months:6,next_service_date:today,service_note:'Чистка и проверка'}]},tokens.owner);assert.equal(r.status,201);const contractId=r.data.id;assert.match(r.data.number,/^SC-\d{4}-\d{5}$/);
 r=await call('POST','/api/v1/service-contracts/sync',{},tokens.manager);assert.equal(r.status,200);assert.equal(r.data.cycles,1);assert.equal(messages.length,1);assert.match(messages[0].body,/плановое техническое обслуживание/i);
 const cycle=(await query('SELECT * FROM service_maintenance_cycles ORDER BY id LIMIT 1')).rows[0];assert.ok(cycle.task_id);const task=(await query('SELECT * FROM tasks WHERE id=$1',[cycle.task_id])).rows[0];assert.equal(Number(task.assigned_to),2);assert.equal(task.status,'OPEN');
 r=await call('GET','/api/v1/service-contracts/'+contractId,undefined,tokens.manager);assert.equal(r.status,200);assert.equal(r.data.assets.length,1);r=await call('GET','/api/v1/service-contracts/'+contractId,undefined,tokens.other);assert.equal(r.status,403);
 const order=(await query("INSERT INTO requests(number,customer_id,equipment_id,manager_id,branch_id,status,complaint) VALUES('SC-ORDER-1',1,1,3,$1,'NEW','Плановое ТО') RETURNING id",[kst])).rows[0];r=await call('POST',`/api/v1/service-contracts/cycles/${cycle.id}/plan`,{request_id:order.id},tokens.manager);assert.equal(r.status,200);assert.equal(r.data.status,'PLANNED');
 r=await call('POST',`/api/v1/service-contracts/cycles/${cycle.id}/complete`,{note:'Выполнено'},tokens.manager);assert.equal(r.status,409);await query("UPDATE requests SET status='CLOSED',closed_at=now() WHERE id=$1",[order.id]);r=await call('POST',`/api/v1/service-contracts/cycles/${cycle.id}/complete`,{note:'Выполнено по регламенту'},tokens.manager);assert.equal(r.status,200,r.error?.message||JSON.stringify(r));assert.equal(r.data.status,'COMPLETED');assert.notEqual(r.data.next_service_date,today);
 const asset=(await query('SELECT * FROM service_contract_assets WHERE contract_id=$1',[contractId])).rows[0];assert.equal(dateOnly(asset.last_service_date),today);assert.equal(Number((await query("SELECT count(*) c FROM service_maintenance_cycles WHERE contract_asset_id=$1 AND status='DUE'",[asset.id])).rows[0].c),1);assert.equal((await query('SELECT status FROM tasks WHERE id=$1',[cycle.task_id])).rows[0].status,'DONE');
 const actions=(await query('SELECT action FROM service_contract_audit WHERE contract_id=$1 ORDER BY id',[contractId])).rows.map(x=>x.action);assert.equal(actions.includes('CONTRACT_CREATED'),true);assert.equal(actions.includes('MAINTENANCE_REMINDER_CREATED'),true);assert.equal(actions.includes('MAINTENANCE_PLANNED'),true);assert.equal(actions.includes('MAINTENANCE_COMPLETED'),true);
 const summary=await call('GET','/api/v1/service-contracts/summary',undefined,tokens.owner);assert.equal(summary.status,200);assert.equal(summary.data.active_contracts,1);
 await flow.ensureCycles();await app.close();await db.close();
});
