import {test} from 'node:test';
import assert from 'node:assert/strict';
import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import {PGlite} from '@electric-sql/pglite';
import {migrateCore} from '../src/migrate.js';
import {prepareSupplierCatalog,installSupplierCatalog} from '../src/supplier-catalog.js';
import {parseSupplierFile,detectMapping,normalizeSupplierRows} from '../src/supplier-file-parser.js';

function zipStore(files){let offset=0;const locals=[],centrals=[];for(const[name,text]of Object.entries(files)){const data=Buffer.from(text),nb=Buffer.from(name),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0,6);local.writeUInt16LE(0,8);local.writeUInt32LE(0,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(nb.length,26);local.writeUInt16LE(0,28);locals.push(local,nb,data);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0,8);central.writeUInt16LE(0,10);central.writeUInt32LE(0,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(nb.length,28);central.writeUInt16LE(0,30);central.writeUInt16LE(0,32);central.writeUInt32LE(0,38);central.writeUInt32LE(offset,42);centrals.push(central,nb);offset+=30+nb.length+data.length}const body=Buffer.concat(locals),cd=Buffer.concat(centrals),e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50,0);e.writeUInt16LE(Object.keys(files).length,8);e.writeUInt16LE(Object.keys(files).length,10);e.writeUInt32LE(cd.length,12);e.writeUInt32LE(body.length,16);return Buffer.concat([body,cd,e])}

test('supplier parser reads semicolon CSV and first XLSX sheet without external libraries',()=>{
 const csv=Buffer.from('Артикул;Наименование;Цена;Остаток\nA-1;Термостат;1 250,50;4\n').toString('base64'),p=parseSupplierFile({filename:'price.csv',contentBase64:csv}),m=detectMapping(p.headers),rows=normalizeSupplierRows(p,m);assert.equal(p.format,'CSV');assert.equal(rows[0].supplier_sku,'A-1');assert.equal(rows[0].purchase_price,1250.5);assert.equal(rows[0].available_qty,4);
 const xlsx=zipStore({'xl/workbook.xml':'<workbook xmlns:r="r"><sheets><sheet name="Price" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>','xl/sharedStrings.xml':'<sst><si><t>Артикул</t></si><si><t>Наименование</t></si><si><t>Цена</t></si><si><t>X-7</t></si><si><t>Компрессор</t></si></sst>','xl/worksheets/sheet1.xml':'<worksheet><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="s"><v>2</v></c></row><row r="2"><c r="A2" t="s"><v>3</v></c><c r="B2" t="s"><v>4</v></c><c r="C2"><v>78000</v></c></row></sheetData></worksheet>'});const xp=parseSupplierFile({filename:'price.xlsx',contentBase64:xlsx.toString('base64')}),xr=normalizeSupplierRows(xp,detectMapping(xp.headers));assert.equal(xp.format,'XLSX');assert.equal(xr[0].supplier_sku,'X-7');assert.equal(xr[0].name,'Компрессор');assert.equal(xr[0].purchase_price,78000);
});

test('supplier catalog preview/apply is idempotent, branch-scoped and never rewrites existing stock accounting',async()=>{
 const db=await PGlite.create(),query=(sql,p=[])=>p.length?db.query(sql,p):db.exec(sql).then(r=>r.at(-1));let chain=Promise.resolve();const pool={query,connect:async()=>{const before=chain;let release;chain=new Promise(r=>release=r);await before;return{query,release}},end:async()=>{}};await migrateCore(pool);
 await query(`CREATE TABLE IF NOT EXISTS warehouse_items(id SERIAL PRIMARY KEY,branch_id INT NOT NULL REFERENCES branches(id),sku TEXT,name TEXT NOT NULL,oem_code TEXT,supplier TEXT,purchase_price NUMERIC(14,2) NOT NULL DEFAULT 0,sale_price NUMERIC(14,2) NOT NULL DEFAULT 0,quantity NUMERIC(14,3) NOT NULL DEFAULT 0,min_quantity NUMERIC(14,3) NOT NULL DEFAULT 0,location TEXT,notes TEXT,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`);await query(`CREATE UNIQUE INDEX IF NOT EXISTS test_uq_wh_branch_sku ON warehouse_items(branch_id,sku) WHERE sku IS NOT NULL`);await query(`CREATE TABLE IF NOT EXISTS suppliers(id SERIAL PRIMARY KEY,name TEXT NOT NULL,bin TEXT,phone TEXT,email TEXT,address TEXT,contact_person TEXT,notes TEXT,active BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now())`);await prepareSupplierCatalog(pool);
 const kst=(await query("SELECT id FROM branches WHERE code='KST'")).rows[0].id;await query("INSERT INTO branches(code,name,address) VALUES('ALT','Другой филиал','ALT')");const alt=(await query("SELECT id FROM branches WHERE code='ALT'")).rows[0].id;await query("INSERT INTO users(name,email,password_hash,role,primary_branch_id) VALUES('Import Owner','import-owner@test','x','OWNER',$1),('Foreign Manager','foreign-manager@test','x','MANAGER',$2)",[kst,alt]);const users=(await query("SELECT id,email FROM users WHERE email IN('import-owner@test','foreign-manager@test') ORDER BY email")).rows,owner=users.find(x=>x.email==='import-owner@test').id,foreign=users.find(x=>x.email==='foreign-manager@test').id;await query('DELETE FROM user_branches WHERE user_id=$1',[foreign]);await query('INSERT INTO user_branches(user_id,branch_id,is_primary) VALUES($1,$2,true)',[foreign,alt]);
 await query("INSERT INTO suppliers(name) VALUES('Parts KZ')");const supplier=(await query("SELECT id FROM suppliers WHERE name='Parts KZ'")).rows[0].id;await query("INSERT INTO warehouse_items(branch_id,sku,name,oem_code,purchase_price,sale_price,quantity) VALUES($1,'A1','Старый термостат','OEM1',999,1800,7)",[kst]);const existing=(await query("SELECT id FROM warehouse_items WHERE branch_id=$1 AND sku='A1'",[kst])).rows[0].id;
 const app=Fastify({logger:false,bodyLimit:12*1024*1024});await app.register(jwt,{secret:'s'.repeat(64)});installSupplierCatalog(app,pool);await app.ready();const ownerToken=app.jwt.sign({id:owner,role:'OWNER'}),foreignToken=app.jwt.sign({id:foreign,role:'MANAGER'}),csv=Buffer.from('Артикул;Наименование;OEM;Закупочная цена;Остаток\nA1;Термостат;OEM1;1500;5\nB2;ТЭН;OEM2;2500;3\nBAD;;OEM3;abc;2\n').toString('base64'),body={supplier_id:supplier,branch_id:kst,filename:'parts.csv',content_base64:csv,create_missing:true};const call=async(method,url,payload,token=ownerToken)=>{const r=await app.inject({method,url,payload,headers:{authorization:'Bearer '+token}});return{status:r.statusCode,...r.json()}};
 let r=await call('POST','/api/v1/import/preview',body);assert.equal(r.status,200);assert.equal(r.data.counts.valid,2);assert.equal(r.data.counts.invalid,1);assert.equal(r.data.counts.warehouse_match,1);assert.equal(r.data.counts.warehouse_create,1);assert.equal(r.data.items.find(x=>x.supplier_sku==='A1').warehouse_match_id,existing);
 r=await call('POST','/api/v1/import/apply',body);assert.equal(r.status,201);assert.equal(r.data.counts.warehouse_created_applied,1);assert.equal((await query('SELECT count(*)::int n FROM supplier_catalog_items WHERE supplier_id=$1',[supplier])).rows[0].n,2);const stock=(await query("SELECT purchase_price,quantity FROM warehouse_items WHERE id=$1",[existing])).rows[0];assert.equal(Number(stock.purchase_price),999);assert.equal(Number(stock.quantity),7);assert.equal((await query("SELECT count(*)::int n FROM warehouse_items WHERE branch_id=$1 AND sku='B2'",[kst])).rows[0].n,1);
 r=await call('POST','/api/v1/import/apply',body);assert.equal(r.status,201);assert.equal((await query('SELECT count(*)::int n FROM supplier_catalog_items WHERE supplier_id=$1',[supplier])).rows[0].n,2);assert.equal((await query('SELECT count(*)::int n FROM supplier_catalog_imports WHERE supplier_id=$1',[supplier])).rows[0].n,2);assert.equal((await query('SELECT count(*)::int n FROM supplier_catalog_links WHERE branch_id=$1',[kst])).rows[0].n,2);
 r=await call('POST','/api/v1/import/preview',body,foreignToken);assert.equal(r.status,403);const imp=(await query('SELECT id FROM supplier_catalog_imports ORDER BY id LIMIT 1')).rows[0].id;await assert.rejects(()=>query("UPDATE supplier_catalog_imports SET filename='tampered.csv' WHERE id=$1",[imp]));
 await app.close();await db.close();
});
