import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import jwt from '@fastify/jwt';
import bcrypt from 'bcryptjs';
import pg from 'pg';

const app=Fastify({logger:true,bodyLimit:8*1024*1024});
await app.register(cors,{origin:(process.env.CORS_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()),credentials:true});
await app.register(helmet,{contentSecurityPolicy:false});
await app.register(rateLimit,{max:300,timeWindow:'1 minute'});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||10)});
const q=(s,p=[])=>pool.query(s,p);
const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}};
const num=v=>Number(v||0);
const phone=v=>String(v||'').replace(/\D/g,'').replace(/^8(?=7\d{9}$)/,'7');
const err=(reply,code,message,status=422,details)=>reply.code(status).send({data:null,error:{code,message,details}});
const plusMin=m=>new Date(Date.now()+m*60000);

const ensure=[
`ALTER TABLE requests ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(14,2) DEFAULT 0`,
`ALTER TABLE requests ADD COLUMN IF NOT EXISTS visit_type TEXT DEFAULT 'FIELD'`,
`ALTER TABLE requests ADD COLUMN IF NOT EXISTS manager_comment TEXT`,
`CREATE TABLE IF NOT EXISTS request_works(id SERIAL PRIMARY KEY,request_id INT NOT NULL REFERENCES requests(id) ON DELETE CASCADE,name TEXT NOT NULL,qty NUMERIC(10,2) NOT NULL DEFAULT 1,unit_price NUMERIC(14,2) NOT NULL DEFAULT 0,direct_cost NUMERIC(14,2) NOT NULL DEFAULT 0,performed_by INT REFERENCES users(id),created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE INDEX IF NOT EXISTS idx_request_works_request ON request_works(request_id)`,
`CREATE TABLE IF NOT EXISTS request_notes(id SERIAL PRIMARY KEY,request_id INT NOT NULL REFERENCES requests(id) ON DELETE CASCADE,text TEXT NOT NULL,created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now())`
];
for(const s of ensure)await q(s);

const auth=async(req,reply)=>{try{await req.jwtVerify()}catch{return err(reply,'UNAUTHORIZED','Требуется авторизация',401)}};
const roles=(...allowed)=>async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!allowed.includes(req.user.role))return err(reply,'FORBIDDEN','Недостаточно прав',403)};
const hist=(c,id,user,action,details={})=>(c||pool).query('INSERT INTO request_history(request_id,user_id,action,details) VALUES($1,$2,$3,$4)',[id,user,action,details]);
const requestSelect=`SELECT r.*,c.name customer_name,c.phone,c.address,c.email customer_email,e.category,e.brand,e.model,e.serial_number,eng.name engineer_name,m.name manager_name,(r.total-r.direct_cost) gross_profit,CASE WHEN r.total>0 THEN round(((r.total-r.direct_cost)/r.total*100)::numeric,2) ELSE 0 END gross_margin FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN equipment e ON e.id=r.equipment_id LEFT JOIN users eng ON eng.id=r.engineer_id LEFT JOIN users m ON m.id=r.manager_id`;

function redactRequest(r,role){
  if(!r||role!=='ENGINEER')return r;
  const out={...r};
  delete out.direct_cost;delete out.gross_profit;delete out.gross_margin;delete out.manager_comment;
  if(Array.isArray(out.works))out.works=out.works.map(({direct_cost,...w})=>w);
  if(Array.isArray(out.parts))out.parts=out.parts.map(({purchase_price,...p})=>p);
  return out;
}
async function requireRequestAccess(req,reply,id,client=pool){
  const r=(await client.query('SELECT id,engineer_id,status,total,paid FROM requests WHERE id=$1',[id])).rows[0];
  if(!r){err(reply,'NOT_FOUND','Заказ не найден',404);return null}
  if(req.user.role==='ENGINEER'&&Number(r.engineer_id)!==Number(req.user.id)){err(reply,'FORBIDDEN','Нет доступа к этому заказу',403);return null}
  return r;
}
async function recalc(c,id){const works=(await c.query('SELECT COALESCE(sum(qty*unit_price),0) sale,COALESCE(sum(qty*direct_cost),0) cost FROM request_works WHERE request_id=$1',[id])).rows[0];const parts=(await c.query('SELECT COALESCE(sum(qty*sale_price),0) sale,COALESCE(sum(qty*purchase_price),0) cost FROM parts WHERE request_id=$1',[id])).rows[0];const cur=(await c.query('SELECT discount_amount FROM requests WHERE id=$1',[id])).rows[0];const total=Math.max(0,num(works.sale)+num(parts.sale)-num(cur?.discount_amount));const cost=num(works.cost)+num(parts.cost);await c.query('UPDATE requests SET total=$1,direct_cost=$2,updated_at=now() WHERE id=$3',[total,cost,id]);return {total,direct_cost:cost}}
async function getRequest(id){const r=(await q(`${requestSelect} WHERE r.id=$1`,[id])).rows[0];if(!r)return null;const [history,payments,parts,works,approvals,tasks,complaints,notes]=await Promise.all([
q('SELECT h.*,u.name user_name FROM request_history h LEFT JOIN users u ON u.id=h.user_id WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT p.*,u.name created_by_name FROM payments p LEFT JOIN users u ON u.id=p.created_by WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT * FROM parts WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT w.*,u.name performed_by_name FROM request_works w LEFT JOIN users u ON u.id=w.performed_by WHERE request_id=$1 ORDER BY created_at',[id]),
q('SELECT * FROM approvals WHERE request_id=$1 ORDER BY version DESC',[id]),
q('SELECT t.*,u.name assigned_name FROM tasks t LEFT JOIN users u ON u.id=t.assigned_to WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT * FROM complaints WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT n.*,u.name created_by_name FROM request_notes n LEFT JOIN users u ON u.id=n.created_by WHERE request_id=$1 ORDER BY created_at DESC',[id])]);
return {...r,history:history.rows,payments:payments.rows,parts:parts.rows,works:works.rows,approvals:approvals.rows,tasks:tasks.rows,complaints:complaints.rows,notes:notes.rows}}

const transitions={NEW:['ASSIGNED','CANCELLED'],ASSIGNED:['ACCEPTED','CANCELLED'],ACCEPTED:['DIAGNOSTICS','CANCELLED'],DIAGNOSTICS:['APPROVAL_REQUIRED','CANCELLED'],APPROVAL_REQUIRED:['WAITING_PART','REPAIR','CANCELLED'],WAITING_PART:['REPAIR','CANCELLED'],REPAIR:['TESTING','WAITING_PART','CANCELLED'],TESTING:['PAYMENT_REQUIRED','REPAIR'],PAYMENT_REQUIRED:['CLOSED'],CLOSED:[],CANCELLED:[]};
app.setErrorHandler((e,req,reply)=>{req.log.error(e);if(e.code==='23505')return err(reply,'DUPLICATE','Такая запись уже существует',409);return err(reply,'INTERNAL_ERROR',process.env.NODE_ENV==='production'?'Внутренняя ошибка сервера':e.message,500)});
app.get('/health',async()=>{await q('SELECT 1');return {ok:true,service:'profi24-crm-api',version:'2.1.0'}});

app.post('/api/v1/auth/login',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(req,reply)=>{const {email,password}=req.body||{};const u=(await q('SELECT * FROM users WHERE lower(email)=lower($1) AND active=true',[email||''])).rows[0];if(!u||!await bcrypt.compare(password||'',u.password_hash))return err(reply,'INVALID_CREDENTIALS','Неверный логин или пароль',401);return {data:{access_token:app.jwt.sign({id:u.id,role:u.role,name:u.name,email:u.email},{expiresIn:'12h'}),user:{id:u.id,name:u.name,email:u.email,role:u.role}}}});
app.get('/api/v1/me',{preHandler:auth},async req=>({data:req.user}));
app.get('/api/v1/users',{preHandler:auth},async req=>({data:(await q(req.user.role==='ENGINEER'?'SELECT id,name,role,active FROM users WHERE active=true ORDER BY name':'SELECT id,name,email,role,active,created_at FROM users ORDER BY active DESC,name')).rows}));
app.post('/api/v1/users',{preHandler:roles('OWNER')},async(req,reply)=>{const {name,email,password='profi24',role='ENGINEER'}=req.body||{};if(!name||!email||!['OWNER','MANAGER','ENGINEER'].includes(role))return err(reply,'VALIDATION','Укажите имя, email и корректную роль');const hash=await bcrypt.hash(password,10);const r=await q('INSERT INTO users(name,email,password_hash,role,active) VALUES($1,$2,$3,$4,true) RETURNING id,name,email,role,active,created_at',[name,email,hash,role]);return reply.code(201).send({data:r.rows[0]})});
app.patch('/api/v1/users/:id',{preHandler:roles('OWNER')},async(req,reply)=>{const old=(await q('SELECT * FROM users WHERE id=$1',[req.params.id])).rows[0];if(!old)return err(reply,'NOT_FOUND','Сотрудник не найден',404);const name=req.body?.name??old.name,email=req.body?.email??old.email,role=req.body?.role??old.role,active=req.body?.active??old.active;if(!['OWNER','MANAGER','ENGINEER'].includes(role))return err(reply,'VALIDATION','Некорректная роль');const r=await q('UPDATE users SET name=$1,email=$2,role=$3,active=$4 WHERE id=$5 RETURNING id,name,email,role,active,created_at',[name,email,role,active,req.params.id]);return {data:r.rows[0]}});
app.post('/api/v1/users/:id/password',{preHandler:roles('OWNER')},async(req,reply)=>{if(!req.body?.password||String(req.body.password).length<6)return err(reply,'VALIDATION','Пароль минимум 6 символов');const hash=await bcrypt.hash(req.body.password,10);const r=await q('UPDATE users SET password_hash=$1 WHERE id=$2 RETURNING id',[hash,req.params.id]);if(!r.rows[0])return err(reply,'NOT_FOUND','Сотрудник не найден',404);return {data:{ok:true}}});

app.get('/api/v1/customers',{preHandler:auth},async()=>({data:(await q(`SELECT c.*,count(DISTINCT r.id)::int request_count,COALESCE(sum(r.paid),0)::numeric lifetime_paid FROM customers c LEFT JOIN requests r ON r.customer_id=c.id GROUP BY c.id ORDER BY c.created_at DESC LIMIT 1000`)).rows}));
app.post('/api/v1/customers',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {name,phone:raw,email,address,notes}=req.body||{};if(!name||!raw)return err(reply,'VALIDATION','Имя и телефон обязательны');const pn=phone(raw);const dup=(await q('SELECT id,name,phone FROM customers WHERE phone_norm=$1 LIMIT 1',[pn])).rows[0];if(dup&&!req.body?.force)return reply.code(409).send({data:null,error:{code:'POSSIBLE_DUPLICATE_CUSTOMER',message:'Клиент с таким телефоном уже существует',candidate:dup}});const r=await q('INSERT INTO customers(name,phone,phone_norm,email,address,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,raw,pn,email||null,address||null,notes||null]);return reply.code(201).send({data:r.rows[0]})});
app.get('/api/v1/equipment',{preHandler:auth},async()=>({data:(await q('SELECT e.*,c.name customer_name FROM equipment e JOIN customers c ON c.id=e.customer_id ORDER BY e.created_at DESC')).rows}));
app.post('/api/v1/equipment',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {customer_id,category,brand,model,serial_number,notes}=req.body||{};if(!customer_id||!category)return err(reply,'VALIDATION','Клиент и категория обязательны');const r=await q('INSERT INTO equipment(customer_id,category,brand,model,serial_number,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[customer_id,category,brand||null,model||null,serial_number||null,notes||null]);return reply.code(201).send({data:r.rows[0]})});

app.get('/api/v1/requests',{preHandler:auth},async req=>{const p=[],where=[];if(req.user.role==='ENGINEER'){p.push(req.user.id);where.push(`r.engineer_id=$${p.length}`)}const rows=(await q(`${requestSelect} ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE WHEN r.status NOT IN ('CLOSED','CANCELLED') THEN 0 ELSE 1 END,r.created_at DESC LIMIT 1000`,p)).rows;return {data:rows.map(r=>redactRequest(r,req.user.role))}});
app.post('/api/v1/requests',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {customer_id,equipment_id,complaint,priority='NORMAL',scheduled_at,source='OTHER',engineer_id,visit_type='FIELD',manager_comment}=req.body||{};if(!customer_id||!complaint?.trim())return err(reply,'VALIDATION','Клиент и описание неисправности обязательны');const seq=(await q(`SELECT nextval('request_number_seq') n`)).rows[0].n;const number=`KST-${new Date().getFullYear()}-${String(seq).padStart(7,'0')}`;const status=engineer_id?'ASSIGNED':'NEW';const sla=plusMin(priority==='CRITICAL'?15:60);const r=await q('INSERT INTO requests(number,customer_id,equipment_id,manager_id,engineer_id,status,priority,source,complaint,scheduled_at,sla_deadline,visit_type,manager_comment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *',[number,customer_id,equipment_id||null,req.user.id,engineer_id||null,status,priority,source,complaint.trim(),scheduled_at||null,sla,visit_type,manager_comment||null]);await hist(null,r.rows[0].id,req.user.id,'REQUEST_CREATED',{source,priority,visit_type});if(engineer_id)await hist(null,r.rows[0].id,req.user.id,'REQUEST_ASSIGNED',{engineer_id,scheduled_at});return reply.code(201).send({data:r.rows[0]})});
app.get('/api/v1/requests/:id',{preHandler:auth},async(req,reply)=>{const r=await getRequest(req.params.id);if(!r)return err(reply,'NOT_FOUND','Заказ не найден',404);if(req.user.role==='ENGINEER'&&Number(r.engineer_id)!==Number(req.user.id))return err(reply,'FORBIDDEN','Нет доступа',403);return {data:redactRequest(r,req.user.role)}});
app.post('/api/v1/requests/:id/assign',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {engineer_id,scheduled_at}=req.body||{};if(!engineer_id)return err(reply,'VALIDATION','Выберите инженера');const r=await q("UPDATE requests SET engineer_id=$1,status=CASE WHEN status='NEW' THEN 'ASSIGNED' ELSE status END,scheduled_at=COALESCE($2,scheduled_at),updated_at=now() WHERE id=$3 RETURNING *",[engineer_id,scheduled_at||null,req.params.id]);if(!r.rows[0])return err(reply,'NOT_FOUND','Заказ не найден',404);await hist(null,req.params.id,req.user.id,'REQUEST_ASSIGNED',{engineer_id,scheduled_at});return {data:r.rows[0]}});
app.patch('/api/v1/requests/:id/schedule',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {scheduled_at,engineer_id,visit_type,manager_comment}=req.body||{};const r=await q('UPDATE requests SET scheduled_at=$1,engineer_id=COALESCE($2,engineer_id),visit_type=COALESCE($3,visit_type),manager_comment=COALESCE($4,manager_comment),status=CASE WHEN status=\'NEW\' AND COALESCE($2,engineer_id) IS NOT NULL THEN \'ASSIGNED\' ELSE status END,updated_at=now() WHERE id=$5 RETURNING *',[scheduled_at||null,engineer_id||null,visit_type||null,manager_comment??null,req.params.id]);if(!r.rows[0])return err(reply,'NOT_FOUND','Заказ не найден',404);await hist(null,req.params.id,req.user.id,'SCHEDULE_CHANGED',{scheduled_at,engineer_id,visit_type});return {data:r.rows[0]}});
app.post('/api/v1/requests/:id/accept',{preHandler:roles('ENGINEER')},async(req,reply)=>{const r=await q("UPDATE requests SET status='ACCEPTED',updated_at=now() WHERE id=$1 AND engineer_id=$2 AND status='ASSIGNED' RETURNING *",[req.params.id,req.user.id]);if(!r.rows[0])return err(reply,'STATE_CONFLICT','Заказ не назначен вам',409);await hist(null,req.params.id,req.user.id,'REQUEST_ACCEPTED');return {data:r.rows[0]}});
app.post('/api/v1/requests/:id/status',{preHandler:auth},async(req,reply)=>{const cur=await requireRequestAccess(req,reply,req.params.id);if(!cur)return;const status=req.body?.status;if(!(transitions[cur.status]||[]).includes(status))return err(reply,'INVALID_TRANSITION',`Переход ${cur.status} → ${status} не разрешён`,409);if(status==='CLOSED'&&num(cur.paid)<num(cur.total))return err(reply,'PAYMENT_REQUIRED','Нельзя закрыть неоплаченный заказ',409);const r=await q("UPDATE requests SET status=$1,updated_at=now(),closed_at=CASE WHEN $1='CLOSED' THEN now() ELSE closed_at END,cancelled_at=CASE WHEN $1='CANCELLED' THEN now() ELSE cancelled_at END WHERE id=$2 RETURNING *",[status,req.params.id]);await hist(null,req.params.id,req.user.id,'STATUS_CHANGED',{from:cur.status,to:status});return {data:redactRequest(r.rows[0],req.user.role)}});
app.post('/api/v1/requests/:id/diagnosis',{preHandler:auth},async(req,reply)=>{if(!req.body?.diagnosis?.trim())return err(reply,'VALIDATION','Заполните диагностику');const cur=await requireRequestAccess(req,reply,req.params.id);if(!cur)return;const r=await q("UPDATE requests SET diagnosis=$1,status='APPROVAL_REQUIRED',updated_at=now() WHERE id=$2 RETURNING *",[req.body.diagnosis.trim(),req.params.id]);await hist(null,req.params.id,req.user.id,'DIAGNOSIS_COMPLETED');return {data:redactRequest(r.rows[0],req.user.role)}});
app.post('/api/v1/requests/:id/test',{preHandler:auth},async(req,reply)=>{if(!req.body?.test_result?.trim())return err(reply,'VALIDATION','Укажите результат проверки');const cur=await requireRequestAccess(req,reply,req.params.id);if(!cur)return;const r=await q("UPDATE requests SET test_result=$1,status='PAYMENT_REQUIRED',updated_at=now() WHERE id=$2 RETURNING *",[req.body.test_result.trim(),req.params.id]);await hist(null,req.params.id,req.user.id,'TEST_COMPLETED');return {data:redactRequest(r.rows[0],req.user.role)}});
app.post('/api/v1/requests/:id/notes',{preHandler:auth},async(req,reply)=>{if(!req.body?.text?.trim())return err(reply,'VALIDATION','Введите комментарий');const cur=await requireRequestAccess(req,reply,req.params.id);if(!cur)return;const r=await q('INSERT INTO request_notes(request_id,text,created_by) VALUES($1,$2,$3) RETURNING *',[req.params.id,req.body.text.trim(),req.user.id]);await hist(null,req.params.id,req.user.id,'NOTE_ADDED');return reply.code(201).send({data:r.rows[0]})});

app.post('/api/v1/requests/:id/works',{preHandler:auth},async(req,reply)=>{const {name,qty=1,unit_price=0,direct_cost=0,performed_by}=req.body||{};if(!name?.trim()||num(qty)<=0)return err(reply,'VALIDATION','Укажите работу и количество');const cur=await requireRequestAccess(req,reply,req.params.id);if(!cur)return;const performer=req.user.role==='ENGINEER'?req.user.id:(performed_by||cur.engineer_id||null);const safeCost=req.user.role==='ENGINEER'?0:direct_cost;const result=await tx(async c=>{const w=(await c.query('INSERT INTO request_works(request_id,name,qty,unit_price,direct_cost,performed_by,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[req.params.id,name.trim(),qty,unit_price,safeCost,performer,req.user.id])).rows[0];const totals=await recalc(c,req.params.id);await hist(c,req.params.id,req.user.id,'WORK_ITEM_ADDED',{work_id:w.id,name,unit_price,performed_by:performer});return {...w,totals}});return reply.code(201).send({data:redactRequest(result,req.user.role)})});
app.patch('/api/v1/works/:id',{preHandler:auth},async(req,reply)=>{const old=(await q('SELECT w.*,r.engineer_id FROM request_works w JOIN requests r ON r.id=w.request_id WHERE w.id=$1',[req.params.id])).rows[0];if(!old)return err(reply,'NOT_FOUND','Работа не найдена',404);if(req.user.role==='ENGINEER'&&Number(old.engineer_id)!==Number(req.user.id))return err(reply,'FORBIDDEN','Нет доступа',403);const b={...old,...req.body};const performer=req.user.role==='ENGINEER'?req.user.id:(b.performed_by||old.engineer_id||null);const cost=req.user.role==='ENGINEER'?old.direct_cost:b.direct_cost;const result=await tx(async c=>{const w=(await c.query('UPDATE request_works SET name=$1,qty=$2,unit_price=$3,direct_cost=$4,performed_by=$5,updated_at=now() WHERE id=$6 RETURNING *',[b.name,b.qty,b.unit_price,cost,performer,req.params.id])).rows[0];await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'WORK_ITEM_CHANGED',{work_id:old.id});return w});return {data:redactRequest({works:[result]},req.user.role).works[0]}});
app.delete('/api/v1/works/:id',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const old=(await q('SELECT * FROM request_works WHERE id=$1',[req.params.id])).rows[0];if(!old)return err(reply,'NOT_FOUND','Работа не найдена',404);await tx(async c=>{await c.query('DELETE FROM request_works WHERE id=$1',[req.params.id]);await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'WORK_ITEM_DELETED',{work_id:old.id})});return {data:{ok:true}}});
app.post('/api/v1/requests/:id/discount',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const amount=Math.max(0,num(req.body?.amount));const result=await tx(async c=>{await c.query('UPDATE requests SET discount_amount=$1 WHERE id=$2',[amount,req.params.id]);const totals=await recalc(c,req.params.id);await hist(c,req.params.id,req.user.id,'DISCOUNT_CHANGED',{amount});return totals});return {data:result}});

app.post('/api/v1/requests/:id/parts',{preHandler:auth},async(req,reply)=>{const {name,oem_code,qty=1,purchase_price=0,sale_price=0,supplier,status='REQUESTED',eta}=req.body||{};if(!name?.trim())return err(reply,'VALIDATION','Укажите запчасть');const cur=await requireRequestAccess(req,reply,req.params.id);if(!cur)return;const safePurchase=req.user.role==='ENGINEER'?0:purchase_price;const result=await tx(async c=>{const p=(await c.query('INSERT INTO parts(request_id,name,oem_code,qty,purchase_price,sale_price,supplier,status,eta,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[req.params.id,name.trim(),oem_code||null,qty,safePurchase,sale_price,supplier||null,status,eta||null,req.user.id])).rows[0];await recalc(c,req.params.id);await hist(c,req.params.id,req.user.id,'PART_ADDED',{part_id:p.id,name,status});return p});return reply.code(201).send({data:req.user.role==='ENGINEER'?redactRequest({parts:[result]},req.user.role).parts[0]:result})});
app.patch('/api/v1/parts/:id',{preHandler:auth},async(req,reply)=>{const old=(await q('SELECT p.*,r.engineer_id FROM parts p JOIN requests r ON r.id=p.request_id WHERE p.id=$1',[req.params.id])).rows[0];if(!old)return err(reply,'NOT_FOUND','Запчасть не найдена',404);if(req.user.role==='ENGINEER'&&Number(old.engineer_id)!==Number(req.user.id))return err(reply,'FORBIDDEN','Нет доступа',403);const b={...old,...req.body};const purchase=req.user.role==='ENGINEER'?old.purchase_price:b.purchase_price;const result=await tx(async c=>{const p=(await c.query('UPDATE parts SET name=$1,oem_code=$2,qty=$3,purchase_price=$4,sale_price=$5,supplier=$6,status=$7,eta=$8,updated_at=now() WHERE id=$9 RETURNING *',[b.name,b.oem_code,b.qty,purchase,b.sale_price,b.supplier,b.status,b.eta,req.params.id])).rows[0];await recalc(c,old.request_id);if(b.status==='RECEIVED'&&old.status!=='RECEIVED')await hist(c,old.request_id,req.user.id,'PART_RECEIVED',{part_id:old.id});return p});return {data:req.user.role==='ENGINEER'?redactRequest({parts:[result]},req.user.role).parts[0]:result}});

app.post('/api/v1/requests/:id/payment',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const amount=num(req.body?.amount),method=req.body?.method||'KASPI';if(amount<=0)return err(reply,'VALIDATION','Сумма должна быть больше 0');const result=await tx(async c=>{const cur=(await c.query('SELECT * FROM requests WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!cur)throw Object.assign(new Error('Заказ не найден'),{statusCode:404});if(num(cur.total)<=0)throw Object.assign(new Error('В заказе нет суммы к оплате'),{statusCode:409});const balance=Math.max(0,num(cur.total)-num(cur.paid));if(amount>balance+0.001)throw Object.assign(new Error(`Сумма больше долга: ${balance}`),{statusCode:409});await c.query('INSERT INTO payments(request_id,amount,method,kind,reference,created_by) VALUES($1,$2,$3,\'PAYMENT\',$4,$5)',[req.params.id,amount,method,req.body?.reference||null,req.user.id]);const paid=num(cur.paid)+amount;const fullyPaid=paid>=num(cur.total)-0.001;const status=cur.status==='PAYMENT_REQUIRED'&&fullyPaid?'CLOSED':cur.status;const r=(await c.query("UPDATE requests SET paid=$1,status=$2,closed_at=CASE WHEN $2='CLOSED' THEN COALESCE(closed_at,now()) ELSE closed_at END,updated_at=now() WHERE id=$3 RETURNING *",[paid,status,req.params.id])).rows[0];await hist(c,req.params.id,req.user.id,'PAYMENT_RECEIVED',{amount,method,fully_paid:fullyPaid});return r});return {data:result}});
app.post('/api/v1/payments/:id/refund',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const amount=num(req.body?.amount);if(amount<=0)return err(reply,'VALIDATION','Сумма возврата должна быть больше 0');const result=await tx(async c=>{const p=(await c.query("SELECT p.*,r.paid,r.total,r.status FROM payments p JOIN requests r ON r.id=p.request_id WHERE p.id=$1 AND p.kind='PAYMENT' FOR UPDATE",[req.params.id])).rows[0];if(!p)throw Object.assign(new Error('Платёж не найден'),{statusCode:404});const refunded=num((await c.query("SELECT COALESCE(sum(amount),0) amount FROM payments WHERE request_id=$1 AND kind='REFUND' AND reference=$2",[p.request_id,`refund:${p.id}`])).rows[0]?.amount);const available=Math.max(0,num(p.amount)-refunded);if(amount>available+0.001)throw Object.assign(new Error(`Можно вернуть не более ${available}`),{statusCode:409});await c.query("INSERT INTO payments(request_id,amount,method,kind,reference,created_by) VALUES($1,$2,$3,'REFUND',$4,$5)",[p.request_id,amount,p.method,`refund:${p.id}`,req.user.id]);const paid=Math.max(0,num(p.paid)-amount);const status=p.status==='CLOSED'&&paid<num(p.total)-0.001?'PAYMENT_REQUIRED':p.status;const r=(await c.query("UPDATE requests SET paid=$1,status=$2,closed_at=CASE WHEN $2='CLOSED' THEN closed_at ELSE NULL END,updated_at=now() WHERE id=$3 RETURNING *",[paid,status,p.request_id])).rows[0];await hist(c,p.request_id,req.user.id,'PAYMENT_REFUNDED',{payment_id:p.id,amount,method:p.method});return r});return {data:result}});

app.get('/api/v1/tasks',{preHandler:auth},async req=>{const p=[],where=[];if(req.user.role!=='OWNER'){p.push(req.user.id);where.push(`t.assigned_to=$1`)}return {data:(await q(`SELECT t.*,u.name assigned_name,r.number request_number,c.name customer_name FROM tasks t JOIN users u ON u.id=t.assigned_to LEFT JOIN requests r ON r.id=t.request_id LEFT JOIN customers c ON c.id=r.customer_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE WHEN t.status='OPEN' THEN 0 ELSE 1 END,t.due_at NULLS LAST`,p)).rows}});
app.post('/api/v1/tasks/:id/complete',{preHandler:auth},async(req,reply)=>{const r=await q("UPDATE tasks SET status='DONE',completed_at=now() WHERE id=$1 AND (assigned_to=$2 OR $3='OWNER') RETURNING *",[req.params.id,req.user.id,req.user.role]);if(!r.rows[0])return err(reply,'FORBIDDEN','Нельзя закрыть задачу',403);return {data:r.rows[0]}});
app.get('/api/v1/complaints',{preHandler:auth},async req=>{const p=[],where=[];if(req.user.role==='ENGINEER'){p.push(req.user.id);where.push(`r.engineer_id=$1`)}return {data:(await q(`SELECT co.*,r.number request_number,c.name customer_name FROM complaints co LEFT JOIN requests r ON r.id=co.request_id JOIN customers c ON c.id=co.customer_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY co.created_at DESC`,p)).rows}});
app.get('/api/v1/dashboard',{preHandler:auth},async req=>{const own=req.user.role==='ENGINEER'?'WHERE engineer_id=$1':'',p=req.user.role==='ENGINEER'?[req.user.id]:[];const s=(await q(`SELECT count(*)::int total,count(*) FILTER(WHERE status='NEW')::int new,count(*) FILTER(WHERE status NOT IN ('CLOSED','CANCELLED'))::int active,count(*) FILTER(WHERE status='CLOSED')::int closed,count(*) FILTER(WHERE sla_deadline<now() AND status NOT IN ('CLOSED','CANCELLED'))::int overdue,COALESCE(sum(total-direct_cost) FILTER(WHERE status='CLOSED'),0)::numeric gross_profit FROM requests ${own}`,p)).rows[0];const tasks=req.user.role==='ENGINEER'?(await q("SELECT count(*)::int c FROM tasks WHERE assigned_to=$1 AND status='OPEN'",[req.user.id])).rows[0].c:(await q("SELECT count(*)::int c FROM tasks WHERE status='OPEN'")).rows[0].c;const complaints=req.user.role==='ENGINEER'?(await q("SELECT count(*)::int c FROM complaints co JOIN requests r ON r.id=co.request_id WHERE co.status='OPEN' AND r.engineer_id=$1",[req.user.id])).rows[0].c:(await q("SELECT count(*)::int c FROM complaints WHERE status='OPEN'")).rows[0].c;if(req.user.role==='ENGINEER')delete s.gross_profit;return {data:{...s,tasks_open:tasks,complaints_open:complaints}}});
app.get('/api/v1/dashboard/finance',{preHandler:roles('OWNER','MANAGER')},async()=>{const totals=(await q(`SELECT COALESCE(sum(total),0)::numeric revenue,COALESCE(sum(direct_cost),0)::numeric direct_cost,COALESCE(sum(total-direct_cost),0)::numeric gross_profit,COALESCE(sum(paid),0)::numeric paid,COALESCE(sum(GREATEST(total-paid,0)),0)::numeric outstanding FROM requests WHERE created_at>=date_trunc('month',now())`)).rows[0];return {data:{totals}}});

const close=async()=>{try{await pool.end()}finally{process.exit(0)}};process.on('SIGTERM',close);process.on('SIGINT',close);
app.listen({port:Number(process.env.PORT||8080),host:'0.0.0.0'});
