import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import jwt from '@fastify/jwt';
import bcrypt from 'bcryptjs';
import pg from 'pg';

const app=Fastify({logger:true,bodyLimit:8*1024*1024});
await app.register(cors,{origin:(process.env.CORS_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()),credentials:true});
await app.register(helmet,{contentSecurityPolicy:false});
await app.register(rateLimit,{max:300,timeWindow:'1 minute'});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});

const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||10),idleTimeoutMillis:30000});
const q=(text,params=[])=>pool.query(text,params);
const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}};
const money=n=>Number(n||0);
const nowPlusMinutes=m=>new Date(Date.now()+m*60000);
const normalizePhone=v=>String(v||'').replace(/\D/g,'').replace(/^8(?=7\d{9}$)/,'7');
const sendError=(reply,code,message,status=422,details)=>reply.code(status).send({data:null,error:{code,message,details}});

const schema=[
`CREATE SEQUENCE IF NOT EXISTS request_number_seq START 1001`,
`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('OWNER','MANAGER','ENGINEER')),active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS customers(id SERIAL PRIMARY KEY,name TEXT NOT NULL,phone TEXT NOT NULL,phone_norm TEXT,email TEXT,address TEXT,notes TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE INDEX IF NOT EXISTS idx_customers_phone_norm ON customers(phone_norm)`,
`CREATE TABLE IF NOT EXISTS equipment(id SERIAL PRIMARY KEY,customer_id INT REFERENCES customers(id),category TEXT NOT NULL,brand TEXT,model TEXT,serial_number TEXT,notes TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE INDEX IF NOT EXISTS idx_equipment_customer ON equipment(customer_id)`,
`CREATE TABLE IF NOT EXISTS requests(id SERIAL PRIMARY KEY,number TEXT UNIQUE NOT NULL,customer_id INT NOT NULL REFERENCES customers(id),equipment_id INT REFERENCES equipment(id),manager_id INT REFERENCES users(id),engineer_id INT REFERENCES users(id),status TEXT NOT NULL DEFAULT 'NEW',priority TEXT NOT NULL DEFAULT 'NORMAL',source TEXT DEFAULT 'OTHER',complaint TEXT NOT NULL,diagnosis TEXT,work_description TEXT,test_result TEXT,warranty_until DATE,total NUMERIC(14,2) DEFAULT 0,direct_cost NUMERIC(14,2) DEFAULT 0,paid NUMERIC(14,2) DEFAULT 0,scheduled_at TIMESTAMPTZ,sla_deadline TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),closed_at TIMESTAMPTZ,cancelled_at TIMESTAMPTZ,original_request_id INT REFERENCES requests(id))`,
`CREATE INDEX IF NOT EXISTS idx_requests_status ON requests(status)`,
`CREATE INDEX IF NOT EXISTS idx_requests_engineer ON requests(engineer_id,status)`,
`CREATE INDEX IF NOT EXISTS idx_requests_customer ON requests(customer_id,created_at DESC)`,
`CREATE TABLE IF NOT EXISTS request_history(id SERIAL PRIMARY KEY,request_id INT REFERENCES requests(id) ON DELETE CASCADE,user_id INT REFERENCES users(id),action TEXT NOT NULL,details JSONB DEFAULT '{}',created_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS payments(id SERIAL PRIMARY KEY,request_id INT NOT NULL REFERENCES requests(id),amount NUMERIC(14,2) NOT NULL CHECK(amount>0),method TEXT NOT NULL DEFAULT 'KASPI',kind TEXT NOT NULL DEFAULT 'PAYMENT' CHECK(kind IN ('PAYMENT','REFUND')),reference TEXT,created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS parts(id SERIAL PRIMARY KEY,request_id INT NOT NULL REFERENCES requests(id),name TEXT NOT NULL,oem_code TEXT,qty NUMERIC(10,2) NOT NULL DEFAULT 1,purchase_price NUMERIC(14,2) DEFAULT 0,sale_price NUMERIC(14,2) DEFAULT 0,supplier TEXT,status TEXT NOT NULL DEFAULT 'REQUESTED',eta DATE,created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS approvals(id SERIAL PRIMARY KEY,request_id INT NOT NULL REFERENCES requests(id),version INT NOT NULL DEFAULT 1,amount NUMERIC(14,2) NOT NULL,channel TEXT NOT NULL DEFAULT 'PHONE',status TEXT NOT NULL DEFAULT 'APPROVED',comment TEXT,created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS complaints(id SERIAL PRIMARY KEY,number TEXT UNIQUE NOT NULL,request_id INT REFERENCES requests(id),customer_id INT NOT NULL REFERENCES customers(id),text TEXT NOT NULL,severity TEXT NOT NULL DEFAULT 'NORMAL',status TEXT NOT NULL DEFAULT 'OPEN',classification TEXT,resolution TEXT,responsible_id INT REFERENCES users(id),created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),closed_at TIMESTAMPTZ)`,
`CREATE TABLE IF NOT EXISTS tasks(id SERIAL PRIMARY KEY,title TEXT NOT NULL,request_id INT REFERENCES requests(id),assigned_to INT NOT NULL REFERENCES users(id),priority TEXT NOT NULL DEFAULT 'NORMAL',status TEXT NOT NULL DEFAULT 'OPEN',due_at TIMESTAMPTZ,created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),completed_at TIMESTAMPTZ)`,
`CREATE TABLE IF NOT EXISTS quality_incidents(id SERIAL PRIMARY KEY,request_id INT REFERENCES requests(id),employee_id INT REFERENCES users(id),category TEXT NOT NULL,description TEXT NOT NULL,financial_impact NUMERIC(14,2) DEFAULT 0,root_cause TEXT,prevention TEXT,status TEXT NOT NULL DEFAULT 'OPEN',created_by INT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),closed_at TIMESTAMPTZ)`
];

async function init(){for(const s of schema)await q(s);await q(`UPDATE customers SET phone_norm=regexp_replace(phone,'\\D','','g') WHERE phone_norm IS NULL`);const {rows}=await q('SELECT count(*)::int c FROM users');if(!rows[0].c){const h=await bcrypt.hash('profi24',10);for(const u of [['Александр','owner@profi24.kz','OWNER'],['Менеджер','manager@profi24.kz','MANAGER'],['Инженер','engineer@profi24.kz','ENGINEER']])await q('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4)',[u[0],u[1],h,u[2]])}}
await init();

const auth=async(req,reply)=>{try{await req.jwtVerify()}catch{return sendError(reply,'UNAUTHORIZED','Требуется авторизация',401)}};
const roles=(...allowed)=>async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!allowed.includes(req.user.role))return sendError(reply,'FORBIDDEN','Недостаточно прав',403)};
const history=(client,id,user,action,details={})=>(client||pool).query('INSERT INTO request_history(request_id,user_id,action,details) VALUES($1,$2,$3,$4)',[id,user,action,details]);
const requestSelect=`SELECT r.*,c.name customer_name,c.phone,c.address,e.category,e.brand,e.model,e.serial_number,eng.name engineer_name,m.name manager_name,(r.total-r.direct_cost) gross_profit,CASE WHEN r.total>0 THEN round(((r.total-r.direct_cost)/r.total*100)::numeric,2) ELSE 0 END gross_margin FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN equipment e ON e.id=r.equipment_id LEFT JOIN users eng ON eng.id=r.engineer_id LEFT JOIN users m ON m.id=r.manager_id`;
const getRequest=async(id)=>{const r=(await q(`${requestSelect} WHERE r.id=$1`,[id])).rows[0];if(!r)return null;const [h,pay,parts,approvals,tasks,complaints]=await Promise.all([
q('SELECT h.*,u.name user_name FROM request_history h LEFT JOIN users u ON u.id=h.user_id WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT p.*,u.name created_by_name FROM payments p LEFT JOIN users u ON u.id=p.created_by WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT * FROM parts WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT * FROM approvals WHERE request_id=$1 ORDER BY version DESC',[id]),
q('SELECT t.*,u.name assigned_name FROM tasks t LEFT JOIN users u ON u.id=t.assigned_to WHERE request_id=$1 ORDER BY created_at DESC',[id]),
q('SELECT * FROM complaints WHERE request_id=$1 ORDER BY created_at DESC',[id])]);
return {...r,history:h.rows,payments:pay.rows,parts:parts.rows,approvals:approvals.rows,tasks:tasks.rows,complaints:complaints.rows}}

const transitions={NEW:['ASSIGNED','CANCELLED'],ASSIGNED:['ACCEPTED','CANCELLED'],ACCEPTED:['DIAGNOSTICS','CANCELLED'],DIAGNOSTICS:['APPROVAL_REQUIRED','CANCELLED'],APPROVAL_REQUIRED:['WAITING_PART','REPAIR','CANCELLED'],WAITING_PART:['REPAIR','CANCELLED'],REPAIR:['TESTING','WAITING_PART','CANCELLED'],TESTING:['PAYMENT_REQUIRED','REPAIR'],PAYMENT_REQUIRED:['CLOSED'],CLOSED:[],CANCELLED:[]};

app.setErrorHandler((err,req,reply)=>{req.log.error(err);if(err.code==='23505')return sendError(reply,'DUPLICATE','Такая запись уже существует',409);if(err.code==='23503')return sendError(reply,'RELATED_DATA_NOT_FOUND','Связанная запись не найдена',422);return sendError(reply,'INTERNAL_ERROR',process.env.NODE_ENV==='production'?'Внутренняя ошибка сервера':err.message,500)});
app.get('/health',async()=>{await q('SELECT 1');return {ok:true,service:'profi24-crm-api',version:'1.1.0'}});

app.post('/api/v1/auth/login',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(req,reply)=>{const {email,password}=req.body||{};if(!email||!password)return sendError(reply,'VALIDATION','Введите логин и пароль');const {rows}=await q('SELECT * FROM users WHERE lower(email)=lower($1) AND active=true',[email]);if(!rows[0]||!await bcrypt.compare(password,rows[0].password_hash))return sendError(reply,'INVALID_CREDENTIALS','Неверный логин или пароль',401);const u=rows[0];return {data:{access_token:app.jwt.sign({id:u.id,role:u.role,name:u.name,email:u.email},{expiresIn:'12h'}),user:{id:u.id,name:u.name,email:u.email,role:u.role}}}});
app.get('/api/v1/me',{preHandler:auth},async req=>({data:req.user}));
app.get('/api/v1/users',{preHandler:auth},async()=>({data:(await q('SELECT id,name,email,role FROM users WHERE active=true ORDER BY name')).rows}));

app.get('/api/v1/customers',{preHandler:auth},async req=>{const search=String(req.query?.search||'').trim();const p=[];let where='';if(search){p.push(`%${search}%`, `%${normalizePhone(search)}%`);where='WHERE c.name ILIKE $1 OR c.phone_norm LIKE $2'}const rows=(await q(`SELECT c.*,count(DISTINCT r.id)::int request_count,COALESCE(sum(r.paid),0)::numeric lifetime_paid FROM customers c LEFT JOIN requests r ON r.customer_id=c.id ${where} GROUP BY c.id ORDER BY c.created_at DESC LIMIT 500`,p)).rows;return {data:rows}});
app.get('/api/v1/customers/:id',{preHandler:auth},async(req,reply)=>{const c=(await q('SELECT * FROM customers WHERE id=$1',[req.params.id])).rows[0];if(!c)return sendError(reply,'NOT_FOUND','Клиент не найден',404);const [e,r]=await Promise.all([q('SELECT * FROM equipment WHERE customer_id=$1 ORDER BY created_at DESC',[c.id]),q(`${requestSelect} WHERE r.customer_id=$1 ORDER BY r.created_at DESC`,[c.id])]);return {data:{...c,equipment:e.rows,requests:r.rows}}});
app.post('/api/v1/customers',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {name,phone,email,address,notes}=req.body||{};if(!name||!phone)return sendError(reply,'VALIDATION','Имя и телефон обязательны');const pn=normalizePhone(phone);const dup=(await q('SELECT id,name,phone FROM customers WHERE phone_norm=$1 LIMIT 1',[pn])).rows[0];if(dup&&!req.body?.force)return reply.code(409).send({data:null,error:{code:'POSSIBLE_DUPLICATE_CUSTOMER',message:'Клиент с таким телефоном уже существует',candidate:dup}});const r=await q('INSERT INTO customers(name,phone,phone_norm,email,address,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,phone,pn,email||null,address||null,notes||null]);return reply.code(201).send({data:r.rows[0]})});
app.patch('/api/v1/customers/:id',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const old=(await q('SELECT * FROM customers WHERE id=$1',[req.params.id])).rows[0];if(!old)return sendError(reply,'NOT_FOUND','Клиент не найден',404);const b={...old,...req.body};const r=await q('UPDATE customers SET name=$1,phone=$2,phone_norm=$3,email=$4,address=$5,notes=$6,updated_at=now() WHERE id=$7 RETURNING *',[b.name,b.phone,normalizePhone(b.phone),b.email||null,b.address||null,b.notes||null,req.params.id]);return {data:r.rows[0]}});

app.get('/api/v1/equipment',{preHandler:auth},async req=>{const cid=req.query?.customer_id;const rows=(await q(`SELECT e.*,c.name customer_name FROM equipment e JOIN customers c ON c.id=e.customer_id ${cid?'WHERE e.customer_id=$1':''} ORDER BY e.created_at DESC`,cid?[cid]:[])).rows;return {data:rows}});
app.post('/api/v1/equipment',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {customer_id,category,brand,model,serial_number,notes}=req.body||{};if(!customer_id||!category)return sendError(reply,'VALIDATION','Клиент и категория обязательны');const r=await q('INSERT INTO equipment(customer_id,category,brand,model,serial_number,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[customer_id,category,brand||null,model||null,serial_number||null,notes||null]);return reply.code(201).send({data:r.rows[0]})});

app.get('/api/v1/requests',{preHandler:auth},async req=>{const p=[];const where=[];if(req.user.role==='ENGINEER'){p.push(req.user.id);where.push(`r.engineer_id=$${p.length}`)}if(req.query?.status){p.push(req.query.status);where.push(`r.status=$${p.length}`)}if(req.query?.overdue==='true')where.push(`r.sla_deadline<now() AND r.status NOT IN ('CLOSED','CANCELLED')`);if(req.query?.search){p.push(`%${req.query.search}%`);where.push(`(r.number ILIKE $${p.length} OR c.name ILIKE $${p.length} OR c.phone ILIKE $${p.length} OR r.complaint ILIKE $${p.length})`)}const rows=(await q(`${requestSelect} ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE WHEN r.status NOT IN ('CLOSED','CANCELLED') THEN 0 ELSE 1 END,r.created_at DESC LIMIT 1000`,p)).rows;return {data:rows}});
app.post('/api/v1/requests',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {customer_id,equipment_id,complaint,priority='NORMAL',scheduled_at,source='OTHER',original_request_id}=req.body||{};if(!customer_id||!complaint)return sendError(reply,'VALIDATION','Клиент и описание неисправности обязательны');if(equipment_id){const recent=(await q(`SELECT id,number,status,closed_at FROM requests WHERE equipment_id=$1 AND status<>'CANCELLED' AND created_at>now()-interval '90 days' ORDER BY created_at DESC LIMIT 1`,[equipment_id])).rows[0];if(recent&&!original_request_id&&!req.body?.force)return reply.code(409).send({data:null,error:{code:'POSSIBLE_REPEAT_REQUEST',message:'У этого оборудования есть недавняя заявка',previous_request:recent}})}const seq=(await q(`SELECT nextval('request_number_seq') n`)).rows[0].n;const number=`KST-${new Date().getFullYear()}-${String(seq).padStart(7,'0')}`;const sla=nowPlusMinutes(priority==='CRITICAL'?15:60);const r=await q('INSERT INTO requests(number,customer_id,equipment_id,manager_id,status,priority,source,complaint,scheduled_at,sla_deadline,original_request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[number,customer_id,equipment_id||null,req.user.id,'NEW',priority,source,complaint,scheduled_at||null,sla,original_request_id||null]);await history(null,r.rows[0].id,req.user.id,'REQUEST_CREATED',{source,priority});return reply.code(201).send({data:r.rows[0]})});
app.get('/api/v1/requests/:id',{preHandler:auth},async(req,reply)=>{const r=await getRequest(req.params.id);if(!r)return sendError(reply,'NOT_FOUND','Заявка не найдена',404);if(req.user.role==='ENGINEER'&&r.engineer_id!==req.user.id)return sendError(reply,'FORBIDDEN','Нет доступа к этой заявке',403);return {data:r}});
app.post('/api/v1/requests/:id/assign',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {engineer_id,scheduled_at}=req.body||{};if(!engineer_id)return sendError(reply,'VALIDATION','Выберите инженера');const u=(await q("SELECT id FROM users WHERE id=$1 AND role='ENGINEER' AND active=true",[engineer_id])).rows[0];if(!u)return sendError(reply,'VALIDATION','Инженер не найден');const r=await q("UPDATE requests SET engineer_id=$1,status='ASSIGNED',scheduled_at=COALESCE($2,scheduled_at),updated_at=now() WHERE id=$3 AND status IN ('NEW','ASSIGNED') RETURNING *",[engineer_id,scheduled_at||null,req.params.id]);if(!r.rows[0])return sendError(reply,'STATE_CONFLICT','Заявку нельзя назначить из текущего статуса',409);await history(null,req.params.id,req.user.id,'REQUEST_ASSIGNED',{engineer_id,scheduled_at});return {data:r.rows[0]}});
app.post('/api/v1/requests/:id/accept',{preHandler:roles('ENGINEER')},async(req,reply)=>{const r=await q("UPDATE requests SET status='ACCEPTED',updated_at=now() WHERE id=$1 AND engineer_id=$2 AND status='ASSIGNED' RETURNING *",[req.params.id,req.user.id]);if(!r.rows[0])return sendError(reply,'STATE_CONFLICT','Эта заявка не назначена вам или уже принята',409);await history(null,req.params.id,req.user.id,'REQUEST_ACCEPTED');return {data:r.rows[0]}});
app.post('/api/v1/requests/:id/status',{preHandler:auth},async(req,reply)=>{const {status}=req.body||{};const cur=(await q('SELECT * FROM requests WHERE id=$1',[req.params.id])).rows[0];if(!cur)return sendError(reply,'NOT_FOUND','Заявка не найдена',404);if(req.user.role==='ENGINEER'&&cur.engineer_id!==req.user.id)return sendError(reply,'FORBIDDEN','Нет доступа',403);if(!(transitions[cur.status]||[]).includes(status))return sendError(reply,'INVALID_TRANSITION',`Переход ${cur.status} → ${status} не разрешён`,409);if(status==='CLOSED'&&money(cur.paid)<money(cur.total))return sendError(reply,'PAYMENT_REQUIRED','Нельзя закрыть неоплаченную заявку',409);if(status==='TESTING'&&!cur.work_description)return sendError(reply,'WORK_REQUIRED','Сначала укажите выполненные работы');if(status==='PAYMENT_REQUIRED'&&!cur.test_result)return sendError(reply,'TEST_REQUIRED','Сначала внесите результат проверки');const r=await q(`UPDATE requests SET status=$1,updated_at=now(),closed_at=CASE WHEN $1='CLOSED' THEN now() ELSE closed_at END,cancelled_at=CASE WHEN $1='CANCELLED' THEN now() ELSE cancelled_at END WHERE id=$2 RETURNING *`,[status,req.params.id]);await history(null,req.params.id,req.user.id,'STATUS_CHANGED',{from:cur.status,to:status});return {data:r.rows[0]}});
app.post('/api/v1/requests/:id/diagnosis',{preHandler:auth},async(req,reply)=>{const {diagnosis}=req.body||{};if(!diagnosis?.trim())return sendError(reply,'VALIDATION','Заполните диагностику');const cur=(await q('SELECT * FROM requests WHERE id=$1',[req.params.id])).rows[0];if(req.user.role==='ENGINEER'&&cur?.engineer_id!==req.user.id)return sendError(reply,'FORBIDDEN','Нет доступа',403);const r=await q("UPDATE requests SET diagnosis=$1,status='APPROVAL_REQUIRED',updated_at=now() WHERE id=$2 AND status IN ('ACCEPTED','DIAGNOSTICS','APPROVAL_REQUIRED') RETURNING *",[diagnosis.trim(),req.params.id]);if(!r.rows[0])return sendError(reply,'STATE_CONFLICT','Диагностику нельзя сохранить из текущего статуса',409);await history(null,req.params.id,req.user.id,'DIAGNOSIS_COMPLETED');return {data:r.rows[0]}});
app.post('/api/v1/requests/:id/work',{preHandler:auth},async(req,reply)=>{const {work_description,total,direct_cost=0,channel='PHONE'}=req.body||{};if(!work_description?.trim()||money(total)<=0)return sendError(reply,'VALIDATION','Укажите работы и стоимость');const cur=(await q('SELECT * FROM requests WHERE id=$1',[req.params.id])).rows[0];if(req.user.role==='ENGINEER'&&cur?.engineer_id!==req.user.id)return sendError(reply,'FORBIDDEN','Нет доступа',403);const result=await tx(async c=>{const last=(await c.query('SELECT COALESCE(max(version),0)::int v FROM approvals WHERE request_id=$1',[req.params.id])).rows[0].v;await c.query('INSERT INTO approvals(request_id,version,amount,channel,status,created_by) VALUES($1,$2,$3,$4,$5,$6)',[req.params.id,last+1,total,channel,'APPROVED',req.user.id]);const r=await c.query("UPDATE requests SET work_description=$1,total=$2,direct_cost=$3,status='REPAIR',updated_at=now() WHERE id=$4 RETURNING *",[work_description.trim(),total,direct_cost,req.params.id]);await history(c,req.params.id,req.user.id,'WORK_APPROVED',{total,direct_cost,channel,version:last+1});return r.rows[0]});return {data:result}});
app.post('/api/v1/requests/:id/test',{preHandler:auth},async(req,reply)=>{const {test_result}=req.body||{};if(!test_result?.trim())return sendError(reply,'VALIDATION','Укажите результат проверки');const r=await q("UPDATE requests SET test_result=$1,status='PAYMENT_REQUIRED',updated_at=now() WHERE id=$2 AND status IN ('REPAIR','TESTING') RETURNING *",[test_result.trim(),req.params.id]);if(!r.rows[0])return sendError(reply,'STATE_CONFLICT','Заявка не находится на ремонте/проверке',409);await history(null,req.params.id,req.user.id,'TEST_COMPLETED',{test_result});return {data:r.rows[0]}});

app.get('/api/v1/requests/:id/parts',{preHandler:auth},async req=>({data:(await q('SELECT * FROM parts WHERE request_id=$1 ORDER BY created_at DESC',[req.params.id])).rows}));
app.post('/api/v1/requests/:id/parts',{preHandler:auth},async(req,reply)=>{const {name,oem_code,qty=1,purchase_price=0,sale_price=0,supplier,status='REQUESTED',eta}=req.body||{};if(!name?.trim()||Number(qty)<=0)return sendError(reply,'VALIDATION','Укажите запчасть и количество');const r=await q('INSERT INTO parts(request_id,name,oem_code,qty,purchase_price,sale_price,supplier,status,eta,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[req.params.id,name.trim(),oem_code||null,qty,purchase_price,sale_price,supplier||null,status,eta||null,req.user.id]);if(status==='ORDERED'||status==='REQUESTED')await q("UPDATE requests SET status='WAITING_PART',updated_at=now() WHERE id=$1 AND status IN ('APPROVAL_REQUIRED','REPAIR')",[req.params.id]);await history(null,req.params.id,req.user.id,'PART_ADDED',{part_id:r.rows[0].id,name,status});return reply.code(201).send({data:r.rows[0]})});
app.patch('/api/v1/parts/:id',{preHandler:auth},async(req,reply)=>{const old=(await q('SELECT * FROM parts WHERE id=$1',[req.params.id])).rows[0];if(!old)return sendError(reply,'NOT_FOUND','Запчасть не найдена',404);const b={...old,...req.body};const r=await q('UPDATE parts SET name=$1,oem_code=$2,qty=$3,purchase_price=$4,sale_price=$5,supplier=$6,status=$7,eta=$8,updated_at=now() WHERE id=$9 RETURNING *',[b.name,b.oem_code,b.qty,b.purchase_price,b.sale_price,b.supplier,b.status,b.eta,req.params.id]);if(b.status==='RECEIVED'){const managers=(await q("SELECT id FROM users WHERE role IN ('MANAGER','OWNER') AND active=true ORDER BY role='MANAGER' DESC LIMIT 1")).rows;for(const u of managers)await q('INSERT INTO tasks(title,request_id,assigned_to,priority,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6)',['Запчасть поступила — назначить клиента',old.request_id,u.id,'HIGH',nowPlusMinutes(120),req.user.id]);await history(null,old.request_id,req.user.id,'PART_RECEIVED',{part_id:old.id})}return {data:r.rows[0]}});

app.post('/api/v1/requests/:id/payment',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const amount=money(req.body?.amount);const method=req.body?.method||'KASPI';if(amount<=0)return sendError(reply,'VALIDATION','Сумма должна быть больше 0');const result=await tx(async c=>{const cur=(await c.query('SELECT * FROM requests WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!cur)throw new Error('Заявка не найдена');await c.query('INSERT INTO payments(request_id,amount,method,kind,reference,created_by) VALUES($1,$2,$3,$4,$5,$6)',[req.params.id,amount,method,'PAYMENT',req.body?.reference||null,req.user.id]);const newPaid=money(cur.paid)+amount;const status=newPaid>=money(cur.total)&&money(cur.total)>0?'CLOSED':'PAYMENT_REQUIRED';const r=await c.query("UPDATE requests SET paid=$1,status=$2,closed_at=CASE WHEN $2='CLOSED' THEN now() ELSE closed_at END,updated_at=now() WHERE id=$3 RETURNING *",[newPaid,status,req.params.id]);await history(c,req.params.id,req.user.id,'PAYMENT_RECEIVED',{amount,method});if(status==='CLOSED'){const managerId=cur.manager_id||req.user.id;await c.query('INSERT INTO tasks(title,request_id,assigned_to,priority,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6)',['Контроль качества после ремонта',req.params.id,managerId,'NORMAL',new Date(Date.now()+24*3600000),req.user.id]);await history(c,req.params.id,req.user.id,'REQUEST_CLOSED',{reason:'PAID_IN_FULL'})}return r.rows[0]});return {data:result}});
app.post('/api/v1/payments/:id/refund',{preHandler:roles('OWNER')},async(req,reply)=>{const amount=money(req.body?.amount);if(amount<=0)return sendError(reply,'VALIDATION','Укажите сумму возврата');const p=(await q('SELECT * FROM payments WHERE id=$1',[req.params.id])).rows[0];if(!p||p.kind!=='PAYMENT')return sendError(reply,'NOT_FOUND','Исходный платёж не найден',404);const already=money((await q("SELECT COALESCE(sum(amount),0) s FROM payments WHERE request_id=$1 AND kind='REFUND'",[p.request_id])).rows[0].s);if(already+amount>money((await q("SELECT COALESCE(sum(amount),0) s FROM payments WHERE request_id=$1 AND kind='PAYMENT'",[p.request_id])).rows[0].s))return sendError(reply,'VALIDATION','Сумма возвратов превышает полученную оплату');const r=await q('INSERT INTO payments(request_id,amount,method,kind,reference,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[p.request_id,amount,p.method,'REFUND',req.body?.reason||null,req.user.id]);await q('UPDATE requests SET paid=GREATEST(0,paid-$1),updated_at=now() WHERE id=$2',[amount,p.request_id]);await history(null,p.request_id,req.user.id,'PAYMENT_REFUNDED',{amount,reason:req.body?.reason});return {data:r.rows[0]}});

app.get('/api/v1/tasks',{preHandler:auth},async req=>{const p=[];let where='';if(req.user.role!=='OWNER'){p.push(req.user.id);where='WHERE t.assigned_to=$1'}const rows=(await q(`SELECT t.*,u.name assigned_name,r.number request_number,c.name customer_name FROM tasks t JOIN users u ON u.id=t.assigned_to LEFT JOIN requests r ON r.id=t.request_id LEFT JOIN customers c ON c.id=r.customer_id ${where} ORDER BY CASE WHEN t.status='OPEN' THEN 0 ELSE 1 END,t.due_at NULLS LAST,t.created_at DESC`,p)).rows;return {data:rows}});
app.post('/api/v1/tasks',{preHandler:auth},async(req,reply)=>{const {title,request_id,assigned_to,priority='NORMAL',due_at}=req.body||{};if(!title||!assigned_to)return sendError(reply,'VALIDATION','Укажите задачу и ответственного');const r=await q('INSERT INTO tasks(title,request_id,assigned_to,priority,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[title,request_id||null,assigned_to,priority,due_at||null,req.user.id]);return reply.code(201).send({data:r.rows[0]})});
app.post('/api/v1/tasks/:id/complete',{preHandler:auth},async(req,reply)=>{const r=await q("UPDATE tasks SET status='DONE',completed_at=now() WHERE id=$1 AND (assigned_to=$2 OR $3='OWNER') RETURNING *",[req.params.id,req.user.id,req.user.role]);if(!r.rows[0])return sendError(reply,'FORBIDDEN','Нельзя закрыть эту задачу',403);return {data:r.rows[0]}});

app.get('/api/v1/complaints',{preHandler:auth},async()=>({data:(await q(`SELECT co.*,r.number request_number,c.name customer_name,u.name responsible_name FROM complaints co LEFT JOIN requests r ON r.id=co.request_id JOIN customers c ON c.id=co.customer_id LEFT JOIN users u ON u.id=co.responsible_id ORDER BY CASE WHEN co.status='OPEN' THEN 0 ELSE 1 END,co.created_at DESC`)).rows}));
app.post('/api/v1/complaints',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const {request_id,customer_id,text,severity='NORMAL'}=req.body||{};if(!customer_id||!text)return sendError(reply,'VALIDATION','Укажите клиента и текст обращения');const seq=Date.now().toString().slice(-6);const number=`RC-${new Date().getFullYear()}-${seq}`;const responsible=(await q("SELECT id FROM users WHERE role='OWNER' AND active=true ORDER BY id LIMIT 1")).rows[0]?.id||req.user.id;const r=await q('INSERT INTO complaints(number,request_id,customer_id,text,severity,responsible_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[number,request_id||null,customer_id,text,severity,responsible,req.user.id]);if(request_id)await history(null,request_id,req.user.id,'COMPLAINT_CREATED',{complaint_id:r.rows[0].id,severity});await q('INSERT INTO tasks(title,request_id,assigned_to,priority,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6)',['Разобрать рекламацию '+number,request_id||null,responsible,severity==='CRITICAL'?'CRITICAL':'HIGH',nowPlusMinutes(60),req.user.id]);return reply.code(201).send({data:r.rows[0]})});
app.patch('/api/v1/complaints/:id',{preHandler:roles('OWNER','MANAGER')},async(req,reply)=>{const old=(await q('SELECT * FROM complaints WHERE id=$1',[req.params.id])).rows[0];if(!old)return sendError(reply,'NOT_FOUND','Рекламация не найдена',404);const b={...old,...req.body};const closing=b.status==='CLOSED';const r=await q('UPDATE complaints SET status=$1,classification=$2,resolution=$3,responsible_id=$4,closed_at=CASE WHEN $1=\'CLOSED\' THEN now() ELSE closed_at END WHERE id=$5 RETURNING *',[b.status,b.classification||null,b.resolution||null,b.responsible_id||old.responsible_id,req.params.id]);if(['G4','G5'].includes(b.classification)&&old.request_id){const exists=(await q('SELECT id FROM quality_incidents WHERE request_id=$1 AND status=\'OPEN\' LIMIT 1',[old.request_id])).rows[0];if(!exists)await q('INSERT INTO quality_incidents(request_id,category,description,created_by) VALUES($1,$2,$3,$4)',[old.request_id,b.classification==='G4'?'DIAGNOSTIC_ERROR':'REPAIR_ERROR',b.resolution||b.text,req.user.id])}return {data:r.rows[0]}});

app.get('/api/v1/quality-incidents',{preHandler:roles('OWNER','MANAGER')},async()=>({data:(await q(`SELECT qi.*,r.number request_number,u.name employee_name FROM quality_incidents qi LEFT JOIN requests r ON r.id=qi.request_id LEFT JOIN users u ON u.id=qi.employee_id ORDER BY qi.created_at DESC`)).rows}));
app.post('/api/v1/quality-incidents/:id/close',{preHandler:roles('OWNER')},async(req,reply)=>{const {root_cause,prevention}=req.body||{};if(!root_cause||!prevention)return sendError(reply,'VALIDATION','Укажите первопричину и профилактику');const r=await q("UPDATE quality_incidents SET root_cause=$1,prevention=$2,status='CLOSED',closed_at=now() WHERE id=$3 RETURNING *",[root_cause,prevention,req.params.id]);return {data:r.rows[0]}});

app.get('/api/v1/dashboard',{preHandler:auth},async req=>{const own=req.user.role==='ENGINEER'?'WHERE engineer_id=$1':'';const p=req.user.role==='ENGINEER'?[req.user.id]:[];const {rows}=await q(`SELECT count(*)::int total,count(*) FILTER(WHERE status='NEW')::int new,count(*) FILTER(WHERE status NOT IN ('CLOSED','CANCELLED'))::int active,count(*) FILTER(WHERE status='CLOSED')::int closed,count(*) FILTER(WHERE sla_deadline<now() AND status NOT IN ('CLOSED','CANCELLED'))::int overdue,COALESCE(sum(total) FILTER(WHERE status='CLOSED'),0)::numeric revenue,COALESCE(sum(paid),0)::numeric paid,COALESCE(sum(total-direct_cost) FILTER(WHERE status='CLOSED'),0)::numeric gross_profit FROM requests ${own}`,p);const tasks=req.user.role==='ENGINEER'?(await q("SELECT count(*)::int c FROM tasks WHERE assigned_to=$1 AND status='OPEN'",[req.user.id])).rows[0].c:(await q("SELECT count(*)::int c FROM tasks WHERE status='OPEN'")).rows[0].c;const complaints=(await q("SELECT count(*)::int c FROM complaints WHERE status='OPEN'")).rows[0].c;return {data:{...rows[0],tasks_open:tasks,complaints_open:complaints}}});
app.get('/api/v1/dashboard/finance',{preHandler:roles('OWNER','MANAGER')},async()=>{const totals=(await q(`SELECT COALESCE(sum(total),0)::numeric revenue,COALESCE(sum(direct_cost),0)::numeric direct_cost,COALESCE(sum(total-direct_cost),0)::numeric gross_profit,COALESCE(sum(paid),0)::numeric paid,COALESCE(sum(GREATEST(total-paid,0)) FILTER(WHERE status NOT IN ('CANCELLED')),0)::numeric outstanding FROM requests WHERE created_at>=date_trunc('month',now())`)).rows[0];const byCategory=(await q(`SELECT COALESCE(e.category,'Без категории') category,count(*)::int jobs,COALESCE(sum(r.total),0)::numeric revenue,COALESCE(sum(r.total-r.direct_cost),0)::numeric gross_profit FROM requests r LEFT JOIN equipment e ON e.id=r.equipment_id WHERE r.created_at>=date_trunc('month',now()) GROUP BY e.category ORDER BY revenue DESC`)).rows;return {data:{totals,by_category:byCategory}}});

const close=async()=>{try{await pool.end()}finally{process.exit(0)}};process.on('SIGTERM',close);process.on('SIGINT',close);
app.listen({port:Number(process.env.PORT||8080),host:'0.0.0.0'});
