import Fastify from 'fastify';
import cors from '@fastify/cors';
import jwt from '@fastify/jwt';
import bcrypt from 'bcryptjs';
import pg from 'pg';

const app=Fastify({logger:true});
await app.register(cors,{origin:true});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret'});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
const q=(text,params=[])=>pool.query(text,params);

async function init(){
 await q(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('OWNER','MANAGER','ENGINEER')),active BOOLEAN DEFAULT TRUE);`);
 await q(`CREATE TABLE IF NOT EXISTS customers(id SERIAL PRIMARY KEY,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,address TEXT,created_at TIMESTAMPTZ DEFAULT now());`);
 await q(`CREATE TABLE IF NOT EXISTS equipment(id SERIAL PRIMARY KEY,customer_id INT REFERENCES customers(id) ON DELETE CASCADE,category TEXT NOT NULL,brand TEXT,model TEXT,serial_number TEXT,created_at TIMESTAMPTZ DEFAULT now());`);
 await q(`CREATE TABLE IF NOT EXISTS requests(id SERIAL PRIMARY KEY,number TEXT UNIQUE NOT NULL,customer_id INT REFERENCES customers(id),equipment_id INT REFERENCES equipment(id),engineer_id INT REFERENCES users(id),status TEXT NOT NULL DEFAULT 'NEW',priority TEXT NOT NULL DEFAULT 'NORMAL',complaint TEXT NOT NULL,diagnosis TEXT,work_description TEXT,total NUMERIC(12,2) DEFAULT 0,paid NUMERIC(12,2) DEFAULT 0,scheduled_at TIMESTAMPTZ,sla_deadline TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),closed_at TIMESTAMPTZ);`);
 await q(`CREATE TABLE IF NOT EXISTS request_history(id SERIAL PRIMARY KEY,request_id INT REFERENCES requests(id) ON DELETE CASCADE,user_id INT REFERENCES users(id),action TEXT NOT NULL,details JSONB DEFAULT '{}',created_at TIMESTAMPTZ DEFAULT now());`);
 const {rows}=await q('SELECT count(*)::int c FROM users');
 if(!rows[0].c){const h=await bcrypt.hash('profi24',10);for(const u of [['Александр','owner@profi24.kz','OWNER'],['Менеджер','manager@profi24.kz','MANAGER'],['Инженер','engineer@profi24.kz','ENGINEER']]) await q('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4)',[u[0],u[1],h,u[2]]);}
}
await init();

app.decorate('auth',async req=>{try{await req.jwtVerify()}catch{throw app.httpErrors?.unauthorized?.()||new Error('Unauthorized')}});
const auth=async(req,reply)=>{try{await req.jwtVerify()}catch{return reply.code(401).send({error:{code:'UNAUTHORIZED',message:'Требуется авторизация'}})}};
const history=(id,user,action,details={})=>q('INSERT INTO request_history(request_id,user_id,action,details) VALUES($1,$2,$3,$4)',[id,user,action,details]);

app.get('/health',async()=>({ok:true}));
app.post('/api/v1/auth/login',async(req,reply)=>{const {email,password}=req.body||{};const {rows}=await q('SELECT * FROM users WHERE email=$1 AND active=true',[email]);if(!rows[0]||!await bcrypt.compare(password,rows[0].password_hash))return reply.code(401).send({error:{message:'Неверный логин или пароль'}});const u=rows[0];return {data:{access_token:app.jwt.sign({id:u.id,role:u.role,name:u.name}),user:{id:u.id,name:u.name,email:u.email,role:u.role}}};});
app.get('/api/v1/me',{preHandler:auth},async req=>({data:req.user}));
app.get('/api/v1/users',{preHandler:auth},async()=>({data:(await q('SELECT id,name,email,role FROM users WHERE active=true ORDER BY name')).rows}));
app.get('/api/v1/customers',{preHandler:auth},async()=>({data:(await q('SELECT * FROM customers ORDER BY created_at DESC')).rows}));
app.post('/api/v1/customers',{preHandler:auth},async(req,reply)=>{const {name,phone,email,address}=req.body||{};if(!name||!phone)return reply.code(422).send({error:{message:'Имя и телефон обязательны'}});const r=await q('INSERT INTO customers(name,phone,email,address) VALUES($1,$2,$3,$4) RETURNING *',[name,phone,email||null,address||null]);return reply.code(201).send({data:r.rows[0]});});
app.get('/api/v1/equipment',{preHandler:auth},async()=>({data:(await q('SELECT e.*,c.name customer_name FROM equipment e JOIN customers c ON c.id=e.customer_id ORDER BY e.created_at DESC')).rows}));
app.post('/api/v1/equipment',{preHandler:auth},async(req,reply)=>{const {customer_id,category,brand,model,serial_number}=req.body||{};if(!customer_id||!category)return reply.code(422).send({error:{message:'Клиент и категория обязательны'}});const r=await q('INSERT INTO equipment(customer_id,category,brand,model,serial_number) VALUES($1,$2,$3,$4,$5) RETURNING *',[customer_id,category,brand||null,model||null,serial_number||null]);return reply.code(201).send({data:r.rows[0]});});
app.get('/api/v1/requests',{preHandler:auth},async req=>{let where='',p=[];if(req.user.role==='ENGINEER'){where='WHERE r.engineer_id=$1';p=[req.user.id]}const rows=(await q(`SELECT r.*,c.name customer_name,c.phone,e.category,e.brand,e.model,u.name engineer_name FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN equipment e ON e.id=r.equipment_id LEFT JOIN users u ON u.id=r.engineer_id ${where} ORDER BY r.created_at DESC`,p)).rows;return {data:rows};});
app.post('/api/v1/requests',{preHandler:auth},async(req,reply)=>{const {customer_id,equipment_id,complaint,priority='NORMAL',scheduled_at}=req.body||{};if(!customer_id||!complaint)return reply.code(422).send({error:{message:'Клиент и описание неисправности обязательны'}});const number=`KST-${new Date().getFullYear()}-${String(Date.now()).slice(-7)}`;const sla=new Date(Date.now()+60*60*1000);const r=await q('INSERT INTO requests(number,customer_id,equipment_id,complaint,priority,scheduled_at,sla_deadline) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[number,customer_id,equipment_id||null,complaint,priority,scheduled_at||null,sla]);await history(r.rows[0].id,req.user.id,'REQUEST_CREATED');return reply.code(201).send({data:r.rows[0]});});
app.get('/api/v1/requests/:id',{preHandler:auth},async req=>{const r=(await q('SELECT r.*,c.name customer_name,c.phone,c.address,e.category,e.brand,e.model,e.serial_number,u.name engineer_name FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN equipment e ON e.id=r.equipment_id LEFT JOIN users u ON u.id=r.engineer_id WHERE r.id=$1',[req.params.id])).rows[0];const h=(await q('SELECT h.*,u.name user_name FROM request_history h LEFT JOIN users u ON u.id=h.user_id WHERE request_id=$1 ORDER BY created_at DESC',[req.params.id])).rows;return {data:{...r,history:h}};});
app.post('/api/v1/requests/:id/assign',{preHandler:auth},async(req,reply)=>{if(req.user.role==='ENGINEER')return reply.code(403).send({error:{message:'Недостаточно прав'}});const {engineer_id}=req.body||{};const r=await q("UPDATE requests SET engineer_id=$1,status='ASSIGNED' WHERE id=$2 RETURNING *",[engineer_id,req.params.id]);await history(req.params.id,req.user.id,'REQUEST_ASSIGNED',{engineer_id});return {data:r.rows[0]};});
app.post('/api/v1/requests/:id/accept',{preHandler:auth},async req=>{const r=await q("UPDATE requests SET status='ACCEPTED' WHERE id=$1 AND engineer_id=$2 RETURNING *",[req.params.id,req.user.id]);await history(req.params.id,req.user.id,'REQUEST_ACCEPTED');return {data:r.rows[0]};});
app.post('/api/v1/requests/:id/status',{preHandler:auth},async(req,reply)=>{const allowed=['NEW','ASSIGNED','ACCEPTED','DIAGNOSTICS','APPROVAL_REQUIRED','REPAIR','TESTING','PAYMENT_REQUIRED','CLOSED','CANCELLED'];const {status}=req.body||{};if(!allowed.includes(status))return reply.code(422).send({error:{message:'Недопустимый статус'}});const closed=status==='CLOSED'?new Date():null;const r=await q('UPDATE requests SET status=$1,closed_at=COALESCE($2,closed_at) WHERE id=$3 RETURNING *',[status,closed,req.params.id]);await history(req.params.id,req.user.id,'STATUS_CHANGED',{status});return {data:r.rows[0]};});
app.post('/api/v1/requests/:id/diagnosis',{preHandler:auth},async(req,reply)=>{const {diagnosis}=req.body||{};if(!diagnosis)return reply.code(422).send({error:{message:'Заполните диагностику'}});const r=await q("UPDATE requests SET diagnosis=$1,status='APPROVAL_REQUIRED' WHERE id=$2 RETURNING *",[diagnosis,req.params.id]);await history(req.params.id,req.user.id,'DIAGNOSIS_COMPLETED');return {data:r.rows[0]};});
app.post('/api/v1/requests/:id/work',{preHandler:auth},async(req)=>{const {work_description,total}=req.body||{};const r=await q("UPDATE requests SET work_description=$1,total=$2,status='REPAIR' WHERE id=$3 RETURNING *",[work_description||'',Number(total)||0,req.params.id]);await history(req.params.id,req.user.id,'WORK_APPROVED',{total});return {data:r.rows[0]};});
app.post('/api/v1/requests/:id/payment',{preHandler:auth},async(req,reply)=>{if(req.user.role==='ENGINEER')return reply.code(403).send({error:{message:'Недостаточно прав'}});const amount=Number(req.body?.amount||0);if(amount<=0)return reply.code(422).send({error:{message:'Сумма должна быть больше 0'}});const r=await q('UPDATE requests SET paid=paid+$1,status=CASE WHEN paid+$1>=total THEN \'CLOSED\' ELSE \'PAYMENT_REQUIRED\' END,closed_at=CASE WHEN paid+$1>=total THEN now() ELSE closed_at END WHERE id=$2 RETURNING *',[amount,req.params.id]);await history(req.params.id,req.user.id,'PAYMENT_RECEIVED',{amount});return {data:r.rows[0]};});
app.get('/api/v1/dashboard',{preHandler:auth},async req=>{const own=req.user.role==='ENGINEER'?'WHERE engineer_id=$1':'';const p=req.user.role==='ENGINEER'?[req.user.id]:[];const {rows}=await q(`SELECT count(*)::int total,count(*) FILTER(WHERE status='NEW')::int new,count(*) FILTER(WHERE status NOT IN ('CLOSED','CANCELLED'))::int active,count(*) FILTER(WHERE status='CLOSED')::int closed,count(*) FILTER(WHERE sla_deadline<now() AND status NOT IN ('CLOSED','CANCELLED'))::int overdue,COALESCE(sum(total) FILTER(WHERE status='CLOSED'),0)::numeric revenue,COALESCE(sum(paid),0)::numeric paid FROM requests ${own}`,p);return {data:rows[0]};});

app.listen({port:Number(process.env.PORT||8080),host:'0.0.0.0'});
