import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import jwt from '@fastify/jwt';
import rateLimit from '@fastify/rate-limit';
import pg from 'pg';
import {pathToFileURL} from 'node:url';
import {authenticate,requireOrder} from './access.js';
import {can,PERMISSIONS} from './rbac.js';
import {knowledgeBaseStatements} from './knowledge-base-schema.js';

const statuses=new Set(['DRAFT','PUBLISHED','ARCHIVED']);
const actions=new Set(['VIEW','APPLIED']);
const clean=(v,max=4000)=>String(v??'').trim().slice(0,max);
const fail=(reply,code,message,status=422)=>reply.code(status).send({data:null,error:{code,message}});
const editable=['title','category','brand','model','error_code','tags','symptoms','cause','solution','verification','safety_notes'];
const articleSelect=`SELECT a.*,cu.name created_by_name,uu.name updated_by_name,pu.name published_by_name,
 (SELECT count(*)::int FROM knowledge_feedback f WHERE f.article_id=a.id AND f.helpful=true) helpful_count,
 (SELECT count(*)::int FROM knowledge_feedback f WHERE f.article_id=a.id AND f.helpful=false) not_helpful_count,
 (SELECT count(*)::int FROM knowledge_use_events e WHERE e.article_id=a.id AND e.action='APPLIED') applied_count
 FROM knowledge_articles a JOIN users cu ON cu.id=a.created_by JOIN users uu ON uu.id=a.updated_by LEFT JOIN users pu ON pu.id=a.published_by`;

export async function prepareKnowledgeBase(pool){for(const sql of knowledgeBaseStatements)await pool.query(sql)}

export function installKnowledgeBase(app,pool){
 const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}};
 const auth=async(req,reply)=>{if(!await authenticate(req,reply,pool))return};
 const permit=permission=>async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!can(req.user.role,permission))return fail(reply,'FORBIDDEN','Недостаточно прав',403)};
 const view=permit(PERMISSIONS.KNOWLEDGE_VIEW),manage=permit(PERMISSIONS.KNOWLEDGE_MANAGE);
 const canManage=req=>can(req.user?.role,PERMISSIONS.KNOWLEDGE_MANAGE);
 async function byId(c,id){return(await c.query(`${articleSelect} WHERE a.id=$1`,[Number(id)])).rows[0]||null}
 function snapshot(row){const out={id:row.id,version:row.version,status:row.status};for(const k of editable)out[k]=row[k]??'';out.published_at=row.published_at||null;return out}
 async function storeVersion(c,row,userId){await c.query('INSERT INTO knowledge_article_versions(article_id,version,snapshot,changed_by) VALUES($1,$2,$3::jsonb,$4)',[row.id,row.version,JSON.stringify(snapshot(row)),userId])}
 async function visibleArticle(req,reply,id){const a=await byId(pool,id);if(!a)return fail(reply,'NOT_FOUND','Статья не найдена',404);if(a.status!=='PUBLISHED'&&!canManage(req))return fail(reply,'NOT_FOUND','Статья не найдена',404);return a}
 function textScore(article,ctx,q,errorCode){let score=0;const reasons=[];const eq=(a,b)=>a&&b&&clean(a,300).toLowerCase()===clean(b,300).toLowerCase();const contains=(a,b)=>a&&b&&clean(a,1000).toLowerCase().includes(clean(b,300).toLowerCase());if(eq(article.category,ctx.category)){score+=30;reasons.push('категория')}if(eq(article.brand,ctx.brand)){score+=28;reasons.push('бренд')}if(article.model&&ctx.model&&(contains(ctx.model,article.model)||contains(article.model,ctx.model))){score+=22;reasons.push('модель')}if(article.error_code&&errorCode&&eq(article.error_code,errorCode)){score+=45;reasons.push('код ошибки')}
  const hay=[article.title,article.tags,article.symptoms,article.cause,article.solution,article.verification,article.error_code].join(' ').toLowerCase(),signal=[q,ctx.symptoms,ctx.diagnosis,errorCode].join(' ').toLowerCase();if(q&&hay.includes(q.toLowerCase())){score+=18;reasons.push('поиск')}const tokens=[...new Set(signal.split(/[^a-zа-яё0-9]+/i).filter(x=>x.length>=3))].slice(0,30);let overlap=0;for(const t of tokens)if(hay.includes(t))overlap++;if(overlap){score+=Math.min(20,overlap*2);reasons.push('симптомы')}const votes=Number(article.helpful_count||0)+Number(article.not_helpful_count||0);if(votes)score+=Math.min(10,Math.round(Number(article.helpful_count||0)/votes*10));return{score,reasons}}

 app.get('/health',async()=>{await pool.query('SELECT 1');return{ok:true,service:'profi24-knowledge-base',version:'1.0.0'}});
 app.get('/api/v1/articles',{preHandler:view},async(req,reply)=>{try{const params=[],where=[];if(!canManage(req))where.push("a.status='PUBLISHED'");else if(req.query?.status){const s=clean(req.query.status,20).toUpperCase();if(!statuses.has(s))return fail(reply,'VALIDATION','Некорректный статус');params.push(s);where.push(`a.status=$${params.length}`)}const q=clean(req.query?.search,200);if(q){params.push(`%${q}%`);where.push(`(a.title ILIKE $${params.length} OR COALESCE(a.category,'') ILIKE $${params.length} OR COALESCE(a.brand,'') ILIKE $${params.length} OR COALESCE(a.model,'') ILIKE $${params.length} OR COALESCE(a.error_code,'') ILIKE $${params.length} OR COALESCE(a.tags,'') ILIKE $${params.length} OR a.symptoms ILIKE $${params.length} OR a.solution ILIKE $${params.length})`)}for(const field of ['category','brand'])if(req.query?.[field]){params.push(clean(req.query[field],160));where.push(`lower(COALESCE(a.${field},''))=lower($${params.length})`)}const rows=(await pool.query(`${articleSelect} ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE a.status WHEN 'PUBLISHED' THEN 0 WHEN 'DRAFT' THEN 1 ELSE 2 END,a.updated_at DESC LIMIT 500`,params)).rows;return{data:rows}}catch(e){throw e}});
 app.get('/api/v1/articles/:id',{preHandler:view},async(req,reply)=>{const a=await visibleArticle(req,reply,req.params.id);if(!a||reply.sent)return;return{data:a}});
 app.post('/api/v1/articles',{preHandler:manage},async(req,reply)=>{const b=req.body||{},title=clean(b.title,300),solution=clean(b.solution,12000);if(!title||!solution)return fail(reply,'VALIDATION','Укажите название и проверенное решение');const row=await tx(async c=>{const vals=editable.map(k=>k==='title'?title:k==='solution'?solution:clean(b[k],12000));const r=(await c.query(`INSERT INTO knowledge_articles(${editable.join(',')},created_by,updated_by) VALUES(${editable.map((_,i)=>'$'+(i+1)).join(',')},$${editable.length+1},$${editable.length+2}) RETURNING *`,[...vals,req.user.id,req.user.id])).rows[0];await storeVersion(c,r,req.user.id);return r});return reply.code(201).send({data:await byId(pool,row.id)})});
 app.patch('/api/v1/articles/:id',{preHandler:manage},async(req,reply)=>{const old=await byId(pool,req.params.id);if(!old)return fail(reply,'NOT_FOUND','Статья не найдена',404);const b=req.body||{},next={};for(const k of editable)next[k]=b[k]===undefined?old[k]:clean(b[k],k==='title'?300:12000);if(!next.title||!next.solution)return fail(reply,'VALIDATION','Название и решение обязательны');const row=await tx(async c=>{const params=editable.map(k=>next[k]);const sets=editable.map((k,i)=>`${k}=$${i+1}`);params.push(req.user.id,Number(old.version)+1,old.id);const r=(await c.query(`UPDATE knowledge_articles SET ${sets.join(',')},updated_by=$${editable.length+1},version=$${editable.length+2},updated_at=clock_timestamp() WHERE id=$${editable.length+3} RETURNING *`,params)).rows[0];await storeVersion(c,r,req.user.id);return r});return{data:await byId(pool,row.id)}});
 app.post('/api/v1/articles/:id/publish',{preHandler:manage},async(req,reply)=>{const old=await byId(pool,req.params.id);if(!old)return fail(reply,'NOT_FOUND','Статья не найдена',404);if(!clean(old.solution))return fail(reply,'VALIDATION','Нельзя публиковать статью без решения');const row=await tx(async c=>{const r=(await c.query("UPDATE knowledge_articles SET status='PUBLISHED',published_by=$1,published_at=clock_timestamp(),updated_by=$1,version=version+1,updated_at=clock_timestamp() WHERE id=$2 RETURNING *",[req.user.id,old.id])).rows[0];await storeVersion(c,r,req.user.id);return r});return{data:await byId(pool,row.id)}});
 app.post('/api/v1/articles/:id/archive',{preHandler:manage},async(req,reply)=>{const old=await byId(pool,req.params.id);if(!old)return fail(reply,'NOT_FOUND','Статья не найдена',404);const row=await tx(async c=>{const r=(await c.query("UPDATE knowledge_articles SET status='ARCHIVED',updated_by=$1,version=version+1,updated_at=clock_timestamp() WHERE id=$2 RETURNING *",[req.user.id,old.id])).rows[0];await storeVersion(c,r,req.user.id);return r});return{data:await byId(pool,row.id)}});
 app.get('/api/v1/articles/:id/versions',{preHandler:manage},async(req,reply)=>{if(!await byId(pool,req.params.id))return fail(reply,'NOT_FOUND','Статья не найдена',404);return{data:(await pool.query('SELECT v.*,u.name changed_by_name FROM knowledge_article_versions v JOIN users u ON u.id=v.changed_by WHERE article_id=$1 ORDER BY version DESC',[Number(req.params.id)])).rows}});
 app.get('/api/v1/suggest',{preHandler:view},async(req,reply)=>{const requestId=Number(req.query?.request_id||0);if(!requestId)return fail(reply,'REQUEST_REQUIRED','Укажите заказ');try{await requireOrder(pool,req.user,requestId)}catch(e){return fail(reply,e.code||'FORBIDDEN',e.message,e.statusCode||403)}const ctx=(await pool.query(`SELECT r.id,e.category,e.brand,e.model,COALESCE(d.symptoms,'') symptoms,COALESCE(d.diagnosis,'') diagnosis FROM requests r LEFT JOIN equipment e ON e.id=r.equipment_id LEFT JOIN request_diagnostics d ON d.request_id=r.id WHERE r.id=$1 AND r.deleted_at IS NULL`,[requestId])).rows[0];if(!ctx)return fail(reply,'NOT_FOUND','Заказ не найден',404);const q=clean(req.query?.q,300),errorCode=clean(req.query?.error_code,100);const articles=(await pool.query(`${articleSelect} WHERE a.status='PUBLISHED' ORDER BY a.updated_at DESC LIMIT 500`)).rows;const ranked=articles.map(a=>{const s=textScore(a,ctx,q,errorCode);return{...a,match_score:s.score,match_reasons:s.reasons}}).filter(x=>x.match_score>0).sort((a,b)=>b.match_score-a.match_score||Number(b.helpful_count)-Number(a.helpful_count)).slice(0,12);return{data:{context:ctx,articles:ranked}}});
 app.post('/api/v1/articles/:id/feedback',{preHandler:view},async(req,reply)=>{const a=await visibleArticle(req,reply,req.params.id);if(!a||reply.sent)return;const requestId=Number(req.body?.request_id||0);if(!requestId||typeof req.body?.helpful!=='boolean')return fail(reply,'VALIDATION','Укажите заказ и оценку');try{await requireOrder(pool,req.user,requestId)}catch(e){return fail(reply,e.code||'FORBIDDEN',e.message,e.statusCode||403)}await pool.query(`INSERT INTO knowledge_feedback(article_id,request_id,user_id,helpful,note) VALUES($1,$2,$3,$4,$5) ON CONFLICT(article_id,request_id,user_id) DO UPDATE SET helpful=EXCLUDED.helpful,note=EXCLUDED.note,updated_at=clock_timestamp()`,[a.id,requestId,req.user.id,req.body.helpful,clean(req.body?.note,1000)||null]);return{data:await byId(pool,a.id)}});
 app.post('/api/v1/articles/:id/use',{preHandler:view},async(req,reply)=>{const a=await visibleArticle(req,reply,req.params.id);if(!a||reply.sent)return;const requestId=Number(req.body?.request_id||0),action=clean(req.body?.action,20).toUpperCase();if(!requestId||!actions.has(action))return fail(reply,'VALIDATION','Укажите заказ и действие');try{await requireOrder(pool,req.user,requestId)}catch(e){return fail(reply,e.code||'FORBIDDEN',e.message,e.statusCode||403)}await tx(async c=>{await c.query('INSERT INTO knowledge_use_events(article_id,article_version,request_id,user_id,action) VALUES($1,$2,$3,$4,$5)',[a.id,a.version,requestId,req.user.id,action]);if(action==='APPLIED')await c.query('INSERT INTO request_history(request_id,user_id,action,details) VALUES($1,$2,$3,$4::jsonb)',[requestId,req.user.id,'KNOWLEDGE_APPLIED',JSON.stringify({article_id:a.id,article_version:a.version,title:a.title})])});return reply.code(201).send({data:{ok:true,article_id:a.id,version:a.version,action}})});
 return app;
}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const app=Fastify({logger:true,bodyLimit:2*1024*1024});await app.register(cors,{origin:(process.env.CORS_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()),credentials:true});await app.register(helmet,{contentSecurityPolicy:false});await app.register(rateLimit,{max:240,timeWindow:'1 minute'});await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||8)});await prepareKnowledgeBase(pool);installKnowledgeBase(app,pool);await app.listen({port:Number(process.env.PORT||8112),host:'0.0.0.0'})}
