import {authenticate,installOrderAccess} from './access.js';
import {can,PERMISSIONS} from './rbac.js';
import {payrollPeriod} from './payroll-calculation.js';
import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import jwt from '@fastify/jwt';
import pg from 'pg';
import {createHash} from 'node:crypto';

const app=Fastify({logger:true});
await app.register(cors,{origin:(process.env.CORS_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()),credentials:true});
await app.register(helmet,{contentSecurityPolicy:false});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||8)});
const q=(s,p=[])=>pool.query(s,p),n=v=>Number(v||0),fail=(r,c,m,s=422)=>r.code(s).send({data:null,error:{code:c,message:m}});
const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}};
const auth=async(req,r)=>{if(!await authenticate(req,r,pool))return;};
const reportAccess=async(req,r)=>{await auth(req,r);if(r.sent)return;if(!can(req.user.role,PERMISSIONS.KPI_VIEW_ALL)&&!can(req.user.role,PERMISSIONS.KPI_VIEW_SELF))return fail(r,'FORBIDDEN','Нет доступа к KPI',403)};
const manage=async(req,r)=>{await auth(req,r);if(r.sent)return;if(!can(req.user.role,PERMISSIONS.KPI_MANAGE))return fail(r,'FORBIDDEN','Нет прав на управление KPI',403)};
const owner=async(req,r)=>{await auth(req,r);if(r.sent)return;if(req.user.role!=='OWNER')return fail(r,'FORBIDDEN','Утверждение KPI доступно только собственнику',403)};
const monthDate=v=>payrollPeriod(v)[0].toISOString().slice(0,10);
const money=v=>Math.round((n(v)+Number.EPSILON)*100)/100;
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');

installOrderAccess(app,pool,'kpi');
app.get('/health',async()=>{await q('SELECT 1');return{ok:true,service:'profi24-kpi',version:'2.0.1'}});

async function employee(c,id){const u=(await c.query("SELECT id,name,role,active,primary_branch_id FROM users WHERE id=$1 AND role IN('ENGINEER','MANAGER')",[Number(id)])).rows[0];if(!u)throw Object.assign(new Error('KPI настраивается только для менеджера или инженера'),{code:'VALIDATION',statusCode:422});if(!u.primary_branch_id)throw Object.assign(new Error('У сотрудника не указан основной филиал'),{code:'BRANCH_REQUIRED',statusCode:409});return u}

app.put('/api/v1/plans/:userId',{preHandler:manage},async(req,reply)=>{const b=req.body||{},month=monthDate(b.month),id=Number(req.params.userId);if(!Number.isSafeInteger(id)||id<1)return fail(reply,'VALIDATION','Не выбран сотрудник');for(const k of ['target_jobs','target_revenue','target_avg_check','target_conversion','target_sla','target_quality','bonus_max'])if(!Number.isFinite(Number(b[k]||0))||n(b[k])<0)return fail(reply,'VALIDATION','Плановые показатели не могут быть отрицательными');const result=await tx(async c=>{const u=await employee(c,id);const payrollLocked=(await c.query("SELECT id FROM payroll_periods WHERE branch_id=$1 AND period_month=$2::date AND status IN('APPROVED','PAID','CLOSED')",[u.primary_branch_id,month])).rows[0];if(payrollLocked)throw Object.assign(new Error('План KPI нельзя менять после утверждения зарплатного периода'),{code:'PAYROLL_PERIOD_LOCKED',statusCode:409});const kpiLocked=(await c.query("SELECT id FROM kpi_result_snapshots WHERE branch_id=$1 AND period_month=$2::date AND user_id=$3 AND status='APPROVED'",[u.primary_branch_id,month,id])).rows[0];if(kpiLocked)throw Object.assign(new Error('План KPI нельзя менять после утверждения результата'),{code:'KPI_ALREADY_APPROVED',statusCode:409});return(await c.query(`INSERT INTO kpi_plans(user_id,month,branch_id,target_jobs,target_revenue,target_avg_check,target_conversion,target_sla,target_quality,bonus_max,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(user_id,month) DO UPDATE SET branch_id=$3,target_jobs=$4,target_revenue=$5,target_avg_check=$6,target_conversion=$7,target_sla=$8,target_quality=$9,bonus_max=$10,created_by=$11,updated_at=now() RETURNING *`,[id,month,u.primary_branch_id,n(b.target_jobs),n(b.target_revenue),n(b.target_avg_check),n(b.target_conversion),n(b.target_sla||95),n(b.target_quality||95),n(b.bonus_max),req.user.id])).rows[0]});return{data:result}});

async function computeReport(c,{month,branchId=null,userId=null}){
  const[start,end]=payrollPeriod(month),monthStr=start.toISOString().slice(0,10),params=[monthStr];
  let userWhere="WHERE u.role IN('ENGINEER','MANAGER')";
  if(branchId){params.push(branchId);userWhere+=` AND u.primary_branch_id=$${params.length}`;}
  if(userId){params.push(userId);userWhere+=` AND u.id=$${params.length}`;}
  const users=(await c.query(`SELECT u.id,u.name,u.role,u.active,u.primary_branch_id,k.id plan_id,k.target_jobs,k.target_revenue,k.target_avg_check,k.target_conversion,k.target_sla,k.target_quality,k.bonus_max FROM users u LEFT JOIN kpi_plans k ON k.user_id=u.id AND k.month=$1::date ${userWhere} ORDER BY u.role,u.name`,params)).rows;
  const requestParams=[start,end];let requestBranch='';if(branchId){requestParams.push(branchId);requestBranch=` AND r.branch_id=$${requestParams.length}`;}
  const requests=(await c.query(`SELECT r.id,r.manager_id,r.engineer_id,r.status,r.total,r.created_at,r.closed_at,r.sla_deadline,r.branch_id FROM requests r WHERE r.deleted_at IS NULL AND ((r.created_at>=$1 AND r.created_at<$2) OR (r.closed_at>=$1 AND r.closed_at<$2))${requestBranch}`,requestParams)).rows;
  const taskParams=[start,end];let taskBranch='';if(branchId){taskParams.push(branchId);taskBranch=` AND (r.id IS NULL OR r.branch_id=$${taskParams.length})`;}
  const tasks=(await c.query(`SELECT t.assigned_to,t.status,t.due_at,t.completed_at FROM tasks t LEFT JOIN requests r ON r.id=t.request_id WHERE t.created_at>=$1 AND t.created_at<$2 AND (t.request_id IS NULL OR r.deleted_at IS NULL)${taskBranch}`,taskParams)).rows;
  const claimParams=[start,end];let claimBranch='';if(branchId){claimParams.push(branchId);claimBranch=` AND r.branch_id=$${claimParams.length}`;}
  let complaints=[];try{complaints=(await c.query(`SELECT r.manager_id,r.engineer_id FROM complaints co JOIN requests r ON r.id=co.request_id WHERE r.deleted_at IS NULL AND co.created_at>=$1 AND co.created_at<$2${claimBranch}`,claimParams)).rows}catch{}
  const now=new Date(),sameMonth=now.getUTCFullYear()===start.getUTCFullYear()&&now.getUTCMonth()===start.getUTCMonth();const elapsed=sameMonth?Math.max(1,now.getUTCDate()):new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate();const totalDays=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate();
  const rows=users.map(u=>{
    const key=u.role==='ENGINEER'?'engineer_id':'manager_id';
    const created=requests.filter(r=>Number(r[key])===Number(u.id)&&new Date(r.created_at)>=start&&new Date(r.created_at)<end);
    const closed=requests.filter(r=>Number(r[key])===Number(u.id)&&r.status==='CLOSED'&&r.closed_at&&new Date(r.closed_at)>=start&&new Date(r.closed_at)<end);
    const assigned=created.length,closedCount=closed.length,revenue=money(closed.reduce((s,r)=>s+n(r.total),0)),avgCheck=closedCount?money(revenue/closedCount):0;
    const converted=created.filter(r=>['REPAIR','TESTING','PAYMENT_REQUIRED','CLOSED'].includes(r.status)).length,conversion=assigned?converted/assigned*100:0;
    const slaPopulation=requests.filter(r=>Number(r[key])===Number(u.id)&&r.sla_deadline&&((r.closed_at&&new Date(r.closed_at)>=start&&new Date(r.closed_at)<end)||(!r.closed_at&&new Date(r.created_at)>=start&&new Date(r.created_at)<end)));
    const slaBad=slaPopulation.filter(r=>new Date(r.closed_at||Date.now())>new Date(r.sla_deadline)).length,sla=slaPopulation.length?100-slaBad/slaPopulation.length*100:100;
    const claims=complaints.filter(x=>Number(x[key])===Number(u.id)).length,quality=closedCount?Math.max(0,100-claims/closedCount*100):100;
    const ownTasks=tasks.filter(t=>Number(t.assigned_to)===Number(u.id)),taskTotal=ownTasks.length,taskDone=ownTasks.filter(t=>t.status==='DONE').length,taskOnTime=ownTasks.filter(t=>t.status==='DONE'&&(!t.due_at||new Date(t.completed_at)<=new Date(t.due_at))).length,taskOverdue=ownTasks.filter(t=>!['DONE','CANCELLED'].includes(t.status)&&t.due_at&&new Date(t.due_at)<now).length,taskScore=taskTotal?Math.max(0,Math.min(100,(taskOnTime/taskTotal*100)-(taskOverdue/taskTotal*30))):100;
    const factors=[];if(n(u.target_jobs)>0)factors.push(closedCount/n(u.target_jobs));if(n(u.target_revenue)>0)factors.push(revenue/n(u.target_revenue));if(n(u.target_avg_check)>0)factors.push(avgCheck/n(u.target_avg_check));if(n(u.target_conversion)>0)factors.push(conversion/n(u.target_conversion));if(n(u.target_sla)>0)factors.push(sla/n(u.target_sla));if(n(u.target_quality)>0)factors.push(quality/n(u.target_quality));if(taskTotal)factors.push(taskScore/100);const score=factors.length?Math.round(factors.map(v=>Math.min(1.2,v)).reduce((a,b)=>a+b,0)/factors.length*100):0,bonus=money(n(u.bonus_max)*Math.min(1,score/100)),forecast=sameMonth?money(revenue/elapsed*totalDays):revenue;
    return{...u,assigned,closed:closedCount,revenue,avg_check:avgCheck,conversion,converted,sla,quality,claims,tasks_total:taskTotal,tasks_done:taskDone,tasks_on_time:taskOnTime,tasks_overdue:taskOverdue,task_score:Math.round(taskScore),score,bonus,forecast_revenue:forecast};
  });
  return{month:start.toISOString().slice(0,7),branch_id:branchId,rows};
}

app.get('/api/v1/report',{preHandler:reportAccess},async req=>{const all=can(req.user.role,PERMISSIONS.KPI_VIEW_ALL),branchId=req.query?.branch_id?Number(req.query.branch_id):null,userId=all?null:req.user.id;return{data:await computeReport(pool,{month:req.query?.month,branchId,userId})}});

app.post('/api/v1/results/calculate',{preHandler:manage},async(req,reply)=>{const b=req.body||{},branchId=Number(b.branch_id);if(!Number.isSafeInteger(branchId)||branchId<1)return fail(reply,'VALIDATION','Выберите филиал');const periodMonth=monthDate(b.month);const result=await tx(async c=>{const br=(await c.query('SELECT id FROM branches WHERE id=$1 AND active=true',[branchId])).rows[0];if(!br)throw Object.assign(new Error('Филиал не найден'),{code:'BRANCH_NOT_FOUND',statusCode:422});const approvedPeriod=(await c.query("SELECT id,status FROM payroll_periods WHERE branch_id=$1 AND period_month=$2::date AND status IN('APPROVED','PAID','CLOSED')",[branchId,periodMonth])).rows[0];if(approvedPeriod)throw Object.assign(new Error('KPI нельзя пересчитать после утверждения зарплатного периода'),{code:'PAYROLL_PERIOD_LOCKED',statusCode:409});const report=await computeReport(c,{month:b.month,branchId});const snapshots=[];for(const row of report.rows){const approved=(await c.query("SELECT id FROM kpi_result_snapshots WHERE branch_id=$1 AND period_month=$2::date AND user_id=$3 AND status='APPROVED'",[branchId,periodMonth,row.id])).rows[0];if(approved)throw Object.assign(new Error(`KPI сотрудника ${row.name} уже утверждён`),{code:'KPI_ALREADY_APPROVED',statusCode:409});const revision=Number((await c.query('SELECT COALESCE(max(revision),0)+1 n FROM kpi_result_snapshots WHERE branch_id=$1 AND period_month=$2::date AND user_id=$3',[branchId,periodMonth,row.id])).rows[0].n);const plan={plan_id:row.plan_id,target_jobs:n(row.target_jobs),target_revenue:n(row.target_revenue),target_avg_check:n(row.target_avg_check),target_conversion:n(row.target_conversion),target_sla:n(row.target_sla),target_quality:n(row.target_quality),bonus_max:n(row.bonus_max)};const metrics={assigned:row.assigned,closed:row.closed,revenue:row.revenue,avg_check:row.avg_check,conversion:row.conversion,sla:row.sla,quality:row.quality,claims:row.claims,tasks_total:row.tasks_total,tasks_done:row.tasks_done,tasks_on_time:row.tasks_on_time,tasks_overdue:row.tasks_overdue,task_score:row.task_score,forecast_revenue:row.forecast_revenue};const fingerprint=hash({branchId,periodMonth,user_id:row.id,role:row.role,revision,plan,metrics,score:row.score,bonus:row.bonus});const snap=(await c.query(`INSERT INTO kpi_result_snapshots(branch_id,period_month,user_id,revision,employee_role,plan_snapshot,metrics,score,bonus_amount,status,fingerprint,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'DRAFT',$10,$11) RETURNING *`,[branchId,periodMonth,row.id,revision,row.role,plan,metrics,row.score,row.bonus,fingerprint,req.user.id])).rows[0];snapshots.push(snap)}return{...report,snapshots}});return reply.code(201).send({data:result})});

app.get('/api/v1/results',{preHandler:reportAccess},async req=>{const all=can(req.user.role,PERMISSIONS.KPI_VIEW_ALL),params=[];let where='WHERE 1=1';if(req.query?.month){params.push(monthDate(req.query.month));where+=` AND s.period_month=$${params.length}::date`;}if(req.query?.branch_id){params.push(Number(req.query.branch_id));where+=` AND s.branch_id=$${params.length}`;}if(!all){params.push(req.user.id);where+=` AND s.user_id=$${params.length}`;}return{data:(await q(`SELECT s.*,u.name,u.role,b.code branch_code FROM kpi_result_snapshots s JOIN users u ON u.id=s.user_id JOIN branches b ON b.id=s.branch_id ${where} ORDER BY s.period_month DESC,u.name,s.revision DESC`,params)).rows}});

app.post('/api/v1/results/:id/approve',{preHandler:owner},async(req,reply)=>{const result=await tx(async c=>{const s=(await c.query('SELECT * FROM kpi_result_snapshots WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!s)throw Object.assign(new Error('Снимок KPI не найден'),{code:'NOT_FOUND',statusCode:404});if(s.status==='APPROVED')return s;const locked=(await c.query("SELECT status FROM payroll_periods WHERE branch_id=$1 AND period_month=$2 AND status IN('APPROVED','PAID','CLOSED')",[s.branch_id,s.period_month])).rows[0];if(locked)throw Object.assign(new Error('Зарплатный период уже утверждён; KPI менять поздно'),{code:'PAYROLL_PERIOD_LOCKED',statusCode:409});return(await c.query("UPDATE kpi_result_snapshots SET status='APPROVED',approved_by=$1,approved_at=clock_timestamp() WHERE id=$2 RETURNING *",[req.user.id,s.id])).rows[0]});return{data:result}});

const close=async()=>{try{await pool.end()}finally{process.exit(0)}};process.on('SIGTERM',close);process.on('SIGINT',close);
app.listen({port:Number(process.env.PORT||8093),host:'0.0.0.0'});
