import Fastify from'fastify';import cors from'@fastify/cors';import helmet from'@fastify/helmet';import jwt from'@fastify/jwt';import pg from'pg';
const app=Fastify({logger:true});await app.register(cors,{origin:true,credentials:true});await app.register(helmet,{contentSecurityPolicy:false});await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||10)}),q=(s,p=[])=>pool.query(s,p),fail=(r,c,m,s=422)=>r.code(s).send({data:null,error:{code:c,message:m}});const auth=async(req,r)=>{try{await req.jwtVerify()}catch{return fail(r,'UNAUTHORIZED','Требуется авторизация',401)}};const ops=async(req,r)=>{await auth(req,r);if(r.sent)return;if(!['OWNER','MANAGER'].includes(req.user.role))return fail(r,'FORBIDDEN','Доступно руководителю и менеджеру',403)};
const stageSql=`CASE WHEN r.status='ACCEPTED' AND EXISTS(SELECT 1 FROM request_stage_events se WHERE se.request_id=r.id AND se.event='DEPART') AND NOT EXISTS(SELECT 1 FROM request_stage_events se WHERE se.request_id=r.id AND se.event='ARRIVE') THEN 'ON_ROUTE' ELSE r.status END`;
app.get('/health',async()=>{await q('SELECT 1');return{ok:true,service:'profi24-operations-center',version:'1.1.0'}});
app.get('/api/v1/operations/live',{preHandler:ops},async()=>{const now=new Date();
 const metrics=(await q(`SELECT
 count(*) FILTER(WHERE status NOT IN('CLOSED','CANCELLED'))::int active,
 count(*) FILTER(WHERE created_at>=date_trunc('day',now()))::int created_today,
 count(*) FILTER(WHERE status='NEW')::int new,
 count(*) FILTER(WHERE engineer_id IS NULL AND status NOT IN('CLOSED','CANCELLED'))::int unassigned,
 count(*) FILTER(WHERE sla_deadline<now() AND status NOT IN('CLOSED','CANCELLED'))::int sla_overdue,
 count(*) FILTER(WHERE scheduled_at<now()-interval '20 minutes' AND status NOT IN('CLOSED','CANCELLED','PAYMENT_REQUIRED'))::int visit_overdue,
 count(*) FILTER(WHERE status='APPROVAL_REQUIRED')::int approval_waiting,
 count(*) FILTER(WHERE status='WAITING_PART')::int waiting_parts,
 count(*) FILTER(WHERE status='CLOSED' AND closed_at>=date_trunc('day',now()))::int closed_today,
 COALESCE(sum(total) FILTER(WHERE status='CLOSED' AND closed_at>=date_trunc('day',now())),0)::numeric revenue_today,
 COALESCE(sum(total) FILTER(WHERE status NOT IN('CLOSED','CANCELLED')),0)::numeric active_order_value,
 COALESCE(sum(GREATEST(COALESCE(total,0)-COALESCE(paid,0),0)) FILTER(WHERE status NOT IN('CANCELLED')),0)::numeric receivable,
 COALESCE(sum(paid) FILTER(WHERE updated_at>=date_trunc('day',now())),0)::numeric request_paid_snapshot
 FROM requests`)).rows[0];
 const cash=(await q(`SELECT COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount ELSE -amount END),0)::numeric amount,count(*) FILTER(WHERE kind='PAYMENT')::int payments FROM payments WHERE created_at>=date_trunc('day',now())`)).rows[0];
 const engineers=(await q(`WITH active_orders AS(SELECT r.id,r.number,r.engineer_id,r.status,r.scheduled_at,r.updated_at,c.name customer_name,c.phone,c.address,r.complaint,${stageSql} live_stage,row_number() over(partition by r.engineer_id order by CASE ${stageSql} WHEN 'DIAGNOSTICS' THEN 1 WHEN 'REPAIR' THEN 2 WHEN 'ON_ROUTE' THEN 3 WHEN 'TESTING' THEN 4 WHEN 'APPROVAL_REQUIRED' THEN 5 WHEN 'ACCEPTED' THEN 6 WHEN 'ASSIGNED' THEN 7 ELSE 8 END,r.updated_at desc) rn FROM requests r JOIN customers c ON c.id=r.customer_id WHERE r.status NOT IN('CLOSED','CANCELLED') AND r.engineer_id IS NOT NULL),today AS(SELECT engineer_id,count(*) FILTER(WHERE created_at>=date_trunc('day',now()))::int assigned_today,count(*) FILTER(WHERE status='CLOSED' AND closed_at>=date_trunc('day',now()))::int closed_today FROM requests GROUP BY engineer_id) SELECT u.id,u.name,u.active,ao.id request_id,ao.number,ao.live_stage,ao.scheduled_at,ao.updated_at,ao.customer_name,ao.phone,ao.address,ao.complaint,COALESCE(t.assigned_today,0) assigned_today,COALESCE(t.closed_today,0) closed_today,(SELECT min(r2.scheduled_at) FROM requests r2 WHERE r2.engineer_id=u.id AND r2.status NOT IN('CLOSED','CANCELLED') AND r2.scheduled_at>now()) next_visit FROM users u LEFT JOIN active_orders ao ON ao.engineer_id=u.id AND ao.rn=1 LEFT JOIN today t ON t.engineer_id=u.id WHERE u.role='ENGINEER' AND u.active=true ORDER BY CASE WHEN ao.live_stage='ON_ROUTE' THEN 1 WHEN ao.live_stage IN('DIAGNOSTICS','REPAIR','TESTING') THEN 2 WHEN ao.id IS NULL THEN 4 ELSE 3 END,u.name`)).rows;
 const attention=(await q(`SELECT r.id,r.number,r.status,${stageSql} live_stage,r.priority,r.sla_deadline,r.scheduled_at,r.updated_at,c.name customer_name,c.phone,eng.name engineer_name,r.complaint,
 CASE WHEN r.sla_deadline<now() THEN 'SLA_OVERDUE' WHEN r.scheduled_at<now()-interval '20 minutes' AND r.status NOT IN('PAYMENT_REQUIRED') THEN 'VISIT_OVERDUE' WHEN r.engineer_id IS NULL AND r.created_at<now()-interval '15 minutes' THEN 'UNASSIGNED' WHEN r.status='APPROVAL_REQUIRED' AND r.updated_at<now()-interval '30 minutes' THEN 'APPROVAL_STUCK' ELSE 'OTHER' END reason
 FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN users eng ON eng.id=r.engineer_id WHERE r.status NOT IN('CLOSED','CANCELLED') AND (r.sla_deadline<now() OR (r.scheduled_at<now()-interval '20 minutes' AND r.status NOT IN('PAYMENT_REQUIRED')) OR (r.engineer_id IS NULL AND r.created_at<now()-interval '15 minutes') OR (r.status='APPROVAL_REQUIRED' AND r.updated_at<now()-interval '30 minutes')) ORDER BY CASE WHEN r.sla_deadline<now() THEN 1 WHEN r.scheduled_at<now()-interval '20 minutes' THEN 2 ELSE 3 END,r.updated_at LIMIT 100`)).rows;
 const timeline=(await q(`SELECT r.id,r.number,r.status,${stageSql} live_stage,r.scheduled_at,c.name customer_name,eng.name engineer_name,c.address FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN users eng ON eng.id=r.engineer_id WHERE r.status NOT IN('CLOSED','CANCELLED') AND r.scheduled_at>=date_trunc('day',now()) AND r.scheduled_at<date_trunc('day',now())+interval '1 day' ORDER BY r.scheduled_at`)).rows;
 let approvals={pending:0,declined_today:0};try{approvals=(await q(`SELECT count(*) FILTER(WHERE status='PENDING')::int pending,count(*) FILTER(WHERE status='DECLINED' AND responded_at>=date_trunc('day',now()))::int declined_today FROM customer_approvals`)).rows[0]}catch{}
 const complaints=(await q(`SELECT count(*) FILTER(WHERE status='OPEN')::int open FROM complaints`)).rows[0];
 return{data:{generated_at:now.toISOString(),metrics:{...metrics,cash_today:cash.amount,payments_today:cash.payments,pending_approvals:approvals.pending,declined_today:approvals.declined_today,complaints_open:complaints.open},engineers,attention,timeline}}});
app.listen({port:Number(process.env.PORT||8091),host:'0.0.0.0'});