import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import pg from 'pg';

const app=Fastify({logger:true});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:5});
const q=(s,p=[])=>pool.query(s,p);
const fail=(r,code,message,status=422)=>r.code(status).send({data:null,error:{code,message}});
const owner=async(req,reply)=>{try{await req.jwtVerify()}catch{return fail(reply,'UNAUTHORIZED','Требуется авторизация',401)}if(req.user.role!=='OWNER')return fail(reply,'FORBIDDEN','Корректировка доступна только руководителю',403)};
const n=v=>Number(v||0);
await q(`CREATE TABLE IF NOT EXISTS owner_order_corrections(request_id INT PRIMARY KEY REFERENCES requests(id) ON DELETE CASCADE,active BOOLEAN NOT NULL DEFAULT true,opened_by INT REFERENCES users(id),opened_at TIMESTAMPTZ DEFAULT now(),reason TEXT,original_status TEXT,original_closed_at TIMESTAMPTZ,closed_by INT REFERENCES users(id),closed_at TIMESTAMPTZ,close_reason TEXT)`);
const hist=(c,id,user,action,details)=>(c||pool).query('INSERT INTO request_history(request_id,user_id,action,details) VALUES($1,$2,$3,$4)',[id,user,action,details||{}]);
async function recalc(c,id){const w=(await c.query('SELECT COALESCE(sum(qty*unit_price),0) sale,COALESCE(sum(qty*direct_cost),0) cost FROM request_works WHERE request_id=$1',[id])).rows[0];const p=(await c.query('SELECT COALESCE(sum(qty*sale_price),0) sale,COALESCE(sum(qty*purchase_price),0) cost FROM parts WHERE request_id=$1',[id])).rows[0];const r=(await c.query('SELECT COALESCE(discount_amount,0) discount FROM requests WHERE id=$1',[id])).rows[0];const total=Math.max(0,n(w.sale)+n(p.sale)-n(r.discount)),cost=n(w.cost)+n(p.cost);await c.query('UPDATE requests SET total=$1,direct_cost=$2,updated_at=now() WHERE id=$3',[total,cost,id]);return{total,direct_cost:cost}}
async function active(c,id){return (await c.query('SELECT * FROM owner_order_corrections WHERE request_id=$1 AND active=true',[id])).rows[0]}

app.get('/health',async()=>{await q('SELECT 1');return{ok:true,service:'owner-control',version:'2.0.0'}});
app.get('/api/v1/orders/:number/correction',{preHandler:owner},async(req,reply)=>{const r=(await q(`SELECT r.id,r.number,r.status,r.total,r.paid,oc.active,oc.opened_at,oc.reason,oc.original_status FROM requests r LEFT JOIN owner_order_corrections oc ON oc.request_id=r.id AND oc.active=true WHERE r.number=$1`,[req.params.number])).rows[0];if(!r)return fail(reply,'NOT_FOUND','Заказ не найден',404);return{data:{...r,correction_active:!!r.active}}});

app.post('/api/v1/orders/:number/reopen',{preHandler:owner},async(req,reply)=>{const number=String(req.params.number||'').trim(),reason=String(req.body?.reason||'Корректировка закрытого заказа').trim();const c=await pool.connect();try{await c.query('BEGIN');const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[number])).rows[0];if(!cur){await c.query('ROLLBACK');return fail(reply,'NOT_FOUND','Заказ не найден',404)}const already=await active(c,cur.id);if(already){await c.query('COMMIT');return{data:{...cur,correction_active:true}}}await c.query(`INSERT INTO owner_order_corrections(request_id,active,opened_by,reason,original_status,original_closed_at) VALUES($1,true,$2,$3,$4,$5) ON CONFLICT(request_id) DO UPDATE SET active=true,opened_by=$2,opened_at=now(),reason=$3,original_status=$4,original_closed_at=$5,closed_by=NULL,closed_at=NULL,close_reason=NULL`,[cur.id,req.user.id,reason,cur.status,cur.closed_at]);if(cur.status==='CLOSED')await c.query("UPDATE requests SET status='PAYMENT_REQUIRED',closed_at=NULL,updated_at=now() WHERE id=$1",[cur.id]);await hist(c,cur.id,req.user.id,'OWNER_CORRECTION_STARTED',{reason,from_status:cur.status,total:cur.total,paid:cur.paid});await c.query('COMMIT');return{data:{number,correction_active:true,message:'Режим корректировки включён'}}}catch(e){await c.query('ROLLBACK');req.log.error(e);return fail(reply,'REOPEN_FAILED','Не удалось включить режим корректировки',500)}finally{c.release()}});

app.patch('/api/v1/correction/works/:id',{preHandler:owner},async(req,reply)=>{const c=await pool.connect();try{await c.query('BEGIN');const old=(await c.query('SELECT * FROM request_works WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)return fail(reply,'NOT_FOUND','Работа не найдена',404);if(!await active(c,old.request_id))return fail(reply,'CORRECTION_REQUIRED','Сначала включите режим корректировки',409);const b={...old,...req.body};if(n(b.qty)<=0||n(b.unit_price)<0)return fail(reply,'VALIDATION','Проверьте количество и цену');const row=(await c.query('UPDATE request_works SET name=$1,qty=$2,unit_price=$3,direct_cost=$4,updated_at=now() WHERE id=$5 RETURNING *',[b.name,b.qty,b.unit_price,b.direct_cost,old.id])).rows[0];const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_CORRECTED_WORK',{work_id:old.id,before:{name:old.name,qty:old.qty,unit_price:old.unit_price,direct_cost:old.direct_cost},after:{name:row.name,qty:row.qty,unit_price:row.unit_price,direct_cost:row.direct_cost}});await c.query('COMMIT');return{data:{item:row,totals}}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.delete('/api/v1/correction/works/:id',{preHandler:owner},async(req,reply)=>{const c=await pool.connect();try{await c.query('BEGIN');const old=(await c.query('SELECT * FROM request_works WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)return fail(reply,'NOT_FOUND','Работа не найдена',404);if(!await active(c,old.request_id))return fail(reply,'CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM request_works WHERE id=$1',[old.id]);const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_DELETED_WORK',{work_id:old.id,before:old});await c.query('COMMIT');return{data:{ok:true,totals}}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.patch('/api/v1/correction/parts/:id',{preHandler:owner},async(req,reply)=>{const c=await pool.connect();try{await c.query('BEGIN');const old=(await c.query('SELECT * FROM parts WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)return fail(reply,'NOT_FOUND','Запчасть не найдена',404);if(!await active(c,old.request_id))return fail(reply,'CORRECTION_REQUIRED','Сначала включите режим корректировки',409);const b={...old,...req.body};const row=(await c.query('UPDATE parts SET name=$1,qty=$2,purchase_price=$3,sale_price=$4,updated_at=now() WHERE id=$5 RETURNING *',[b.name,b.qty,b.purchase_price,b.sale_price,old.id])).rows[0];const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_CORRECTED_PART',{part_id:old.id,before:{name:old.name,qty:old.qty,purchase_price:old.purchase_price,sale_price:old.sale_price},after:{name:row.name,qty:row.qty,purchase_price:row.purchase_price,sale_price:row.sale_price}});await c.query('COMMIT');return{data:{item:row,totals}}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.delete('/api/v1/correction/parts/:id',{preHandler:owner},async(req,reply)=>{const c=await pool.connect();try{await c.query('BEGIN');const old=(await c.query('SELECT * FROM parts WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)return fail(reply,'NOT_FOUND','Запчасть не найдена',404);if(!await active(c,old.request_id))return fail(reply,'CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM parts WHERE id=$1',[old.id]);const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_DELETED_PART',{part_id:old.id,before:old});await c.query('COMMIT');return{data:{ok:true,totals}}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.delete('/api/v1/correction/payments/:id',{preHandler:owner},async(req,reply)=>{const c=await pool.connect();try{await c.query('BEGIN');const p=(await c.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!p)return fail(reply,'NOT_FOUND','Платёж не найден',404);if(!await active(c,p.request_id))return fail(reply,'CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM payments WHERE id=$1',[p.id]);const sums=(await c.query("SELECT COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount WHEN kind='REFUND' THEN -amount ELSE 0 END),0) paid FROM payments WHERE request_id=$1",[p.request_id])).rows[0];await c.query('UPDATE requests SET paid=$1,updated_at=now() WHERE id=$2',[Math.max(0,n(sums.paid)),p.request_id]);await hist(c,p.request_id,req.user.id,'OWNER_DELETED_PAYMENT',{payment_id:p.id,before:p});await c.query('COMMIT');return{data:{ok:true,paid:Math.max(0,n(sums.paid))}}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});

app.post('/api/v1/orders/:number/close',{preHandler:owner},async(req,reply)=>{const number=String(req.params.number||'').trim(),reason=String(req.body?.reason||'Корректировка завершена').trim();const c=await pool.connect();try{await c.query('BEGIN');const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[number])).rows[0];if(!cur)return fail(reply,'NOT_FOUND','Заказ не найден',404);const corr=await active(c,cur.id);if(!corr)return fail(reply,'CORRECTION_NOT_ACTIVE','Режим корректировки не активен',409);if(n(cur.paid)+0.001<n(cur.total))return fail(reply,'PAYMENT_REQUIRED',`Нельзя закрыть заказ: оплачено ${cur.paid||0}, итог ${cur.total||0}`,409);const row=(await c.query("UPDATE requests SET status='CLOSED',closed_at=now(),updated_at=now() WHERE id=$1 RETURNING id,number,status,total,paid,closed_at",[cur.id])).rows[0];await c.query('UPDATE owner_order_corrections SET active=false,closed_by=$1,closed_at=now(),close_reason=$2 WHERE request_id=$3',[req.user.id,reason,cur.id]);await hist(c,cur.id,req.user.id,'OWNER_CORRECTION_FINISHED',{reason,total:cur.total,paid:cur.paid});await c.query('COMMIT');return{data:{...row,correction_active:false,message:'Корректировка завершена'}}}catch(e){await c.query('ROLLBACK');req.log.error(e);return fail(reply,'CLOSE_FAILED',e.message||'Не удалось завершить корректировку',500)}finally{c.release()}});
app.listen({port:Number(process.env.PORT||8103),host:'0.0.0.0'});