import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import pg from 'pg';

const app=Fastify({logger:true});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:5});
const q=(s,p=[])=>pool.query(s,p);const n=v=>Number(v||0);const fail=(r,code,message,status=422)=>r.code(status).send({data:null,error:{code,message}});
class ApiError extends Error{constructor(code,message,status=422){super(message);this.code=code;this.status=status}}
const abort=(code,message,status)=>{throw new ApiError(code,message,status)};
const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release()}};
const owner=async(req,reply)=>{try{await req.jwtVerify()}catch{return fail(reply,'UNAUTHORIZED','Требуется авторизация',401)}if(req.user.role!=='OWNER')return fail(reply,'FORBIDDEN','Корректировка доступна только руководителю',403)};
await q(`CREATE TABLE IF NOT EXISTS owner_order_corrections(request_id INT PRIMARY KEY REFERENCES requests(id) ON DELETE CASCADE,active BOOLEAN NOT NULL DEFAULT true,opened_by INT REFERENCES users(id),opened_at TIMESTAMPTZ DEFAULT now(),reason TEXT,original_status TEXT,original_closed_at TIMESTAMPTZ,closed_by INT REFERENCES users(id),closed_at TIMESTAMPTZ,close_reason TEXT)`);
const hist=(c,id,user,action,details={})=>c.query('INSERT INTO request_history(request_id,user_id,action,details) VALUES($1,$2,$3,$4)',[id,user,action,details]);
async function active(c,id){return (await c.query('SELECT * FROM owner_order_corrections WHERE request_id=$1 AND active=true',[id])).rows[0]}
async function recalc(c,id){const w=(await c.query('SELECT COALESCE(sum(qty*unit_price),0) sale,COALESCE(sum(qty*direct_cost),0) cost FROM request_works WHERE request_id=$1',[id])).rows[0];const p=(await c.query('SELECT COALESCE(sum(qty*sale_price),0) sale,COALESCE(sum(qty*purchase_price),0) cost FROM parts WHERE request_id=$1',[id])).rows[0];const r=(await c.query('SELECT COALESCE(discount_amount,0) discount FROM requests WHERE id=$1',[id])).rows[0];if(!r)abort('NOT_FOUND','Заказ не найден',404);const total=Math.max(0,n(w.sale)+n(p.sale)-n(r.discount)),direct_cost=Math.max(0,n(w.cost)+n(p.cost));await c.query('UPDATE requests SET total=$1,direct_cost=$2,updated_at=now() WHERE id=$3',[total,direct_cost,id]);return{total,direct_cost}}
function validateLine(b,type){const name=String(b.name||'').trim();if(!name)abort('VALIDATION','Укажите наименование');if(n(b.qty)<=0)abort('VALIDATION','Количество должно быть больше нуля');const price=type==='work'?n(b.unit_price):n(b.sale_price),cost=type==='work'?n(b.direct_cost):n(b.purchase_price);if(price<0||cost<0)abort('VALIDATION','Цена и себестоимость не могут быть отрицательными');return name}
app.setErrorHandler((e,req,reply)=>{if(e instanceof ApiError)return fail(reply,e.code,e.message,e.status);req.log.error(e);return fail(reply,'INTERNAL_ERROR','Внутренняя ошибка сервера',500)});
app.get('/health',async()=>{await q('SELECT 1');return{ok:true,service:'owner-control',version:'2.1.0'}});
app.get('/api/v1/orders/:number/correction',{preHandler:owner},async(req,reply)=>{const r=(await q(`SELECT r.id,r.number,r.status,r.total,r.paid,r.direct_cost,oc.active,oc.opened_at,oc.reason,oc.original_status FROM requests r LEFT JOIN owner_order_corrections oc ON oc.request_id=r.id AND oc.active=true WHERE r.number=$1`,[req.params.number])).rows[0];if(!r)return fail(reply,'NOT_FOUND','Заказ не найден',404);return{data:{...r,correction_active:!!r.active}}});
app.get('/api/v1/orders/:number/correction/details',{preHandler:owner},async(req,reply)=>{const r=(await q(`SELECT r.id,r.number,r.status,r.total,r.paid,r.direct_cost,r.discount_amount,oc.active correction_active,oc.opened_at,oc.reason,oc.original_status FROM requests r LEFT JOIN owner_order_corrections oc ON oc.request_id=r.id AND oc.active=true WHERE r.number=$1`,[req.params.number])).rows[0];if(!r)return fail(reply,'NOT_FOUND','Заказ не найден',404);const [works,parts,payments]=await Promise.all([q('SELECT w.*,u.name performed_by_name FROM request_works w LEFT JOIN users u ON u.id=w.performed_by WHERE request_id=$1 ORDER BY w.created_at',[r.id]),q('SELECT * FROM parts WHERE request_id=$1 ORDER BY created_at DESC',[r.id]),q('SELECT p.*,u.name created_by_name FROM payments p LEFT JOIN users u ON u.id=p.created_by WHERE request_id=$1 ORDER BY p.created_at DESC',[r.id])]);return{data:{...r,correction_active:!!r.correction_active,works:works.rows,parts:parts.rows,payments:payments.rows}}});
app.post('/api/v1/orders/:number/reopen',{preHandler:owner},async req=>tx(async c=>{const number=String(req.params.number||'').trim(),reason=String(req.body?.reason||'Корректировка заказа').trim();const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[number])).rows[0];if(!cur)abort('NOT_FOUND','Заказ не найден',404);if(await active(c,cur.id))return{data:{number,correction_active:true,message:'Режим корректировки уже активен'}};await c.query(`INSERT INTO owner_order_corrections(request_id,active,opened_by,reason,original_status,original_closed_at) VALUES($1,true,$2,$3,$4,$5) ON CONFLICT(request_id) DO UPDATE SET active=true,opened_by=$2,opened_at=now(),reason=$3,original_status=$4,original_closed_at=$5,closed_by=NULL,closed_at=NULL,close_reason=NULL`,[cur.id,req.user.id,reason,cur.status,cur.closed_at]);if(cur.status==='CLOSED')await c.query("UPDATE requests SET status='PAYMENT_REQUIRED',closed_at=NULL,updated_at=now() WHERE id=$1",[cur.id]);await hist(c,cur.id,req.user.id,'OWNER_CORRECTION_STARTED',{reason,from_status:cur.status,total:cur.total,paid:cur.paid});return{data:{number,correction_active:true,message:'Режим корректировки включён'}}}));
app.patch('/api/v1/correction/works/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM request_works WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Работа не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);const b={...old,...req.body},name=validateLine(b,'work');const row=(await c.query('UPDATE request_works SET name=$1,qty=$2,unit_price=$3,direct_cost=$4,updated_at=now() WHERE id=$5 RETURNING *',[name,n(b.qty),n(b.unit_price),n(b.direct_cost),old.id])).rows[0];const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_CORRECTED_WORK',{work_id:old.id,before:old,after:row});return{data:{item:row,totals}}}));
app.delete('/api/v1/correction/works/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM request_works WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Работа не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM request_works WHERE id=$1',[old.id]);const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_DELETED_WORK',{work_id:old.id,before:old});return{data:{ok:true,totals}}}));
app.patch('/api/v1/correction/parts/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM parts WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Запчасть не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);const b={...old,...req.body},name=validateLine(b,'part');const row=(await c.query('UPDATE parts SET name=$1,qty=$2,purchase_price=$3,sale_price=$4,updated_at=now() WHERE id=$5 RETURNING *',[name,n(b.qty),n(b.purchase_price),n(b.sale_price),old.id])).rows[0];const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_CORRECTED_PART',{part_id:old.id,before:old,after:row});return{data:{item:row,totals}}}));
app.delete('/api/v1/correction/parts/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM parts WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Запчасть не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM parts WHERE id=$1',[old.id]);const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_DELETED_PART',{part_id:old.id,before:old});return{data:{ok:true,totals}}}));
app.delete('/api/v1/correction/payments/:id',{preHandler:owner},async req=>tx(async c=>{const p=(await c.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!p)abort('NOT_FOUND','Платёж не найден',404);if(!await active(c,p.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM payments WHERE id=$1',[p.id]);const sums=(await c.query("SELECT COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount WHEN kind='REFUND' THEN -amount ELSE 0 END),0) paid FROM payments WHERE request_id=$1",[p.request_id])).rows[0],paid=Math.max(0,n(sums.paid));await c.query('UPDATE requests SET paid=$1,updated_at=now() WHERE id=$2',[paid,p.request_id]);await hist(c,p.request_id,req.user.id,'OWNER_DELETED_PAYMENT',{payment_id:p.id,before:p,paid_after:paid});return{data:{ok:true,paid}}}));
app.post('/api/v1/orders/:number/close',{preHandler:owner},async req=>tx(async c=>{const number=String(req.params.number||'').trim(),reason=String(req.body?.reason||'Корректировка завершена').trim();const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[number])).rows[0];if(!cur)abort('NOT_FOUND','Заказ не найден',404);if(!await active(c,cur.id))abort('CORRECTION_NOT_ACTIVE','Режим корректировки не активен',409);const total=n(cur.total),paid=n(cur.paid),delta=paid-total;if(delta<-0.01)abort('PAYMENT_REQUIRED',`Нельзя закрыть заказ: оплачено ${paid}, итог ${total}`,409);if(delta>1)abort('OVERPAYMENT_REQUIRES_REVIEW',`Нельзя закрыть заказ: переплата ${delta.toFixed(2)} ₸. Исправьте ошибочные платежи.`,409);const row=(await c.query("UPDATE requests SET status='CLOSED',closed_at=now(),updated_at=now() WHERE id=$1 RETURNING id,number,status,total,paid,closed_at",[cur.id])).rows[0];await c.query('UPDATE owner_order_corrections SET active=false,closed_by=$1,closed_at=now(),close_reason=$2 WHERE request_id=$3',[req.user.id,reason,cur.id]);await hist(c,cur.id,req.user.id,'OWNER_CORRECTION_FINISHED',{reason,total,paid});return{data:{...row,correction_active:false,message:'Корректировка завершена'}}}));
const close=async()=>{try{await pool.end()}finally{process.exit(0)}};process.on('SIGTERM',close);process.on('SIGINT',close);
app.listen({port:Number(process.env.PORT||8103),host:'0.0.0.0'});