import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import pg from 'pg';

const app=Fastify({logger:true});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:5});
const q=(s,p=[])=>pool.query(s,p);const n=v=>Number(v||0);const fail=(r,code,message,status=422)=>r.code(status).send({data:null,error:{code,message}});
class ApiError extends Error{constructor(code,message,status=422){super(message);this.code=code;this.status=status}}
const abort=(code,message,status)=>{throw new ApiError(code,message,status)};
const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release()}};
const owner=async(req,reply)=>{try{await req.jwtVerify()}catch{return fail(reply,'UNAUTHORIZED','Требуется авторизация',401)}if(req.user.role!=='OWNER')return fail(reply,'FORBIDDEN','Доступно только владельцу',403)};
for(const s of[
 `ALTER TABLE requests ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ`,
 `ALTER TABLE requests ADD COLUMN IF NOT EXISTS deleted_by INT REFERENCES users(id)`,
 `ALTER TABLE requests ADD COLUMN IF NOT EXISTS delete_reason TEXT`,
 `ALTER TABLE requests ADD COLUMN IF NOT EXISTS deleted_snapshot JSONB`
])await q(s);
await q(`CREATE TABLE IF NOT EXISTS owner_order_corrections(request_id INT PRIMARY KEY REFERENCES requests(id) ON DELETE CASCADE,active BOOLEAN NOT NULL DEFAULT true,opened_by INT REFERENCES users(id),opened_at TIMESTAMPTZ DEFAULT now(),reason TEXT,original_status TEXT,original_closed_at TIMESTAMPTZ,closed_by INT REFERENCES users(id),closed_at TIMESTAMPTZ,close_reason TEXT)`);
const hist=(c,id,user,action,details={})=>c.query('INSERT INTO request_history(request_id,user_id,action,details) VALUES($1,$2,$3,$4)',[id,user,action,details]);
async function active(c,id){return (await c.query('SELECT * FROM owner_order_corrections WHERE request_id=$1 AND active=true',[id])).rows[0]}
async function recalc(c,id){const w=(await c.query('SELECT COALESCE(sum(qty*unit_price),0) sale,COALESCE(sum(qty*direct_cost),0) cost FROM request_works WHERE request_id=$1',[id])).rows[0];const p=(await c.query('SELECT COALESCE(sum(qty*sale_price),0) sale,COALESCE(sum(qty*purchase_price),0) cost FROM parts WHERE request_id=$1',[id])).rows[0];const r=(await c.query('SELECT COALESCE(discount_amount,0) discount,deleted_at FROM requests WHERE id=$1',[id])).rows[0];if(!r)abort('NOT_FOUND','Заказ не найден',404);if(r.deleted_at)abort('ORDER_DELETED','Сначала восстановите заказ',409);const total=Math.max(0,n(w.sale)+n(p.sale)-n(r.discount)),direct_cost=Math.max(0,n(w.cost)+n(p.cost));await c.query('UPDATE requests SET total=$1,direct_cost=$2,updated_at=now() WHERE id=$3',[total,direct_cost,id]);return{total,direct_cost}}
function validateLine(b,type){const name=String(b.name||'').trim();if(!name)abort('VALIDATION','Укажите наименование');if(n(b.qty)<=0)abort('VALIDATION','Количество должно быть больше нуля');const price=type==='work'?n(b.unit_price):n(b.sale_price),cost=type==='work'?n(b.direct_cost):n(b.purchase_price);if(price<0||cost<0)abort('VALIDATION','Цена и себестоимость не могут быть отрицательными');return name}
const allowedStatuses=new Set(['NEW','ASSIGNED','ACCEPTED','ON_ROUTE','DIAGNOSTICS','APPROVAL_REQUIRED','WAITING_PART','REPAIR','TESTING','PAYMENT_REQUIRED','CLOSED','CANCELLED']);
const nullable=v=>v===''||v==null?null:v;
app.setErrorHandler((e,req,reply)=>{if(e instanceof ApiError)return fail(reply,e.code,e.message,e.status);if(e.statusCode&&e.statusCode<500)return fail(reply,e.code||'REQUEST_ERROR',e.message,e.statusCode);req.log.error(e);return fail(reply,'INTERNAL_ERROR','Внутренняя ошибка сервера',500)});
app.get('/health',async()=>{await q('SELECT 1');return{ok:true,service:'owner-control',version:'3.0.0'}});

app.get('/api/v1/orders/deleted',{preHandler:owner},async()=>({data:(await q(`SELECT r.id,r.number,r.customer_id,r.status,r.deleted_at,r.delete_reason,r.deleted_snapshot,c.name customer_name,u.name deleted_by_name FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN users u ON u.id=r.deleted_by WHERE r.deleted_at IS NOT NULL ORDER BY r.deleted_at DESC LIMIT 500`)).rows}));
app.get('/api/v1/orders/:number/admin-details',{preHandler:owner},async(req,reply)=>{const r=(await q(`SELECT r.*,c.name customer_name,e.category,e.brand,e.model,eng.name engineer_name,m.name manager_name FROM requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN equipment e ON e.id=r.equipment_id LEFT JOIN users eng ON eng.id=r.engineer_id LEFT JOIN users m ON m.id=r.manager_id WHERE r.number=$1`,[req.params.number])).rows[0];if(!r)return fail(reply,'NOT_FOUND','Заказ не найден',404);return{data:r}});
app.patch('/api/v1/orders/:number',{preHandler:owner},async req=>tx(async c=>{const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[req.params.number])).rows[0];if(!cur)abort('NOT_FOUND','Заказ не найден',404);if(cur.deleted_at)abort('ORDER_DELETED','Сначала восстановите заказ',409);const b={...cur,...req.body};const complaint=String(b.complaint||'').trim();if(!complaint)abort('VALIDATION','Описание неисправности обязательно');if(!allowedStatuses.has(String(b.status)))abort('VALIDATION','Недопустимый статус');const customer=(await c.query('SELECT id FROM customers WHERE id=$1',[b.customer_id])).rows[0];if(!customer)abort('VALIDATION','Клиент не найден');let equipmentId=nullable(b.equipment_id);if(equipmentId){const eq=(await c.query('SELECT id,customer_id FROM equipment WHERE id=$1',[equipmentId])).rows[0];if(!eq)abort('VALIDATION','Техника не найдена');if(Number(eq.customer_id)!==Number(b.customer_id))abort('VALIDATION','Выбранная техника принадлежит другому клиенту')}
 let managerId=nullable(b.manager_id),engineerId=nullable(b.engineer_id);if(managerId){const u=(await c.query("SELECT id FROM users WHERE id=$1 AND role IN ('OWNER','MANAGER') AND active=true",[managerId])).rows[0];if(!u)abort('VALIDATION','Менеджер не найден')}if(engineerId){const u=(await c.query("SELECT id FROM users WHERE id=$1 AND role='ENGINEER' AND active=true",[engineerId])).rows[0];if(!u)abort('VALIDATION','Инженер не найден')}
 const row=(await c.query(`UPDATE requests SET customer_id=$1,equipment_id=$2,manager_id=$3,engineer_id=$4,status=$5,priority=$6,source=$7,complaint=$8,diagnosis=$9,work_description=$10,test_result=$11,scheduled_at=$12,sla_deadline=$13,warranty_until=$14,closed_at=CASE WHEN $5='CLOSED' THEN COALESCE(closed_at,now()) ELSE NULL END,cancelled_at=CASE WHEN $5='CANCELLED' THEN COALESCE(cancelled_at,now()) ELSE NULL END,updated_at=now() WHERE id=$15 RETURNING *`,[b.customer_id,equipmentId,managerId,engineerId,String(b.status),String(b.priority||'NORMAL'),String(b.source||'OTHER'),complaint,nullable(b.diagnosis),nullable(b.work_description),nullable(b.test_result),nullable(b.scheduled_at),nullable(b.sla_deadline),nullable(b.warranty_until),cur.id])).rows[0];
 const fields=['customer_id','equipment_id','manager_id','engineer_id','status','priority','source','complaint','diagnosis','work_description','test_result','scheduled_at','sla_deadline','warranty_until'];const before={},after={};for(const k of fields){before[k]=cur[k];after[k]=row[k]}await hist(c,cur.id,req.user.id,'OWNER_ORDER_EDITED',{before,after});return{data:row}}));
app.delete('/api/v1/orders/:number',{preHandler:owner},async req=>tx(async c=>{const reason=String(req.body?.reason||'').trim();if(reason.length<3)abort('VALIDATION','Укажите причину удаления заказа');const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[req.params.number])).rows[0];if(!cur)abort('NOT_FOUND','Заказ не найден',404);if(cur.deleted_at)return{data:{number:cur.number,deleted:true,deleted_at:cur.deleted_at}};const snapshot={status:cur.status,total:cur.total,direct_cost:cur.direct_cost,paid:cur.paid,closed_at:cur.closed_at,cancelled_at:cur.cancelled_at};await hist(c,cur.id,req.user.id,'OWNER_ORDER_DELETED',{reason,snapshot});await c.query(`UPDATE requests SET deleted_at=now(),deleted_by=$1,delete_reason=$2,deleted_snapshot=$3,status='CANCELLED',total=0,direct_cost=0,paid=0,closed_at=NULL,cancelled_at=now(),updated_at=now() WHERE id=$4`,[req.user.id,reason,snapshot,cur.id]);await c.query('UPDATE owner_order_corrections SET active=false,closed_by=$1,closed_at=now(),close_reason=$2 WHERE request_id=$3 AND active=true',[req.user.id,'Заказ удалён владельцем',cur.id]);return{data:{number:cur.number,deleted:true,message:'Заказ перемещён в корзину и исключён из финансовых результатов'}}}));
app.post('/api/v1/orders/:number/restore',{preHandler:owner},async req=>tx(async c=>{const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[req.params.number])).rows[0];if(!cur)abort('NOT_FOUND','Заказ не найден',404);if(!cur.deleted_at)return{data:{number:cur.number,restored:true,message:'Заказ уже восстановлен'}};const s=cur.deleted_snapshot||{};const status=allowedStatuses.has(String(s.status))?String(s.status):'NEW';const row=(await c.query(`UPDATE requests SET deleted_at=NULL,deleted_by=NULL,delete_reason=NULL,deleted_snapshot=NULL,status=$1,total=$2,direct_cost=$3,paid=$4,closed_at=$5,cancelled_at=$6,updated_at=now() WHERE id=$7 RETURNING *`,[status,n(s.total),n(s.direct_cost),n(s.paid),nullable(s.closed_at),nullable(s.cancelled_at),cur.id])).rows[0];await hist(c,cur.id,req.user.id,'OWNER_ORDER_RESTORED',{restored_status:status});return{data:{...row,restored:true}}}));

app.get('/api/v1/orders/:number/correction',{preHandler:owner},async(req,reply)=>{const r=(await q(`SELECT r.id,r.number,r.status,r.total,r.paid,r.direct_cost,r.deleted_at,oc.active,oc.opened_at,oc.reason,oc.original_status FROM requests r LEFT JOIN owner_order_corrections oc ON oc.request_id=r.id AND oc.active=true WHERE r.number=$1`,[req.params.number])).rows[0];if(!r)return fail(reply,'NOT_FOUND','Заказ не найден',404);return{data:{...r,correction_active:!!r.active}}});
app.get('/api/v1/orders/:number/correction/details',{preHandler:owner},async(req,reply)=>{const r=(await q(`SELECT r.id,r.number,r.status,r.total,r.paid,r.direct_cost,r.discount_amount,r.deleted_at,oc.active correction_active,oc.opened_at,oc.reason,oc.original_status FROM requests r LEFT JOIN owner_order_corrections oc ON oc.request_id=r.id AND oc.active=true WHERE r.number=$1`,[req.params.number])).rows[0];if(!r)return fail(reply,'NOT_FOUND','Заказ не найден',404);if(r.deleted_at)return fail(reply,'ORDER_DELETED','Сначала восстановите заказ',409);const [works,parts,payments]=await Promise.all([q('SELECT w.*,u.name performed_by_name FROM request_works w LEFT JOIN users u ON u.id=w.performed_by WHERE request_id=$1 ORDER BY w.created_at',[r.id]),q('SELECT * FROM parts WHERE request_id=$1 ORDER BY created_at DESC',[r.id]),q('SELECT p.*,u.name created_by_name FROM payments p LEFT JOIN users u ON u.id=p.created_by WHERE request_id=$1 ORDER BY p.created_at DESC',[r.id])]);return{data:{...r,correction_active:!!r.correction_active,works:works.rows,parts:parts.rows,payments:payments.rows}}});
app.post('/api/v1/orders/:number/reopen',{preHandler:owner},async req=>tx(async c=>{const number=String(req.params.number||'').trim(),reason=String(req.body?.reason||'Корректировка заказа').trim();const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[number])).rows[0];if(!cur)abort('NOT_FOUND','Заказ не найден',404);if(cur.deleted_at)abort('ORDER_DELETED','Сначала восстановите заказ',409);if(await active(c,cur.id))return{data:{number,correction_active:true,message:'Режим корректировки уже активен'}};await c.query(`INSERT INTO owner_order_corrections(request_id,active,opened_by,reason,original_status,original_closed_at) VALUES($1,true,$2,$3,$4,$5) ON CONFLICT(request_id) DO UPDATE SET active=true,opened_by=$2,opened_at=now(),reason=$3,original_status=$4,original_closed_at=$5,closed_by=NULL,closed_at=NULL,close_reason=NULL`,[cur.id,req.user.id,reason,cur.status,cur.closed_at]);if(cur.status==='CLOSED')await c.query("UPDATE requests SET status='PAYMENT_REQUIRED',closed_at=NULL,updated_at=now() WHERE id=$1",[cur.id]);await hist(c,cur.id,req.user.id,'OWNER_CORRECTION_STARTED',{reason,from_status:cur.status,total:cur.total,paid:cur.paid});return{data:{number,correction_active:true,message:'Режим корректировки включён'}}}));
app.patch('/api/v1/correction/works/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM request_works WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Работа не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);const b={...old,...req.body},name=validateLine(b,'work');const row=(await c.query('UPDATE request_works SET name=$1,qty=$2,unit_price=$3,direct_cost=$4,updated_at=now() WHERE id=$5 RETURNING *',[name,n(b.qty),n(b.unit_price),n(b.direct_cost),old.id])).rows[0];const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_CORRECTED_WORK',{work_id:old.id,before:old,after:row});return{data:{item:row,totals}}}));
app.delete('/api/v1/correction/works/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM request_works WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Работа не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM request_works WHERE id=$1',[old.id]);const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_DELETED_WORK',{work_id:old.id,before:old});return{data:{ok:true,totals}}}));
app.patch('/api/v1/correction/parts/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM parts WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Запчасть не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);const b={...old,...req.body},name=validateLine(b,'part');const row=(await c.query('UPDATE parts SET name=$1,qty=$2,purchase_price=$3,sale_price=$4,updated_at=now() WHERE id=$5 RETURNING *',[name,n(b.qty),n(b.purchase_price),n(b.sale_price),old.id])).rows[0];const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_CORRECTED_PART',{part_id:old.id,before:old,after:row});return{data:{item:row,totals}}}));
app.delete('/api/v1/correction/parts/:id',{preHandler:owner},async req=>tx(async c=>{const old=(await c.query('SELECT * FROM parts WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old)abort('NOT_FOUND','Запчасть не найдена',404);if(!await active(c,old.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM parts WHERE id=$1',[old.id]);const totals=await recalc(c,old.request_id);await hist(c,old.request_id,req.user.id,'OWNER_DELETED_PART',{part_id:old.id,before:old});return{data:{ok:true,totals}}}));
app.delete('/api/v1/correction/payments/:id',{preHandler:owner},async req=>tx(async c=>{const p=(await c.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!p)abort('NOT_FOUND','Платёж не найден',404);if(!await active(c,p.request_id))abort('CORRECTION_REQUIRED','Сначала включите режим корректировки',409);await c.query('DELETE FROM payments WHERE id=$1',[p.id]);const sums=(await c.query("SELECT COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount WHEN kind='REFUND' THEN -amount ELSE 0 END),0) paid FROM payments WHERE request_id=$1",[p.request_id])).rows[0],paid=Math.max(0,n(sums.paid));await c.query('UPDATE requests SET paid=$1,updated_at=now() WHERE id=$2',[paid,p.request_id]);await hist(c,p.request_id,req.user.id,'OWNER_DELETED_PAYMENT',{payment_id:p.id,before:p,paid_after:paid});return{data:{ok:true,paid}}}));
app.post('/api/v1/orders/:number/close',{preHandler:owner},async req=>tx(async c=>{const number=String(req.params.number||'').trim(),reason=String(req.body?.reason||'Корректировка завершена').trim();const cur=(await c.query('SELECT * FROM requests WHERE number=$1 FOR UPDATE',[number])).rows[0];if(!cur)abort('NOT_FOUND','Заказ не найден',404);if(cur.deleted_at)abort('ORDER_DELETED','Сначала восстановите заказ',409);if(!await active(c,cur.id))abort('CORRECTION_NOT_ACTIVE','Режим корректировки не активен',409);const total=n(cur.total),paid=n(cur.paid),delta=paid-total;if(delta<-0.01)abort('PAYMENT_REQUIRED',`Нельзя закрыть заказ: оплачено ${paid}, итог ${total}`,409);if(delta>1)abort('OVERPAYMENT_REQUIRES_REVIEW',`Нельзя закрыть заказ: переплата ${delta.toFixed(2)} ₸. Исправьте ошибочные платежи.`,409);const row=(await c.query("UPDATE requests SET status='CLOSED',closed_at=now(),updated_at=now() WHERE id=$1 RETURNING id,number,status,total,paid,closed_at",[cur.id])).rows[0];await c.query('UPDATE owner_order_corrections SET active=false,closed_by=$1,closed_at=now(),close_reason=$2 WHERE request_id=$3',[req.user.id,reason,cur.id]);await hist(c,cur.id,req.user.id,'OWNER_CORRECTION_FINISHED',{reason,total,paid});return{data:{...row,correction_active:false,message:'Корректировка завершена'}}}));
const close=async()=>{try{await pool.end()}finally{process.exit(0)}};process.on('SIGTERM',close);process.on('SIGINT',close);
app.listen({port:Number(process.env.PORT||8103),host:'0.0.0.0'});