import {calculatePayroll,payrollPeriod} from './payroll-calculation.js';
import {authenticate,installOrderAccess} from './access.js';
import {can,PERMISSIONS} from './rbac.js';
import {lockAccounts,insertEntry,date as financeDate,money as financeMoney} from './finance/service.js';
import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import jwt from '@fastify/jwt';
import pg from 'pg';
import {createHash,randomUUID} from 'node:crypto';

const app=Fastify({logger:true});
await app.register(cors,{origin:(process.env.CORS_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()),credentials:true});
await app.register(helmet,{contentSecurityPolicy:false});
await app.register(rateLimit,{max:300,timeWindow:'1 minute'});
await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||10)});
const q=(s,p=[])=>pool.query(s,p);const n=v=>Number(v||0);const fail=(r,c,m,s=422)=>r.code(s).send({data:null,error:{code:c,message:m}});
const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}};
const auth=async(req,reply)=>{if(!await authenticate(req,reply,pool))return;};
const view=async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!can(req.user.role,PERMISSIONS.PAYROLL_VIEW))return fail(reply,'FORBIDDEN','Нет доступа к зарплате',403)};
const manage=async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!can(req.user.role,PERMISSIONS.PAYROLL_MANAGE))return fail(reply,'FORBIDDEN','Нет прав на операции по зарплате',403)};
const summaryView=async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!can(req.user.role,PERMISSIONS.PAYROLL_SUMMARY_VIEW))return fail(reply,'FORBIDDEN','Нет доступа к сводке зарплаты',403)};
const selfView=async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!can(req.user.role,PERMISSIONS.PAYROLL_SELF_VIEW)&&!can(req.user.role,PERMISSIONS.PAYROLL_VIEW))return fail(reply,'FORBIDDEN','Нет доступа к собственным начислениям',403)};
const owner=async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(req.user.role!=='OWNER')return fail(reply,'FORBIDDEN','Это действие доступно только собственнику',403)};
const money=v=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
const monthStart=v=>payrollPeriod(v)[0];
const monthEnd=start=>new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,1));
const monthKey=d=>new Date(d).toISOString().slice(0,7)+'-01';
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const opKey=req=>String(req.headers['idempotency-key']||`payroll-${randomUUID()}`).slice(0,160);
const documentNo=prefix=>`${prefix}-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${randomUUID().slice(0,8).toUpperCase()}`;
const requiredText=(v,label,min=2,max=500)=>{const s=String(v||'').trim();if(s.length<min||s.length>max)throw Object.assign(new Error(`Заполните поле «${label}»`),{code:'VALIDATION',statusCode:422});return s};

installOrderAccess(app,pool,'payroll');
app.get('/health',async()=>{await q('SELECT 1');return{ok:true,service:'profi24-payroll',version:'2.1.1'}});

async function branch(c,id){const row=(await c.query('SELECT id,code,name FROM branches WHERE id=$1 AND active=true',[Number(id)])).rows[0];if(!row)throw Object.assign(new Error('Филиал не найден или отключён'),{code:'BRANCH_NOT_FOUND',statusCode:422});return row}
async function employee(c,id){const row=(await c.query('SELECT id,name,role,active,primary_branch_id FROM users WHERE id=$1',[Number(id)])).rows[0];if(!row)throw Object.assign(new Error('Сотрудник не найден'),{code:'NOT_FOUND',statusCode:404});if(!row.primary_branch_id)throw Object.assign(new Error('У сотрудника не назначен основной филиал'),{code:'BRANCH_REQUIRED',statusCode:409});return row}
async function ensurePeriodMutable(c,branchId,periodMonth){const row=(await c.query('SELECT * FROM payroll_periods WHERE branch_id=$1 AND period_month=$2::date FOR UPDATE',[branchId,periodMonth])).rows[0];if(row&&['APPROVED','PAID','CLOSED'].includes(row.status))throw Object.assign(new Error(`Период ${String(periodMonth).slice(0,7)} уже ${row.status}; изменения входных данных запрещены`),{code:'PAYROLL_PERIOD_LOCKED',statusCode:409});return row}
async function periodPaymentTotals(c,p){
  const due=Number((await c.query('SELECT COALESCE(sum(GREATEST(total,0)),0) amount FROM payroll_accruals WHERE period_id=$1 AND revision=$2',[p.id,p.calculation_revision])).rows[0].amount||0);
  const paid=Number((await c.query("SELECT COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount ELSE -amount END),0) amount FROM payroll_payments WHERE period_id=$1 AND revision=$2",[p.id,p.calculation_revision])).rows[0].amount||0);
  return{due:money(due),paid:money(paid),remaining:money(Math.max(0,due-paid))};
}
async function periodDetails(c,id){
  const p=(await c.query(`SELECT p.*,b.code branch_code,b.name branch_name,cu.name calculated_by_name,au.name approved_by_name,pu.name paid_by_name,cl.name closed_by_name FROM payroll_periods p JOIN branches b ON b.id=p.branch_id LEFT JOIN users cu ON cu.id=p.calculated_by LEFT JOIN users au ON au.id=p.approved_by LEFT JOIN users pu ON pu.id=p.paid_by LEFT JOIN users cl ON cl.id=p.closed_by WHERE p.id=$1`,[id])).rows[0];if(!p)return null;
  const paymentTotals=await periodPaymentTotals(c,p);
  const paidByUser=new Map((await c.query("SELECT user_id,COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount ELSE -amount END),0) paid FROM payroll_payments WHERE period_id=$1 AND revision=$2 GROUP BY user_id",[p.id,p.calculation_revision])).rows.map(x=>[Number(x.user_id),Number(x.paid)]));
  const accruals=p.calculation_revision?(await c.query(`SELECT a.*,u.name,u.role,u.active FROM payroll_accruals a JOIN users u ON u.id=a.user_id WHERE a.period_id=$1 AND a.revision=$2 ORDER BY u.role,u.name`,[p.id,p.calculation_revision])).rows.map(a=>({...a,paid_amount:money(paidByUser.get(Number(a.user_id))||0),due_amount:money(Math.max(0,n(a.total)-(paidByUser.get(Number(a.user_id))||0)))})):[];
  const payments=(await c.query(`SELECT pp.*,u.name user_name,a.name account_name,cb.name created_by_name,ft.occurred_at FROM payroll_payments pp JOIN users u ON u.id=pp.user_id JOIN finance_accounts a ON a.id=pp.account_id JOIN finance_transactions ft ON ft.id=pp.finance_transaction_id LEFT JOIN users cb ON cb.id=pp.created_by WHERE pp.period_id=$1 ORDER BY pp.id DESC`,[p.id])).rows;
  const events=(await c.query(`SELECT e.*,u.name actor_name FROM payroll_period_events e LEFT JOIN users u ON u.id=e.actor_id WHERE e.period_id=$1 ORDER BY e.id DESC`,[p.id])).rows;
  return{...p,payment_totals:paymentTotals,accruals,payments,events};
}

app.get('/api/v1/rules',{preHandler:view},async()=>({data:(await q(`SELECT u.id user_id,u.name,u.email,u.role,u.active,u.primary_branch_id,
 rv.id rule_version_id,rv.effective_from,COALESCE(rv.base_salary,0)::numeric base_salary,COALESCE(rv.order_percent,0)::numeric order_percent,
 COALESCE(rv.work_percent,0)::numeric work_percent,COALESCE(rv.gross_profit_percent,0)::numeric gross_profit_percent,
 COALESCE(rv.active,false) rule_active,rv.reason rule_reason
 FROM users u LEFT JOIN LATERAL(SELECT v.* FROM payroll_rule_versions v WHERE v.user_id=u.id ORDER BY v.effective_from DESC,v.id DESC LIMIT 1) rv ON true
 ORDER BY u.active DESC,u.role,u.name`)).rows}));

app.put('/api/v1/rules/:userId',{preHandler:owner},async(req,reply)=>{
 const userId=Number(req.params.userId),b=req.body||{};if(!Number.isSafeInteger(userId)||userId<1)return fail(reply,'VALIDATION','Сотрудник не указан');
 for(const x of ['base_salary','order_percent','work_percent','gross_profit_percent'])if(!Number.isFinite(Number(b[x]||0))||n(b[x])<0)return fail(reply,'VALIDATION','Значения правила не могут быть отрицательными');
 const effective=monthKey(monthStart(b.effective_from||b.month));const reason=String(b.reason||'Изменение условий оплаты').trim();if(reason.length<3)return fail(reply,'VALIDATION','Укажите причину изменения правила');
 try{const result=await tx(async c=>{await employee(c,userId);const previous=(await c.query('SELECT id FROM payroll_rule_versions WHERE user_id=$1 ORDER BY effective_from DESC,id DESC LIMIT 1',[userId])).rows[0];const row=(await c.query(`INSERT INTO payroll_rule_versions(user_id,effective_from,base_salary,order_percent,work_percent,gross_profit_percent,active,supersedes_id,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[userId,effective,n(b.base_salary),n(b.order_percent),n(b.work_percent),n(b.gross_profit_percent),b.active!==false,previous?.id||null,reason,req.user.id])).rows[0];const latest=(await c.query('SELECT * FROM payroll_rule_versions WHERE user_id=$1 ORDER BY effective_from DESC,id DESC LIMIT 1',[userId])).rows[0];await c.query(`INSERT INTO payroll_rules(user_id,base_salary,order_percent,work_percent,gross_profit_percent,active,updated_by,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()) ON CONFLICT(user_id) DO UPDATE SET base_salary=$2,order_percent=$3,work_percent=$4,gross_profit_percent=$5,active=$6,updated_by=$7,updated_at=now()`,[userId,latest.base_salary,latest.order_percent,latest.work_percent,latest.gross_profit_percent,latest.active,req.user.id]);return row});return reply.code(201).send({data:result})}catch(e){if(e.code==='23505')return fail(reply,'RULE_VERSION_EXISTS','Для этого сотрудника уже есть версия правила с такой датой. Создайте новую дату вступления в силу.',409);throw e}
});

app.get('/api/v1/adjustments',{preHandler:view},async req=>{const start=monthStart(req.query?.month),end=monthEnd(start),branchId=req.query?.branch_id?Number(req.query.branch_id):null;const params=[start,end];let bs='';if(branchId){params.push(branchId);bs=` AND a.branch_id=$${params.length}`;}return{data:(await q(`SELECT a.*,u.name user_name,cb.name created_by_name,rb.name reversed_by_name FROM payroll_adjustments a JOIN users u ON u.id=a.user_id LEFT JOIN users cb ON cb.id=a.created_by LEFT JOIN payroll_adjustments rev ON rev.reversal_of=a.id LEFT JOIN users rb ON rb.id=rev.created_by WHERE a.period_month>=$1 AND a.period_month<$2${bs} ORDER BY a.created_at DESC`,params)).rows}});

app.post('/api/v1/adjustments',{preHandler:manage},async(req,reply)=>{const b=req.body||{},amount=Math.abs(n(b.amount));if(!b.user_id||!amount||!b.reason?.trim()||!['BONUS','PENALTY','OTHER'].includes(b.type))return fail(reply,'VALIDATION','Заполните сотрудника, сумму, тип и причину');const start=monthStart(b.month),period=monthKey(start),key=opKey(req);const result=await tx(async c=>{const replay=(await c.query('SELECT * FROM payroll_adjustments WHERE idempotency_key=$1',[key])).rows[0];if(replay)return replay;const u=await employee(c,b.user_id);await ensurePeriodMutable(c,u.primary_branch_id,period);const signed=b.type==='PENALTY'?-amount:amount;return(await c.query(`INSERT INTO payroll_adjustments(user_id,period_month,amount,type,reason,created_by,branch_id,idempotency_key,document_no) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[u.id,period,signed,b.type,String(b.reason).trim(),req.user.id,u.primary_branch_id,key,documentNo('ADJ')])).rows[0]});return reply.code(201).send({data:result})});

app.delete('/api/v1/adjustments/:id',{preHandler:manage},async(req,reply)=>fail(reply,'IMMUTABLE_ADJUSTMENT','Корректировку нельзя удалить. Используйте сторно.',409));
app.post('/api/v1/adjustments/:id/reverse',{preHandler:manage},async(req,reply)=>{const reason=String(req.body?.reason||'').trim();if(reason.length<3)return fail(reply,'VALIDATION','Укажите причину сторно');const key=opKey(req);const result=await tx(async c=>{const replay=(await c.query('SELECT * FROM payroll_adjustments WHERE idempotency_key=$1',[key])).rows[0];if(replay)return replay;const source=(await c.query('SELECT * FROM payroll_adjustments WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!source)throw Object.assign(new Error('Корректировка не найдена'),{code:'NOT_FOUND',statusCode:404});const existing=(await c.query('SELECT * FROM payroll_adjustments WHERE reversal_of=$1 ORDER BY id DESC LIMIT 1',[source.id])).rows[0];if(existing)return existing;await ensurePeriodMutable(c,source.branch_id,source.period_month);return(await c.query(`INSERT INTO payroll_adjustments(user_id,period_month,amount,type,reason,created_by,branch_id,reversal_of,idempotency_key,document_no) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[source.user_id,source.period_month,-n(source.amount),source.type,`Сторно: ${reason}`,req.user.id,source.branch_id,source.id,key,documentNo('REV')])).rows[0]});return reply.code(201).send({data:result})});

app.get('/api/v1/report',{preHandler:view},async req=>{const[start,end]=payrollPeriod(req.query?.month),branchId=req.query?.branch_id?Number(req.query.branch_id):null;const{rows,totals}=await calculatePayroll(pool,start,end,{branchId});return{data:{month:start.toISOString().slice(0,7),branch_id:branchId,rows,totals}}});

app.get('/api/v1/summary',{preHandler:summaryView},async req=>{const params=[];let where="WHERE p.status IN('CALCULATED','APPROVED','PAID','CLOSED')";if(req.query?.month){params.push(monthKey(monthStart(req.query.month)));where+=` AND p.period_month=$${params.length}::date`;}if(req.query?.branch_id){params.push(Number(req.query.branch_id));where+=` AND p.branch_id=$${params.length}`;}const rows=(await q(`SELECT p.id,p.branch_id,p.period_month,p.status,p.calculation_revision,p.totals,p.calculated_at,p.approved_at,p.paid_at,p.closed_at,b.code branch_code,b.name branch_name FROM payroll_periods p JOIN branches b ON b.id=p.branch_id ${where} ORDER BY p.period_month DESC,b.name`,params)).rows;return{data:{rows,totals:{salary:money(rows.reduce((s,x)=>s+n(x.totals?.salary),0)),revenue:money(rows.reduce((s,x)=>s+n(x.totals?.revenue),0)),gross_profit:money(rows.reduce((s,x)=>s+n(x.totals?.gross_profit),0))}}}});
app.get('/api/v1/self',{preHandler:selfView},async(req,reply)=>{const month=monthKey(monthStart(req.query?.month));const row=(await q(`SELECT a.*,p.period_month,p.status,p.approved_at,p.paid_at,p.closed_at,b.code branch_code,b.name branch_name FROM payroll_periods p JOIN payroll_accruals a ON a.period_id=p.id AND a.revision=p.calculation_revision JOIN branches b ON b.id=p.branch_id WHERE a.user_id=$1 AND p.period_month=$2::date AND p.status IN('APPROVED','PAID','CLOSED') ORDER BY p.id DESC LIMIT 1`,[req.user.id,month])).rows[0];if(!row)return{data:null};const paid=Number((await q("SELECT COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount ELSE -amount END),0) paid FROM payroll_payments WHERE period_id=$1 AND revision=$2 AND user_id=$3",[row.period_id,row.revision,req.user.id])).rows[0].paid||0);return{data:{...row,paid_amount:money(paid),due_amount:money(Math.max(0,n(row.total)-paid))}}});

app.get('/api/v1/periods',{preHandler:view},async req=>{const params=[];let where='WHERE 1=1';if(req.query?.month){params.push(monthKey(monthStart(req.query.month)));where+=` AND p.period_month=$${params.length}::date`;}if(req.query?.branch_id){params.push(Number(req.query.branch_id));where+=` AND p.branch_id=$${params.length}`;}return{data:(await q(`SELECT p.*,b.code branch_code,b.name branch_name FROM payroll_periods p JOIN branches b ON b.id=p.branch_id ${where} ORDER BY p.period_month DESC,b.name`,params)).rows}});
app.get('/api/v1/periods/:id',{preHandler:view},async(req,reply)=>{const data=await periodDetails(pool,Number(req.params.id));if(!data)return fail(reply,'NOT_FOUND','Расчётный период не найден',404);return{data}});

app.post('/api/v1/periods/calculate',{preHandler:manage},async(req,reply)=>{const b=req.body||{},branchId=Number(b.branch_id);if(!Number.isSafeInteger(branchId)||branchId<1)return fail(reply,'VALIDATION','Выберите филиал');const[start,end]=payrollPeriod(b.month),periodMonth=monthKey(start);const result=await tx(async c=>{await branch(c,branchId);let period=(await c.query('SELECT * FROM payroll_periods WHERE branch_id=$1 AND period_month=$2::date FOR UPDATE',[branchId,periodMonth])).rows[0];if(!period)period=(await c.query(`INSERT INTO payroll_periods(branch_id,period_month,status,created_by) VALUES($1,$2,'DRAFT',$3) RETURNING *`,[branchId,periodMonth,req.user.id])).rows[0];if(['APPROVED','PAID','CLOSED'].includes(period.status))throw Object.assign(new Error('Утверждённый или закрытый период нельзя пересчитать'),{code:'PAYROLL_PERIOD_LOCKED',statusCode:409});const revision=Number(period.calculation_revision||0)+1;const calc=await calculatePayroll(c,start,end,{branchId});const fingerprint=hash({branch_id:branchId,period_month:periodMonth,revision,rows:calc.rows.map(x=>({id:x.id,rule:x.rule_version_id,salary:x.salary,kpi:x.kpi_result_id,adjustments:x.adjustments,jobs:x.jobs,revenue:x.revenue})),totals:calc.totals});for(const row of calc.rows){await c.query(`INSERT INTO payroll_accruals(period_id,revision,user_id,branch_id,rule_version_id,kpi_result_id,base_salary,order_commission,work_commission,gross_profit_commission,kpi_bonus,adjustments,total,inputs,fingerprint,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[period.id,revision,row.id,branchId,row.rule_version_id,row.kpi_result_id,row.rule_active?n(row.base_salary):0,row.order_commission,row.work_commission,row.gross_profit_commission,row.kpi_bonus,row.adjustments,row.salary,{jobs:row.jobs,revenue:row.revenue,gross_profit:row.gross_profit,work_sales:row.work_sales,kpi_score:row.kpi_score,role:row.role,active:row.active},fingerprint,req.user.id])}period=(await c.query(`UPDATE payroll_periods SET status='CALCULATED',calculation_revision=$1,input_cutoff=clock_timestamp(),totals=$2,snapshot_hash=$3,calculated_by=$4,calculated_at=clock_timestamp(),updated_at=now() WHERE id=$5 RETURNING *`,[revision,calc.totals,fingerprint,req.user.id,period.id])).rows[0];await c.query(`INSERT INTO payroll_period_events(period_id,actor_id,action,details) VALUES($1,$2,'PAYROLL_CALCULATED',$3)`,[period.id,req.user.id,{revision,fingerprint,totals:calc.totals}]);return periodDetails(c,period.id)});return reply.code(201).send({data:result})});

app.post('/api/v1/periods/:id/approve',{preHandler:owner},async(req,reply)=>{const result=await tx(async c=>{const p=(await c.query('SELECT * FROM payroll_periods WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!p)throw Object.assign(new Error('Расчётный период не найден'),{code:'NOT_FOUND',statusCode:404});if(['APPROVED','PAID','CLOSED'].includes(p.status))return periodDetails(c,p.id);if(p.status!=='CALCULATED'||!p.calculation_revision)throw Object.assign(new Error('Сначала выполните расчёт периода'),{code:'PAYROLL_NOT_CALCULATED',statusCode:409});await c.query(`UPDATE payroll_periods SET status='APPROVED',approved_by=$1,approved_at=clock_timestamp(),updated_at=now() WHERE id=$2`,[req.user.id,p.id]);await c.query(`INSERT INTO payroll_period_events(period_id,actor_id,action,details) VALUES($1,$2,'PAYROLL_APPROVED',$3)`,[p.id,req.user.id,{revision:p.calculation_revision,snapshot_hash:p.snapshot_hash,totals:p.totals}]);return periodDetails(c,p.id)});return{data:result}});

app.post('/api/v1/periods/:id/payments',{preHandler:manage},async(req,reply)=>{
  const b=req.body||{},userId=Number(b.user_id),accountId=Number(b.account_id),doc=requiredText(b.document_reference,'Документ выплаты',2,200),key=opKey(req);
  if(!Number.isSafeInteger(userId)||userId<1||!Number.isSafeInteger(accountId)||accountId<1)return fail(reply,'VALIDATION','Выберите сотрудника и денежный счёт');
  const amountText=financeMoney(b.amount),occurredAt=financeDate(b.occurred_at);const amount=n(amountText);
  const result=await tx(async c=>{
    const replay=(await c.query('SELECT * FROM payroll_payments WHERE idempotency_key=$1',[key])).rows[0];if(replay)return{payment:replay,period:await periodDetails(c,replay.period_id)};
    const p=(await c.query('SELECT * FROM payroll_periods WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!p)throw Object.assign(new Error('Расчётный период не найден'),{code:'NOT_FOUND',statusCode:404});if(p.status==='CLOSED')throw Object.assign(new Error('Закрытый зарплатный период нельзя изменять'),{code:'PAYROLL_PERIOD_LOCKED',statusCode:409});if(!['APPROVED','PAID'].includes(p.status))throw Object.assign(new Error('Сначала утвердите расчёт зарплаты'),{code:'PAYROLL_NOT_APPROVED',statusCode:409});
    const accrual=(await c.query('SELECT a.*,u.name FROM payroll_accruals a JOIN users u ON u.id=a.user_id WHERE a.period_id=$1 AND a.revision=$2 AND a.user_id=$3',[p.id,p.calculation_revision,userId])).rows[0];if(!accrual)throw Object.assign(new Error('Начисление сотрудника не найдено в утверждённой ревизии'),{code:'NOT_FOUND',statusCode:404});
    const already=Number((await c.query("SELECT COALESCE(sum(CASE WHEN kind='PAYMENT' THEN amount ELSE -amount END),0) amount FROM payroll_payments WHERE period_id=$1 AND revision=$2 AND user_id=$3",[p.id,p.calculation_revision,userId])).rows[0].amount||0),due=Math.max(0,n(accrual.total)-already);if(amount>due+0.001)throw Object.assign(new Error(`Сумма выплаты больше долга сотруднику: ${money(due)} ₸`),{code:'PAYROLL_OVERPAYMENT',statusCode:409});
    const [account]=await lockAccounts(c,[accountId],req.user);if(Number(account.branch_id)!==Number(p.branch_id))throw Object.assign(new Error('Денежный счёт относится к другому филиалу'),{code:'ACCOUNT_BRANCH_MISMATCH',statusCode:422});
    const financeKey=`payroll:${key}`;const finance=(await c.query('SELECT * FROM finance_transactions WHERE idempotency_key=$1',[financeKey])).rows[0]||await insertEntry(c,req.user,{account_id:account.id,type:'EXPENSE',kind:'PAYROLL_PAYMENT',category:'PAYROLL',amount:amountText,occurred_at:occurredAt,comment:`Выплата зарплаты ${String(p.period_month).slice(0,7)} — ${accrual.name}`,document_reference:doc,counterparty:accrual.name,idempotency_key:financeKey,metadata:{payroll_period_id:p.id,payroll_revision:p.calculation_revision,payroll_user_id:userId}});
    const payment=(await c.query(`INSERT INTO payroll_payments(period_id,revision,user_id,branch_id,account_id,finance_transaction_id,kind,amount,document_reference,idempotency_key,created_by) VALUES($1,$2,$3,$4,$5,$6,'PAYMENT',$7,$8,$9,$10) RETURNING *`,[p.id,p.calculation_revision,userId,p.branch_id,account.id,finance.id,amountText,doc,key,req.user.id])).rows[0];
    const totals=await periodPaymentTotals(c,p);if(totals.remaining<=0.001&&p.status!=='PAID'){await c.query("UPDATE payroll_periods SET status='PAID',paid_by=$1,paid_at=clock_timestamp(),updated_at=now() WHERE id=$2",[req.user.id,p.id]);await c.query(`INSERT INTO payroll_period_events(period_id,actor_id,action,details) VALUES($1,$2,'PAYROLL_PAID',$3)`,[p.id,req.user.id,{revision:p.calculation_revision,due:totals.due,paid:totals.paid}])}else await c.query(`INSERT INTO payroll_period_events(period_id,actor_id,action,details) VALUES($1,$2,'PAYROLL_PAYMENT_POSTED',$3)`,[p.id,req.user.id,{payment_id:payment.id,user_id:userId,amount,account_id:account.id,remaining:totals.remaining}]);
    return{payment,period:await periodDetails(c,p.id)};
  });return reply.code(201).send({data:result});
});

app.post('/api/v1/payments/:id/reverse',{preHandler:manage},async(req,reply)=>{
  const reason=requiredText(req.body?.reason,'Причина сторно',3,500),doc=requiredText(req.body?.document_reference,'Документ сторно',2,200),key=opKey(req),occurredAt=financeDate(req.body?.occurred_at);
  const result=await tx(async c=>{
    const replay=(await c.query('SELECT * FROM payroll_payments WHERE idempotency_key=$1',[key])).rows[0];if(replay)return{payment:replay,period:await periodDetails(c,replay.period_id)};
    const source=(await c.query("SELECT pp.*,ft.type finance_type,ft.category finance_category FROM payroll_payments pp JOIN finance_transactions ft ON ft.id=pp.finance_transaction_id WHERE pp.id=$1 AND pp.kind='PAYMENT' FOR UPDATE OF pp",[req.params.id])).rows[0];if(!source)throw Object.assign(new Error('Выплата зарплаты не найдена'),{code:'NOT_FOUND',statusCode:404});const p=(await c.query('SELECT * FROM payroll_periods WHERE id=$1 FOR UPDATE',[source.period_id])).rows[0];if(p.status==='CLOSED')throw Object.assign(new Error('Закрытый зарплатный период нельзя сторнировать'),{code:'PAYROLL_PERIOD_LOCKED',statusCode:409});
    const existing=(await c.query("SELECT * FROM payroll_payments WHERE reversal_of=$1 AND kind='REVERSAL'",[source.id])).rows[0];if(existing)return{payment:existing,period:await periodDetails(c,p.id)};
    const [account]=await lockAccounts(c,[source.account_id],req.user,{active:false});const financeKey=`payroll:${key}`;const finance=await insertEntry(c,req.user,{account_id:account.id,type:'INCOME',kind:'REVERSAL',category:source.finance_category||'PAYROLL',amount:String(source.amount),occurred_at:occurredAt,comment:`Сторно выплаты зарплаты: ${reason}`,document_reference:doc,reversal_of:source.finance_transaction_id,idempotency_key:financeKey,metadata:{payroll_period_id:p.id,payroll_payment_id:source.id,reason}});
    const reversal=(await c.query(`INSERT INTO payroll_payments(period_id,revision,user_id,branch_id,account_id,finance_transaction_id,kind,amount,reversal_of,document_reference,reason,idempotency_key,created_by) VALUES($1,$2,$3,$4,$5,$6,'REVERSAL',$7,$8,$9,$10,$11,$12) RETURNING *`,[source.period_id,source.revision,source.user_id,source.branch_id,source.account_id,finance.id,source.amount,source.id,doc,reason,key,req.user.id])).rows[0];if(p.status==='PAID')await c.query("UPDATE payroll_periods SET status='APPROVED',paid_by=NULL,paid_at=NULL,updated_at=now() WHERE id=$1",[p.id]);await c.query(`INSERT INTO payroll_period_events(period_id,actor_id,action,details) VALUES($1,$2,'PAYROLL_PAYMENT_REVERSED',$3)`,[p.id,req.user.id,{payment_id:source.id,reversal_id:reversal.id,user_id:source.user_id,amount:source.amount,reason}]);return{payment:reversal,period:await periodDetails(c,p.id)};
  });return reply.code(201).send({data:result});
});

app.post('/api/v1/periods/:id/close',{preHandler:owner},async(req,reply)=>{const reason=requiredText(req.body?.reason||'Период проверен и закрыт','Причина закрытия',3,500);const result=await tx(async c=>{const p=(await c.query('SELECT * FROM payroll_periods WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!p)throw Object.assign(new Error('Расчётный период не найден'),{code:'NOT_FOUND',statusCode:404});if(p.status==='CLOSED')return periodDetails(c,p.id);const totals=await periodPaymentTotals(c,p);if(p.status==='APPROVED'&&totals.due<=0.001){await c.query("UPDATE payroll_periods SET status='PAID',paid_by=$1,paid_at=clock_timestamp(),updated_at=now() WHERE id=$2",[req.user.id,p.id]);await c.query(`INSERT INTO payroll_period_events(period_id,actor_id,action,details) VALUES($1,$2,'PAYROLL_ZERO_BALANCE_PAID',$3)`,[p.id,req.user.id,{revision:p.calculation_revision}]);p.status='PAID'}if(p.status!=='PAID'||totals.remaining>0.001)throw Object.assign(new Error(`Период нельзя закрыть: осталось выплатить ${totals.remaining} ₸`),{code:'PAYROLL_NOT_PAID',statusCode:409});await c.query("UPDATE payroll_periods SET status='CLOSED',closed_by=$1,closed_at=clock_timestamp(),updated_at=now() WHERE id=$2",[req.user.id,p.id]);await c.query(`INSERT INTO payroll_period_events(period_id,actor_id,action,details) VALUES($1,$2,'PAYROLL_CLOSED',$3)`,[p.id,req.user.id,{revision:p.calculation_revision,reason,totals:p.totals,payment_totals:totals}]);return periodDetails(c,p.id)});return{data:result}});

const close=async()=>{try{await pool.end()}finally{process.exit(0)}};process.on('SIGTERM',close);process.on('SIGINT',close);
app.listen({port:Number(process.env.PORT||8083),host:'0.0.0.0'});
