import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import jwt from '@fastify/jwt';
import rateLimit from '@fastify/rate-limit';
import pg from 'pg';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {authenticate} from './access.js';
import {can,PERMISSIONS} from './rbac.js';
import {supplierCatalogStatements} from './supplier-catalog-schema.js';
import {parseSupplierFile,detectMapping,normalizeSupplierRows} from './supplier-file-parser.js';

const fail=(reply,code,message,status=422,details)=>reply.code(status).send({data:null,error:{code,message,details}});
const n=v=>Number(v||0),clean=(v,max=500)=>String(v??'').trim().slice(0,max);
const globalRoles=new Set(['OWNER','SUPERVISOR','ACCOUNTANT']);
const sameNum=(a,b)=>Math.abs(Number(a??0)-Number(b??0))<0.005;
const norm=v=>String(v||'').trim().toLowerCase();

export async function prepareSupplierCatalog(pool){for(const sql of supplierCatalogStatements)await pool.query(sql)}

export function installSupplierCatalog(app,pool){
 const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}};
 const auth=async(req,reply)=>{if(!await authenticate(req,reply,pool))return};
 const permit=permission=>async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(!can(req.user.role,permission))return fail(reply,'FORBIDDEN','Недостаточно прав',403)};
 const view=permit(PERMISSIONS.PROCUREMENT_VIEW),manage=permit(PERMISSIONS.PROCUREMENT_MANAGE);
 async function branchIds(c,user){if(globalRoles.has(user.role))return null;return(await c.query('SELECT branch_id FROM user_branches WHERE user_id=$1',[user.id])).rows.map(x=>Number(x.branch_id))}
 async function defaultBranch(c,user){const u=(await c.query('SELECT primary_branch_id FROM users WHERE id=$1',[user.id])).rows[0];if(u?.primary_branch_id)return Number(u.primary_branch_id);return Number((await c.query("SELECT id FROM branches WHERE code='KST' AND active=true LIMIT 1")).rows[0]?.id||0)}
 async function assertBranch(c,user,id){const branchId=Number(id||await defaultBranch(c,user));if(!branchId)throw Object.assign(new Error('Филиал не найден'),{code:'BRANCH_REQUIRED',statusCode:422});const b=(await c.query('SELECT id,code,name,active FROM branches WHERE id=$1',[branchId])).rows[0];if(!b||!b.active)throw Object.assign(new Error('Филиал не найден или отключён'),{code:'BRANCH_NOT_FOUND',statusCode:404});if(!globalRoles.has(user.role)&&!(await c.query('SELECT 1 FROM user_branches WHERE user_id=$1 AND branch_id=$2',[user.id,branchId])).rows[0])throw Object.assign(new Error('Нет доступа к этому филиалу'),{code:'FORBIDDEN',statusCode:403});return b}
 async function supplier(c,id){const s=(await c.query('SELECT * FROM suppliers WHERE id=$1 AND active=true',[Number(id)])).rows[0];if(!s)throw Object.assign(new Error('Поставщик не найден'),{code:'SUPPLIER_NOT_FOUND',statusCode:404});return s}
 function fileInput(body){const filename=clean(body?.filename,260),contentBase64=String(body?.content_base64||'');if(!filename||!contentBase64)throw Object.assign(new Error('Выберите файл прайса'),{code:'FILE_REQUIRED',statusCode:422});return{filename,contentBase64}}
 function mapWarehouse(rows){const bySku=new Map(),byOem=new Map();for(const w of rows){if(w.sku){const k=norm(w.sku);if(!bySku.has(k))bySku.set(k,[]);bySku.get(k).push(w)}if(w.oem_code){const k=norm(w.oem_code);if(!byOem.has(k))byOem.set(k,[]);byOem.get(k).push(w)}}return{bySku,byOem}}
 function catalogChanged(old,row){if(!old)return true;return clean(old.supplier_sku,160)!==(row.supplier_sku||'')||clean(old.name)!==row.name||clean(old.oem_code,160)!==(row.oem_code||'')||clean(old.brand,160)!==(row.brand||'')||!sameNum(old.purchase_price,row.purchase_price)||!sameNum(old.recommended_sale_price,row.recommended_sale_price)||!sameNum(old.available_qty,row.available_qty)||Number(old.lead_time_days??-1)!==Number(row.lead_time_days??-1)||clean(old.currency,8)!==row.currency||old.active===false}
 async function buildPreview(c,user,body){
  const s=await supplier(c,body?.supplier_id),branch=await assertBranch(c,user,body?.branch_id),file=fileInput(body),parsed=parseSupplierFile(file),mapping=body?.mapping&&typeof body.mapping==='object'?body.mapping:{},rows=normalizeSupplierRows(parsed,mapping),valid=rows.filter(x=>!x.errors.length),keys=[...new Set(valid.map(x=>x.catalog_key))];
  const existing=keys.length?(await c.query('SELECT * FROM supplier_catalog_items WHERE supplier_id=$1 AND catalog_key=ANY($2::text[])',[s.id,keys])).rows:[],existingByKey=new Map(existing.map(x=>[x.catalog_key,x]));
  const ids=existing.map(x=>Number(x.id)),links=ids.length?(await c.query('SELECT * FROM supplier_catalog_links WHERE branch_id=$1 AND catalog_item_id=ANY($2::bigint[])',[branch.id,ids])).rows:[],linkByCatalog=new Map(links.map(x=>[Number(x.catalog_item_id),x]));
  const skus=[...new Set(valid.map(x=>norm(x.supplier_sku)).filter(Boolean))],oems=[...new Set(valid.map(x=>norm(x.oem_code)).filter(Boolean))],warehouse=(skus.length||oems.length)?(await c.query(`SELECT id,branch_id,sku,name,oem_code,purchase_price,sale_price,quantity FROM warehouse_items WHERE branch_id=$1 AND active=true AND ((cardinality($2::text[])>0 AND lower(COALESCE(sku,''))=ANY($2::text[])) OR (cardinality($3::text[])>0 AND lower(COALESCE(oem_code,''))=ANY($3::text[])))`,[branch.id,skus,oems])).rows:[],wm=mapWarehouse(warehouse);
  const createMissing=body?.create_missing===true;let counts={total:rows.length,valid:0,invalid:0,catalog_create:0,catalog_update:0,catalog_unchanged:0,warehouse_linked:0,warehouse_match:0,warehouse_create:0,warehouse_unlinked:0,warehouse_conflict:0};
  const items=rows.map(row=>{if(row.errors.length){counts.invalid++;return{...row,catalog_action:'INVALID',warehouse_action:'SKIP'}}counts.valid++;const old=existingByKey.get(row.catalog_key);let catalogAction=!old?'CREATE':catalogChanged(old,row)?'UPDATE':'UNCHANGED';counts['catalog_'+catalogAction.toLowerCase()]++;
   const linked=old?linkByCatalog.get(Number(old.id)):null;let candidates=[];if(row.supplier_sku)candidates.push(...(wm.bySku.get(norm(row.supplier_sku))||[]));if(row.oem_code)candidates.push(...(wm.byOem.get(norm(row.oem_code))||[]));const unique=[...new Map(candidates.map(x=>[Number(x.id),x])).values()];let warehouseAction,warehouseMatch=null;if(linked){warehouseAction='LINKED';warehouseMatch=warehouse.find(x=>Number(x.id)===Number(linked.warehouse_item_id))||{id:linked.warehouse_item_id};counts.warehouse_linked++}else if(unique.length===1){warehouseAction='MATCH';warehouseMatch=unique[0];counts.warehouse_match++}else if(unique.length>1){warehouseAction='CONFLICT';counts.warehouse_conflict++}else if(createMissing){warehouseAction='CREATE';counts.warehouse_create++}else{warehouseAction='UNLINKED';counts.warehouse_unlinked++}return{...row,catalog_id:old?.id||null,catalog_action:catalogAction,warehouse_action:warehouseAction,warehouse_match_id:warehouseMatch?.id||null,warehouse_match_name:warehouseMatch?.name||null}});
  return{supplier:s,branch,filename:file.filename,format:parsed.format,file_sha256:createHash('sha256').update(Buffer.from(file.contentBase64,'base64')).digest('hex'),headers:parsed.headers,detected_mapping:detectMapping(parsed.headers),mapping:{...detectMapping(parsed.headers),...mapping},counts,items};
 }
 app.get('/health',async()=>{await pool.query('SELECT 1');return{ok:true,service:'profi24-supplier-catalog',version:'1.0.0'}});
 app.post('/api/v1/import/parse',{preHandler:manage},async(req,reply)=>{try{const file=fileInput(req.body),parsed=parseSupplierFile(file);return{data:{filename:file.filename,format:parsed.format,headers:parsed.headers,detected_mapping:detectMapping(parsed.headers),sample:parsed.rows.slice(0,8)}}}catch(e){return fail(reply,e.code||'PARSE_ERROR',e.message,e.statusCode||422)}});
 app.post('/api/v1/import/preview',{preHandler:manage},async(req,reply)=>{try{const p=await buildPreview(pool,req.user,req.body||{});return{data:{...p,items:p.items.slice(0,500),preview_limited:p.items.length>500}}}catch(e){if(e.statusCode||e.code)return fail(reply,e.code||'PREVIEW_ERROR',e.message,e.statusCode||422);throw e}});
 app.post('/api/v1/import/apply',{preHandler:manage},async(req,reply)=>{try{const result=await tx(async c=>{const p=await buildPreview(c,req.user,req.body||{}),valid=p.items.filter(x=>!x.errors.length),createMissing=req.body?.create_missing===true,deactivateMissing=req.body?.deactivate_missing===true;
   const imp=(await c.query(`INSERT INTO supplier_catalog_imports(supplier_id,branch_id,filename,file_format,file_sha256,mapping,create_missing,deactivate_missing,rows_total,rows_valid,rows_created,rows_updated,rows_unchanged,rows_invalid,warehouse_linked,warehouse_created,imported_by) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[p.supplier.id,p.branch.id,p.filename,p.format,p.file_sha256,JSON.stringify(p.mapping),createMissing,deactivateMissing,p.counts.total,p.counts.valid,p.counts.catalog_create,p.counts.catalog_update,p.counts.catalog_unchanged,p.counts.invalid,p.counts.warehouse_linked+p.counts.warehouse_match,p.counts.warehouse_create,req.user.id])).rows[0];
   let linked=0,createdWarehouse=0;const importedKeys=[];for(const row of valid){importedKeys.push(row.catalog_key);const cat=(await c.query(`INSERT INTO supplier_catalog_items(supplier_id,catalog_key,supplier_sku,name,oem_code,brand,purchase_price,recommended_sale_price,currency,available_qty,lead_time_days,source_import_id,active,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true,clock_timestamp()) ON CONFLICT(supplier_id,catalog_key) DO UPDATE SET supplier_sku=EXCLUDED.supplier_sku,name=EXCLUDED.name,oem_code=EXCLUDED.oem_code,brand=EXCLUDED.brand,purchase_price=EXCLUDED.purchase_price,recommended_sale_price=EXCLUDED.recommended_sale_price,currency=EXCLUDED.currency,available_qty=EXCLUDED.available_qty,lead_time_days=EXCLUDED.lead_time_days,source_import_id=EXCLUDED.source_import_id,active=true,updated_at=clock_timestamp() RETURNING id`,[p.supplier.id,row.catalog_key,row.supplier_sku,row.name,row.oem_code,row.brand,row.purchase_price,row.recommended_sale_price,row.currency,row.available_qty,row.lead_time_days,imp.id])).rows[0];
    let wid=row.warehouse_match_id?Number(row.warehouse_match_id):null;if(!wid&&row.warehouse_action==='CREATE'&&createMissing){try{wid=(await c.query(`INSERT INTO warehouse_items(branch_id,sku,name,oem_code,supplier,purchase_price,sale_price,quantity,min_quantity,active) VALUES($1,$2,$3,$4,$5,$6,$7,0,0,true) RETURNING id`,[p.branch.id,row.supplier_sku,row.name,row.oem_code,p.supplier.name,row.purchase_price,row.recommended_sale_price||0])).rows[0].id;createdWarehouse++}catch(e){if(e.code!=='23505')throw e;const found=(await c.query('SELECT id FROM warehouse_items WHERE branch_id=$1 AND lower(COALESCE(sku,\'\'))=lower($2) LIMIT 1',[p.branch.id,row.supplier_sku||''])).rows[0];if(found)wid=found.id;else throw e}}
    if(wid){await c.query(`INSERT INTO supplier_catalog_links(catalog_item_id,branch_id,warehouse_item_id,linked_by) VALUES($1,$2,$3,$4) ON CONFLICT(catalog_item_id,branch_id) DO UPDATE SET warehouse_item_id=EXCLUDED.warehouse_item_id,linked_by=EXCLUDED.linked_by,linked_at=clock_timestamp()`,[cat.id,p.branch.id,wid,req.user.id]);linked++}}
   if(deactivateMissing){if(importedKeys.length)await c.query('UPDATE supplier_catalog_items SET active=false,updated_at=clock_timestamp() WHERE supplier_id=$1 AND NOT(catalog_key=ANY($2::text[]))',[p.supplier.id,importedKeys]);else await c.query('UPDATE supplier_catalog_items SET active=false,updated_at=clock_timestamp() WHERE supplier_id=$1',[p.supplier.id])}
   return{import_id:imp.id,counts:{...p.counts,warehouse_links_applied:linked,warehouse_created_applied:createdWarehouse},supplier:p.supplier,branch:p.branch}});return reply.code(201).send({data:result})}catch(e){if(e.statusCode||e.code)return fail(reply,e.code||'IMPORT_ERROR',e.message,e.statusCode||422);throw e}});
 app.get('/api/v1/catalog',{preHandler:view},async(req,reply)=>{try{const supplierId=Number(req.query?.supplier_id||0),branch=await assertBranch(pool,req.user,req.query?.branch_id),search=clean(req.query?.search,160),params=[branch.id];let where='WHERE ci.active=true';if(supplierId){await supplier(pool,supplierId);params.push(supplierId);where+=` AND ci.supplier_id=$${params.length}`}if(search){params.push(`%${search}%`);where+=` AND (ci.name ILIKE $${params.length} OR COALESCE(ci.supplier_sku,'') ILIKE $${params.length} OR COALESCE(ci.oem_code,'') ILIKE $${params.length} OR COALESCE(ci.brand,'') ILIKE $${params.length})`}const rows=(await pool.query(`SELECT ci.*,s.name supplier_name,l.warehouse_item_id,w.name warehouse_name,w.quantity warehouse_quantity,w.purchase_price warehouse_cost FROM supplier_catalog_items ci JOIN suppliers s ON s.id=ci.supplier_id LEFT JOIN supplier_catalog_links l ON l.catalog_item_id=ci.id AND l.branch_id=$1 LEFT JOIN warehouse_items w ON w.id=l.warehouse_item_id ${where} ORDER BY s.name,ci.name LIMIT 1000`,params)).rows;return{data:rows}}catch(e){if(e.statusCode)return fail(reply,e.code||'CATALOG_ERROR',e.message,e.statusCode);throw e}});
 app.get('/api/v1/imports',{preHandler:view},async(req,reply)=>{try{const ids=await branchIds(pool,req.user),params=[];let where='';if(ids){params.push(ids);where='WHERE i.branch_id=ANY($1::int[])'}const rows=(await pool.query(`SELECT i.*,s.name supplier_name,b.name branch_name,u.name imported_by_name FROM supplier_catalog_imports i JOIN suppliers s ON s.id=i.supplier_id JOIN branches b ON b.id=i.branch_id JOIN users u ON u.id=i.imported_by ${where} ORDER BY i.created_at DESC LIMIT 100`,params)).rows;return{data:rows}}catch(e){return fail(reply,e.code||'IMPORT_LIST_ERROR',e.message,e.statusCode||422)}});
 return app;
}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){
 const app=Fastify({logger:true,bodyLimit:12*1024*1024});await app.register(cors,{origin:(process.env.CORS_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()),credentials:true});await app.register(helmet,{contentSecurityPolicy:false});await app.register(rateLimit,{max:120,timeWindow:'1 minute'});await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_MAX||8)});await prepareSupplierCatalog(pool);installSupplierCatalog(app,pool);await app.listen({port:Number(process.env.PORT||8111),host:'0.0.0.0'});
}
