import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Building2,Plus,RefreshCw,X,UsersRound,ClipboardList,MapPin,Save,UserRound,CheckCircle2}from'lucide-react';
import'./branch-admin.css';

const B='/branch-api/v1',A='/api/v1',token=()=>localStorage.token;
async function call(base,path,opt={}){const r=await fetch(base+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
const api=(p,o)=>call(A,p,o),branch=(p,o)=>call(B,p,o);
function currentUser(){try{return JSON.parse(localStorage.user||'null')}catch{return null}}

function App(){
 const user=currentUser(),rbac=window.Profi24RBAC,P=rbac?.P||{},view=Boolean(P.BRANCHES_VIEW&&rbac?.can(P.BRANCHES_VIEW,user?.role)),manage=Boolean(P.BRANCHES_MANAGE&&rbac?.can(P.BRANCHES_MANAGE,user?.role));
 const[open,setOpen]=useState(false),[rows,setRows]=useState([]),[users,setUsers]=useState([]),[selectedUser,setSelectedUser]=useState(''),[membership,setMembership]=useState(null),[createOpen,setCreateOpen]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 async function load(){if(!view)return;try{setBusy(true);setErr('');const b=await branch('/branches');setRows(b||[]);if(manage){const u=await api('/users');setUsers((u||[]).filter(x=>x.active!==false))}}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function loadUser(id){setSelectedUser(String(id||''));setMembership(null);if(!id)return;try{setMembership(await branch('/users/'+id+'/branches'))}catch(e){setErr(e.message)}}
 useEffect(()=>{if(open)load()},[open,view,manage]);
 useEffect(()=>{if(!view)return;const reg=()=>window.Profi24UI?.registerNav({id:'branches',label:'Филиалы',group:'team',permission:P.BRANCHES_VIEW,onClick:()=>setOpen(true)});reg();window.addEventListener('profi24:core-ui-ready',reg);return()=>{window.removeEventListener('profi24:core-ui-ready',reg);window.Profi24UI?.removeNav?.('branches')}},[view,user?.id,user?.role]);
 if(!view||!open)return null;
 return <div className="branchScreen"><header><div><h1><Building2/> Филиалы</h1><p>Подразделения, сотрудники и операционная ответственность</p></div><div className="branchActions"><button onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/></button>{manage&&<button className="primary" onClick={()=>setCreateOpen(true)}><Plus/>Новый филиал</button>}<button onClick={()=>setOpen(false)}><X/></button></div></header>{err&&<div className="branchErr">{err}</div>}<section className="branchGrid">{rows.map(x=><article className={!x.active?'inactive':''} key={x.id}><div className="branchCode">{x.code}</div><h2>{x.name}</h2><p><MapPin/>{x.address||'Адрес не указан'}</p><div className="branchStats"><span><UsersRound/><b>{x.active_users??'—'}</b><small>сотрудников</small></span><span><ClipboardList/><b>{x.active_orders??'—'}</b><small>активных заказов</small></span></div><footer><span>{x.timezone}</span><b>{x.active?'Работает':'Отключён'}</b></footer></article>)}</section>{manage&&<section className="branchPeople"><div><h2>Сотрудники по филиалам</h2><p>У сотрудника может быть несколько доступных филиалов, но один основной.</p></div><select value={selectedUser} onChange={e=>loadUser(e.target.value)}><option value="">Выберите сотрудника</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select>{membership&&<Membership data={membership} branches={rows.filter(x=>x.active)} saved={async()=>{await loadUser(selectedUser);await load()}} error={setErr}/>}</section>}{createOpen&&<Create close={()=>setCreateOpen(false)} done={async()=>{setCreateOpen(false);await load()}} error={setErr}/>}</div>
}

function Membership({data,branches,saved,error}){const initial=(data.branches||[]).map(x=>Number(x.id)),[ids,setIds]=useState(initial),[primary,setPrimary]=useState(Number(data.user.primary_branch_id)||initial[0]||''),[busy,setBusy]=useState(false);function toggle(id){id=Number(id);setIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);if(primary===id&&ids.includes(id))setPrimary('')}async function save(){try{setBusy(true);if(!ids.length||!primary||!ids.includes(Number(primary)))throw new Error('Выберите хотя бы один филиал и укажите основной');await branch('/users/'+data.user.id+'/branches',{method:'PUT',body:JSON.stringify({branch_ids:ids,primary_branch_id:Number(primary)})});await saved()}catch(e){error(e.message)}finally{setBusy(false)}}return <div className="membership"><div className="memberHead"><UserRound/><div><b>{data.user.name}</b><span>{data.user.role}</span></div></div><div className="memberBranches">{branches.map(b=><label key={b.id}><input type="checkbox" checked={ids.includes(Number(b.id))} onChange={()=>toggle(b.id)}/><span><b>{b.name}</b><small>{b.code}</small></span></label>)}</div><label className="primaryBranch">Основной филиал<select value={primary} onChange={e=>setPrimary(Number(e.target.value))}><option value="">Выберите</option>{branches.filter(b=>ids.includes(Number(b.id))).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary save" onClick={save} disabled={busy}><Save/>{busy?'Сохранение...':'Сохранить назначение'}</button></div>}

function Create({close,done,error}){const[f,setF]=useState({code:'',name:'',address:'',timezone:'Asia/Qostanay'}),[busy,setBusy]=useState(false);async function save(){try{setBusy(true);await branch('/branches',{method:'POST',body:JSON.stringify(f)});done()}catch(e){error(e.message)}finally{setBusy(false)}}return <div className="branchOverlay"><div className="branchModal"><header><div><small>НОВЫЙ ФИЛИАЛ</small><h2>Создать подразделение</h2></div><button onClick={close}><X/></button></header><label>Код<input value={f.code} onChange={e=>setF({...f,code:e.target.value.toUpperCase()})} placeholder="KST2"/></label><label>Название<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Костанай — Север"/></label><label>Адрес<input value={f.address} onChange={e=>setF({...f,address:e.target.value})}/></label><label>Часовой пояс<input value={f.timezone} onChange={e=>setF({...f,timezone:e.target.value})}/></label><div className="modalActions"><button onClick={close}>Отмена</button><button className="primary" onClick={save} disabled={busy}><CheckCircle2/>{busy?'Создание...':'Создать'}</button></div></div></div>}

const root=document.createElement('div');root.id='branch-admin-addon-root';document.body.appendChild(root);createRoot(root).render(<App/>);
