import React,{useEffect,useState} from 'react';
import {financeApi,financeMoney as money,accountTypes} from './finance-client.js';
import {FinanceDialog,useFinanceForm,FormActions} from './finance-forms.jsx';

const buckets={flow:'Доходы и расходы',transfer:'Внутренние переводы',opening:'Начальные остатки',adjustment:'Корректировки'};
export function CashFlowPanel({periodQuery,periodControls,accounts}){
  const [account,setAccount]=useState(''),[method,setMethod]=useState(''),[report,setReport]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false);
  useEffect(()=>{
    const controller=new AbortController();setReport(null);setError('');setBusy(true);
    financeApi('/cash-flow?'+periodQuery+'&'+new URLSearchParams({...(account?{account_id:account}:{}),...(method?{payment_method:method}:{})}),{signal:controller.signal})
      .then(data=>{if(!controller.signal.aborted)setReport(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});
    return()=>controller.abort();
  },[periodQuery,account,method,retry]);
  return <div aria-busy={busy}><div className="finSectionHead"><h2>Движение денежных средств по статьям</h2><button disabled={busy} onClick={()=>setRetry(x=>x+1)}>Обновить ДДС</button></div><div className="finFilters">{periodControls}<label>Счёт<select value={account} onChange={e=>setAccount(e.target.value)}><option value="">Все доступные счета</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Способ оплаты<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Все способы</option>{Object.entries(accountTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
    {error&&<p role="alert" className="finError">{error} <button onClick={()=>setRetry(x=>x+1)}>Повторить</button></p>}{busy&&<p>Загрузка отчёта ДДС…</p>}
    {report&&<><div className="finPeriod">{[['opening','На начало периода'],['income','Поступления'],['expense','Расходы'],['net','Чистый денежный поток'],['closing','На конец периода']].map(([k,label])=><div key={k}><small>{label}</small><b>{money(report.summary[k])}</b></div>)}</div><p className="finHint">Поступления и расходы включают возвраты и сторно. Внутренние переводы, начальные остатки и корректировки показаны отдельно; остатки учитывают все движения. ДДС отражает деньги по дате проведения, а прибыль рассчитывается в P&amp;L.</p>
      <div className="finTableWrap"><table><thead><tr><th>Раздел</th><th>Статья ДДС</th><th>Способ оплаты</th><th>Операций</th><th>Поступления</th><th>Списания</th><th>Поток</th></tr></thead><tbody>{report.rows.map(row=><tr key={[row.bucket,row.category,row.payment_method].join(':')}><td>{buckets[row.bucket]}</td><td>{row.category_name}</td><td>{accountTypes[row.payment_method]||row.payment_method}</td><td>{row.operations}</td><td>{money(row.income)}</td><td>{money(row.expense)}</td><td>{money(row.net)}</td></tr>)}</tbody></table>{!report.rows.length&&<p className="finEmpty">За этот период операций нет</p>}</div></>}
  </div>;
}
function CategoryForm({category,close,done}){
  const f=useFinanceForm({name:category?.name||'',type:category?.type||'EXPENSE',payment_methods:category?.payment_methods||Object.keys(accountTypes),is_active:category?.is_active??true}),b=f.form;
  return <FinanceDialog title={category?'Редактировать статью ДДС':'Новая статья ДДС'} close={()=>!f.busy&&close()}><form className="finForm" onSubmit={f.submit(async body=>{const payload=category?{name:body.name,payment_methods:body.payment_methods,is_active:body.is_active,version:category.version}:{name:body.name,type:body.type,payment_methods:body.payment_methods};await financeApi('/categories'+(category?'/'+encodeURIComponent(category.code):''),{method:category?'PATCH':'POST',body:payload});done();})}><fieldset disabled={f.busy}><label>Название статьи<input required maxLength={100} value={b.name} onChange={e=>f.change('name',e.target.value)}/></label><label>Тип статьи<select disabled={!!category} value={b.type} onChange={e=>f.change('type',e.target.value)}><option value="EXPENSE">Расход</option><option value="INCOME">Доход</option></select></label><p>Доступные способы оплаты</p>{Object.entries(accountTypes).map(([k,v])=><label key={k} className="finCheck"><input type="checkbox" checked={b.payment_methods.includes(k)} onChange={e=>f.change('payment_methods',e.target.checked?[...b.payment_methods,k]:b.payment_methods.filter(x=>x!==k))}/>{v}</label>)}{category&&<label className="finCheck"><input type="checkbox" checked={b.is_active} onChange={e=>f.change('is_active',e.target.checked)}/>Статья активна</label>}<p className="finHint">Отключённая статья остаётся в исторических отчётах. Сохранение справочника не меняет денежные записи.</p></fieldset><FormActions busy={f.busy} error={f.error} close={close} label="Сохранить статью" disabled={!b.payment_methods.length}/></form></FinanceDialog>;
}
export function CategoryPanel({admin}){
  const [rows,setRows]=useState([]),[error,setError]=useState(''),[retry,setRetry]=useState(0),[modal,setModal]=useState(null),[busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();setRows([]);setError('');setBusy(true);financeApi('/categories',{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setRows(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[retry]);
  return <div aria-busy={busy}><div className="finSectionHead"><h2>Статьи ДДС</h2><div className="finActions"><button disabled={busy} onClick={()=>setRetry(x=>x+1)}>Обновить статьи</button>{admin&&<button className="finPrimary" onClick={()=>setModal({})}>Добавить статью</button>}</div></div>{error&&<p role="alert" className="finError">{error}</p>}{busy&&<p>Загрузка статей…</p>}<div className="finTableWrap"><table><thead><tr><th>Статья</th><th>Тип</th><th>Способы оплаты</th><th>Статус</th>{admin&&<th>Действия</th>}</tr></thead><tbody>{rows.map(c=><tr key={c.code}><td>{c.name}</td><td>{c.type==='INCOME'?'Доход':'Расход'}</td><td>{c.payment_methods.map(x=>accountTypes[x]).join(', ')}</td><td>{c.is_system?'Системная':c.is_active?'Активна':'Отключена'}</td>{admin&&<td>{!c.is_system&&<button onClick={()=>setModal({category:c})}>Редактировать статью</button>}</td>}</tr>)}</tbody></table></div>{modal&&admin&&<CategoryForm category={modal.category} close={()=>setModal(null)} done={()=>{setModal(null);setRetry(x=>x+1);}}/>}</div>;
}
