import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{CalendarCheck2,MessageCircle,RefreshCw,X,Send,Smartphone,RotateCcw,Ban,Save}from'lucide-react';
import'./communications.css';
const A='/communications-api/v1',token=()=>localStorage.token;
async function api(p,o={}){const r=await fetch(A+p,{...o,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(o.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
const dt=v=>v?new Date(v).toLocaleString('ru-RU',{timeZone:'Asia/Qostanay',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const visitLabel=s=>s==='CONFIRMED'?'Подтверждено':s==='RESCHEDULE_REQUESTED'?'Нужен перенос':'Ожидает ответа';
function App(){const[open,setOpen]=useState(false),[tab,setTab]=useState('queue'),[status,setStatus]=useState(null),[templates,setTemplates]=useState([]),[queue,setQueue]=useState([]),[visits,setVisits]=useState([]),[orders,setOrders]=useState([]),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({request_id:'',template_code:'',audience:'CUSTOMER',channel:'WHATSAPP',body:''});const user=(()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}})();const rbac=window.Profi24RBAC,permission=rbac?.P?.COMMUNICATIONS_MANAGE,allowed=Boolean(permission&&rbac.can(permission,user?.role));
async function load(){try{setErr('');const[s,t,q,v,r]=await Promise.all([api('/communications/status'),api('/communications/templates'),api('/communications/queue'),api('/visit-confirmations'),fetch('/api/v1/requests',{headers:{Authorization:`Bearer ${token()}`}}).then(x=>x.json()).then(x=>x.data||[])]);setStatus(s);setTemplates(t||[]);setQueue(q||[]);setVisits(v||[]);setOrders(r||[])}catch(e){setErr(e.message)}}
useEffect(()=>{if(open&&allowed)load()},[open,allowed]);useEffect(()=>{if(!allowed)return;window.Profi24UI?.registerNav({id:'communications',label:'Коммуникации',group:'clients',permission,badge:visits.filter(x=>x.status==='RESCHEDULE_REQUESTED'&&x.followup_status==='OPEN').length||null,onClick:()=>setOpen(true)});return()=>window.Profi24UI?.removeNav?.('communications')},[user?.id,user?.role,allowed,permission]);useEffect(()=>{window.Profi24UI?.updateNav?.('communications',{badge:visits.filter(x=>x.status==='RESCHEDULE_REQUESTED'&&x.followup_status==='OPEN').length||null})},[visits]);
const selectedTemplate=useMemo(()=>templates.find(x=>x.code===form.template_code),[templates,form.template_code]);useEffect(()=>{if(selectedTemplate)setForm(f=>({...f,audience:selectedTemplate.audience,channel:selectedTemplate.channel,body:selectedTemplate.body}))},[selectedTemplate?.id]);
async function sync(){try{setBusy(true);await api('/communications/sync',{method:'POST'});await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
async function send(){try{setBusy(true);await api('/communications/manual',{method:'POST',body:JSON.stringify({...form,request_id:Number(form.request_id)})});setForm({request_id:'',template_code:'',audience:'CUSTOMER',channel:'WHATSAPP',body:''});await load();setTab('queue')}catch(e){setErr(e.message)}finally{setBusy(false)}}
if(!allowed||!open)return null;const needMove=visits.filter(x=>x.status==='RESCHEDULE_REQUESTED'&&x.followup_status==='OPEN').length;return <div className="commScreen"><div className="commTop"><div><h1>Коммуникационный центр</h1><p>WhatsApp / Telegram, подтверждения визитов и ответы клиентов</p></div><div className="commActions"><button onClick={sync} disabled={busy}><RefreshCw size={17}/>{busy?'Обработка...':'Синхронизировать'}</button><button onClick={()=>setOpen(false)}><X/></button></div></div>{err&&<div className="commError">{err}</div>}<div className="commMetrics"><M t="WhatsApp" v={status?.whatsapp_configured?'Подключён':'Не подключён'} ok={status?.whatsapp_configured}/><M t="В очереди" v={status?.queued??0}/><M t="Нужен перенос" v={needMove} warn={needMove>0}/><M t="Ошибки" v={status?.errors??0} warn={status?.errors>0}/></div><div className="commTabs"><button className={tab==='queue'?'on':''} onClick={()=>setTab('queue')}>Очередь</button><button className={tab==='visits'?'on':''} onClick={()=>setTab('visits')}>Визиты{needMove?` · ${needMove}`:''}</button><button className={tab==='manual'?'on':''} onClick={()=>setTab('manual')}>Новое сообщение</button><button className={tab==='templates'?'on':''} onClick={()=>setTab('templates')}>Шаблоны</button></div>{tab==='queue'&&<Queue rows={queue} reload={load}/>} {tab==='visits'&&<Visits rows={visits} reload={load}/>} {tab==='manual'&&<Manual form={form} setForm={setForm} orders={orders} templates={templates} send={send} busy={busy}/>} {tab==='templates'&&<Templates rows={templates} reload={load}/>}</div>}
function Queue({rows,reload}){async function act(id,type){await api(`/communications/queue/${id}/${type}`,{method:'POST'});reload()}return <section className="commPanel"><div className="commTable"><div className="commHead"><span>Статус</span><span>Канал</span><span>Заявка</span><span>Получатель</span><span>Сообщение</span><span>Время</span><span></span></div>{rows.map(x=><div className="commRow" key={x.id}><span><b className={'commStatus s'+x.status}>{x.status}</b></span><span>{x.channel==='WHATSAPP'?<><Smartphone size={14}/> WhatsApp</>:<><MessageCircle size={14}/> Telegram</>}</span><span>{x.request_number||'—'}<small>{x.customer_name||''}</small></span><span>{x.recipient||'не указан'}</span><span className="commMsg">{x.body}</span><span>{dt(x.created_at)}<small>{x.sent_at?'Отправлено '+dt(x.sent_at):''}</small></span><span className="commRowActions">{['ERROR','QUEUED','WAITING_RECIPIENT'].includes(x.status)&&<button onClick={()=>act(x.id,'retry')}><RotateCcw size={15}/></button>}{!['SENT','DELIVERED','READ','CANCELLED'].includes(x.status)&&<button onClick={()=>act(x.id,'cancel')}><Ban size={15}/></button>}</span></div>)}</div>{!rows.length&&<div className="commEmpty">Очередь сообщений пока пуста.</div>}</section>}
function Visits({rows,reload}){const[busy,setBusy]=useState(null);async function resend(row){try{setBusy(row.request_id);await api(`/visit-confirmations/${row.request_id}/resend`,{method:'POST'});await reload()}finally{setBusy(null)}}return <section className="commPanel"><div className="commVisitList">{rows.map(x=><article className={'commVisit '+String(x.status).toLowerCase()} key={x.id} data-visit-request={x.request_number}><div className="commVisitIcon"><CalendarCheck2/></div><div className="commVisitMain"><div><b>{x.request_number}</b><span>{x.customer_name}</span></div><small>{x.engineer_name||'Инженер не назначен'} · {dt(x.scheduled_at_snapshot)} · версия {x.version}</small>{x.response_comment&&<p>Комментарий клиента: {x.response_comment}</p>}{x.followup_task_id&&<p className="commVisitTask">Задача #{x.followup_task_id}: {x.followup_status||'—'} · срок {dt(x.followup_due_at)}</p>}</div><b className={'commVisitStatus '+String(x.status).toLowerCase()}>{visitLabel(x.status)}</b><button className="commVisitResend" disabled={busy===x.request_id||x.status!=='PENDING'} onClick={()=>resend(x)}><RotateCcw size={15}/>{busy===x.request_id?'Отправка...':'Отправить снова'}</button></article>)}</div>{!rows.length&&<div className="commEmpty">Подтверждений визитов пока нет.</div>}</section>}
function Manual({form,setForm,orders,templates,send,busy}){return <section className="commPanel commManual"><h2><Send size={19}/> Отправить сообщение</h2><label>Заявка<select value={form.request_id} onChange={e=>setForm({...form,request_id:e.target.value})}><option value="">Выберите заявку</option>{orders.slice(0,300).map(x=><option key={x.id} value={x.id}>{x.number} — {x.customer_name}</option>)}</select></label><label>Шаблон<select value={form.template_code} onChange={e=>setForm({...form,template_code:e.target.value})}><option value="">Без шаблона</option>{templates.filter(x=>x.active).map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><div className="commTwo"><label>Получатель<select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="CUSTOMER">Клиент</option><option value="ENGINEER">Инженер</option></select></label><label>Канал<select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option value="WHATSAPP">WhatsApp</option><option value="TELEGRAM">Telegram</option></select></label></div><label>Текст<textarea rows="7" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><div className="commHint">Переменные шаблона подставятся на сервере при выборе шаблона. Для ручного текста сообщение уйдёт как введено.</div><button className="commPrimary" disabled={busy||!form.request_id||!form.body.trim()} onClick={send}><Send size={16}/>Поставить в очередь</button></section>}
function Templates({rows,reload}){return <section className="commTemplates">{rows.map(t=><Template key={t.id} t={t} reload={reload}/>)}</section>}
function Template({t,reload}){const[b,setB]=useState(t);async function save(){await api('/communications/templates/'+t.id,{method:'PATCH',body:JSON.stringify({name:b.name,channel:b.channel,body:b.body,active:b.active})});reload()}return <article className="commTemplate"><div className="commTemplateTop"><div><b>{b.name}</b><small>{b.code} · {b.audience}</small></div><label className="switch"><input type="checkbox" checked={b.active} onChange={e=>setB({...b,active:e.target.checked})}/><span>{b.active?'Активен':'Выключен'}</span></label></div><select value={b.channel} onChange={e=>setB({...b,channel:e.target.value})}><option value="WHATSAPP">WhatsApp</option><option value="TELEGRAM">Telegram</option></select><textarea rows="6" value={b.body} onChange={e=>setB({...b,body:e.target.value})}/><button onClick={save}><Save size={15}/>Сохранить</button></article>}
function M({t,v,ok,warn}){return <div className={'commMetric '+(ok?'ok ':'')+(warn?'warn':'')}><small>{t}</small><b>{v}</b></div>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
