import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import'./customer-portal.css';

const token=decodeURIComponent(location.pathname.split('/').filter(Boolean).at(-1)||'');
const statusNames={NEW:'Заявка принята',ASSIGNED:'Назначен специалист',ACCEPTED:'Специалист принял заказ',ON_ROUTE:'Специалист в пути',DIAGNOSTICS:'Диагностика',APPROVAL_REQUIRED:'Ожидается согласование',WAITING_PART:'Ожидается запчасть',REPAIR:'Ремонт',TESTING:'Проверка после ремонта',PAYMENT_REQUIRED:'Ожидается оплата',CLOSED:'Заказ завершён',CANCELLED:'Заказ отменён'};
const money=v=>`${Number(v||0).toLocaleString('ru-RU')} ₸`;
const date=v=>v?new Date(v).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
const dt=v=>v?new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
async function load(){const r=await fetch('/approvals-api/public/customer-portal/'+encodeURIComponent(token)),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Не удалось открыть кабинет');return j.data}
function App(){const[data,setData]=useState(null),[err,setErr]=useState('');useEffect(()=>{load().then(setData).catch(e=>setErr(e.message))},[]);if(err)return <main className="cpPage"><section className="cpCard cpState"><div className="cpBrand">PROFI24</div><h1>Кабинет недоступен</h1><p>{err}</p><small>Запросите у сервисного центра новую персональную ссылку.</small></section></main>;if(!data)return <main className="cpPage"><section className="cpCard cpState"><div className="cpBrand">PROFI24</div><p>Загружаем историю ремонта…</p></section></main>;return <main className="cpPage"><header className="cpHeader"><div><div className="cpBrand">PROFI24</div><h1>{data.customer.name}, ваши ремонты</h1><p>Здесь отображаются только данные ваших заказов и клиентские этапы ремонта.</p></div><div className="cpExpiry">Ссылка действует до <b>{date(data.expires_at)}</b></div></header><section className="cpOrders">{data.orders.length?data.orders.map(o=><Order key={o.id} order={o}/>):<div className="cpCard cpState"><h2>Заказов пока нет</h2></div>}</section><footer>PROFI24 · Информация обновляется из CRM</footer></main>}
function Order({order:o}){const due=Math.max(0,Number(o.total||0)-Number(o.paid||0)),equipment=[o.category,o.brand,o.model].filter(Boolean).join(' ');return <article className="cpCard cpOrder"><div className="cpOrderTop"><div><small>Заказ</small><h2>{o.number}</h2><p>{equipment||'Техника'}{o.serial_number?` · S/N ${o.serial_number}`:''}</p></div><span className={'cpStatus '+String(o.status||'').toLowerCase()}>{statusNames[o.status]||o.status}</span></div><div className="cpFacts"><div><small>Обращение</small><b>{o.complaint}</b></div>{o.diagnosis&&<div><small>Диагностика</small><b>{o.diagnosis}</b></div>}<div><small>Стоимость</small><b>{money(o.total)}</b></div><div><small>Оплачено</small><b>{money(o.paid)}</b></div><div><small>{due?'К оплате':'Расчёт'}</small><b>{due?money(due):'Оплачено полностью'}</b></div>{o.scheduled_at&&<div><small>Запланировано</small><b>{dt(o.scheduled_at)}</b></div>}{o.closed_at&&<div><small>Завершено</small><b>{date(o.closed_at)}</b></div>}</div>{(o.actions?.approval_url||o.actions?.warranty_url)&&<div className="cpActions">{o.actions.approval_url&&<a href={o.actions.approval_url}>Согласовать стоимость</a>}{o.actions.warranty_url&&<a href={o.actions.warranty_url}>Открыть гарантию{o.actions.warranty_until?` до ${date(o.actions.warranty_until)}`:''}</a>}</div>}<div className="cpTimeline"><h3>История</h3>{o.timeline?.length?o.timeline.map((e,i)=><div className="cpEvent" key={i}><span></span><div><b>{e.label}</b><small>{dt(e.created_at)}</small></div></div>):<p className="cpMuted">Публичных событий пока нет.</p>}</div></article>}
createRoot(document.getElementById('root')).render(<App/>);
