// PROFI24 owner directory administration: soft-delete customers/equipment + restore.
(function(){
const token=()=>localStorage.getItem('token')||'';
function role(){try{return JSON.parse(localStorage.getItem('user')||'null')?.role||''}catch{return''}}
if(String(role()).toUpperCase()!=='OWNER')return;
const nativeFetch=window.fetch.bind(window);
let activeCustomers=[],activeEquipment=[];
function target(input){return typeof input==='string'?input:(input?.url||'')}
function cloneFilteredResponse(resp,filter){return resp.clone().json().then(j=>{if(Array.isArray(j?.data))j.data=j.data.filter(filter);const body=JSON.stringify(j);return new Response(body,{status:resp.status,statusText:resp.statusText,headers:{'Content-Type':'application/json'}})}).catch(()=>resp)}
function bodyObject(init){try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}}
async function directory(path,opt={}){const r=await nativeFetch('/directory-api/v1'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||`Ошибка ${r.status}`);return j.data}
window.fetch=async function(input,init){const url=target(input);const method=String(init?.method||'GET').toUpperCase();let resp=await nativeFetch(input,init);
 if(method==='POST'&&/\/api\/v1\/customers(?:\?|$)/.test(url)&&resp.status===409){const j=await resp.clone().json().catch(()=>null);if(j?.error?.code==='POSSIBLE_DUPLICATE_CUSTOMER'){const b=bodyObject(init),pn=b?.phone;if(pn){const deleted=await directory('/customers/deleted-by-phone?phone='+encodeURIComponent(pn)).catch(()=>null);if(deleted&&Number(deleted.id)===Number(j?.error?.candidate?.id)){await directory('/customers/'+deleted.id+'/restore',{method:'POST',body:'{}'});const restored={...deleted,...b,id:deleted.id,deleted_at:null,restored:true};return new Response(JSON.stringify({data:restored}),{status:201,headers:{'Content-Type':'application/json'}})}}}}
 if(method==='GET'&&resp.ok&&/\/api\/v1\/customers(?:\?|$)/.test(url)){return cloneFilteredResponse(resp,x=>!x.deleted_at).then(r=>{activeCustomers=[];r.clone().json().then(j=>{activeCustomers=j.data||[]}).catch(()=>{});return r})}if(method==='GET'&&resp.ok&&/\/api\/v1\/equipment(?:\?|$)/.test(url)){return cloneFilteredResponse(resp,x=>!x.deleted_at).then(r=>{activeEquipment=[];r.clone().json().then(j=>{activeEquipment=j.data||[]}).catch(()=>{});return r})}return resp};
async function api(path,opt={}){return directory(path,opt)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function txt(e){return(e?.textContent||'').replace(/\s+/g,' ').trim()}
function shade(html){const s=document.createElement('div');s.className='dirShade';s.innerHTML=html;document.body.appendChild(s);s.addEventListener('mousedown',e=>{if(e.target===s)s.remove()});return s}
function styles(){if(document.getElementById('dirAdminStyle'))return;const s=document.createElement('style');s.id='dirAdminStyle';s.textContent=`.dirDelete,.dirMerge{border-radius:8px;padding:7px 9px;cursor:pointer;font-weight:700;display:inline-flex;align-items:center;position:relative;z-index:5;pointer-events:auto}.dirDelete{margin-left:4px;border:1px solid #f0b4b4;background:#fff;color:#b42318}.dirMerge{margin-left:auto;border:1px solid #98a2b3;background:#fff;color:#344054}.dirShade{position:fixed;inset:0;background:#0f172a80;z-index:100001;display:flex;align-items:center;justify-content:center;padding:20px}.dirModal{width:min(850px,96vw);max-height:90vh;overflow:auto;background:#fff;color:#172033;border-radius:14px;padding:20px;box-shadow:0 20px 70px #0004}.dirModal h2{margin:0 0 4px}.dirModal>p{color:#667085;margin:0 0 16px}.dirTabs{display:flex;gap:8px;margin:12px 0}.dirTabs button{border:1px solid #d0d5dd;background:#fff;border-radius:8px;padding:8px 12px;cursor:pointer}.dirTabs button.on{background:#ffb800;border-color:#ffb800}.dirRow{display:grid;grid-template-columns:1.3fr 1.4fr 1fr auto;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid #eee}.dirRow small{color:#667085}.dirRow button{border:1px solid #d0d5dd;background:#fff;border-radius:8px;padding:7px 10px;cursor:pointer;font-weight:700}.dirForm{display:grid;gap:8px}.dirForm label{font-weight:700;margin-top:6px}.dirForm select,.dirForm textarea{font:inherit;border:1px solid #d0d5dd;border-radius:8px;padding:10px;background:#fff}.dirPreview{margin-top:10px;padding:12px;border-radius:10px;background:#f8fafc;border:1px solid #e4e7ec}.dirPreview.warn{background:#fffaeb;border-color:#fedf89}.dirPreview b{display:block;margin-bottom:5px}.dirCounts{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.dirCounts span{background:#fff;border:1px solid #e4e7ec;border-radius:999px;padding:5px 8px}.dirEmpty{padding:30px;text-align:center;color:#667085}.dirActions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.dirActions button{border:1px solid #d0d5dd;background:#fff;border-radius:8px;padding:9px 14px;font-weight:700;cursor:pointer}.dirActions button.primary{background:#ffb800;border-color:#ffb800;color:#172033}.dirActions button:disabled,.dirRow button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:700px){.dirRow{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function refreshCurrentPage(){const b=document.querySelector('main header .actions .icon, main header .topActions .iconBtn');if(b){b.click();return true}return false}
async function remove(kind,item){const title=kind==='customers'?'клиента':'технику';const reason=prompt(`Причина удаления ${title}:`,'Создано ошибочно');if(reason===null)return;if(reason.trim().length<3){alert('Укажите причину удаления');return}if(!confirm(`Подтвердите удаление: ${kind==='customers'?item.name:[item.category,item.brand,item.model].filter(Boolean).join(' ')}`))return;try{await api(`/${kind}/${item.id}`,{method:'DELETE',body:JSON.stringify({reason:reason.trim()})});if(kind==='customers')activeCustomers=activeCustomers.filter(x=>Number(x.id)!==Number(item.id));else activeEquipment=activeEquipment.filter(x=>Number(x.id)!==Number(item.id));if(!refreshCurrentPage())location.reload()}catch(e){alert(e.message)}}
async function openMerge(source){
 const targets=activeCustomers.filter(x=>Number(x.id)!==Number(source.id));
 if(!targets.length){alert('Для объединения нужна вторая активная карточка клиента');return}
 const s=shade(`<div class="dirModal"><h2>Объединить дубликаты клиентов</h2><p>История из карточки «${esc(source.name)}» будет перенесена в выбранную основную карточку. Операция фиксируется в неизменяемом журнале.</p><div class="dirForm"><label>Основная карточка — останется активной</label><select data-target><option value="">Выберите клиента</option>${targets.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.phone)}</option>`).join('')}</select><label>Причина объединения</label><textarea data-reason rows="3" placeholder="Например: повторно создан клиент с тем же телефоном"></textarea><div class="dirPreview" data-preview>Выберите основную карточку для предварительной проверки.</div></div><div class="dirActions"><button data-c>Отмена</button><button class="primary" data-merge disabled>Объединить</button></div></div>`);
 const select=s.querySelector('[data-target]'),preview=s.querySelector('[data-preview]'),merge=s.querySelector('[data-merge]');let actual=null;
 s.querySelector('[data-c]').onclick=()=>s.remove();
 select.onchange=async()=>{actual=null;merge.disabled=true;const targetId=Number(select.value);if(!targetId){preview.textContent='Выберите основную карточку для предварительной проверки.';return}preview.textContent='Проверяем связанные данные…';try{actual=await api(`/customers/${source.id}/merge-preview?target_id=${targetId}`);const c=actual.source.counts,labels={orders:'заказов',equipment:'ед. техники',complaints:'рекламаций',feedback:'NPS',visit_confirmations:'подтверждений визита',pickup_states:'выдач',service_contracts:'договоров'};preview.classList.toggle('warn',!actual.phones_match);preview.innerHTML=`<b>${actual.phones_match?'Телефоны совпадают':'Внимание: телефоны различаются'}</b><span>Перенос: ${esc(actual.source.customer.name)} → ${esc(actual.target.customer.name)}</span><div class="dirCounts">${Object.entries(labels).filter(([k])=>c[k]).map(([k,v])=>`<span>${c[k]} ${v}</span>`).join('')||'<span>Связанных записей нет</span>'}</div>`;merge.disabled=false}catch(e){preview.textContent=e.message}};
 merge.onclick=async()=>{const reason=s.querySelector('[data-reason]').value.trim();if(!actual)return;if(reason.length<5){alert('Укажите причину минимум из 5 символов');return}const target=actual.target.customer;if(!confirm(`Основной останется клиент «${target.name}» (${target.phone}). Продолжить?`))return;try{merge.disabled=true;merge.textContent='Объединение…';await api(`/customers/${source.id}/merge`,{method:'POST',body:JSON.stringify({target_id:target.id,confirm_target_id:target.id,reason})});activeCustomers=activeCustomers.filter(x=>Number(x.id)!==Number(source.id));s.remove();if(!refreshCurrentPage())location.reload()}catch(e){merge.disabled=false;merge.textContent='Объединить';alert(e.message)}};
}
function currentPage(){const h=document.querySelector('main header h1,main h1');return txt(h)}
function scoreRow(row,item,page){const s=txt(row).toLowerCase();if(page==='Клиенты'){const name=String(item.name||'').toLowerCase(),phone=String(item.phone||'').replace(/\D/g,'');return (name&&s.includes(name)?5:0)+(phone&&s.replace(/\D/g,'').includes(phone)?5:0)}const vals=[item.category,item.brand,item.model,item.serial_number,item.customer_name].filter(Boolean).map(x=>String(x).toLowerCase());return vals.reduce((a,v)=>a+(s.includes(v)?2:0),0)}
function candidateRows(){return [...document.querySelectorAll('main .simple,main .simpleRow,main .trow,main .simpleTable>div,main [class*="row"],main [class*="Row"]')].filter(r=>!r.matches('.simpleHead,.thead')&&r.getBoundingClientRect().height>25)}
function mountButtons(){const page=currentPage();if(page!=='Клиенты'&&page!=='Техника')return;const data=page==='Клиенты'?activeCustomers:activeEquipment,rows=candidateRows();for(const item of data){const best=rows.map(row=>({row,score:scoreRow(row,item,page)})).filter(x=>x.score>0&&!x.row.querySelector('.dirDelete')).sort((a,b)=>b.score-a.score)[0];if(!best)continue;if(page==='Клиенты'){const m=document.createElement('button');m.className='dirMerge';m.type='button';m.textContent='⇄ Объединить';m.title='Объединить карточку с дубликатом';m.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openMerge(item)},true);best.row.appendChild(m)}const b=document.createElement('button');b.className='dirDelete';b.type='button';b.textContent='🗑 Удалить';b.title=page==='Клиенты'?'Удалить клиента':'Удалить технику';b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();remove(page==='Клиенты'?'customers':'equipment',item)},true);best.row.appendChild(b)}}
async function openTrash(){try{const data=await api('/deleted');let tab='customers';const render=(s)=>{const list=s.querySelector('[data-list]');const rows=tab==='customers'?data.customers:data.equipment;list.innerHTML=rows.length?rows.map(x=>{const merged=tab==='customers'&&String(x.delete_reason||'').startsWith('MERGED_INTO:');return `<div class="dirRow"><div><b>${esc(tab==='customers'?x.name:[x.category,x.brand,x.model].filter(Boolean).join(' '))}</b><br><small>${esc(tab==='customers'?x.phone:x.serial_number||'Без серийного номера')}</small></div><div>${esc(tab==='customers'?x.address||'Адрес не указан':x.customer_name)}<br><small>${esc(merged?'Объединено с основной карточкой':String(x.delete_reason||'').replace(/^AUTO_CUSTOMER:\d+:/,''))}</small></div><div>${esc(new Date(x.deleted_at).toLocaleString('ru-RU'))}</div><button data-r="${x.id}" ${merged?'disabled title="История уже перенесена"':''}>${merged?'Объединено':'Восстановить'}</button></div>`}).join(''):'<div class="dirEmpty">Корзина пуста</div>';list.querySelectorAll('[data-r]:not(:disabled)').forEach(b=>b.onclick=async()=>{if(!confirm('Восстановить запись?'))return;try{await api(`/${tab}/${b.dataset.r}/restore`,{method:'POST',body:'{}'});s.remove();if(!refreshCurrentPage())location.reload()}catch(e){alert(e.message)}})};const s=shade(`<div class="dirModal"><h2>Корзина клиентов и техники</h2><p>Удаление не уничтожает старые заказы и финансовую историю.</p><div class="dirTabs"><button class="on" data-t="customers">Клиенты (${data.customers.length})</button><button data-t="equipment">Техника (${data.equipment.length})</button></div><div data-list></div><div class="dirActions"><button data-c>Закрыть</button></div></div>`);s.querySelector('[data-c]').onclick=()=>s.remove();s.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{tab=b.dataset.t;s.querySelectorAll('[data-t]').forEach(x=>x.classList.toggle('on',x===b));render(s)});render(s)}catch(e){alert(e.message)}}
function register(){if(window.Profi24UI?.registerNav){window.Profi24UI.registerNav({id:'directory-trash',label:'Корзина клиентов',group:'management',onClick:openTrash});return true}return false}
styles();let tries=0;const navTimer=setInterval(()=>{tries++;if(register()||tries>20)clearInterval(navTimer)},500);let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(mountButtons,180)}).observe(document.body,{childList:true,subtree:true});setInterval(mountButtons,1500);setTimeout(mountButtons,400);
})();
