// PROFI24 owner directory administration: soft-delete customers/equipment + restore.
(function(){
const token=()=>localStorage.getItem('token')||'';
function role(){try{return JSON.parse(localStorage.getItem('user')||'null')?.role||''}catch{return''}}
if(String(role()).toUpperCase()!=='OWNER')return;
const nativeFetch=window.fetch.bind(window);
let activeCustomers=[],activeEquipment=[];
function target(input){return typeof input==='string'?input:(input?.url||'')}
function cloneFilteredResponse(resp,filter){return resp.clone().json().then(j=>{if(Array.isArray(j?.data))j.data=j.data.filter(filter);const body=JSON.stringify(j);return new Response(body,{status:resp.status,statusText:resp.statusText,headers:{'Content-Type':'application/json'}})}).catch(()=>resp)}
function bodyObject(init){try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}}
async function directory(path,opt={}){const r=await nativeFetch('/directory-api/v1'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||`Ошибка ${r.status}`);return j.data}
window.fetch=async function(input,init){const url=target(input);const method=String(init?.method||'GET').toUpperCase();let resp=await nativeFetch(input,init);
 if(method==='POST'&&/\/api\/v1\/customers(?:\?|$)/.test(url)&&resp.status===409){const j=await resp.clone().json().catch(()=>null);if(j?.error?.code==='POSSIBLE_DUPLICATE_CUSTOMER'){const b=bodyObject(init),pn=b?.phone;if(pn){const deleted=await directory('/customers/deleted-by-phone?phone='+encodeURIComponent(pn)).catch(()=>null);if(deleted&&Number(deleted.id)===Number(j?.error?.candidate?.id)){await directory('/customers/'+deleted.id+'/restore',{method:'POST',body:'{}'});const restored={...deleted,...b,id:deleted.id,deleted_at:null,restored:true};return new Response(JSON.stringify({data:restored}),{status:201,headers:{'Content-Type':'application/json'}})}}}}
 if(method==='GET'&&resp.ok&&/\/api\/v1\/customers(?:\?|$)/.test(url)){return cloneFilteredResponse(resp,x=>!x.deleted_at).then(r=>{activeCustomers=[];r.clone().json().then(j=>{activeCustomers=j.data||[]}).catch(()=>{});return r})}if(method==='GET'&&resp.ok&&/\/api\/v1\/equipment(?:\?|$)/.test(url)){return cloneFilteredResponse(resp,x=>!x.deleted_at).then(r=>{activeEquipment=[];r.clone().json().then(j=>{activeEquipment=j.data||[]}).catch(()=>{});return r})}return resp};
async function api(path,opt={}){return directory(path,opt)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function txt(e){return(e?.textContent||'').replace(/\s+/g,' ').trim()}
function shade(html){const s=document.createElement('div');s.className='dirShade';s.innerHTML=html;document.body.appendChild(s);s.addEventListener('mousedown',e=>{if(e.target===s)s.remove()});return s}
function styles(){if(document.getElementById('dirAdminStyle'))return;const s=document.createElement('style');s.id='dirAdminStyle';s.textContent=`.dirDelete{margin-left:auto;border:1px solid #f0b4b4;background:#fff;color:#b42318;border-radius:8px;padding:7px 9px;cursor:pointer;font-weight:700;display:inline-flex;align-items:center}.dirShade{position:fixed;inset:0;background:#0f172a80;z-index:100001;display:flex;align-items:center;justify-content:center;padding:20px}.dirModal{width:min(850px,96vw);max-height:90vh;overflow:auto;background:#fff;color:#172033;border-radius:14px;padding:20px;box-shadow:0 20px 70px #0004}.dirModal h2{margin:0 0 4px}.dirModal>p{color:#667085;margin:0 0 16px}.dirTabs{display:flex;gap:8px;margin:12px 0}.dirTabs button{border:1px solid #d0d5dd;background:#fff;border-radius:8px;padding:8px 12px;cursor:pointer}.dirTabs button.on{background:#ffb800;border-color:#ffb800}.dirRow{display:grid;grid-template-columns:1.3fr 1.4fr 1fr auto;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid #eee}.dirRow small{color:#667085}.dirRow button{border:1px solid #d0d5dd;background:#fff;border-radius:8px;padding:7px 10px;cursor:pointer;font-weight:700}.dirEmpty{padding:30px;text-align:center;color:#667085}.dirActions{display:flex;justify-content:flex-end;margin-top:16px}.dirActions button{border:1px solid #d0d5dd;background:#fff;border-radius:8px;padding:9px 14px;font-weight:700;cursor:pointer}@media(max-width:700px){.dirRow{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function refreshCurrentPage(){const b=document.querySelector('main header .actions .icon, main header .topActions .iconBtn');if(b){b.click();return true}return false}
async function remove(kind,item){const title=kind==='customers'?'клиента':'технику';const reason=prompt(`Причина удаления ${title}:`,'Создано ошибочно');if(reason===null)return;if(reason.trim().length<3){alert('Укажите причину удаления');return}if(!confirm(`Подтвердите удаление: ${kind==='customers'?item.name:[item.category,item.brand,item.model].filter(Boolean).join(' ')}`))return;try{await api(`/${kind}/${item.id}`,{method:'DELETE',body:JSON.stringify({reason:reason.trim()})});if(kind==='customers')activeCustomers=activeCustomers.filter(x=>Number(x.id)!==Number(item.id));else activeEquipment=activeEquipment.filter(x=>Number(x.id)!==Number(item.id));if(!refreshCurrentPage())location.reload()}catch(e){alert(e.message)}}
function currentPage(){const h=document.querySelector('main header h1,main h1');return txt(h)}
function mountButtons(){const page=currentPage();if(page!=='Клиенты'&&page!=='Техника')return;const rows=[...document.querySelectorAll('main .simple')];const data=page==='Клиенты'?activeCustomers:activeEquipment;rows.forEach((row,i)=>{if(row.querySelector('.dirDelete'))return;const item=data[i];if(!item)return;const b=document.createElement('button');b.className='dirDelete';b.type='button';b.textContent='🗑 Удалить';b.onclick=e=>{e.preventDefault();e.stopPropagation();remove(page==='Клиенты'?'customers':'equipment',item)};row.appendChild(b)})}
async function openTrash(){try{const data=await api('/deleted');let tab='customers';const render=(s)=>{const list=s.querySelector('[data-list]');const rows=tab==='customers'?data.customers:data.equipment;list.innerHTML=rows.length?rows.map(x=>`<div class="dirRow"><div><b>${esc(tab==='customers'?x.name:[x.category,x.brand,x.model].filter(Boolean).join(' '))}</b><br><small>${esc(tab==='customers'?x.phone:x.serial_number||'Без серийного номера')}</small></div><div>${esc(tab==='customers'?x.address||'Адрес не указан':x.customer_name)}<br><small>${esc(String(x.delete_reason||'').replace(/^AUTO_CUSTOMER:\d+:/,''))}</small></div><div>${esc(new Date(x.deleted_at).toLocaleString('ru-RU'))}</div><button data-r="${x.id}">Восстановить</button></div>`).join(''):'<div class="dirEmpty">Корзина пуста</div>';list.querySelectorAll('[data-r]').forEach(b=>b.onclick=async()=>{if(!confirm('Восстановить запись?'))return;try{await api(`/${tab}/${b.dataset.r}/restore`,{method:'POST',body:'{}'});s.remove();if(!refreshCurrentPage())location.reload()}catch(e){alert(e.message)}})};const s=shade(`<div class="dirModal"><h2>Корзина клиентов и техники</h2><p>Удаление не уничтожает старые заказы и финансовую историю.</p><div class="dirTabs"><button class="on" data-t="customers">Клиенты (${data.customers.length})</button><button data-t="equipment">Техника (${data.equipment.length})</button></div><div data-list></div><div class="dirActions"><button data-c>Закрыть</button></div></div>`);s.querySelector('[data-c]').onclick=()=>s.remove();s.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{tab=b.dataset.t;s.querySelectorAll('[data-t]').forEach(x=>x.classList.toggle('on',x===b));render(s)});render(s)}catch(e){alert(e.message)}}
function register(){if(window.Profi24UI?.registerNav){window.Profi24UI.registerNav({id:'directory-trash',label:'Корзина клиентов',group:'management',onClick:openTrash});return true}return false}
styles();let tries=0;const navTimer=setInterval(()=>{tries++;if(register()||tries>20)clearInterval(navTimer)},500);let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(mountButtons,250)}).observe(document.body,{childList:true,subtree:true});setTimeout(mountButtons,600);
})();
