import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{AlertTriangle,CalendarClock,CheckCircle2,Clock3,Gauge,RefreshCw,Route,ShieldAlert,UserRoundCheck,UsersRound,Wrench,X}from'lucide-react';
import'./engineer-capacity.css';

const ANALYTICS='/analytics-api/v1',CORE='/api/v1',BRANCH='/branch-api/v1',token=()=>localStorage.token;
const currentUser=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}};
async function request(base,path,opt={}){const r=await fetch(base+path,{...opt,headers:{Authorization:`Bearer ${token()}`,...(opt.body!=null?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||`Ошибка ${r.status}`);return j.data}
const ymd=v=>{const d=v?new Date(v):new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dt=v=>v?new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const statusText={AVAILABLE:'Свободные окна',FULL:'День заполнен',OVERLOADED:'Перегрузка'};

function App(){
 const u=currentUser(),rbac=window.Profi24RBAC,P=rbac?.P||{},view=Boolean(P.OPERATIONS_MANAGE&&rbac?.can?.(P.OPERATIONS_MANAGE,u?.role));
 const[open,setOpen]=useState(false),[date,setDate]=useState(ymd()),[branch,setBranch]=useState('ALL'),[branches,setBranches]=useState([]),[data,setData]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[notice,setNotice]=useState('');
 async function load(){if(!view)return;try{setBusy(true);setErr('');const qs=new URLSearchParams({date});if(branch!=='ALL')qs.set('branch_id',branch);const[d,b]=await Promise.all([request(ANALYTICS,'/engineer-capacity?'+qs),request(BRANCH,'/branches').catch(()=>[])]);setData(d);setBranches(b||[])}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open)load()},[open,view,date,branch]);
 useEffect(()=>{if(!view)return;const register=()=>window.Profi24UI?.registerNav({id:'engineer-capacity',label:'Загрузка инженеров',group:'work',permission:P.OPERATIONS_MANAGE,badge:data?.summary?.unassigned||null,onClick:()=>setOpen(true)});if(window.Profi24UI)register();else window.addEventListener('profi24:core-ui-ready',register,{once:true});return()=>{window.removeEventListener('profi24:core-ui-ready',register);window.Profi24UI?.removeNav?.('engineer-capacity')}},[view]);
 useEffect(()=>{window.Profi24UI?.updateNav?.('engineer-capacity',{badge:data?.summary?.unassigned||null})},[data?.summary?.unassigned]);
 async function assign(row,candidate){if(!candidate?.next_free_time)return;const scheduled_at=`${date}T${candidate.next_free_time}`;if(!window.confirm(`Назначить ${candidate.engineer_name} на заказ ${row.number} на ${candidate.next_free_time}?`))return;try{setBusy(true);setErr('');setNotice('');await request(CORE,`/requests/${row.id}/schedule`,{method:'PATCH',body:JSON.stringify({engineer_id:candidate.engineer_id,scheduled_at})});setNotice(`${row.number}: назначен ${candidate.engineer_name}, выезд ${candidate.next_free_time}.`);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 if(!view||!open)return null;const s=data?.summary||{};
 return <div className="ecScreen"><header className="ecTop"><div><h1><Gauge/>Загрузка инженеров</h1><p>Распределение заявок по текущей загрузке, опыту категории и ближайшему свободному окну</p></div><div className="ecActions"><input aria-label="Дата загрузки" type="date" value={date} onChange={e=>setDate(e.target.value)}/><select aria-label="Филиал загрузки" value={branch} onChange={e=>setBranch(e.target.value)}><option value="ALL">Все доступные филиалы</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/>Обновить</button><button className="icon" onClick={()=>setOpen(false)}><X/></button></div></header>{err&&<div className="ecError"><AlertTriangle/>{err}</div>}{notice&&<div className="ecNotice"><CheckCircle2/>{notice}</div>}{data&&<><div className="ecMetrics"><Metric icon={<UsersRound/>} label="Инженеров" value={s.engineers||0}/><Metric icon={<CalendarClock/>} label="Выездов на день" value={s.scheduled_jobs||0}/><Metric icon={<ShieldAlert/>} label="Перегружены" value={s.overloaded||0} hot={s.overloaded>0}/><Metric icon={<UserRoundCheck/>} label="Без инженера" value={s.unassigned||0} hot={s.unassigned>0}/><Metric icon={<Clock3/>} label="Просрочено SLA" value={s.overdue_sla||0} hot={s.overdue_sla>0}/><Metric icon={<Route/>} label="Пропущено выездов" value={s.missed_visits||0} hot={s.missed_visits>0}/></div><section className="ecCard"><div className="ecCardTop"><div><h2>Кто реально загружен</h2><p>Красная карточка означает перегрузку по дневному плану, активным заказам или просрочкам.</p></div></div><div className="ecEngineerGrid">{data.engineers.map(x=><Engineer key={x.id} x={x}/>)}</div></section><section className="ecCard"><div className="ecCardTop"><div><h2>Кому назначить новые заявки</h2><p>CRM показывает до пяти кандидатов, но автоматическое назначение доступно только при найденном свободном окне.</p></div></div><div className="ecQueue">{data.unassigned.map(row=><Request key={row.id} row={row} assign={assign} busy={busy}/>) }{!data.unassigned.length&&<div className="ecEmpty"><CheckCircle2/><b>Все активные заявки распределены</b><span>Неназначенных заказов в доступных филиалах нет.</span></div>}</div></section><div className="ecMethod"><b>Методика</b><span>{data.methodology?.load}</span><span>{data.methodology?.recommendation}</span><small>Рабочий день {data.methodology?.working_day}, базовый слот {data.methodology?.slot_minutes} мин., ориентир {data.methodology?.max_daily_jobs} выездов в день. Опыт категории — закрытые заказы за {data.methodology?.skill_window_days} дней.</small></div></>}</div>
}
function Metric({icon,label,value,hot}){return <div className={'ecMetric '+(hot?'hot':'')}><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>}
function Engineer({x}){return <article className={'ecEngineer '+x.status}><div className="ecEngineerTop"><div><b>{x.name}</b><span className={'ecState '+x.status}>{statusText[x.status]||x.status}</span></div><strong>{Math.round(Number(x.utilization_pct||0))}%</strong></div><div className="ecBar"><i style={{width:Math.min(100,Number(x.utilization_pct||0))+'%'}}/></div><div className="ecEngineerFacts"><span><CalendarClock/>Выездов: <b>{x.scheduled_jobs}</b></span><span><Wrench/>Активных: <b>{x.active_orders}</b></span><span><Clock3/>Окно: <b>{x.next_free_time||'нет'}</b></span><span className={x.overdue_sla?'bad':''}><ShieldAlert/>SLA: <b>{x.overdue_sla}</b></span></div></article>}
function Request({row,assign,busy}){const r=row.recommended_engineer;return <article className={'ecRequest '+(row.priority==='CRITICAL'?'critical':'')}><div className="ecReqMain"><div className="ecReqTitle"><b>{row.number}</b>{row.priority==='CRITICAL'&&<span>Критично</span>}</div><h3>{row.customer_name}</h3><p>{[row.category,row.brand,row.model].filter(Boolean).join(' ')||'Техника не указана'}</p><small>Создан: {dt(row.created_at)}{row.sla_deadline?` · SLA ${dt(row.sla_deadline)}`:''}</small></div>{r?<div className="ecRecommendation"><div className="ecRecTop"><div><small>Рекомендуемый инженер</small><b>{r.engineer_name}</b></div><strong>{Math.round(r.score)}/100</strong></div><div className="ecScores"><span>Загрузка <b>{Math.round(r.load_score)}</b></span><span>Опыт <b>{Math.round(r.skill_score)}</b></span><span>Окно <b>{Math.round(r.availability_score)}</b></span></div><p>{r.reason}</p><div className="ecRecAction"><span>{r.next_free_time?`Свободно сегодня в ${r.next_free_time}`:'Сегодня свободного окна нет'}</span><button disabled={busy||!r.next_free_time} onClick={()=>assign(row,r)}><UserRoundCheck/>Назначить{r.next_free_time?` · ${r.next_free_time}`:''}</button></div>{row.candidates?.length>1&&<details><summary>Другие кандидаты ({row.candidates.length-1})</summary>{row.candidates.slice(1).map(c=><div className="ecAlt" key={c.engineer_id}><b>{c.engineer_name}</b><span>{Math.round(c.score)}/100 · {c.next_free_time||'нет окна'} · опыт {c.category_jobs}</span></div>)}</details>}</div>:<div className="ecNoCandidate"><AlertTriangle/><b>Нет доступного инженера филиала</b><span>Проверьте привязку сотрудников к филиалу или расписание.</span></div>}</article>}

const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
