import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{AlertTriangle,CheckCircle2,Clock3,MapPin,RefreshCw,Route,ShieldAlert,Truck,X}from'lucide-react';
import'./engineer-route-execution.css';
const AN='/analytics-api/v1',BR='/branch-api/v1',token=()=>localStorage.token;
const me=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}};
async function call(base,path){const r=await fetch(base+path,{headers:{Authorization:`Bearer ${token()}`}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||`Ошибка ${r.status}`);return j.data}
function kzDate(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qostanay',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
const tm=v=>v?new Date(v).toLocaleTimeString('ru-RU',{timeZone:'Asia/Qostanay',hour:'2-digit',minute:'2-digit'}):'—';
const stateLabel=s=>s==='ARRIVED'?'На месте':s==='ON_ROUTE'?'В пути':'Ожидает';
function App(){
 const user=me(),rbac=window.Profi24RBAC,P=rbac?.P||{},view=Boolean(P.OPERATIONS_MANAGE&&rbac?.can?.(P.OPERATIONS_MANAGE,user?.role)),[open,setOpen]=useState(false),[date,setDate]=useState(kzDate()),[branches,setBranches]=useState([]),[branch,setBranch]=useState(''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[onlyRisk,setOnlyRisk]=useState(false),seq=useRef(0);
 async function loadBranches(){const rows=await call(BR,'/branches');setBranches(rows||[]);setBranch(v=>v&&rows.some(x=>String(x.id)===String(v))?v:String(rows[0]?.id||''))}
 async function load(){if(!branch)return;const n=++seq.current;try{setBusy(true);setErr('');const d=await call(AN,`/engineer-route/execution?date=${encodeURIComponent(date)}&branch_id=${branch}`);if(n===seq.current)setData(d)}catch(e){if(n===seq.current)setErr(e.message)}finally{if(n===seq.current)setBusy(false)}}
 useEffect(()=>{if(open&&view)loadBranches().catch(e=>setErr(e.message))},[open,view]);
 useEffect(()=>{if(open&&branch)load()},[open,branch,date]);
 useEffect(()=>{if(!open||!branch)return;const id=setInterval(load,60000);return()=>clearInterval(id)},[open,branch,date]);
 useEffect(()=>{if(!view)return;const reg=()=>window.Profi24UI?.registerNav({id:'engineer-route-control',label:'Контроль маршрутов',group:'work',permission:P.OPERATIONS_MANAGE,badge:data?.summary?.at_risk||data?.summary?.overdue_unstarted||null,onClick:()=>setOpen(true)});if(window.Profi24UI)reg();else window.addEventListener('profi24:core-ui-ready',reg,{once:true});return()=>{window.removeEventListener('profi24:core-ui-ready',reg);window.Profi24UI?.removeNav?.('engineer-route-control')}},[view]);
 useEffect(()=>{window.Profi24UI?.updateNav?.('engineer-route-control',{badge:data?.summary?.at_risk||data?.summary?.overdue_unstarted||null})},[data?.summary?.at_risk,data?.summary?.overdue_unstarted]);
 if(!view||!open)return null;const s=data?.summary||{},routes=(data?.routes||[]).filter(r=>!onlyRisk||r.summary.at_risk||r.summary.overdue_unstarted);
 return <div className="ercScreen"><header><div><h1><Route/>Контроль маршрутов</h1><p>План/факт выездов по событиям CRM, прогноз ETA и риск опоздания</p></div><div className="ercFilters"><input aria-label="Дата контроля маршрутов" type="date" value={date} onChange={e=>setDate(e.target.value)}/><select aria-label="Филиал контроля маршрутов" value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label><input type="checkbox" checked={onlyRisk} onChange={e=>setOnlyRisk(e.target.checked)}/>Только риски</label><button onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/>Обновить</button><button className="icon" onClick={()=>setOpen(false)}><X/></button></div></header>{err&&<div className="ercError"><AlertTriangle/>{err}</div>}<div className="ercMetrics"><Metric label="Маршрутов" value={s.routes||0}/><Metric label="Активно" value={s.active||0}/><Metric label="В пути" value={s.on_route||0}/><Metric label="На месте" value={s.arrived||0}/><Metric label="Под риском" value={s.at_risk||0} hot={s.at_risk>0}/><Metric label="Не выехали" value={s.overdue_unstarted||0} hot={s.overdue_unstarted>0}/></div><div className="ercNote"><ShieldAlert/>Фактические отметки — только «Выехал» и «На месте» из CRM Workflow. Геолокация сотрудника не отслеживается.</div><section className="ercRoutes">{routes.map(r=><RouteCard key={r.engineer.id} route={r}/>) }{!routes.length&&<div className="ercEmpty"><CheckCircle2/><b>{onlyRisk?'Маршрутов с риском нет':'Опубликованных маршрутов нет'}</b><span>{onlyRisk?'По текущему прогнозу вмешательство диспетчера не требуется.':'Сначала опубликуйте маршрут инженера на выбранную дату.'}</span></div>}</section></div>
}
function Metric({label,value,hot}){return <div className={hot?'hot':''}><small>{label}</small><b>{value}</b></div>}
function RouteCard({route}){const current=route.current_stop,risks=route.stops.filter(x=>x.at_risk||x.overdue_unstarted);return <article className={'ercRoute '+(risks.length?'risk':'')}><header><div><small>{route.branch?.code||''} · rev {route.plan?.revision}</small><h2>{route.engineer.name}</h2></div><div className={'ercRouteState '+String(route.summary.route_state).toLowerCase()}>{route.summary.route_state==='ALL_ARRIVED'?'Все прибыли':route.summary.route_state==='ACTIVE'?'Маршрут начат':'Не начат'}</div></header>{current?<div className="ercCurrent"><div className="ercStateIcon">{current.execution_state==='ON_ROUTE'?<Truck/>:<Clock3/>}</div><div><small>ТЕКУЩАЯ ТОЧКА · {stateLabel(current.execution_state)}</small><b>{current.number} · {current.customer_name}</b><span><MapPin/>{current.address||'Адрес не указан'}</span></div><div><small>План</small><b>{tm(current.planned_at)}</b></div><div><small>ETA</small><b>{tm(current.projected_arrival_at)}</b>{Number(current.arrival_delay_minutes)>0&&<em>+{current.arrival_delay_minutes} мин</em>}</div></div>:<div className="ercDone"><CheckCircle2/>Все точки маршрута имеют отметку «На месте».</div>}<div className="ercStops">{route.stops.map(x=><button key={x.id} className={`${x.at_risk||x.overdue_unstarted?'risk ':''}${x.execution_state.toLowerCase()}`} onClick={()=>window.dispatchEvent(new CustomEvent('profi24:open-order360',{detail:{number:x.number}}))}><span>{x.sequence_no}</span><div><b>{x.number}</b><small>{tm(x.planned_at)} → {tm(x.projected_arrival_at)}</small></div><strong>{stateLabel(x.execution_state)}</strong>{x.at_risk&&<em>+{x.arrival_delay_minutes} мин</em>}{x.overdue_unstarted&&<em>не выехал</em>}</button>)}</div></article>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);