import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{CalendarClock,CheckCircle2,ChevronRight,Clock3,MapPin,Navigation,RefreshCw,Route,Truck,X}from'lucide-react';
import'./engineer-route.css';

const AN='/analytics-api/v1',BR='/branch-api/v1',W='/workflow-api/v1',token=()=>localStorage.token;
const me=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}};
async function call(base,path,opt={}){const r=await fetch(base+path,{...opt,headers:{Authorization:`Bearer ${token()}`,...(opt.body!=null?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||`Ошибка ${r.status}`);return j.data}
function kzDate(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qostanay',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
const tm=v=>v?new Date(v).toLocaleTimeString('ru-RU',{timeZone:'Asia/Qostanay',hour:'2-digit',minute:'2-digit'}):'—';
const allowedRouteEvents=new Set(['ACCEPT','DEPART','ARRIVE']);

function App(){
 const user=me(),[open,setOpen]=useState(false),[date,setDate]=useState(kzDate()),[branches,setBranches]=useState([]),[branch,setBranch]=useState(''),[data,setData]=useState(null),[workflow,setWorkflow]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[notice,setNotice]=useState('');
 async function loadBranches(){const rows=await call(BR,'/branches');setBranches(rows||[]);setBranch(v=>v&&rows.some(x=>String(x.id)===String(v))?v:String(rows[0]?.id||''))}
 async function load(){if(!branch||!user?.id)return;try{setBusy(true);setErr('');const board=await call(AN,`/engineer-route/execution?date=${date}&branch_id=${branch}&engineer_id=${user.id}`),route=board?.routes?.[0]||null;setData(route);setWorkflow(null);if(route?.current_stop?.request_id){const wf=await call(W,`/requests/${route.current_stop.request_id}/workflow`);setWorkflow(wf)}}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function advance(){const next=workflow?.next,current=data?.current_stop;if(!current||!next||!allowedRouteEvents.has(next.event))return;try{setBusy(true);setErr('');setNotice('');await call(W,`/requests/${current.request_id}/workflow`,{method:'POST',body:JSON.stringify({event:next.event,note:'Отметка из «Мой маршрут»'})});setNotice(`${next.label}: зафиксировано в CRM.`);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open&&user?.role==='ENGINEER')loadBranches().catch(e=>setErr(e.message))},[open,user?.role]);
 useEffect(()=>{if(open&&branch){setNotice('');load()}},[open,branch,date]);
 useEffect(()=>{if(user?.role!=='ENGINEER')return;const reg=()=>window.Profi24UI?.registerNav({id:'engineer-my-route',label:'Мой маршрут',group:'team',roles:['ENGINEER'],onClick:()=>setOpen(true)});if(window.Profi24UI)reg();else window.addEventListener('profi24:core-ui-ready',reg,{once:true});return()=>{window.removeEventListener('profi24:core-ui-ready',reg);window.Profi24UI?.removeNav?.('engineer-my-route')}},[user?.role]);
 if(user?.role!=='ENGINEER'||!open)return null;const plan=data?.plan,stops=data?.stops||[],summary=data?.summary||{},current=data?.current_stop;
 return <div className="ermScreen"><header><div><h1><Route/>Мой маршрут</h1><small>{plan?`Опубликованная ревизия ${plan.revision} · факт по событиям CRM`:'Маршрут ещё не опубликован'}</small></div><div><input aria-label="Дата моего маршрута" type="date" value={date} onChange={e=>setDate(e.target.value)}/><select aria-label="Филиал моего маршрута" value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button aria-label="Обновить мой маршрут" onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/></button><button aria-label="Закрыть мой маршрут" onClick={()=>setOpen(false)}><X/></button></div></header>{err&&<div className="erError">{err}</div>}{notice&&<div className="ermNotice"><CheckCircle2/>{notice}</div>}{!plan?<div className="ermEmpty"><CalendarClock/><b>На этот день опубликованного маршрута нет</b><span>После публикации руководителем порядок появится здесь.</span></div>:<><div className="ermSummary"><span><b>{stops.length}</b> выездов</span><span><b>{summary.started||0}</b> начато</span><span><b>{summary.arrived||0}</b> на месте</span><span className={summary.at_risk?'risk':''}><b>{summary.at_risk||0}</b> под риском</span></div>{current&&<div className="ermCurrent"><div><small>ТЕКУЩАЯ ТОЧКА</small><b>{current.number} · {current.customer_name}</b><span>План {tm(current.planned_at)} · ETA {tm(current.projected_arrival_at)}</span></div>{workflow?.next&&allowedRouteEvents.has(workflow.next.event)?<button data-route-action={workflow.next.event} disabled={busy} onClick={advance}>{workflow.next.event==='DEPART'?<Truck/>:workflow.next.event==='ARRIVE'?<MapPin/>:<CheckCircle2/>}{workflow.next.label}</button>:<span>{current.execution_state==='ARRIVED'?'Вы на месте — продолжите работу в заказе':'Следующий этап выполняется в заказе'}</span>}</div>}<div className="ermList">{stops.map(s=><Stop key={s.id} s={s} current={current?.request_id===s.request_id} close={()=>setOpen(false)}/>)}</div><div className="ermMethod">{data?.methodology?.facts}<br/>{data?.methodology?.eta}</div></>}</div>
}
function Stop({s,current,close}){const delay=Number(s.arrival_delay_minutes||0);return <article className={`${s.at_risk?'risk ':''}${current?'current ':''}state-${String(s.execution_state||'').toLowerCase()}`}><div className="ermSeq">{s.sequence_no}</div><div className="ermTime"><b>{tm(s.planned_at)}</b><small>ETA {tm(s.projected_arrival_at)}</small>{delay>0&&<em>+{delay} мин</em>}</div><div className="ermMain"><div className="ermState">{s.execution_state==='ARRIVED'?<><CheckCircle2/>На месте</>:s.execution_state==='ON_ROUTE'?<><Truck/>В пути</>:<><Clock3/>Ожидает</>}</div><b>{s.number}</b><h3>{s.customer_name||'Клиент'}</h3><p><MapPin/>{s.address||'Адрес не указан'}</p><small>{s.departed_at?`Выехал ${tm(s.departed_at)}`:'Выезд не отмечен'} · {s.arrived_at?`На месте ${tm(s.arrived_at)}`:'прибытие не отмечено'}</small>{s.overdue_unstarted&&<em>Выезд не начат вовремя</em>}{s.at_risk&&!s.overdue_unstarted&&<em>Прогнозируется опоздание</em>}</div><div className="ermButtons">{s.address&&<a target="_blank" rel="noreferrer" href={`https://maps.google.com/?q=${encodeURIComponent(s.address)}`}><Navigation/>Навигатор</a>}<button onClick={()=>{close();window.dispatchEvent(new CustomEvent('profi24:open-order360',{detail:{number:s.number}}))}}>Заказ<ChevronRight/></button></div></article>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);