import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import'./feedback.css';

const token=decodeURIComponent(location.pathname.split('/').filter(Boolean).at(-1)||'');
async function api(method='GET',body){const r=await fetch('/feedback-api/v1/feedback/'+encodeURIComponent(token),{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined}),j=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(j.error?.message||'Не удалось открыть опрос');e.status=r.status;throw e}return j.data}
function App(){const[data,setData]=useState(null),[score,setScore]=useState(null),[comment,setComment]=useState(''),[contact,setContact]=useState(false),[busy,setBusy]=useState(true),[err,setErr]=useState(''),[done,setDone]=useState(null);useEffect(()=>{api().then(d=>{setData(d);if(d.responded)setDone({score:d.score,review_url:d.review_url})}).catch(e=>setErr(e.message)).finally(()=>setBusy(false))},[]);async function submit(){try{setBusy(true);setErr('');const d=await api('POST',{score,comment,contact_requested:contact});setDone(d)}catch(e){setErr(e.message)}finally{setBusy(false)}}if(busy&&!data)return <main className="feedbackPortal"><section className="feedbackCard"><p>Загружаем опрос…</p></section></main>;if(err&&!data)return <main className="feedbackPortal"><section className="feedbackCard"><div className="feedbackBrand">PROFI24KST</div><h1>Опрос недоступен</h1><div className="feedbackError">{err}</div><p>Если вы считаете, что это ошибка, свяжитесь с сервисным центром.</p></section></main>;return <main className="feedbackPortal"><section className="feedbackCard"><div className="feedbackBrand">PROFI24KST</div>{done?<Thanks d={done}/>:<><h1>Оцените качество сервиса</h1><p>Ваш ответ поможет нам контролировать качество ремонта и работу команды.</p><div className="feedbackOrder"><b>Заказ {data?.request_number}</b><span>{data?.equipment}</span></div><div className="feedbackQuestion">Насколько вероятно, что вы порекомендуете PROFI24KST знакомым?</div><div className="scoreGrid">{Array.from({length:11},(_,n)=><button key={n} className={score===n?'on':''} onClick={()=>setScore(n)}>{n}</button>)}</div><div className="scoreHints"><span>Совсем не вероятно</span><span>Очень вероятно</span></div><textarea maxLength="2000" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Комментарий — что понравилось или что нужно улучшить?"/><label className="feedbackCheck"><input type="checkbox" checked={contact} onChange={e=>setContact(e.target.checked)}/><span>Хочу, чтобы со мной связался руководитель сервиса</span></label>{err&&<div className="feedbackError">{err}</div>}<button className="feedbackSubmit" disabled={busy||score===null} onClick={submit}>{busy?'Сохраняем…':'Отправить оценку'}</button><p className="feedbackPrivacy">Опрос связан только с вашим заказом. В публичный отзыв ничего не публикуется автоматически.</p></>}</section></main>}
function Thanks({d}){return <div className="feedbackThanks"><strong>Спасибо!</strong><p>Оценка {d.score}/10 сохранена. Она попадёт в контроль качества PROFI24KST.</p>{d.review_url&&<a className="feedbackReview" href={d.review_url} target="_blank" rel="noreferrer">Оставить публичный отзыв о сервисе</a>}<p className="feedbackPrivacy">Ссылка на публичный отзыв доступна всем клиентам независимо от поставленной оценки.</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
