import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{MessageSquareHeart,RefreshCw,X,Send,Save,RotateCcw}from'lucide-react';
import'./feedback.css';
const A='/communications-api/v1/customer-feedback',token=()=>localStorage.token;
async function api(path='',opt={}){const r=await fetch(A+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка запроса');return j.data}
const user=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}};
const dt=v=>v?new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
function App(){const u=user(),rbac=window.Profi24RBAC,P=rbac?.P||{},permission=P.COMMUNICATIONS_MANAGE,allowed=Boolean(permission&&rbac?.can(permission,u?.role));const[open,setOpen]=useState(false),[tab,setTab]=useState('overview'),[days,setDays]=useState(30),[summary,setSummary]=useState(null),[rows,setRows]=useState([]),[cfg,setCfg]=useState(null),[orders,setOrders]=useState([]),[inviteId,setInviteId]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');const editable=['OWNER','SUPERVISOR'].includes(u?.role);
 async function load(){try{setBusy(true);setErr('');const[s,r,c,o]=await Promise.all([api('/summary?days='+days),api(),api('/settings'),fetch('/api/v1/requests',{headers:{Authorization:`Bearer ${token()}`}}).then(x=>x.json()).then(x=>x.data||[])]);setSummary(s);setRows(r||[]);setCfg(c);setOrders(o||[])}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open&&allowed)load()},[open,allowed,days]);useEffect(()=>{if(!allowed)return;const register=()=>window.Profi24UI?.registerNav({id:'customer-feedback',label:'Отзывы / NPS',group:'clients',permission,onClick:()=>setOpen(true)});if(window.Profi24UI)register();else window.addEventListener('profi24:core-ui-ready',register,{once:true});return()=>{window.removeEventListener('profi24:core-ui-ready',register);window.Profi24UI?.removeNav?.('customer-feedback')}},[u?.id,u?.role,allowed,permission]);
 const available=useMemo(()=>{const known=new Set(rows.map(x=>Number(x.request_id)));return orders.filter(x=>x.status==='CLOSED'&&!known.has(Number(x.id))).slice(0,300)},[orders,rows]);async function invite(){try{setBusy(true);setErr('');await api('/invite/'+inviteId,{method:'POST',body:'{}'});setInviteId('');await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}async function resend(id){try{setBusy(true);await api('/'+id+'/resend',{method:'POST',body:'{}'});await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}async function save(){try{setBusy(true);setErr('');setCfg(await api('/settings',{method:'PATCH',body:JSON.stringify({active:cfg.active,low_score_threshold:Number(cfg.low_score_threshold),public_review_url:cfg.public_review_url||null})}))}catch(e){setErr(e.message)}finally{setBusy(false)}}
 if(!allowed||!open)return null;return <div className="feedbackScreen"><div className="feedbackTop"><div><h1>Отзывы и NPS</h1><p>Контроль удовлетворённости после закрытия заказа и работа с низкими оценками</p></div><div className="feedbackTopActions"><button onClick={load} disabled={busy}><RefreshCw size={16}/> Обновить</button><button onClick={()=>setOpen(false)}><X size={19}/></button></div></div>{err&&<div className="feedbackAdminError">{err}</div>}<section className="feedbackMetrics"><Metric t="NPS" v={summary?.nps==null?'—':summary.nps}/><Metric t="Ответили" v={summary?.responded??0}/><Metric t="Конверсия" v={(summary?.response_rate??0)+'%'}/><Metric t="Средняя оценка" v={summary?.average_score??'—'}/><Metric t="Follow-up открыто" v={summary?.followups_open??0} bad={summary?.followups_open>0}/></section><div className="feedbackTabs"><button className={tab==='overview'?'on':''} onClick={()=>setTab('overview')}>Обзор</button><button className={tab==='settings'?'on':''} onClick={()=>setTab('settings')}>Настройки</button></div>{tab==='overview'?<Overview summary={summary} rows={rows} days={days} setDays={setDays} available={available} inviteId={inviteId} setInviteId={setInviteId} invite={invite} resend={resend} busy={busy}/>:<Settings cfg={cfg} setCfg={setCfg} editable={editable} save={save} busy={busy}/>}</div>}
function Metric({t,v,bad}){return <div className={'feedbackMetric '+(bad?'bad':'')}><small>{t}</small><b>{v}</b></div>}
function Overview({summary,rows,days,setDays,available,inviteId,setInviteId,invite,resend,busy}){return <><section className="feedbackPanel"><div className="feedbackToolbar"><label>Период<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value="30">30 дней</option><option value="90">90 дней</option><option value="365">365 дней</option></select></label><label>Запросить оценку по старому закрытому заказу<select value={inviteId} onChange={e=>setInviteId(e.target.value)}><option value="">Выберите заказ</option>{available.map(x=><option key={x.id} value={x.id}>{x.number} — {x.customer_name}</option>)}</select></label><button className="primary" disabled={busy||!inviteId} onClick={invite}><Send size={15}/> Отправить</button></div><div className="feedbackNote">NPS считается по стандарту: 0–6 — критики, 7–8 — нейтральные, 9–10 — сторонники. Низкая оценка автоматически создаёт задачу на связь с клиентом.</div></section><section className="feedbackPanel"><h2>По инженерам</h2><div className="feedbackEngineers">{summary?.by_engineer?.length?summary.by_engineer.map(x=><div className="feedbackEngineer" key={x.engineer_id||'none'}><b>{x.engineer_name}</b><span>{x.responded} ответов</span><span>Ø {x.average_score??'—'}</span><span>NPS {x.nps??'—'}</span></div>):<div className="feedbackEmpty">Пока нет ответов за выбранный период</div>}</div></section><section className="feedbackPanel"><h2>Последние опросы</h2><div className="feedbackTable"><div className="feedbackHead"><span>Оценка</span><span>Заказ</span><span>Клиент</span><span>Инженер</span><span>Комментарий</span><span>Действие</span></div>{rows.map(x=><div className="feedbackRow" key={x.id}><span>{x.score==null?<span className="scoreBadge">—</span>:<span className={'scoreBadge '+x.nps_group}>{x.score}/10</span>}</span><span><b>{x.request_number}</b><small>{dt(x.responded_at||x.last_invited_at||x.created_at)}</small></span><span>{x.customer_name}<small>{x.branch_name||''}</small></span><span>{x.engineer_name||'Не назначен'}</span><span>{x.comment|| (x.status==='INVITED'?'Ожидаем ответ':'—')} {x.followup_status==='OPEN'&&<small className="followOpen">Есть задача на связь</small>}</span><span>{x.status==='INVITED'?<button disabled={busy} onClick={()=>resend(x.id)}><RotateCcw size={14}/> Повторить</button>:<small>{x.nps_group||'Ответ получен'}</small>}</span></div>)}</div>{!rows.length&&<div className="feedbackEmpty">Опросов пока нет</div>}</section></>}
function Settings({cfg,setCfg,editable,save,busy}){if(!cfg)return <section className="feedbackPanel">Загружаем настройки…</section>;return <section className="feedbackPanel"><h2>Настройки сбора обратной связи</h2><div className="feedbackSettings"><label><span>Автоматический NPS после закрытия заказа</span><select disabled={!editable} value={cfg.active?'1':'0'} onChange={e=>setCfg({...cfg,active:e.target.value==='1'})}><option value="1">Включён</option><option value="0">Выключен</option></select></label><div className="row"><label><span>Создавать задачу при оценке ≤</span><input disabled={!editable} type="number" min="0" max="10" value={cfg.low_score_threshold} onChange={e=>setCfg({...cfg,low_score_threshold:e.target.value})}/></label><label><span>Ссылка для публичного отзыва</span><input disabled={!editable} value={cfg.public_review_url||''} onChange={e=>setCfg({...cfg,public_review_url:e.target.value})} placeholder="https://..."/></label></div><div className="feedbackNote">Публичная ссылка показывается всем ответившим клиентам независимо от оценки. CRM не скрывает её от недовольных клиентов и не публикует ответы автоматически.</div>{editable&&<button className="primary" disabled={busy} onClick={save}><Save size={15}/> Сохранить настройки</button>}</div></section>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
