import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{WalletCards,Plus,X,RefreshCw,Trash2,ArrowRightLeft,Power,PowerOff}from'lucide-react';
import'./warehouse.css';
const B='/finance-api/v1',money=n=>new Intl.NumberFormat('ru-KZ',{maximumFractionDigits:0}).format(Number(n||0))+' ₸',types={CASH:'Наличные',BANK:'Банк',KASPI:'Kaspi',CARD:'Карта',OTHER:'Другой'};
async function api(p,o={}){const r=await fetch(B+p,{...o,headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.token}`}}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
function App(){const[open,setOpen]=useState(false),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[pnl,setPnl]=useState({}),[rows,setRows]=useState([]),[accounts,setAccounts]=useState([]),[accountFilter,setAccountFilter]=useState(''),[modal,setModal]=useState(''),[err,setErr]=useState('');const user=(()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}})();
async function load(){try{setErr('');const suffix=accountFilter?'&account_id='+accountFilter:'';const[a,b,c]=await Promise.all([api('/pnl?month='+month),api('/transactions?month='+month+suffix),api('/accounts')]);setPnl(a);setRows(b);setAccounts(c)}catch(e){setErr(e.message)}}
useEffect(()=>{if(open)load()},[open,month,accountFilter]);useEffect(()=>{if(user?.role!=='OWNER')return;let off=null;const reg=()=>{if(!off&&window.Profi24UI)off=window.Profi24UI.registerNav({id:'finance',label:'Финансы',group:'finance',roles:['OWNER'],onClick:()=>setOpen(true)})};reg();window.addEventListener('profi24:core-ui-ready',reg);return()=>{window.removeEventListener('profi24:core-ui-ready',reg);off?.()}},[user?.id,user?.role]);
const active=accounts.filter(x=>x.is_active),total=useMemo(()=>accounts.reduce((s,x)=>s+Number(x.balance||0),0),[accounts]);if(user?.role!=='OWNER'||!open)return null;
return <div className="warehouseScreen"><div className="whTop"><div><h1>Финансы и счета</h1><p>Деньги компании, движение средств и реальная прибыль</p></div><div className="whTopActions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={load} title="Обновить"><RefreshCw/></button><button onClick={()=>setOpen(false)}><X/></button></div></div>{err&&<div className="whError">{err}</div>}
<div className="whMetrics"><M t="Денег на счетах" v={money(total)}/><M t="Выручка" v={money(pnl.revenue)}/><M t="Валовая прибыль" v={money(pnl.gross_profit)}/><M t="ФОТ" v={money(pnl.payroll)}/><M t="Прочие расходы" v={money(pnl.operating_expenses)}/><M t="Чистая прибыль" v={money(pnl.net_profit)}/></div>
<div className="whTable"><div className="whTop"><div><h2>Счета</h2><small>Актуальные остатки с учётом всех операций</small></div><div className="whTopActions"><button onClick={()=>setModal('transfer')} disabled={active.length<2}><ArrowRightLeft/>Перевод</button><button className="whPrimary" onClick={()=>setModal('account')}><Plus/>Добавить счёт</button></div></div><div className="whMetrics">{accounts.map(a=><button key={a.id} className={'whMetric '+(!a.is_active?'muted':'')} onClick={()=>setModal({type:'account',account:a})}><small>{a.name} · {types[a.type]||a.type}</small><b>{money(a.balance)}</b><span>{a.is_active?'Активен':'Отключён'} · операций {a.operations_count}</span></button>)}</div></div>
<div className="whGrid2"><Box title="Структура расходов">{pnl.expense_categories?.map((x,i)=><Row key={i} a={x.category} b="" c={money(x.amount)}/>)}</Box><Box title="Денежные операции" action={<div className="whTopActions"><select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">Все счета</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button className="whPrimary" onClick={()=>setModal('operation')}><Plus/>Операция</button></div>}>{rows.map(x=><Row key={x.id} a={x.transfer_group_id?(x.type==='INCOME'?'Перевод получен':'Перевод отправлен'):`${x.type==='INCOME'?'Приход':'Расход'} · ${x.category}`} b={`${x.occurred_at?.slice(0,10)} · ${x.account_name||'Без счёта'}${x.comment?' · '+x.comment:''}`} c={(x.type==='EXPENSE'?'-':'+')+money(x.amount)} action={<button title="Удалить" onClick={async()=>{if(confirm(x.transfer_group_id?'Удалить обе части перевода?':'Удалить операцию?')){await api('/transactions/'+x.id,{method:'DELETE'});load()}}}><Trash2 size={16}/></button>}/>)}</Box></div>
{modal==='operation'&&<OperationModal accounts={active} close={()=>setModal('')} done={()=>{setModal('');load()}}/>}{modal==='transfer'&&<TransferModal accounts={active} close={()=>setModal('')} done={()=>{setModal('');load()}}/>}{(modal==='account'||modal?.type==='account')&&<AccountModal account={modal.account} close={()=>setModal('')} done={()=>{setModal('');load()}}/>}</div>}
function M({t,v}){return <div className="whMetric"><small>{t}</small><b>{v}</b></div>}function Box({title,action,children}){return <div className="whTable"><div className="whTop"><h2>{title}</h2>{action}</div>{React.Children.count(children)?children:<div className="whEmpty">Нет данных</div>}</div>}function Row({a,b,c,action}){return <div className="whRow"><div><b>{a}</b><small>{b}</small></div><span></span><b>{c}</b><span></span><div>{action}</div></div>}
function OperationModal({accounts,close,done}){const[f,setF]=useState({type:'EXPENSE',category:'Аренда',amount:'',account_id:accounts[0]?.id||'',occurred_at:new Date().toISOString().slice(0,10),comment:''}),[e,setE]=useState('');async function save(){try{await api('/transactions',{method:'POST',body:JSON.stringify(f)});done()}catch(x){setE(x.message)}}return <Modal title="Денежная операция" close={close} error={e}><label>Счёт<select value={f.account_id} onChange={x=>setF({...f,account_id:+x.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.balance)}</option>)}</select></label><label>Тип<select value={f.type} onChange={x=>setF({...f,type:x.target.value})}><option value="EXPENSE">Расход</option><option value="INCOME">Прочий приход</option></select></label><label>Категория<input value={f.category} onChange={x=>setF({...f,category:x.target.value})}/></label><label>Сумма<input type="number" min="0" value={f.amount} onChange={x=>setF({...f,amount:+x.target.value})}/></label><label>Дата<input type="date" value={f.occurred_at} onChange={x=>setF({...f,occurred_at:x.target.value})}/></label><label>Комментарий<textarea value={f.comment} onChange={x=>setF({...f,comment:x.target.value})}/></label><Actions close={close} save={save}/></Modal>}
function TransferModal({accounts,close,done}){const[f,setF]=useState({from_account_id:accounts[0]?.id||'',to_account_id:accounts[1]?.id||'',amount:'',occurred_at:new Date().toISOString().slice(0,10),comment:''}),[e,setE]=useState('');async function save(){try{await api('/transfers',{method:'POST',body:JSON.stringify(f)});done()}catch(x){setE(x.message)}}return <Modal title="Перевод между счетами" close={close} error={e}><label>Откуда<select value={f.from_account_id} onChange={x=>setF({...f,from_account_id:+x.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.balance)}</option>)}</select></label><label>Куда<select value={f.to_account_id} onChange={x=>setF({...f,to_account_id:+x.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Сумма<input type="number" min="0" value={f.amount} onChange={x=>setF({...f,amount:+x.target.value})}/></label><label>Дата<input type="date" value={f.occurred_at} onChange={x=>setF({...f,occurred_at:x.target.value})}/></label><label>Комментарий<input value={f.comment} onChange={x=>setF({...f,comment:x.target.value})}/></label><Actions close={close} save={save}/></Modal>}
function AccountModal({account,close,done}){const[f,setF]=useState({name:account?.name||'',type:account?.type||'CASH',opening_balance:Number(account?.opening_balance||0),is_active:account?.is_active??true}),[e,setE]=useState('');async function save(){try{await api('/accounts'+(account?'/'+account.id:''),{method:account?'PATCH':'POST',body:JSON.stringify(f)});done()}catch(x){setE(x.message)}}return <Modal title={account?'Настройка счёта':'Новый финансовый счёт'} close={close} error={e}><label>Название<input value={f.name} onChange={x=>setF({...f,name:x.target.value})} placeholder="Например, Касса Орджоникидзе"/></label><label>Тип<select value={f.type} onChange={x=>setF({...f,type:x.target.value})}>{Object.entries(types).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Начальный остаток<input type="number" value={f.opening_balance} onChange={x=>setF({...f,opening_balance:+x.target.value})}/></label>{account&&<button type="button" onClick={()=>setF({...f,is_active:!f.is_active})}>{f.is_active?<><PowerOff/>Отключить счёт</>:<><Power/>Включить счёт</>}</button>}<Actions close={close} save={save}/></Modal>}
function Modal({title,close,error,children}){return <div className="whOverlay"><div className="whModal small"><div className="whModalHead"><h2>{title}</h2><button onClick={close}><X/></button></div>{error&&<div className="whError">{error}</div>}<div className="whForm">{children}</div></div></div>}function Actions({close,save}){return <div className="whButtons"><button onClick={close}>Отмена</button><button className="whPrimary" onClick={save}>Сохранить</button></div>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
