import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Plus,X,RefreshCw,ArrowRightLeft,WalletCards,MoreHorizontal} from 'lucide-react';
import {financeApi,financeMoney as money,financeDate,financeUser,accountTypes,operationNames} from './finance-client.js';
import {AccountForm,MoneyForm} from './finance-forms.jsx';
import './finance.css';

function useSession(){
  const [user,setUser]=useState(financeUser);
  useEffect(()=>{const update=()=>{const next=financeUser();setUser(old=>old?.id===next?.id&&old?.role===next?.role?old:next);};window.addEventListener('profi24:core-ui-ready',update);window.addEventListener('storage',update);return()=>{window.removeEventListener('profi24:core-ui-ready',update);window.removeEventListener('storage',update);};},[]);
  return user;
}
function App(){
  const user=useSession(),owner=user?.role==='OWNER';
  const [open,setOpen]=useState(false),[tab,setTab]=useState('accounts'),[month,setMonth]=useState(financeDate().slice(0,7)),[accountFilter,setAccountFilter]=useState(''),[page,setPage]=useState(1),[version,setVersion]=useState(0);
  const [accounts,setAccounts]=useState([]),[users,setUsers]=useState([]),[ledger,setLedger]=useState(null),[pnl,setPnl]=useState(null),[audit,setAudit]=useState([]),[auditBefore,setAuditBefore]=useState(''),[modal,setModal]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const reload=()=>setVersion(v=>v+1),done=()=>{setModal(null);reload();};
  useEffect(()=>{let registered=false;const register=()=>{if(registered||!window.Profi24UI)return;registered=true;window.Profi24UI.registerNav({id:'finance',label:'Финансы',group:'finance',roles:['OWNER','MANAGER','ENGINEER'],onClick:()=>{setOpen(true);reload();}});};register();window.addEventListener('profi24:core-ui-ready',register);return()=>{window.removeEventListener('profi24:core-ui-ready',register);};},[]);
  useEffect(()=>{setOpen(false);setAccounts([]);setLedger(null);setPnl(null);setUsers([]);setAudit([]);setModal(null);setAccountFilter('');setTab('accounts');},[user?.id,user?.role]);
  useEffect(()=>{setPage(1);setAuditBefore('');},[month,accountFilter,tab]);
  useEffect(()=>{
    if(!open||!user)return;
    const controller=new AbortController(),opts={signal:controller.signal};let current=true;
    setBusy(true);setError('');
    const suffix='?month='+month+(accountFilter?'&account_id='+accountFilter:'')+'&page='+page+(tab==='transfers'?'&transfers=true':'');
    Promise.all([financeApi('/accounts',opts),owner?financeApi('/responsibles',opts):Promise.resolve([]),financeApi('/transactions'+suffix,opts),owner?financeApi('/pnl?month='+month,opts):Promise.resolve(null),owner&&tab==='audit'?financeApi('/audit?'+(accountFilter?'account_id='+accountFilter+'&':'')+(auditBefore?'before='+auditBefore:''),opts):Promise.resolve([])])
      .then(([a,u,l,p,h])=>{if(current){setAccounts(a);setUsers(u);setLedger(l);setPnl(p);setAudit(h);}})
      .catch(e=>{if(current&&e.name!=='AbortError')setError(e.message);}).finally(()=>{if(current)setBusy(false);});
    return()=>{current=false;controller.abort();};
  },[open,user?.id,user?.role,month,accountFilter,page,tab,version,auditBefore]);
  useEffect(()=>{if(!open)return;window.addEventListener('profi24:request-updated',reload);return()=>window.removeEventListener('profi24:request-updated',reload);},[open]);
  if(!open||!user)return null;
  const total=accounts.reduce((sum,a)=>sum+Number(a.balance),0);
  const tabs=[['accounts','Денежные счета'],['movements',owner?'Движение денег':'Мои движения'],...(owner?[['transfers','Переводы'],['pnl','P&L'],['audit','Аудит']]:[])];
  const viewAccount=a=>{setAccountFilter(String(a.id));setTab('movements');};
  return <section className="finScreen" aria-busy={busy}>
    <header className="finTop"><div><h1>Финансы</h1><p>{owner?'Денежные счета и документированные операции':'Счета, за которые вы отвечаете'}</p></div><div className="finActions"><button onClick={reload} disabled={busy} aria-label="Обновить"><RefreshCw size={18}/></button><button onClick={()=>setOpen(false)} aria-label="Закрыть финансы"><X size={20}/></button></div></header>
    <nav className="finTabs" aria-label="Разделы финансов">{tabs.map(([value,label])=><button key={value} aria-current={tab===value?'page':undefined} onClick={()=>setTab(value)}>{label}</button>)}</nav>
    {error&&<p className="finError" role="alert">{error} <button onClick={reload}>Повторить</button></p>}
    {busy&&!ledger?<p className="finEmpty">Загрузка финансовых данных…</p>:<><div className="finSummary"><div><small>{owner?'Всего денег на счетах':'На моих счетах'}</small><strong>{money(total)}</strong></div><p>Остаток рассчитан по всем проведённым движениям, включая начальные остатки. Не зависит от выбранного месяца.</p></div>
    {tab==='accounts'&&<><div className="finSectionHead"><h2>Денежные счета</h2>{owner&&<div className="finActions"><button onClick={()=>setModal({mode:'transfer'})} disabled={accounts.filter(a=>a.is_active).length<2}><ArrowRightLeft size={17}/>Перевести</button><button className="finPrimary" onClick={()=>setModal({mode:'account'})}><Plus size={17}/>Создать счёт</button></div>}</div>
      <div className="finAccounts">{accounts.map(a=><article key={a.id} className={'finAccount '+(!a.is_active?'finInactive':'')}><header><WalletCards size={20}/><span>{accountTypes[a.type]||a.type}</span>{owner&&<details className="finMenu"><summary aria-label={'Действия: '+a.name}><MoreHorizontal size={20}/></summary><div><button onClick={()=>setModal({mode:'account',account:a})}>Редактировать</button><button onClick={()=>viewAccount(a)}>Движения</button><button disabled={!a.is_active} onClick={()=>setModal({mode:'adjustment',account:a})}>Корректировка</button><button disabled={!a.is_active} onClick={()=>setModal({mode:'transfer',account:a})}>Перевести</button></div></details>}</header><button className="finAccountName" onClick={()=>viewAccount(a)}>{a.name}</button><strong className={Number(a.balance)<0?'finNegative':''}>{money(a.balance)}</strong><p>Ответственный: {a.responsible_name||'OWNER'}</p>{a.comment&&<p className="finHint">{a.comment}</p>}<footer><span>{a.is_active?'Активен':'Отключён'}</span><button onClick={()=>viewAccount(a)}>{a.operations_count} операций</button></footer></article>)}</div>
      {!accounts.length&&<p className="finEmpty">{owner?'Создайте первый денежный счёт.':'Нет закреплённых счетов. Обратитесь к OWNER для назначения корпоративной карты или подотчёта.'}</p>}
    </>}
    {['movements','transfers'].includes(tab)&&<><div className="finSectionHead"><h2>{tab==='transfers'?'Переводы между счетами':'Журнал движения денег'}</h2>{owner&&<button className="finPrimary" onClick={()=>setModal({mode:tab==='transfers'?'transfer':'operation'})}><Plus size={17}/>{tab==='transfers'?'Перевод':'Операция'}</button>}</div><div className="finFilters"><label>Месяц<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Счёт<select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">Все доступные счета</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div>
    {tab==='movements'&&ledger?.summary&&<div className="finPeriod">{[['opening','На начало периода'],['income','Поступления'],['expense','Списания'],['closing','На конец периода']].map(([k,label])=><div key={k}><small>{label}</small><b>{money(ledger.summary[k])}</b></div>)}</div>}
    <div className="finTableWrap"><table><thead><tr><th>Дата / №</th><th>Операция</th><th>Счёт / сотрудник</th><th>Приход / расход</th><th>Остаток после проведения</th><th>Основание / заказ</th>{owner&&<th>Действие</th>}</tr></thead><tbody>{ledger?.rows.map(row=><tr key={row.id}><td>{String(row.occurred_at).slice(0,10)}<small>№{row.id}</small></td><td>{operationNames[row.kind]||row.kind}<small>{row.category}</small>{row.transfer_group_id&&<small>Перевод {row.transfer_group_id.slice(0,8)}</small>}{row.reversed_by&&<span className="finBadge">Сторно №{row.reversed_by}</span>}{row.reversal_of&&<small>К операции №{row.reversal_of}</small>}</td><td>{row.account_name}<small>{row.responsible_name||row.created_by_name||'Исторический импорт'}</small></td><td className={row.type==='EXPENSE'?'finNegative':'finPositive'}>{row.type==='EXPENSE'?'−':'+'}{money(row.amount)}</td><td>{money(row.balance_after)}</td><td>{row.comment||'Историческая запись'}<small>{[row.document_reference,row.request_number].filter(Boolean).join(' · ')}</small></td>{owner&&<td>{!row.reversed_by&&!['PAYMENT','REFUND','REVERSAL','PART_PURCHASE'].includes(row.kind)&&<button onClick={()=>setModal({mode:'reverse',entry:row})}>Сторно</button>}</td>}</tr>)}</tbody></table>{!ledger?.rows.length&&<p className="finEmpty">За этот период операций нет</p>}</div>
    <div className="finPager"><button disabled={page<=1||busy} onClick={()=>setPage(p=>p-1)}>Назад</button><span>Страница {page}</span><button disabled={!ledger?.has_more||busy} onClick={()=>setPage(p=>p+1)}>Далее</button></div></>}
    {tab==='pnl'&&owner&&<><div className="finFilters"><label>Месяц<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>{pnl&&!pnl.payroll_available&&<p className="finError">Расчёт зарплаты недоступен: чистая прибыль не показана, чтобы не занизить расходы.</p>}<div className="finPeriod">{[['revenue','Выручка'],['direct_cost','Себестоимость'],['gross_profit','Валовая прибыль'],['payroll','ФОТ'],['operating_expenses','Дополнительные расходы'],['net_profit','Чистая прибыль']].map(([k,label])=><div key={k}><small>{label}</small><b>{pnl?.[k]==null?'—':money(pnl[k])}</b></div>)}</div><p className="finHint">Переводы, подотчёт, начальные остатки и корректировки не формируют прибыль. Покупка детали списывает деньги один раз; её себестоимость учитывается в заказе.</p>{pnl?.expense_categories.map(c=><div className="finCategory" key={c.category}><span>{c.category}</span><b>{money(c.amount)}</b></div>)}</>}
    {tab==='audit'&&owner&&<><div className="finFilters"><label>Счёт<select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">Все счета</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><p className="finHint">Кто, когда и что изменил. Проведённые записи нельзя редактировать или удалять.</p><div className="finAudit">{audit.map(a=><details key={a.id}><summary><b>{a.action==='ACCOUNT_CREATED'?'Создан счёт':a.action==='ACCOUNT_UPDATED'?'Изменены настройки счёта':a.action==='LEGACY_IMPORTED'?'Импорт старой операции':'Проведена операция'} · {a.account_name}</b><span>{a.actor_name} · {new Date(a.created_at).toLocaleString('ru-RU')} · №{a.id}</span></summary><pre>{JSON.stringify(a.details,null,2)}</pre></details>)}</div>{!audit.length&&<p className="finEmpty">Записей нет</p>}<div className="finPager"><button disabled={!auditBefore} onClick={()=>setAuditBefore('')}>Сначала</button><button disabled={audit.length<100} onClick={()=>setAuditBefore(audit.at(-1).id)}>Более ранние</button></div></>}
    </>}
    {modal?.mode==='account'&&<AccountForm account={modal.account} users={users} close={()=>setModal(null)} done={done}/>}
    {modal&&modal.mode!=='account'&&<MoneyForm {...modal} accounts={accounts} close={()=>setModal(null)} done={done}/>}
  </section>;
}
const root=document.createElement('div');root.dataset.profi24Panel='finance';document.body.appendChild(root);createRoot(root).render(<App/>);
