import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{BookOpen,Search,Plus,X,Edit3,CheckCircle2,Archive,History,ThumbsUp,ThumbsDown,Wrench,ShieldAlert,Tag,RefreshCw}from'lucide-react';
import'./knowledge-base.css';
const A='/knowledge-api/v1',tok=()=>localStorage.token;
async function api(path,opt={}){for(let attempt=0;attempt<4;attempt++){const r=await fetch(A+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${tok()}`,...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(r.status===429&&attempt<3){await new Promise(x=>setTimeout(x,1100));continue}if(!r.ok)throw new Error(j.error?.message||'Ошибка базы знаний');return j.data}}
const currentUser=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}},statusLabel={DRAFT:'Черновик',PUBLISHED:'Опубликовано',ARCHIVED:'Архив'},blank={title:'',category:'',brand:'',model:'',error_code:'',tags:'',symptoms:'',cause:'',solution:'',verification:'',safety_notes:''};
function App(){const u=currentUser(),P=window.Profi24RBAC?.P||{},view=Boolean(P.KNOWLEDGE_VIEW&&window.Profi24RBAC?.can?.(P.KNOWLEDGE_VIEW,u?.role)),manage=Boolean(P.KNOWLEDGE_MANAGE&&window.Profi24RBAC?.can?.(P.KNOWLEDGE_MANAGE,u?.role));const[open,setOpen]=useState(false),[items,setItems]=useState([]),[detail,setDetail]=useState(null),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[editor,setEditor]=useState(null),[versions,setVersions]=useState(null),[requestId,setRequestId]=useState(null);
 async function load(){if(!view)return;try{setBusy(true);setErr('');const qs=new URLSearchParams();if(search.trim())qs.set('search',search.trim());if(manage&&status)qs.set('status',status);setItems(await api('/articles'+(qs.toString()?'?'+qs:''))||[])}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function openArticle(id,ctxRequest=null){try{setBusy(true);setErr('');setOpen(true);setRequestId(ctxRequest||null);setVersions(null);setDetail(await api('/articles/'+id))}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open&&view)load()},[open,view,status]);useEffect(()=>{if(!view)return;const reg=()=>window.Profi24UI?.registerNav({id:'knowledge-base',label:'База знаний',group:'operations',permission:P.KNOWLEDGE_VIEW,onClick:()=>{setRequestId(null);setOpen(true)}});reg();window.addEventListener('profi24:core-ui-ready',reg);const onArticle=e=>openArticle(e.detail?.id,e.detail?.requestId);window.addEventListener('profi24:open-knowledge-article',onArticle);return()=>{window.removeEventListener('profi24:core-ui-ready',reg);window.removeEventListener('profi24:open-knowledge-article',onArticle);window.Profi24UI?.removeNav?.('knowledge-base')}},[view,u?.id,u?.role]);
 async function save(form){try{setBusy(true);const id=form.id;const body={};for(const k of Object.keys(blank))body[k]=form[k]||'';const x=await api(id?'/articles/'+id:'/articles',{method:id?'PATCH':'POST',body:JSON.stringify(body)});setEditor(null);await load();await openArticle(x.id,requestId)}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function act(kind){if(!detail)return;try{setBusy(true);const x=await api(`/articles/${detail.id}/${kind}`,{method:'POST',body:'{}'});setDetail(x);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function loadVersions(){try{setVersions(await api(`/articles/${detail.id}/versions`))}catch(e){setErr(e.message)}}
 async function vote(helpful){if(!requestId)return;try{const x=await api(`/articles/${detail.id}/feedback`,{method:'POST',body:JSON.stringify({request_id:Number(requestId),helpful})});setDetail(x)}catch(e){setErr(e.message)}}
 if(!view||!open)return null;const metrics=useMemo(()=>({published:items.filter(x=>x.status==='PUBLISHED').length,drafts:items.filter(x=>x.status==='DRAFT').length,helpful:items.reduce((a,x)=>a+Number(x.helpful_count||0),0),applied:items.reduce((a,x)=>a+Number(x.applied_count||0),0)}),[items]);return <div className="kbScreen"><header className="kbTop"><div><h1><BookOpen/> База знаний</h1><p>Проверенные решения по технике, ошибкам и симптомам — прямо внутри ремонта</p></div><div className="kbTopActions"><button onClick={load} disabled={busy}><RefreshCw size={16}/>Обновить</button>{manage&&<button className="primary" onClick={()=>setEditor({...blank})}><Plus size={16}/>Новая статья</button>}<button onClick={()=>setOpen(false)}><X size={20}/></button></div></header>{err&&<div className="kbError">{err}</div>}<section className="kbMetrics"><Metric t="Опубликовано" v={metrics.published}/>{manage&&<Metric t="Черновики" v={metrics.drafts}/>}<Metric t="Помогло" v={metrics.helpful}/><Metric t="Применено к заказам" v={metrics.applied}/></section><div className="kbToolbar"><div className="kbSearch"><Search size={18}/><input placeholder="Бренд, модель, код ошибки, симптом, решение…" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button onClick={load}>Найти</button></div>{manage&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все статусы</option><option value="PUBLISHED">Опубликованные</option><option value="DRAFT">Черновики</option><option value="ARCHIVED">Архив</option></select>}</div><main className="kbLayout"><section className="kbList">{items.map(x=><button key={x.id} className={'kbCard '+(detail?.id===x.id?'on':'')} onClick={()=>openArticle(x.id,requestId)}><div className="kbCardHead"><b>{x.title}</b><span className={'kbStatus '+x.status}>{statusLabel[x.status]||x.status}</span></div><small>{[x.category,x.brand,x.model,x.error_code&&'Ошибка '+x.error_code].filter(Boolean).join(' · ')||'Общая статья'}</small><p>{x.symptoms||x.solution}</p><footer><span><ThumbsUp size={13}/>{x.helpful_count||0}</span><span><Wrench size={13}/>{x.applied_count||0}</span><span>v{x.version}</span></footer></button>)}{!items.length&&<div className="kbEmpty">Ничего не найдено</div>}</section><section className="kbDetail">{detail?<Article detail={detail} manage={manage} requestId={requestId} edit={()=>setEditor({...detail})} publish={()=>act('publish')} archive={()=>act('archive')} versions={versions} loadVersions={loadVersions} vote={vote}/>:<div className="kbEmpty big"><BookOpen size={40}/><b>Выберите статью</b><span>Или найдите решение по коду ошибки, модели и симптому.</span></div>}</section></main>{editor&&<Editor data={editor} busy={busy} close={()=>setEditor(null)} save={save}/>}</div>}
function Metric({t,v}){return <div><small>{t}</small><b>{v}</b></div>}
function Article({detail,manage,requestId,edit,publish,archive,versions,loadVersions,vote}){return <><div className="kbDetailHead"><div><h2>{detail.title}</h2><p>{[detail.category,detail.brand,detail.model].filter(Boolean).join(' · ')||'Общее решение'}{detail.error_code?' · ошибка '+detail.error_code:''}</p></div><span className={'kbStatus '+detail.status}>{statusLabel[detail.status]}</span></div>{detail.tags&&<div className="kbTags"><Tag size={15}/>{detail.tags}</div>}<Section title="Симптомы" text={detail.symptoms}/><Section title="Причина / диагноз" text={detail.cause}/><Section title="Решение" text={detail.solution} strong/><Section title="Как проверить результат" text={detail.verification}/>{detail.safety_notes&&<div className="kbSafety"><ShieldAlert size={18}/><div><b>Безопасность</b><p>{detail.safety_notes}</p></div></div>}<div className="kbMeta">Версия {detail.version} · обновил {detail.updated_by_name} · полезно {detail.helpful_count||0}/{Number(detail.helpful_count||0)+Number(detail.not_helpful_count||0)||0} · применено {detail.applied_count||0}</div>{requestId&&detail.status==='PUBLISHED'&&<div className="kbVote"><span>Это решение помогло в текущем заказе?</span><button onClick={()=>vote(true)}><ThumbsUp size={16}/>Да</button><button onClick={()=>vote(false)}><ThumbsDown size={16}/>Нет</button></div>}{manage&&<div className="kbManage"><button onClick={edit}><Edit3 size={16}/>Редактировать</button>{detail.status!=='PUBLISHED'&&<button className="primary" onClick={publish}><CheckCircle2 size={16}/>Опубликовать</button>}{detail.status!=='ARCHIVED'&&<button onClick={archive}><Archive size={16}/>В архив</button>}<button onClick={loadVersions}><History size={16}/>Версии</button></div>}{versions&&<div className="kbVersions"><h3>История версий</h3>{versions.map(v=><div key={v.id}><b>v{v.version} · {v.snapshot?.status}</b><span>{v.changed_by_name} · {new Date(v.created_at).toLocaleString('ru-RU')}</span></div>)}</div>}</>}
function Section({title,text,strong}){if(!text)return null;return <section className={'kbSection '+(strong?'strong':'')}><h3>{title}</h3><p>{text}</p></section>}
function Editor({data,busy,close,save}){const[f,setF]=useState(data);return <div className="kbOverlay"><form className="kbModal" onSubmit={e=>{e.preventDefault();save(f)}}><header><div><small>{f.id?'РЕДАКТИРОВАНИЕ':'НОВАЯ СТАТЬЯ'}</small><h2>{f.id?f.title:'Новое техническое решение'}</h2></div><button type="button" onClick={close}><X/></button></header><div className="kbForm"><label className="wide">Название *<input required value={f.title||''} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Категория<input value={f.category||''} onChange={e=>setF({...f,category:e.target.value})} placeholder="Холодильник"/></label><label>Бренд<input value={f.brand||''} onChange={e=>setF({...f,brand:e.target.value})} placeholder="Samsung"/></label><label>Модель<input value={f.model||''} onChange={e=>setF({...f,model:e.target.value})}/></label><label>Код ошибки<input value={f.error_code||''} onChange={e=>setF({...f,error_code:e.target.value})} placeholder="5C1"/></label><label className="wide">Теги<input value={f.tags||''} onChange={e=>setF({...f,tags:e.target.value})} placeholder="слив, насос, ошибка воды"/></label><label className="wide">Симптомы<textarea value={f.symptoms||''} onChange={e=>setF({...f,symptoms:e.target.value})}/></label><label className="wide">Причина / диагноз<textarea value={f.cause||''} onChange={e=>setF({...f,cause:e.target.value})}/></label><label className="wide">Проверенное решение *<textarea required value={f.solution||''} onChange={e=>setF({...f,solution:e.target.value})}/></label><label className="wide">Как проверить результат<textarea value={f.verification||''} onChange={e=>setF({...f,verification:e.target.value})}/></label><label className="wide">Безопасность<textarea value={f.safety_notes||''} onChange={e=>setF({...f,safety_notes:e.target.value})}/></label></div><footer><button type="button" onClick={close}>Отмена</button><button className="primary" disabled={busy}>Сохранить</button></footer></form></div>}
const root=document.createElement('div');root.id='knowledge-base-addon-root';document.body.appendChild(root);createRoot(root).render(<App/>);
