import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{RefreshCw,TrendingUp,Coins,Save,Calculator,CheckCircle2,History,X}from'lucide-react';
import'./kpi.css';
const A='/kpi-api/v1',tok=()=>localStorage.token,m=v=>Number(v||0).toLocaleString('ru-KZ',{maximumFractionDigits:2})+' ₸',monthNow=()=>new Date().toISOString().slice(0,7);
const user=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}},P=()=>window.Profi24RBAC?.P||{},can=p=>Boolean(p&&window.Profi24RBAC?.can?.(p));
async function api(p,o={}){const r=await fetch(A+p,{...o,headers:{'Content-Type':'application/json',Authorization:`Bearer ${tok()}`,...(o.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error?.message||'Ошибка');return j.data}
async function branchApi(){const r=await fetch('/branch-api/v1/branches',{headers:{Authorization:`Bearer ${tok()}`}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error?.message||'Ошибка филиалов');return j.data||[]}
const roleName=r=>window.Profi24RBAC?.ROLE_LABELS?.[r]||r;
function App(){const u=user(),all=can(P().KPI_VIEW_ALL),self=can(P().KPI_VIEW_SELF),manage=can(P().KPI_MANAGE),owner=u?.role==='OWNER';const[open,setOpen]=useState(false),[month,setMonth]=useState(monthNow()),[branchId,setBranchId]=useState(''),[branches,setBranches]=useState([]),[d,setD]=useState({rows:[]}),[results,setResults]=useState([]),[tab,setTab]=useState('report'),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 async function load(){if(!open||(!all&&!self))return;setBusy(true);setErr('');try{let bid=branchId;if(all&&!branches.length){const b=await branchApi();setBranches(b);if(!bid&&b[0]){bid=String(b[0].id);setBranchId(bid)}}if(all&&!bid)return;const suffix=`?month=${month}${all&&bid?'&branch_id='+bid:''}`;const[r,s]=await Promise.all([api('/report'+suffix),api('/results'+suffix)]);setD(r||{rows:[]});setResults(s||[])}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open)load()},[open,month,branchId,all,self]);
 useEffect(()=>{if(!all&&!self)return;let off=null;const reg=()=>{if(off||!window.Profi24UI)return;const permission=all?P().KPI_VIEW_ALL:P().KPI_VIEW_SELF;off=window.Profi24UI.registerNav({id:'kpi',label:all?'KPI команды':'Мои KPI',group:'team',permission,onClick:()=>setOpen(true)})};reg();window.addEventListener('profi24:core-ui-ready',reg);return()=>{window.removeEventListener('profi24:core-ui-ready',reg);off?.()}},[all,self,u?.id]);
 async function save(){try{setBusy(true);await api('/plans/'+edit.id,{method:'PUT',body:JSON.stringify({...edit,month})});setEdit(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function calculate(){try{setBusy(true);await api('/results/calculate',{method:'POST',body:JSON.stringify({branch_id:Number(branchId),month})});setTab('results');await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function approve(id){try{setBusy(true);await api('/results/'+id+'/approve',{method:'POST',body:'{}'});await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 function close(){setOpen(false);window.Profi24UI?.showBase?.()}
 if(!open||(!all&&!self))return null;return <div className="kpi"><header><div><h1>{all?'KPI команды':'Мои KPI'}</h1><p>{all?'План → факт → зафиксированный результат → премия в зарплату':'Ваш план, факт, прогноз и утверждённый результат'}</p></div><div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>{all&&<select value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={load}><RefreshCw className={busy?'spin':''}/></button><button onClick={close}><X/></button></div></header>{err&&<div className="kpiError">{err}</div>}{all&&<div className="kpiTabs"><button className={tab==='report'?'on':''} onClick={()=>setTab('report')}>Текущий KPI</button><button className={tab==='results'?'on':''} onClick={()=>setTab('results')}><History size={16}/>Ревизии</button>{manage&&<button onClick={calculate}><Calculator size={16}/>Зафиксировать расчёт</button>}</div>}{tab==='report'?<Cards rows={d?.rows||[]} manage={manage} setEdit={setEdit}/>:<ResultList rows={results} owner={owner} approve={approve}/>} {edit&&<PlanModal edit={edit} setEdit={setEdit} save={save}/>}</div>}
function Cards({rows,manage,setEdit}){return <section className="kpiGrid">{rows.length?rows.map(x=><article key={x.id}><div className="kpiTop"><div><h3>{x.name}</h3><small>{roleName(x.role)} · {x.plan_id?'план установлен':'план не установлен'}</small></div><strong className={x.score>=100?'ok':x.score>=80?'warn':'low'}>{x.score}%</strong></div><div className="progress"><i style={{width:Math.min(100,x.score)+'%'}}/></div><div className="kpiNums"><span><b>{x.closed} / {x.target_jobs||'—'}</b>закрыто</span><span><b>{m(x.revenue)} / {x.target_revenue?m(x.target_revenue):'—'}</b>выручка</span><span><b>{m(x.avg_check)}</b>средний чек</span><span><b>{Math.round(x.conversion)}%</b>конверсия</span><span><b>{Math.round(x.sla)}%</b>SLA</span><span><b>{Math.round(x.quality)}%</b>качество</span></div><div className="forecast"><TrendingUp/><span>Прогноз <b>{m(x.forecast_revenue)}</b></span><Coins/><span>Расчётная премия <b>{m(x.bonus)}</b></span></div>{manage&&<button className="setup" onClick={()=>setEdit({...x})}>Настроить план</button>}</article>):<div className="kpiEmpty">Нет сотрудников или доступных KPI за выбранный период.</div>}</section>}
function ResultList({rows,owner,approve}){return <section className="kpiGrid">{rows.length?rows.map(x=><article key={x.id}><div className="kpiTop"><div><h3>{x.name}</h3><small>{roleName(x.role)} · ревизия №{x.revision}</small></div><strong className={x.status==='APPROVED'?'ok':'warn'}>{x.status==='APPROVED'?'Утверждён':'Черновик'}</strong></div><div className="kpiNums"><span><b>{Number(x.score)}%</b>итоговый балл</span><span><b>{m(x.bonus_amount)}</b>премия</span><span><b>{x.metrics?.closed??'—'}</b>закрыто</span><span><b>{m(x.metrics?.revenue)}</b>выручка</span><span><b>{Math.round(Number(x.metrics?.sla||0))}%</b>SLA</span><span><b>{Math.round(Number(x.metrics?.quality||0))}%</b>качество</span></div>{owner&&x.status==='DRAFT'&&<button className="setup" onClick={()=>approve(x.id)}><CheckCircle2 size={16}/>Утвердить результат</button>}</article>):<div className="kpiEmpty">Снимков KPI ещё нет. Управляющий или собственник может зафиксировать расчёт.</div>}</section>}
function PlanModal({edit,setEdit,save}){return <div className="modal"><div><h2>План: {edit.name}</h2><small>{roleName(edit.role)}. После утверждения KPI план этого месяца изменять нельзя.</small>{[['target_jobs','Закрытых заявок'],['target_revenue','Выручка, ₸'],['target_avg_check','Средний чек, ₸'],['target_conversion','Конверсия, %'],['target_sla','SLA, %'],['target_quality','Качество, %'],['bonus_max','Максимальная премия, ₸']].map(([k,l])=><label key={k}>{l}<input type="number" min="0" value={edit[k]||''} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<button onClick={save}><Save/>Сохранить план</button><button className="cancel" onClick={()=>setEdit(null)}>Отмена</button></div></div>}
const host=document.createElement('div');document.body.appendChild(host);createRoot(host).render(<App/>);