const token=()=>localStorage.token;
const P=()=>window.Profi24RBAC?.P;
const allowed=()=>Boolean(P()&&window.Profi24RBAC?.can(P().OPERATIONS_MANAGE));
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const fmt=v=>v?new Date(v).toLocaleString('ru-RU'):'—';
const holdLabels={WAITING_CUSTOMER:'Клиент',WAITING_APPROVAL:'Согласование',WAITING_PART:'Запчасть',REPEAT_VISIT:'Повторный визит',EXTERNAL_SERVICE:'Внешний сервис',WAITING_DELIVERY:'Доставка',OTHER:'Другое'};
let open=false,loading=false;
async function api(){const r=await fetch('/lifecycle-api/v1/lifecycle/exceptions',{headers:{Authorization:`Bearer ${token()}`}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Не удалось загрузить исключения');return j.data}
function root(){let r=document.querySelector('[data-lifecycle-center]');if(!r){r=el('section','lifeCenter');r.dataset.lifecycleCenter='1';document.body.appendChild(r)}return r}
function close(){open=false;root().hidden=true}
function orderButton(number){const b=el('button','lifeCenterOrder',number);b.type='button';b.onclick=()=>window.dispatchEvent(new CustomEvent('profi24:open-order360',{detail:{number}}));return b}
function render(data){const r=root();r.replaceChildren();const top=el('header','lifeCenterTop');const title=el('div');title.append(el('h1','','Контроль жизненного цикла'),el('p','','Ожидания, повторные визиты и просроченные исключения'));const x=el('button','lifeCenterClose','×');x.type='button';x.onclick=close;top.append(title,x);r.appendChild(top);
 const s=data.summary||{};const cards=el('div','lifeCenterCards');[['active_holds','Активные ожидания'],['overdue_holds','Просроченные ожидания'],['scheduled_visits','Запланированные визиты'],['overdue_visits','Просроченные визиты']].forEach(([k,l])=>{const c=el('div','lifeCenterCard');c.append(el('b','',String(s[k]||0)),el('span','',l));cards.appendChild(c)});r.appendChild(cards);
 const section=(titleText,rows,kind)=>{const sec=el('section','lifeCenterSection');sec.append(el('h2','',titleText));if(!rows?.length){sec.append(el('p','lifeMuted','Нет записей, требующих внимания.'));return sec}const table=el('div','lifeCenterTable');for(const row of rows){const item=el('div','lifeCenterRow');const main=el('div');main.append(orderButton(row.number),el('strong','',row.customer_name||''));const details=kind==='hold'?`${holdLabels[row.hold_type]||row.hold_type} · ${row.reason||''}`:`Визит №${row.attempt_no} · ${row.engineer_name||'инженер не назначен'}`;main.append(el('small','',details));const when=kind==='hold'?row.expected_until:row.scheduled_at;const badge=el('span',when&&new Date(when)<new Date()?'lifeCenterOverdue':'lifeCenterDue',when?fmt(when):'без срока');item.append(main,badge);table.appendChild(item)}sec.appendChild(table);return sec};
 r.append(section('Ожидания',data.holds,'hold'),section('Повторные визиты',data.visits,'visit'));r.hidden=false}
async function load(){if(!open||loading||!allowed())return;loading=true;const r=root();r.hidden=false;r.replaceChildren(el('p','lifeMuted','Загрузка…'));try{render(await api())}catch(e){r.replaceChildren(el('div','lifeError',e.message))}finally{loading=false}}
function register(){if(!allowed()||!window.Profi24UI)return;window.Profi24UI.registerNav({id:'lifecycle-center',label:'Контроль заказов',group:'operations',permission:P().OPERATIONS_MANAGE,onClick:()=>{open=true;load()}})}
window.addEventListener('profi24:core-ui-ready',register);window.addEventListener('profi24:rbac-ready',register);window.addEventListener('profi24:request-updated',()=>{if(open)load()});setTimeout(register,100);
