import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Bell,AlertTriangle,Clock3,UserRound,CalendarClock,RefreshCw,X,CheckCheck,Volume2,VolumeX,TimerReset,History}from'lucide-react';
import'./notifications.css';

const BASE='/notifications-api/v1',token=()=>localStorage.token;
async function api(p,o={}){const r=await fetch(BASE+p,{...o,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(o.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
const ago=v=>{if(!v)return'';const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<1)return'только что';if(m<60)return`${m} мин назад`;const h=Math.floor(m/60);if(h<24)return`${h} ч назад`;return`${Math.floor(h/24)} дн назад`};
const getUser=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}};

function App(){const[open,setOpen]=useState(false),[items,setItems]=useState([]),[history,setHistory]=useState([]),[tab,setTab]=useState('active'),[err,setErr]=useState(''),[sound,setSound]=useState(localStorage.getItem('profi24_notifications_browser')==='1');const user=getUser();
 async function load(silent=false){if(!token())return;try{if(!silent)setErr('');const data=await api('/notifications');setItems(data||[])}catch(e){if(!silent)setErr(e.message)}}
 async function loadHistory(){try{setErr('');setHistory(await api('/notifications/history')||[])}catch(e){setErr(e.message)}}
 useEffect(()=>{if(!token())return;load();const id=setInterval(()=>load(true),60000);return()=>clearInterval(id)},[]);
 const unread=useMemo(()=>items.filter(x=>!x.user_read_at),[items]);
 useEffect(()=>{if(!sound||!unread.length||typeof Notification==='undefined'||Notification.permission!=='granted')return;const n=unread[0],last=localStorage.getItem('profi24_notification_last_popup');if(last===String(n.id))return;new Notification(n.title,{body:`${n.subtitle||''}. ${n.detail||''}`,tag:String(n.id)});localStorage.setItem('profi24_notification_last_popup',String(n.id))},[unread.length,sound]);
 useEffect(()=>{if(!user||!window.Profi24UI)return;return window.Profi24UI.registerNav({id:'notifications',label:'Уведомления',group:'clients',badge:unread.length?unread.length>99?'99+':unread.length:null,onClick:()=>setOpen(true)})},[user]);
 useEffect(()=>{window.Profi24UI?.updateNav('notifications',{badge:unread.length?unread.length>99?'99+':unread.length:null})},[unread.length]);
 async function mark(id){try{await api(`/notifications/${id}/read`,{method:'POST'});setItems(x=>x.map(n=>n.id===id?{...n,user_read_at:new Date().toISOString()}:n));setHistory(x=>x.map(n=>n.id===id?{...n,user_read_at:new Date().toISOString()}:n))}catch(e){setErr(e.message)}}
 async function markAll(){try{await api('/notifications/read-all',{method:'POST'});const t=new Date().toISOString();setItems(x=>x.map(n=>({...n,user_read_at:t}))}catch(e){setErr(e.message)}}
 async function toggleBrowser(){if(typeof Notification==='undefined'){setErr('Браузер не поддерживает системные уведомления');return}if(!sound){const p=await Notification.requestPermission();if(p!=='granted'){setErr('Разрешение на уведомления не выдано');return}localStorage.setItem('profi24_notifications_browser','1');setSound(true)}else{localStorage.setItem('profi24_notifications_browser','0');setSound(false)}}
 function switchTab(v){setTab(v);if(v==='history')loadHistory()}
 if(!open)return null;const list=tab==='active'?items:history;return <div className="notifyShade" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><aside className="notifyPanel"><header><div><h2><Bell size={21}/> Центр уведомлений</h2><p>Серверный журнал событий CRM</p></div><button onClick={()=>setOpen(false)}><X/></button></header><div className="notifyTools"><button onClick={()=>tab==='active'?load():loadHistory()}><RefreshCw size={16}/>Обновить</button><button onClick={markAll} disabled={!unread.length||tab!=='active'}><CheckCheck size={16}/>Все прочитано</button><button onClick={toggleBrowser}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}Браузер</button></div><div className="notifyTools"><button className={tab==='active'?'on':''} onClick={()=>switchTab('active')}><Bell size={16}/>Активные</button><button className={tab==='history'?'on':''} onClick={()=>switchTab('history')}><History size={16}/>История</button></div>{err&&<div className="notifyError">{err}</div>}<div className="notifySummary"><span><b>{unread.length}</b> новых</span><span><b>{items.filter(x=>x.severity==='critical').length}</b> критичных</span><span><b>{list.length}</b> {tab==='active'?'активных':'в журнале'}</span></div><div className="notifyList">{list.length?list.map(n=><NotificationCard key={n.id} n={n} unread={!n.user_read_at} onRead={()=>mark(n.id)}/>):<div className="notifyEmpty"><CheckCheck size={34}/><b>{tab==='active'?'Всё под контролем':'Журнал пока пуст'}</b><span>{tab==='active'?'Сейчас нет событий, требующих внимания.':'История уведомлений появится после первых событий.'}</span></div>}</div><footer><TimerReset size={15}/> PostgreSQL · автообновление каждые 60 секунд</footer></aside></div>}
function NotificationCard({n,unread,onRead}){const Icon=n.type?.includes('SLA')?TimerReset:n.type?.includes('VISIT')?CalendarClock:n.type==='NOT_ACCEPTED'?UserRound:n.severity==='critical'?AlertTriangle:Clock3;return <article className={`notifyCard ${n.severity} ${unread?'unread':''} ${n.resolved_at?'resolved':''}`}><div className="notifyIcon"><Icon size={18}/></div><div className="notifyBody"><div className="notifyTitle"><b>{n.title}</b>{unread&&<i/>}</div><strong>{n.subtitle}</strong><p>{n.detail}</p><small>{ago(n.created_at)}{n.resolved_at?' · завершено':''}</small></div>{unread&&<button className="notifyRead" onClick={onRead} title="Отметить прочитанным"><CheckCheck size={17}/></button>}</article>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
