import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Gauge,RefreshCw,X,AlertTriangle,UsersRound,Wallet,Clock3,MapPin,Phone,CalendarClock,CheckCircle2,Wrench,Navigation,Search,ShieldAlert,Flame,ListChecks,Coins,Filter}from'lucide-react';import'./operations-center.css';
const A='/operations-api/v1',BR='/branch-api/v1',tok=()=>localStorage.token;
const money=v=>`${Number(v||0).toLocaleString('ru-RU')} ₸`,dt=v=>v?new Date(v).toLocaleString('ru-RU',{timeZone:'Asia/Qostanay',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—',age=v=>{if(v==null)return'—';const m=Math.max(0,Number(v));return m<60?`${m} мин`:`${Math.floor(m/60)} ч ${m%60} мин`};
const stage={NEW:'Новая',ASSIGNED:'Назначена',ACCEPTED:'Принята',ON_ROUTE:'В пути',DIAGNOSTICS:'Диагностика',APPROVAL_REQUIRED:'Согласование',WAITING_PART:'Ждёт деталь',REPAIR:'Ремонт',TESTING:'Проверка',PAYMENT_REQUIRED:'К оплате',CLOSED:'Закрыта'};
const typeLabel={SLA_OVERDUE:'SLA',VISIT_OVERDUE:'Выезд',UNASSIGNED:'Назначение',APPROVAL_STUCK:'Согласование',PART_STUCK:'Запчасть',PAYMENT_STUCK:'Оплата',TASK_OVERDUE:'Задача',RESCHEDULE_REQUIRED:'Перенос',CONFIRMATION_CALL:'Подтверждение',COMPLAINT_OPEN:'Претензия'};
async function fetchJson(url){const r=await fetch(url,{headers:{Authorization:`Bearer ${tok()}`}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error?.message||`Ошибка ${r.status}`);return j.data}
async function loadBranches(){return fetchJson(BR+'/branches')}
async function loadLive(branch){return fetchJson(A+'/operations/live'+(branch?`?branch_id=${encodeURIComponent(branch)}`:''))}
function openOrder(number){if(number)window.dispatchEvent(new CustomEvent('profi24:open-order360',{detail:{number}}))}
function App(){
 const user=(()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}})(),rbac=window.Profi24RBAC,permission=rbac?.P?.OPERATIONS_MANAGE,allowed=Boolean(permission&&rbac.can(permission,user?.role));
 const[open,setOpen]=useState(false),[d,setD]=useState(null),[branches,setBranches]=useState([]),[branch,setBranch]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[severity,setSeverity]=useState('ALL'),[kind,setKind]=useState('ALL');
 async function load(){try{setBusy(true);setErr('');const data=await loadLive(branch);setD(data)}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(!allowed)return;const reg=()=>window.Profi24UI?.registerNav({id:'operations',label:'Центр действий',group:'management',permission,badge:(Number(d?.action_summary?.critical)||0)+(Number(d?.action_summary?.high)||0)||null,onClick:()=>setOpen(true)});if(window.Profi24UI)reg();else window.addEventListener('profi24:core-ui-ready',reg,{once:true});return()=>{window.removeEventListener('profi24:core-ui-ready',reg);window.Profi24UI?.removeNav?.('operations')}},[allowed,permission,user?.id,user?.role]);
 useEffect(()=>{window.Profi24UI?.updateNav?.('operations',{badge:(Number(d?.action_summary?.critical)||0)+(Number(d?.action_summary?.high)||0)||null})},[d?.action_summary?.critical,d?.action_summary?.high]);
 useEffect(()=>{if(!open||!allowed)return;loadBranches().then(rows=>{setBranches(rows||[]);setBranch(v=>v&&(rows||[]).some(x=>String(x.id)===String(v))?v:'')}).catch(()=>{});load();const t=setInterval(load,20000);return()=>clearInterval(t)},[open,allowed]);
 useEffect(()=>{if(open)load()},[branch]);
 const actions=useMemo(()=>{const needle=q.trim().toLowerCase();return(d?.actions||[]).filter(x=>(severity==='ALL'||x.severity===severity)&&(kind==='ALL'||x.type===kind)&&(!needle||[x.number,x.customer_name,x.engineer_name,x.title,x.next_action,x.detail].join(' ').toLowerCase().includes(needle)))},[d,q,severity,kind]);
 const eng=useMemo(()=>!d?[]:d.engineers.filter(x=>[x.name,x.number,x.customer_name,x.address].join(' ').toLowerCase().includes(q.toLowerCase())),[d,q]);
 if(!allowed||!open)return null;const m=d?.metrics||{},s=d?.action_summary||{};
 return <div className="opscc"><header><div><h1><Gauge/>Центр действий</h1><p>Приоритетная очередь руководителя · автообновление 20 сек</p></div><div className="opsccActions">{branches.length>1&&<select aria-label="Филиал центра действий" value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Все доступные филиалы</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<button onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''} size={17}/>Обновить</button><button onClick={()=>setOpen(false)}><X/></button></div></header>{err&&<div className="opsccErr">{err}</div>}{d&&<><section className="opsccMetrics"><Metric icon={Flame} t="Критично" v={s.critical||0} bad/><Metric icon={AlertTriangle} t="Высокий приоритет" v={s.high||0} bad={Number(s.high)>0}/><Metric icon={Coins} t="Оплата под риском" v={money(s.payment_at_risk)} bad={Number(s.payment_at_risk)>0}/><Metric icon={UsersRound} t="Активные заявки" v={m.active}/><Metric icon={Wallet} t="Касса сегодня" v={money(m.cash_today)} good/><Metric icon={CheckCircle2} t="Закрыто сегодня" v={m.closed_today} good/></section>
 <section className="opsccPanel actionCenter"><div className="opsccPanelHead"><div><h2><ListChecks/>Что требует действия</h2><span>{actions.length} из {s.total||0} · сортировка по риску</span></div><div className="opsccActionFilters"><div className="opsccSearch"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Заявка, клиент, инженер"/></div><label><Filter size={14}/><select aria-label="Приоритет действий" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="ALL">Все приоритеты</option><option value="CRITICAL">Критично</option><option value="HIGH">Высокий</option><option value="MEDIUM">Средний</option></select></label><select aria-label="Тип действия" value={kind} onChange={e=>setKind(e.target.value)}><option value="ALL">Все причины</option>{Object.entries(typeLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><div className="opsActionList">{actions.map(x=><Action key={x.action_id} x={x}/>) }{!actions.length&&<div className="opsccEmpty"><CheckCircle2/><b>По выбранному фильтру действий нет</b><span>Очередь пересчитывается автоматически из фактического состояния CRM.</span></div>}</div></section>
 <div className="opsccGrid"><section className="opsccPanel engineers"><div className="opsccPanelHead"><div><h2>Инженеры сейчас</h2><span>{d.engineers.length} сотрудников в выбранном контуре</span></div></div><div className="engineerGrid">{eng.map(x=><Engineer key={x.id} x={x}/>)}</div></section><section className="opsccPanel opsSummary"><div className="opsccPanelHead"><div><h2>Контроль сервиса</h2><span>Фактические показатели</span></div></div><SummaryRow t="Просрочен SLA" v={m.sla_overdue}/><SummaryRow t="Без инженера" v={m.unassigned}/><SummaryRow t="Ждут запчасть" v={m.waiting_parts}/><SummaryRow t="Ждут согласование" v={m.pending_approvals}/><SummaryRow t="Открытые претензии" v={m.complaints_open}/><SummaryRow t="Дебиторка" v={money(m.receivable)}/></section></div>
 <section className="opsccPanel day"><div className="opsccPanelHead"><div><h2>Расписание сегодня</h2><span>Все назначенные выезды выбранного филиала</span></div><b>{new Date(d.generated_at).toLocaleTimeString('ru-RU',{timeZone:'Asia/Qostanay',hour:'2-digit',minute:'2-digit'})}</b></div><div className="dayline">{d.timeline.map(x=><button className="visit" key={x.id} onClick={()=>openOrder(x.number)}><time>{dt(x.scheduled_at).slice(-5)}</time><i className={x.live_stage}/><div><b>{x.number} · {x.customer_name}</b><span>{x.engineer_name||'Инженер не назначен'} · {x.address||'Адрес не указан'}</span></div><small>{stage[x.live_stage]||x.live_stage}</small></button>)}</div></section></>}</div>
}
function Metric({icon:I,t,v,bad,good}){return <article className={(bad?'bad ':'')+(good?'good':'')}><I size={19}/><div><small>{t}</small><b>{v??0}</b></div></article>}
function SummaryRow({t,v}){return <div className="opsSummaryRow"><span>{t}</span><b>{v??0}</b></div>}
function Action({x}){return <article className={'opsAction '+String(x.severity||'MEDIUM').toLowerCase()} data-action-type={x.type}><div className="opsActionScore"><b>{x.score}</b><small>{x.severity==='CRITICAL'?'КРИТИЧНО':x.severity==='HIGH'?'ВЫСОКИЙ':'СРЕДНИЙ'}</small></div><div className="opsActionMain"><div><span className="opsType">{typeLabel[x.type]||x.type}</span>{x.branch_name&&<span>{x.branch_name}</span>}{x.number&&<button onClick={()=>openOrder(x.number)}>{x.number}</button>}</div><h3>{x.title}</h3><b>{x.customer_name||x.task_title||'Операционная задача'}</b><p>{x.next_action}</p>{x.detail&&<small>{x.detail}</small>}</div><div className="opsActionMeta"><span>{x.engineer_name||x.manager_name||'Ответственный не указан'}</span><b>{x.outstanding_amount>0?money(x.outstanding_amount):age(x.age_minutes)}</b>{x.due_at&&<small>{dt(x.due_at)}</small>}{x.phone&&<a href={'tel:'+x.phone}><Phone size={14}/>Позвонить</a>}</div></article>}
function Engineer({x}){const free=!x.request_id;const Icon=x.live_stage==='ON_ROUTE'?Navigation:['DIAGNOSTICS','REPAIR','TESTING'].includes(x.live_stage)?Wrench:Clock3;return <article className={'engineerCard '+(free?'free':x.live_stage||'busy')}><div className="engTop"><div className="avatar">{x.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</div><div><b>{x.name}</b><span>{free?'Свободен':stage[x.live_stage]||x.live_stage}</span></div><Icon size={18}/></div>{free?<div className="freeText">Нет активной заявки</div>:<><button className="engOrder" onClick={()=>openOrder(x.number)}><strong>{x.number}</strong><span>{x.customer_name}</span><small>{x.complaint}</small></button><div className="engMeta"><span><Clock3 size={13}/>В статусе {x.updated_at?age(Math.floor((Date.now()-new Date(x.updated_at))/60000)):'—'}</span>{x.address&&<span><MapPin size={13}/>{x.address}</span>}</div><div className="engBtns"><a href={'tel:'+x.phone}><Phone size={14}/>Позвонить</a></div></>}<footer><span>Назначено сегодня <b>{x.assigned_today}</b></span><span>Закрыто <b>{x.closed_today}</b></span>{x.next_visit&&<span>Следующий <b>{dt(x.next_visit).slice(-5)}</b></span>}</footer></article>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
