// Order 360 presentation sanity. Never inserts/removes React-owned children.
(function(){
  function moneyNum(text){const n=String(text||'').replace(/[^\d,.-]/g,'').replace(',','.');return Number(n||0)||0}
  function currentTotal(){const hero=document.querySelector('.o360Hero');if(!hero)return 0;const amount=hero.querySelector(':scope > div:last-child > b');return moneyNum(amount?.textContent)}
  function fixZeroState(){const hero=document.querySelector('.o360Hero');if(!hero)return;const total=currentTotal(),right=hero.lastElementChild,sub=right?.querySelector('small');if(sub){if(total<=0){sub.textContent='Стоимость не сформирована';sub.dataset.zeroState='1'}else if(sub.dataset.zeroState==='1'){delete sub.dataset.zeroState}}
    document.querySelectorAll('.o360PrimaryAction').forEach(b=>{b.style.display=total<=0?'none':'';b.setAttribute('aria-hidden',total<=0?'true':'false')});
    const finance=[...document.querySelectorAll('.o360Card')].find(c=>c.querySelector('header b')?.textContent.trim()==='Финансы');if(finance&&total<=0){const rows=[...finance.querySelectorAll('.o360Row')];rows.find(r=>r.querySelector('span')?.textContent.trim()==='Оплачено')?.setAttribute('title','Оплата ещё не требуется: стоимость заказа не сформирована');rows.find(r=>r.querySelector('span')?.textContent.trim()==='Долг')?.setAttribute('title','Долг появится после формирования стоимости заказа')}}
  function mount(){if(document.querySelector('.o360'))fixZeroState()}
  let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(mount,60)}).observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener('profi24:o360-current',()=>setTimeout(mount,20));window.addEventListener('profi24:request-updated',()=>setTimeout(mount,40));setInterval(mount,2000);setTimeout(mount,300);
})();