// PROFI24 direct order attachments: desktop files + smartphone camera.
(function(){
const B='/documents-api/v1';
const token=()=>localStorage.getItem('token')||'';
const role=()=>{try{return JSON.parse(localStorage.getItem('user')||'null')?.role||''}catch{return''}};
let orderCache={number:'',id:null},loading=false,objectUrls=[];
const kindLabels={DEFECT_PHOTO:'Фото дефекта',NAMEPLATE:'Фото шильдика',PHOTO_AFTER:'Фото после ремонта',RECEIPT:'Чек / накладная',OTHER:'Прочее'};
function txt(e){return(e?.textContent||'').replace(/\s+/g,' ').trim()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function styles(){if(document.getElementById('orderFilesStyle'))return;const s=document.createElement('style');s.id='orderFilesStyle';s.textContent=`
.orderFilesCard{background:#fff;border:1px solid #e2e8f0;border-radius:10px;margin-bottom:16px;overflow:hidden}.orderFilesHead{padding:14px 16px;border-bottom:1px solid #e8edf3;display:flex;align-items:center;justify-content:space-between;gap:12px}.orderFilesHead h3{margin:0;font-size:16px}.orderFilesHead small{color:#667085}.orderFilesBody{padding:16px}.orderFilesActions{display:grid;grid-template-columns:minmax(160px,220px) auto auto;gap:10px;align-items:end;margin-bottom:14px}.orderFilesActions label{font-size:12px;font-weight:700;color:#667085;display:flex;flex-direction:column;gap:5px}.orderFilesActions select{border:1px solid #ccd5e0;border-radius:8px;padding:9px;background:#fff}.orderFilesBtn{border:1px solid #cbd5e1;background:#fff;border-radius:8px;padding:9px 12px;cursor:pointer;font-weight:700;display:inline-flex;gap:7px;align-items:center;justify-content:center;min-height:40px}.orderFilesBtn.primary{background:#ffb800;border-color:#ffb800;color:#172033}.orderFilesBtn.danger{color:#b42318;border-color:#f0b4b4}.orderFilesGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:10px}.orderFileItem{border:1px solid #e2e8f0;border-radius:9px;padding:10px;display:flex;gap:10px;min-width:0;background:#fff}.orderFileThumb{width:58px;height:58px;border-radius:7px;background:#f1f5f9;display:flex;align-items:center;justify-content:center;overflow:hidden;flex:0 0 auto;font-size:24px}.orderFileThumb img{width:100%;height:100%;object-fit:cover}.orderFileMeta{min-width:0;flex:1}.orderFileMeta b{display:block;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.orderFileMeta small{display:block;color:#667085;margin-top:3px}.orderFileBtns{display:flex;gap:5px;margin-top:7px}.orderFileBtns button{border:1px solid #d0d7e2;background:#fff;border-radius:6px;padding:5px 7px;cursor:pointer;font-size:12px}.orderFilesEmpty{padding:14px;background:#f8fafc;border-radius:8px;color:#667085;text-align:center}.orderFilesError{padding:9px 11px;background:#fff1f1;color:#b42318;border:1px solid #fecaca;border-radius:8px;margin-bottom:10px}.orderFilesBusy{opacity:.65;pointer-events:none}@media(max-width:700px){.orderFilesActions{grid-template-columns:1fr 1fr}.orderFilesActions label{grid-column:1/-1}.orderFilesBtn{width:100%}.orderFilesGrid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
async function api(path,opt={}){const r=await fetch(B+path,{...opt,headers:{Authorization:`Bearer ${token()}`,...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.error?.message||`Ошибка ${r.status}`);return j.data}
function currentNumber(){const main=document.querySelector('main');if(!main)return'';for(const e of main.querySelectorAll('h1,h2,h3,b,strong')){const m=txt(e).match(/KST-\d{4}-\d+/i);if(m)return m[0]}return''}
function docsActive(){const b=[...document.querySelectorAll('main .ordertabs button,main .orderTabs button')].find(x=>/Документы/i.test(txt(x)));return !!b&&b.classList.contains('on')}
async function orderId(number){if(orderCache.number===number&&orderCache.id)return orderCache.id;const r=await fetch('/api/v1/requests',{headers:{Authorization:`Bearer ${token()}`}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||'Не удалось определить заказ');const x=(j.data||[]).find(v=>v.number===number);if(!x)throw new Error('Заказ не найден');orderCache={number,id:x.id};return x.id}
function revoke(){objectUrls.forEach(u=>URL.revokeObjectURL(u));objectUrls=[]}
async function openFile(id){const r=await fetch(`${B}/files/${id}`,{headers:{Authorization:`Bearer ${token()}`}});if(!r.ok){let j={};try{j=await r.json()}catch{}throw new Error(j?.error?.message||'Не удалось открыть файл')}const blob=await r.blob(),u=URL.createObjectURL(blob);objectUrls.push(u);window.open(u,'_blank')}
async function thumb(id,img){try{const r=await fetch(`${B}/files/${id}`,{headers:{Authorization:`Bearer ${token()}`}});if(!r.ok)return;const blob=await r.blob(),u=URL.createObjectURL(blob);objectUrls.push(u);img.src=u}catch{}}
function toData(file){return new Promise((resolve,reject)=>{if(file.size>8*1024*1024){reject(new Error(`Файл ${file.name} больше 8 МБ. Уменьшите размер фото или файла.`));return}const rd=new FileReader();rd.onerror=()=>reject(new Error('Не удалось прочитать файл'));rd.onload=()=>resolve(rd.result);rd.readAsDataURL(file)})}
async function uploadFiles(id,files,kind,card){if(!files?.length)return;card.classList.add('orderFilesBusy');const error=card.querySelector('[data-error]');error.hidden=true;try{for(const f of files){const data=await toData(f);await api(`/requests/${id}/files`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name||`photo-${Date.now()}.jpg`,kind,data})})}await render(card,id)}catch(e){error.textContent=e.message;error.hidden=false}finally{card.classList.remove('orderFilesBusy')}}
async function render(card,id){revoke();const error=card.querySelector('[data-error]');try{const files=await api(`/requests/${id}/files`);const grid=card.querySelector('[data-grid]');if(!files.length){grid.innerHTML='<div class="orderFilesEmpty">Вложений пока нет. Добавьте фото дефекта, шильдика или документ.</div>';return}grid.innerHTML=files.map(f=>`<div class="orderFileItem"><div class="orderFileThumb">${String(f.mime_type||'').startsWith('image/')?`<img data-thumb="${f.id}" alt="">`:'📄'}</div><div class="orderFileMeta"><b title="${esc(f.original_name)}">${esc(f.original_name)}</b><small>${esc(kindLabels[f.kind]||f.kind||'Прочее')} · ${Math.max(1,Math.round(Number(f.size_bytes||0)/1024))} КБ</small><small>${esc(f.uploaded_by_name||'')} · ${new Date(f.created_at).toLocaleString('ru-RU')}</small><div class="orderFileBtns"><button data-open="${f.id}">Открыть</button>${String(role()).toUpperCase()!=='ENGINEER'?`<button data-del="${f.id}">Удалить</button>`:''}</div></div></div>`).join('');grid.querySelectorAll('[data-thumb]').forEach(img=>thumb(img.dataset.thumb,img));grid.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openFile(b.dataset.open).catch(e=>{error.textContent=e.message;error.hidden=false}));grid.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Удалить этот файл из заказа?'))return;try{await api('/files/'+b.dataset.del,{method:'DELETE'});await render(card,id)}catch(e){error.textContent=e.message;error.hidden=false}})}catch(e){error.textContent=e.message;error.hidden=false}}
async function mount(){if(!docsActive()){document.querySelectorAll('.orderFilesCard').forEach(x=>x.remove());return}const number=currentNumber(),host=document.querySelector('main .maincol,main .orderMain');if(!number||!host||host.querySelector('.orderFilesCard')||loading)return;loading=true;try{const id=await orderId(number);if(!docsActive())return;const card=document.createElement('section');card.className='orderFilesCard';card.innerHTML=`<div class="orderFilesHead"><div><h3>Фото и файлы заказа</h3><small>Фото дефекта, шильдика, документы и чеки</small></div><small>до 8 МБ на файл</small></div><div class="orderFilesBody"><div class="orderFilesError" data-error hidden></div><div class="orderFilesActions"><label>Тип вложения<select data-kind><option value="DEFECT_PHOTO">Фото дефекта</option><option value="NAMEPLATE">Фото шильдика</option><option value="PHOTO_AFTER">Фото после ремонта</option><option value="RECEIPT">Чек / накладная</option><option value="OTHER">Прочее</option></select></label><button class="orderFilesBtn primary" data-camera>📷 Сфотографировать</button><button class="orderFilesBtn" data-file>⬆ Выбрать файл / фото</button><input data-camera-input hidden type="file" accept="image/*" capture="environment"><input data-file-input hidden type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt"></div><div class="orderFilesGrid" data-grid><div class="orderFilesEmpty">Загрузка...</div></div></div>`;host.prepend(card);const cam=card.querySelector('[data-camera-input]'),file=card.querySelector('[data-file-input]'),kind=card.querySelector('[data-kind]');card.querySelector('[data-camera]').onclick=()=>cam.click();card.querySelector('[data-file]').onclick=()=>file.click();cam.onchange=()=>{uploadFiles(id,[...cam.files],kind.value,card);cam.value=''};file.onchange=()=>{uploadFiles(id,[...file.files],kind.value,card);file.value=''};await render(card,id)}catch(e){console.warn('Order files:',e)}finally{loading=false}}
styles();let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(mount,180)}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});setTimeout(mount,700);
})();
