const token=()=>localStorage.token;
const P=()=>window.Profi24RBAC?.P;
const canManage=()=>Boolean(P()&&window.Profi24RBAC?.can(P().OPERATIONS_MANAGE));
const roleLabel=r=>window.Profi24RBAC?.ROLE_LABELS?.[r]||r||'';
async function api(path,options={}){const r=await fetch('/directory-api'+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
async function core(path){const r=await fetch('/api'+path,{headers:{Authorization:`Bearer ${token()}`}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
const el=(tag,cls,text)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x};
let currentId=null,loading=false,lastUsers=[];
function root(){return document.querySelector('.o360')}
function host(){const r=root();if(!r)return null;let h=r.querySelector('.o360Team');if(!h){h=el('section','o360Team');h.dataset.rbacTeam='1';r.appendChild(h)}return h}
function errorBox(h,msg){let e=h.querySelector('.o360TeamError');if(!e){e=el('div','o360TeamError');h.appendChild(e)}e.textContent=msg||'';e.hidden=!msg}
async function mutate(id,path,options){try{await api(path,options);window.dispatchEvent(new CustomEvent('profi24:request-updated',{detail:{id:Number(id)}}));await load(id,true)}catch(e){const h=host();if(h)errorBox(h,e.message)}}
function render(id,data,users=[]){const h=host();if(!h)return;h.replaceChildren();const head=el('div','o360TeamHead');head.appendChild(el('h3','', 'Команда заказа'));const hint=el('small','',canManage()?'Основной инженер + участники':'Участники заказа');head.appendChild(hint);h.appendChild(head);
 const primary=el('div','o360TeamPrimary');primary.appendChild(el('b','', 'Основной инженер:'));primary.appendChild(el('span','',data?.primary_engineer?.name||'не назначен'));h.appendChild(primary);
 const list=el('div','o360TeamList');for(const m of data?.participants||[]){const row=el('div','o360TeamMember');const info=el('div');info.appendChild(el('b','',m.name));info.appendChild(el('small','',roleLabel(m.participant_role)+(m.mentor_name?` · наставник ${m.mentor_name}`:'')));row.appendChild(info);if(canManage()){const del=el('button','', 'Удалить');del.type='button';del.addEventListener('click',()=>mutate(id,`/v1/requests/${id}/participants/${m.user_id}`,{method:'DELETE'}));row.appendChild(del)}list.appendChild(row)}if(!(data?.participants||[]).length)list.appendChild(el('div','mentorEmpty','Дополнительных участников нет.'));h.appendChild(list);
 if(canManage()){const existing=new Set((data?.participants||[]).map(x=>Number(x.user_id)));if(data?.primary_engineer?.id)existing.add(Number(data.primary_engineer.id));const candidates=(users||[]).filter(u=>u.active!==false&&['ENGINEER','TRAINEE'].includes(u.role)&&!existing.has(Number(u.id)));const add=el('div','o360TeamAdd');const select=el('select');select.appendChild(new Option('Добавить инженера или стажёра',''));for(const u of candidates)select.appendChild(new Option(`${u.name} — ${roleLabel(u.role)}`,String(u.id)));const btn=el('button','', 'Добавить');btn.type='button';btn.disabled=true;select.addEventListener('change',()=>btn.disabled=!select.value);btn.addEventListener('click',()=>{if(select.value)mutate(id,`/v1/requests/${id}/participants`,{method:'POST',body:JSON.stringify({user_id:Number(select.value)})})});add.append(select,btn);h.appendChild(add)}errorBox(h,'')}
async function load(id=currentId,force=false){id=Number(id||window.Profi24O360State?.id||0);if(!id||loading||!root())return;if(!force&&id===currentId&&host()?.dataset.loaded==='1')return;currentId=id;loading=true;try{const data=await api(`/v1/requests/${id}/participants`);if(canManage()&&!lastUsers.length)lastUsers=await core('/v1/users');render(id,data,lastUsers);const h=host();if(h)h.dataset.loaded='1'}catch(e){const h=host();if(h){h.replaceChildren(el('div','o360TeamError',e.message));h.dataset.loaded='1'}}finally{loading=false}}
function refresh(id){const h=host();if(h)h.dataset.loaded='0';setTimeout(()=>load(id||currentId,true),30)}
window.addEventListener('profi24:o360-current',e=>{currentId=Number(e.detail?.id||0);lastUsers=[];refresh(currentId)});
window.addEventListener('profi24:request-updated',e=>{if(!e.detail?.id||Number(e.detail.id)===Number(currentId))refresh(currentId)});
window.addEventListener('profi24:rbac-ready',()=>refresh(currentId));
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if(root())load(window.Profi24O360State?.id||currentId)},80)}).observe(document.body,{childList:true,subtree:true});
