// Order-linked employee tasks inside Order 360.
(function(){
 const tok=()=>localStorage.token||'';const me=()=>{try{return JSON.parse(localStorage.user||'null')||{}}catch{return{}}};
 const api=async(path,opt={})=>{const h={Authorization:`Bearer ${tok()}`};if(opt.body!=null)h['Content-Type']='application/json';const r=await fetch(path,{...opt,headers:{...h,...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j?.error?.message||`Ошибка ${r.status}`);return j.data};
 const rid=()=>Number(document.querySelector('.o360List button.on')?.dataset?.id||0),num=()=>document.querySelector('.o360Hero small')?.textContent?.trim()||'';
 const fmt=d=>d?new Date(d).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Без срока';
 const pri={LOW:'Низкий',NORMAL:'Обычный',HIGH:'Высокий',URGENT:'Срочный'},st={OPEN:'Новая',IN_PROGRESS:'В работе',DONE:'Выполнена',CANCELLED:'Отменена'};
 let cache=[],users=[];function close(){document.querySelector('.otShade')?.remove()}
 async function ensureUsers(){if(users.length)return users;users=await api('/api/v1/users').catch(()=>[]);return users}
 async function createModal(){const id=rid();if(!id)return;await ensureUsers();const u=me(),canAssign=['OWNER','MANAGER'].includes(u.role),people=canAssign?users:[u];const sh=document.createElement('div');sh.className='otShade';sh.innerHTML=`<div class="otModal"><header><div><h2>Новая задача по заказу</h2><p>${num()}</p></div><button data-close>×</button></header><div class="otTemplates"><button data-t="Выставить счёт">Выставить счёт</button><button data-t="Связаться с клиентом">Связаться с клиентом</button><button data-t="Заказать запчасть">Заказать запчасть</button><button data-t="Назначить повторный выезд">Повторный выезд</button><button data-t="Проверить оплату">Проверить оплату</button></div><div class="otForm"><label class="wide">Задача *<input name="title" placeholder="Что нужно сделать"></label><label class="wide">Описание<textarea name="description" placeholder="Детали и ожидаемый результат"></textarea></label><label>Ответственный<select name="assigned_to">${people.map(x=>`<option value="${x.id}">${x.name} · ${x.role}</option>`).join('')}</select></label><label>Приоритет<select name="priority"><option value="NORMAL">Обычный</option><option value="HIGH">Высокий</option><option value="URGENT">Срочный</option><option value="LOW">Низкий</option></select></label><label class="wide">Срок выполнения<input name="due_at" type="datetime-local"></label><div class="otErr"></div></div><footer><button data-close>Отмена</button><button class="save" data-save>Поставить задачу</button></footer></div>`;document.body.appendChild(sh);sh.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);sh.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{sh.querySelector('[name=title]').value=b.dataset.t});sh.onclick=e=>{if(e.target===sh)close()};sh.querySelector('[data-save]').onclick=async e=>{const b=e.currentTarget,er=sh.querySelector('.otErr'),v=n=>sh.querySelector(`[name=${n}]`)?.value||'';try{b.disabled=true;const due=v('due_at');await api(`/order-tasks-api/v1/request/${id}`,{method:'POST',body:JSON.stringify({title:v('title').trim(),description:v('description').trim()||null,assigned_to:Number(v('assigned_to')),priority:v('priority'),due_at:due?new Date(due).toISOString():null})});close();await render();window.dispatchEvent(new CustomEvent('profi24:request-updated',{detail:{id}}))}catch(x){er.textContent=x.message;b.disabled=false}}}
 function finishModal(t){const sh=document.createElement('div');sh.className='otShade';sh.innerHTML=`<div class="otModal small"><header><div><h2>Завершить задачу</h2><p>${t.title}</p></div><button data-close>×</button></header><div class="otForm"><label class="wide">Результат выполнения *<textarea name="result" placeholder="Что сделано"></textarea></label><div class="otErr"></div></div><footer><button data-close>Отмена</button><button class="save" data-save>Выполнено</button></footer></div>`;document.body.appendChild(sh);sh.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);sh.querySelector('[data-save]').onclick=async e=>{const er=sh.querySelector('.otErr'),res=sh.querySelector('[name=result]').value.trim();try{e.currentTarget.disabled=true;await api(`/order-tasks-api/v1/tasks/${t.id}`,{method:'PATCH',body:JSON.stringify({status:'DONE',result:res})});close();await render();window.dispatchEvent(new CustomEvent('profi24:request-updated',{detail:{id:rid()}}))}catch(x){er.textContent=x.message;e.currentTarget.disabled=false}}}
 async function change(t,status){try{await api(`/order-tasks-api/v1/tasks/${t.id}`,{method:'PATCH',body:JSON.stringify({status})});await render()}catch(e){alert(e.message)}}
 async function render(){const id=rid(),root=document.querySelector('.o360');if(!id||!root)return;const left=root.querySelector('.o360Cols>div:first-child');if(!left)return;let card=left.querySelector('.otCard');if(!card){card=document.createElement('section');card.className='o360Card otCard';card.innerHTML=`<header><span class="otIcon">✓</span><b>Задачи по заказу</b><button type="button" class="otAdd">+ Задача</button></header><div class="otBody"><div class="otLoading">Загрузка…</div></div>`;left.appendChild(card);card.querySelector('.otAdd').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();createModal()},{capture:true})}const body=card.querySelector('.otBody');try{cache=await api(`/order-tasks-api/v1/request/${id}`);if(!cache.length){body.innerHTML='<div class="otEmpty">По этому заказу задач нет</div>';return}body.innerHTML=cache.map(t=>`<div class="otRow ${t.overdue?'overdue':''} ${t.status==='DONE'?'done':''}" data-task="${t.id}"><div class="otMain"><b>${t.title}</b><span>${t.description||''}</span><small>${t.assigned_name} · ${fmt(t.due_at)}${t.overdue?' · ПРОСРОЧЕНО':''}</small>${t.result?`<em>Результат: ${t.result}</em>`:''}</div><span class="otPriority ${t.priority}">${pri[t.priority]||t.priority}</span><span class="otStatus ${t.status}">${st[t.status]||t.status}</span><div class="otActions">${t.status==='OPEN'?'<button data-start>Начать</button>':''}${!['DONE','CANCELLED'].includes(t.status)?'<button class="primary" data-done>Выполнить</button>':''}</div></div>`).join('');body.querySelectorAll('.otRow').forEach(el=>{const t=cache.find(x=>String(x.id)===el.dataset.task);el.querySelector('[data-start]')?.addEventListener('click',()=>change(t,'IN_PROGRESS'));el.querySelector('[data-done]')?.addEventListener('click',()=>finishModal(t))})}catch(e){body.innerHTML=`<div class="otError">${e.message}</div>`}}
 let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(()=>{if(document.querySelector('.o360'))render()},150)}).observe(document.body,{childList:true,subtree:true});window.addEventListener('profi24:request-updated',()=>setTimeout(render,80));setInterval(()=>{if(document.querySelector('.o360')&&!document.hidden)render()},20000);setTimeout(render,400);
})();