// Order 360 catalog integration: pricebook works + warehouse parts with cost visibility.
(function(){
  const token=()=>localStorage.token||'';
  const role=()=>{try{return JSON.parse(localStorage.user||'null')?.role||''}catch{return''}};
  const headers=(body)=>({Authorization:`Bearer ${token()}`,...(body!=null?{'Content-Type':'application/json'}:{})});
  async function req(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers(opt.body),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.error?.message||`Ошибка ${r.status}`);return j.data}
  const money=v=>Number(v||0).toLocaleString('ru-RU')+' ₸';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const currentBtn=()=>document.querySelector('.o360List button.on');
  const requestId=()=>Number(currentBtn()?.dataset?.id||0);
  const requestNumber=()=>currentBtn()?.querySelector('b')?.textContent?.trim()||document.querySelector('.o360Hero small')?.textContent?.trim()||'';
  function refresh(){const id=requestId();if(id)window.dispatchEvent(new CustomEvent('profi24:open-order360',{detail:{id}}));setTimeout(mount,350)}
  function close(){document.querySelector('.o360CatalogShade')?.remove()}
  function modal(title,subtitle){close();const sh=document.createElement('div');sh.className='o360CatalogShade';sh.innerHTML=`<div class="o360CatalogModal"><header><div><h2>${esc(title)}</h2><p>${esc(subtitle||'')}</p></div><button data-close>×</button></header><div class="o360CatalogSearch"><input data-search placeholder="Начните вводить название, код, SKU или OEM"><button data-find>Найти</button></div><div class="o360CatalogBody"><div class="o360CatalogEmpty">Загрузка...</div></div><div class="o360CatalogError"></div></div>`;document.body.appendChild(sh);sh.querySelector('[data-close]').onclick=close;sh.onclick=e=>{if(e.target===sh)close()};return sh}
  async function openWorks(){const id=requestId();if(!id)return;const sh=modal('Добавить работу из прайса',requestNumber());const input=sh.querySelector('[data-search]'),body=sh.querySelector('.o360CatalogBody'),err=sh.querySelector('.o360CatalogError');async function load(){try{err.textContent='';body.innerHTML='<div class="o360CatalogEmpty">Загрузка...</div>';const items=await req('/pricebook-api/v1/items?q='+encodeURIComponent(input.value.trim()));body.innerHTML=(items||[]).length?'':'<div class="o360CatalogEmpty">Работы не найдены</div>';for(const x of items||[]){const cost=Number(x.labor_cost||0)+Number(x.material_cost||0),row=document.createElement('div');row.className='o360CatalogItem';row.innerHTML=`<div class="o360CatalogMain"><small>${esc(x.category||'')}${x.code?' · '+esc(x.code):''}</small><b>${esc(x.name)}</b><span>${esc(x.description||'')}</span></div><div class="o360CatalogNums"><span>Себестоимость <b>${money(cost)}</b></span><span>Базовая цена <b>${money(x.base_price)}</b></span><span>Минимум <b>${money(x.min_price)}</b></span></div><div class="o360CatalogAdd"><input type="number" min="0.01" step="0.01" value="1" data-qty><input type="number" min="0" value="${Number(x.base_price||0)}" data-price><button>Добавить</button></div>`;row.querySelector('button').onclick=async()=>{try{const qty=Number(row.querySelector('[data-qty]').value||1),price=Number(row.querySelector('[data-price]').value||0);await req(`/pricebook-api/v1/requests/${id}/add`,{method:'POST',body:JSON.stringify({item_id:x.id,qty,price})});close();refresh()}catch(e){err.textContent=e.message}};body.appendChild(row)}}catch(e){err.textContent=e.message;body.innerHTML=''}}sh.querySelector('[data-find]').onclick=load;input.onkeydown=e=>{if(e.key==='Enter')load()};load()}
  async function openStock(){const id=requestId();if(!id)return;const sh=modal('Добавить запчасть со склада',requestNumber());const input=sh.querySelector('[data-search]'),body=sh.querySelector('.o360CatalogBody'),err=sh.querySelector('.o360CatalogError');async function load(){try{err.textContent='';body.innerHTML='<div class="o360CatalogEmpty">Загрузка...</div>';const items=await req('/warehouse-api/v1/stock?search='+encodeURIComponent(input.value.trim()));body.innerHTML=(items||[]).length?'':'<div class="o360CatalogEmpty">Запчасти не найдены</div>';for(const x of items||[]){const row=document.createElement('div');row.className='o360CatalogItem';row.innerHTML=`<div class="o360CatalogMain"><small>${[x.sku&&'SKU '+x.sku,x.oem_code&&'OEM '+x.oem_code,x.location&&'Ячейка '+x.location].filter(Boolean).map(esc).join(' · ')||'Без артикула'}</small><b>${esc(x.name)}</b><span>${esc(x.supplier||'Поставщик не указан')}</span></div><div class="o360CatalogNums"><span>Остаток <b>${Number(x.quantity||0).toLocaleString('ru-RU')}</b></span><span>Закупка <b>${money(x.purchase_price)}</b></span><span>Продажа <b>${money(x.sale_price)}</b></span></div><div class="o360CatalogAdd"><input type="number" min="0.01" max="${Number(x.quantity||0)}" step="0.01" value="1" data-qty><input type="number" min="0" value="${Number(x.sale_price||0)}" data-price><button ${Number(x.quantity||0)<=0?'disabled':''}>В заказ</button></div>`;row.querySelector('button').onclick=async()=>{try{const qty=Number(row.querySelector('[data-qty]').value||1),price=Number(row.querySelector('[data-price]').value||0);if(qty<=0)throw new Error('Количество должно быть больше 0');await req(`/api/v1/requests/${id}/parts`,{method:'POST',body:JSON.stringify({name:x.name,oem_code:x.oem_code||'',qty,purchase_price:Number(x.purchase_price||0),sale_price:price,supplier:x.supplier||'',status:'REQUESTED'})});close();refresh()}catch(e){err.textContent=e.message}};body.appendChild(row)}}catch(e){err.textContent=e.message;body.innerHTML=''}}sh.querySelector('[data-find]').onclick=load;input.onkeydown=e=>{if(e.key==='Enter')load()};load()}
  async function decorateCosts(){if(!requestNumber())return;try{const d=await req('/owner-api/v1/orders/'+encodeURIComponent(requestNumber())+'/correction/details');const cards=[...document.querySelectorAll('.o360Card')],wc=cards.find(c=>c.querySelector('header b')?.textContent.trim()==='Работы'),pc=cards.find(c=>c.querySelector('header b')?.textContent.trim()==='Запчасти');for(const [card,items,type] of [[wc,d.works||[],'work'],[pc,d.parts||[],'part']]){if(!card)continue;const rows=[...card.querySelectorAll('.o360Row')];rows.forEach((row,i)=>{const x=items[i];if(!x)return;let m=row.querySelector('.o360CostMeta');if(!m){m=document.createElement('small');m.className='o360CostMeta';row.appendChild(m)}const cost=type==='work'?Number(x.direct_cost||0):Number(x.purchase_price||0);m.textContent=(type==='work'?'Себестоимость: ':'Закупка: ')+money(cost)})}}catch(e){console.warn('Order360 cost labels:',e.message)}}
  function mount(){if(!['OWNER','MANAGER'].includes(role()))return;const cards=[...document.querySelectorAll('.o360Card')],wc=cards.find(c=>c.querySelector('header b')?.textContent.trim()==='Работы'),pc=cards.find(c=>c.querySelector('header b')?.textContent.trim()==='Запчасти');if(wc){const h=wc.querySelector('header');if(h&&!h.querySelector('.o360FromPrice')){const b=document.createElement('button');b.type='button';b.className='o360CatalogBtn o360FromPrice';b.textContent='＋ Из прайса';b.onclick=openWorks;h.appendChild(b)}}if(pc){const h=pc.querySelector('header');if(h&&!h.querySelector('.o360FromStock')){const b=document.createElement('button');b.type='button';b.className='o360CatalogBtn o360FromStock';b.textContent='＋ Со склада';b.onclick=openStock;h.appendChild(b)}}decorateCosts()}
  let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(mount,250)}).observe(document.body,{childList:true,subtree:true});window.addEventListener('profi24:request-updated',()=>setTimeout(mount,300));setInterval(()=>{if(document.querySelector('.o360'))mount()},3000);setTimeout(mount,700);
})();