import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{BadgeDollarSign,RefreshCw,X,Plus,Settings2,Trash2,TrendingUp,Users,BriefcaseBusiness}from'lucide-react';
import'./warehouse.css';
const P='/payroll-api/v1';const token=()=>localStorage.token;
async function c(path,opt={}){const r=await fetch(P+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`}});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
const money=n=>new Intl.NumberFormat('ru-KZ').format(Number(n||0))+' ₸';
const monthNow=()=>new Date().toISOString().slice(0,7);
function App(){const user=(()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}})();const[open,setOpen]=useState(false),[tab,setTab]=useState('report'),[month,setMonth]=useState(monthNow()),[report,setReport]=useState({rows:[],totals:{}}),[rules,setRules]=useState([]),[adj,setAdj]=useState([]),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[modal,setModal]=useState(null);
async function load(){if(!user||user.role!=='OWNER')return;setBusy(true);setErr('');try{const[r,ru,a]=await Promise.all([c('/report?month='+month),c('/rules'),c('/adjustments?month='+month)]);setReport(r||{rows:[],totals:{}});setRules(ru||[]);setAdj(a||[])}catch(e){setErr(e.message)}finally{setBusy(false)}}useEffect(()=>{if(open)load()},[open,month]);
useEffect(()=>{if(user?.role!=='OWNER')return;let off=null;const reg=()=>{if(!off&&window.Profi24UI)off=window.Profi24UI.registerNav({id:'payroll',label:'Зарплаты',group:'team',roles:['OWNER'],onClick:()=>setOpen(true)})};reg();window.addEventListener('profi24:core-ui-ready',reg);return()=>{window.removeEventListener('profi24:core-ui-ready',reg);off?.()}},[user?.id,user?.role]);
if(!user||user.role!=='OWNER'||!open)return null;const rows=report.rows||[];return <div className="warehouseScreen"><div className="whTop"><div><h1>Зарплаты и KPI</h1><p>Начисления сотрудников и экономика закрытых заказов</p></div><div className="whTopActions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={load}><RefreshCw size={18} className={busy?'whSpin':''}/></button><button onClick={()=>setOpen(false)}><X/></button></div></div>{err&&<div className="whError">{err}</div>}<div className="whMetrics"><M label="Фонд зарплаты" value={money(report.totals?.salary)}/><M label="Выручка" value={money(report.totals?.revenue)}/><M label="Валовая прибыль" value={money(report.totals?.gross_profit)}/><M label="Закрытых заказов" value={report.totals?.jobs||0}/></div><div className="whTabs"><button className={tab==='report'?'on':''} onClick={()=>setTab('report')}><TrendingUp/>Расчет</button><button className={tab==='rules'?'on':''} onClick={()=>setTab('rules')}><Settings2/>Правила</button><button className={tab==='adj'?'on':''} onClick={()=>setTab('adj')}><Plus/>Премии и штрафы</button></div>{tab==='report'&&<Report rows={rows}/>} {tab==='rules'&&<Rules rows={rules} done={load}/>} {tab==='adj'&&<Adjustments rows={adj} rules={rules} month={month} open={()=>setModal('add')} done={load}/>} {modal&&<AddAdjustment rules={rules} month={month} close={()=>setModal(null)} done={()=>{setModal(null);load()}}/>}</div>}
function M({label,value}){return <div className="whMetric"><small>{label}</small><b>{value}</b></div>}
function Report({rows}){return <div className="whTable"><div className="whMoveHead"><span>Сотрудник</span><span>Роль</span><span>Заказы</span><span>Выручка / работы</span><span>Начисления</span><span>Итого</span></div>{rows.map(x=><div className="whMoveRow" key={x.id}><div><b>{x.name}</b><small>{x.email}</small></div><span>{x.role}</span><b>{x.jobs}</b><div><b>{money(x.revenue)}</b><small>работы {money(x.work_sales)}</small></div><div><b>{money(Number(x.order_commission)+Number(x.work_commission)+Number(x.gross_profit_commission))}</b><small>корректировки {money(x.adjustments)}</small></div><b>{money(x.salary)}</b></div>)}</div>}
function Rules({rows,done}){const[edit,setEdit]=useState({});async function save(x){const b=edit[x.user_id]||x;await c('/rules/'+x.user_id,{method:'PUT',body:JSON.stringify({base_salary:+b.base_salary||0,order_percent:+b.order_percent||0,work_percent:+b.work_percent||0,gross_profit_percent:+b.gross_profit_percent||0,active:b.rule_active!==false})});done()}return <div className="whTable"><div className="whHead"><span>Сотрудник</span><span>Оклад</span><span>% с заказов</span><span>% с работ</span><span>% валовой прибыли</span></div>{rows.map(x=>{const v=edit[x.user_id]||x;return <div className="whRow" key={x.user_id}><div><b>{x.name}</b><small>{x.role}</small></div><input type="number" value={v.base_salary} onChange={e=>setEdit({...edit,[x.user_id]:{...v,base_salary:e.target.value}})}/><input type="number" step="0.1" value={v.order_percent} onChange={e=>setEdit({...edit,[x.user_id]:{...v,order_percent:e.target.value}})}/><input type="number" step="0.1" value={v.work_percent} onChange={e=>setEdit({...edit,[x.user_id]:{...v,work_percent:e.target.value}})}/><div style={{display:'flex',gap:8}}><input type="number" step="0.1" value={v.gross_profit_percent} onChange={e=>setEdit({...edit,[x.user_id]:{...v,gross_profit_percent:e.target.value}})}/><button onClick={()=>save(x)}>Сохранить</button></div></div>})}</div>}
function Adjustments({rows,rules,month,open,done}){return <><div className="whTop"><div><h2>Премии, штрафы и корректировки</h2><small>{month}</small></div><button className="whPrimary" onClick={open}><Plus size={16}/>Добавить</button></div><div className="whTable">{rows.length?rows.map(x=><div className="whRow" key={x.id}><div><b>{x.user_name}</b><small>{x.reason}</small></div><span>{x.type}</span><b>{money(x.amount)}</b><span>{x.created_by_name||'—'}</span><button onClick={async()=>{await c('/adjustments/'+x.id,{method:'DELETE'});done()}}><Trash2 size={15}/></button></div>):<div className="whEmpty">Корректировок за месяц нет</div>}</div></>}
function AddAdjustment({rules,month,close,done}){const[f,setF]=useState({user_id:'',type:'BONUS',amount:'',reason:'',month}),[e,setE]=useState('');async function save(){try{await c('/adjustments',{method:'POST',body:JSON.stringify(f)});done()}catch(x){setE(x.message)}}return <div className="whOverlay"><div className="whModal small"><div className="whModalHead"><h2>Корректировка зарплаты</h2><button onClick={close}><X/></button></div>{e&&<div className="whError">{e}</div>}<div className="whForm"><label>Сотрудник<select value={f.user_id} onChange={x=>setF({...f,user_id:+x.target.value})}><option value="">Выберите</option>{rules.filter(x=>x.active!==false).map(x=><option key={x.user_id} value={x.user_id}>{x.name} · {x.role}</option>)}</select></label><label>Тип<select value={f.type} onChange={x=>setF({...f,type:x.target.value})}><option value="BONUS">Премия</option><option value="PENALTY">Штраф</option><option value="OTHER">Другое</option></select></label><label>Сумма<input type="number" value={f.amount} onChange={x=>setF({...f,amount:x.target.value})}/></label><label>Причина<textarea value={f.reason} onChange={x=>setF({...f,reason:x.target.value})}/></label><div className="whButtons"><button onClick={close}>Отмена</button><button className="whPrimary" onClick={save}>Сохранить</button></div></div></div></div>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);