import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{RefreshCw,X,Plus,Settings2,TrendingUp,RotateCcw,Calculator,CheckCircle2,WalletCards,LockKeyhole,Users,ReceiptText}from'lucide-react';
import'./warehouse.css';
const BASE='/payroll-api/v1',token=()=>localStorage.token;
const currentUser=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}};
const perm=()=>window.Profi24RBAC?.P||{};
const can=p=>Boolean(p&&window.Profi24RBAC?.can?.(p));
const idem=()=>`payroll-ui-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
async function api(base,path,opt={}){const method=opt.method||'GET',headers={'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(opt.headers||{})};if(!['GET','HEAD'].includes(method)&&!headers['idempotency-key'])headers['idempotency-key']=idem();const r=await fetch(base+path,{...opt,method,headers}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка');return j.data}
const c=(path,opt)=>api(BASE,path,opt),branches=()=>api('/branch-api','/v1/branches'),accounts=()=>api('/finance-api','/v1/accounts');
const money=n=>new Intl.NumberFormat('ru-KZ',{maximumFractionDigits:2}).format(Number(n||0))+' ₸';
const monthNow=()=>new Date().toISOString().slice(0,7);
const roleName=r=>window.Profi24RBAC?.ROLE_LABELS?.[r]||r;
const statusLabel={DRAFT:'Черновик',CALCULATED:'Рассчитан',APPROVED:'Утверждён',PAID:'Выплачен',CLOSED:'Закрыт'};
function modeFor(){const P=perm();if(can(P.PAYROLL_VIEW))return'admin';if(can(P.PAYROLL_SUMMARY_VIEW))return'summary';if(can(P.PAYROLL_SELF_VIEW))return'self';return'none'}

function App(){const user=currentUser(),mode=modeFor(),P=perm();const[open,setOpen]=useState(false),[month,setMonth]=useState(monthNow()),[branchId,setBranchId]=useState(''),[branchRows,setBranches]=useState([]),[report,setReport]=useState({rows:[],totals:{}}),[summary,setSummary]=useState({rows:[],totals:{}}),[self,setSelf]=useState(null),[rules,setRules]=useState([]),[adj,setAdj]=useState([]),[periods,setPeriods]=useState([]),[period,setPeriod]=useState(null),[moneyAccounts,setAccounts]=useState([]),[tab,setTab]=useState('period'),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[modal,setModal]=useState(null);
 const admin=mode==='admin',owner=user?.role==='OWNER',manage=can(P.PAYROLL_MANAGE);
 async function loadPeriod(id){if(!id){setPeriod(null);return}try{setPeriod(await c('/periods/'+id))}catch(e){setErr(e.message)}}
 async function load(){if(!open||mode==='none')return;setBusy(true);setErr('');try{
   if(mode==='summary'){setSummary(await c('/summary?month='+month)||{rows:[],totals:{}});return}
   if(mode==='self'){setSelf(await c('/self?month='+month));return}
   let bid=branchId;
   if(!branchRows.length){const br=(await branches())||[];setBranches(br);if(!bid&&br[0]){bid=String(br[0].id);setBranchId(bid)}}
   if(!bid)return;
   const qs=`month=${month}&branch_id=${bid}`;const[r,ru,a,ps,acc]=await Promise.all([c('/report?'+qs),c('/rules'),c('/adjustments?'+qs),c('/periods?'+qs),accounts()]);setReport(r||{rows:[],totals:{}});setRules(ru||[]);setAdj(a||[]);setPeriods(ps||[]);setAccounts((acc||[]).filter(x=>Number(x.branch_id)===Number(bid)&&x.is_active!==false));const keep=period&&ps?.some(x=>Number(x.id)===Number(period.id))?period.id:ps?.[0]?.id;if(keep)await loadPeriod(keep);else setPeriod(null)
 }catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open)load()},[open,month,branchId,mode]);
 useEffect(()=>{if(mode==='none')return;let off=null;const reg=()=>{if(off||!window.Profi24UI)return;const cfg=mode==='admin'?{label:'Зарплаты',permission:P.PAYROLL_VIEW}:mode==='summary'?{label:'ФОТ',permission:P.PAYROLL_SUMMARY_VIEW}:{label:'Моя зарплата',permission:P.PAYROLL_SELF_VIEW};off=window.Profi24UI.registerNav({id:'payroll',group:'team',...cfg,onClick:()=>setOpen(true)})};reg();window.addEventListener('profi24:core-ui-ready',reg);return()=>{window.removeEventListener('profi24:core-ui-ready',reg);off?.()}},[mode,user?.id]);
 function close(){setOpen(false);window.Profi24UI?.showBase?.()}
 if(mode==='none'||!open)return null;
 return <div className="warehouseScreen"><div className="whTop"><div><h1>{mode==='summary'?'Фонд оплаты труда':mode==='self'?'Моя зарплата':'Зарплаты и начисления'}</h1><p>{mode==='summary'?'Сводка по филиалам без доступа к персональным начислениям':mode==='self'?'Только ваши утверждённые начисления и выплаты':'Версионные правила, расчётные периоды, KPI и реальные выплаты'}</p></div><div className="whTopActions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>{admin&&<select value={branchId} onChange={e=>{setBranchId(e.target.value);setPeriod(null)}}>{branchRows.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={load}><RefreshCw size={18} className={busy?'whSpin':''}/></button><button onClick={close}><X/></button></div></div>{err&&<div className="whError">{err}</div>}
 {mode==='summary'?<Summary data={summary}/>:mode==='self'?<SelfPay row={self}/>:<><div className="whMetrics"><M label="Фонд зарплаты" value={money(report.totals?.salary)}/><M label="KPI-премии" value={money(report.totals?.kpi_bonus)}/><M label="Выручка" value={money(report.totals?.revenue)}/><M label="Валовая прибыль" value={money(report.totals?.gross_profit)}/></div><div className="whTabs"><button className={tab==='period'?'on':''} onClick={()=>setTab('period')}><ReceiptText/>Период</button><button className={tab==='preview'?'on':''} onClick={()=>setTab('preview')}><TrendingUp/>Предпросмотр</button><button className={tab==='rules'?'on':''} onClick={()=>setTab('rules')}><Settings2/>Правила</button><button className={tab==='adj'?'on':''} onClick={()=>setTab('adj')}><Plus/>Корректировки</button></div>
 {tab==='period'&&<Periods month={month} branchId={branchId} periods={periods} period={period} select={loadPeriod} manage={manage} owner={owner} accounts={moneyAccounts} calculate={async()=>{try{setBusy(true);const d=await c('/periods/calculate',{method:'POST',body:JSON.stringify({branch_id:Number(branchId),month})});setPeriod(d);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}} approve={async()=>mutate(()=>c(`/periods/${period.id}/approve`,{method:'POST',body:'{}'}))} closePeriod={async()=>{const reason=prompt('Причина закрытия периода','Зарплата проверена и выплачена');if(reason)await mutate(()=>c(`/periods/${period.id}/close`,{method:'POST',body:JSON.stringify({reason})}))}} pay={x=>setModal({type:'pay',row:x})} reverse={p=>setModal({type:'reversePay',row:p})}/>} 
 {tab==='preview'&&<Report rows={report.rows||[]}/>} {tab==='rules'&&<Rules rows={rules} owner={owner} month={month} done={load}/>} {tab==='adj'&&<Adjustments rows={adj} rules={rules} month={month} manage={manage} open={()=>setModal({type:'adjust'})} done={load}/>} </>}
 {modal?.type==='adjust'&&<AddAdjustment rules={rules} month={month} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}{modal?.type==='pay'&&<PayModal row={modal.row} accounts={moneyAccounts} period={period} close={()=>setModal(null)} done={async d=>{setModal(null);setPeriod(d.period);await load()}}/>}{modal?.type==='reversePay'&&<ReversePayment payment={modal.row} close={()=>setModal(null)} done={async d=>{setModal(null);setPeriod(d.period);await load()}}/>}</div>;
 async function mutate(fn){try{setBusy(true);const d=await fn();setPeriod(d);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
}
function M({label,value}){return <div className="whMetric"><small>{label}</small><b>{value}</b></div>}
function Summary({data}){return <><div className="whMetrics"><M label="ФОТ" value={money(data.totals?.salary)}/><M label="Выручка" value={money(data.totals?.revenue)}/><M label="Валовая прибыль" value={money(data.totals?.gross_profit)}/><M label="Периодов" value={data.rows?.length||0}/></div><div className="whTable">{data.rows?.length?data.rows.map(x=><div className="whRow" key={x.id}><div><b>{x.branch_name}</b><small>{String(x.period_month).slice(0,7)}</small></div><span>{statusLabel[x.status]||x.status}</span><b>{money(x.totals?.salary)}</b><span>выручка {money(x.totals?.revenue)}</span></div>):<div className="whEmpty">За месяц ещё нет рассчитанных периодов.</div>}</div></>}
function SelfPay({row}){if(!row)return <div className="whEmpty">За выбранный месяц утверждённого начисления ещё нет.</div>;return <><div className="whMetrics"><M label="Начислено" value={money(row.total)}/><M label="Выплачено" value={money(row.paid_amount)}/><M label="Осталось" value={money(row.due_amount)}/><M label="Статус" value={statusLabel[row.status]||row.status}/></div><div className="whTable"><div className="whRow"><span>Оклад</span><b>{money(row.base_salary)}</b><span>Заказы</span><b>{money(row.order_commission)}</b></div><div className="whRow"><span>Работы</span><b>{money(row.work_commission)}</b><span>Валовая прибыль</span><b>{money(row.gross_profit_commission)}</b></div><div className="whRow"><span>KPI</span><b>{money(row.kpi_bonus)}</b><span>Корректировки</span><b>{money(row.adjustments)}</b></div></div></>}
function Report({rows}){return <div className="whTable"><div className="whMoveHead"><span>Сотрудник</span><span>Роль</span><span>Заказы</span><span>Выручка / работы</span><span>Начисления</span><span>Итого</span></div>{rows.map(x=><div className="whMoveRow" key={x.id}><div><b>{x.name}</b><small>{x.email}</small></div><span>{roleName(x.role)}</span><b>{x.jobs}</b><div><b>{money(x.revenue)}</b><small>работы {money(x.work_sales)}</small></div><div><b>{money(Number(x.order_commission)+Number(x.work_commission)+Number(x.gross_profit_commission))}</b><small>KPI {money(x.kpi_bonus)} · коррект. {money(x.adjustments)}</small></div><b>{money(x.salary)}</b></div>)}</div>}
function Periods({month,branchId,periods,period,select,manage,owner,accounts,calculate,approve,closePeriod,pay,reverse}){const reversed=new Set((period?.payments||[]).filter(x=>x.kind==='REVERSAL').map(x=>Number(x.reversal_of)));return <><div className="whTop"><div><h2>Расчётный период</h2><small>{month} · ревизии не переписываются</small></div><div className="whTopActions">{manage&&(!period||['DRAFT','CALCULATED'].includes(period.status))&&<button className="whPrimary" onClick={calculate}><Calculator size={16}/>Рассчитать</button>}{owner&&period?.status==='CALCULATED'&&<button className="whPrimary" onClick={approve}><CheckCircle2 size={16}/>Утвердить</button>}{owner&&period?.status==='PAID'&&<button className="whPrimary" onClick={closePeriod}><LockKeyhole size={16}/>Закрыть месяц</button>}</div></div>{periods.length>1&&<div className="whTabs">{periods.map(p=><button className={Number(period?.id)===Number(p.id)?'on':''} key={p.id} onClick={()=>select(p.id)}>{p.branch_name} · {statusLabel[p.status]||p.status}</button>)}</div>}{!period?<div className="whEmpty">Период ещё не рассчитывался. Нажмите «Рассчитать».</div>:<><div className="whMetrics"><M label="Статус" value={statusLabel[period.status]||period.status}/><M label="Ревизия" value={'№ '+period.calculation_revision}/><M label="Начислено к выплате" value={money(period.payment_totals?.due)}/><M label="Осталось выплатить" value={money(period.payment_totals?.remaining)}/></div><div className="whTable"><div className="whMoveHead"><span>Сотрудник</span><span>Роль</span><span>Начислено</span><span>Выплачено</span><span>Остаток</span><span>Действие</span></div>{period.accruals?.map(x=><div className="whMoveRow" key={x.user_id}><div><b>{x.name}</b><small>KPI {money(x.kpi_bonus)}</small></div><span>{roleName(x.role)}</span><b>{money(x.total)}</b><span>{money(x.paid_amount)}</span><b>{money(x.due_amount)}</b><div>{manage&&period.status!=='CLOSED'&&Number(x.due_amount)>0&&<button onClick={()=>pay(x)}><WalletCards size={15}/> Выплатить</button>}</div></div>)}</div><h3>Документы выплат</h3><div className="whTable">{period.payments?.length?period.payments.map(p=><div className="whRow" key={p.id}><div><b>{p.user_name}</b><small>{p.document_reference} · {p.account_name}</small></div><span>{p.kind==='REVERSAL'?'СТОРНО':'Выплата'}</span><b>{money(p.kind==='REVERSAL'?-Number(p.amount):p.amount)}</b><span>{String(p.occurred_at||'').slice(0,10)}</span><div>{manage&&p.kind==='PAYMENT'&&!reversed.has(Number(p.id))&&period.status!=='CLOSED'&&<button onClick={()=>reverse(p)}><RotateCcw size={15}/> Сторно</button>}</div></div>):<div className="whEmpty">Выплат пока нет.</div>}</div></>}</>}
function Rules({rows,owner,month,done}){const[edit,setEdit]=useState({});async function save(x){const v=edit[x.user_id]||x;const reason=prompt('Причина новой версии правила','Изменение условий оплаты');if(!reason)return;await c('/rules/'+x.user_id,{method:'PUT',body:JSON.stringify({month,base_salary:+v.base_salary||0,order_percent:+v.order_percent||0,work_percent:+v.work_percent||0,gross_profit_percent:+v.gross_profit_percent||0,active:v.rule_active!==false,reason})});setEdit({});done()}return <div className="whTable"><div className="whHead"><span>Сотрудник</span><span>Оклад</span><span>% заказ</span><span>% работы</span><span>% вал. прибыли</span></div>{rows.map(x=>{const v=edit[x.user_id]||x;return <div className="whRow" key={x.user_id}><div><b>{x.name}</b><small>{roleName(x.role)} · с {x.effective_from?String(x.effective_from).slice(0,10):'—'}</small></div><input disabled={!owner} type="number" value={v.base_salary??0} onChange={e=>setEdit({...edit,[x.user_id]:{...v,base_salary:e.target.value}})}/><input disabled={!owner} type="number" step="0.1" value={v.order_percent??0} onChange={e=>setEdit({...edit,[x.user_id]:{...v,order_percent:e.target.value}})}/><input disabled={!owner} type="number" step="0.1" value={v.work_percent??0} onChange={e=>setEdit({...edit,[x.user_id]:{...v,work_percent:e.target.value}})}/><div style={{display:'flex',gap:8}}><input disabled={!owner} type="number" step="0.1" value={v.gross_profit_percent??0} onChange={e=>setEdit({...edit,[x.user_id]:{...v,gross_profit_percent:e.target.value}})}/>{owner&&<button onClick={()=>save(x)}>Новая версия</button>}</div></div>})}</div>}
function Adjustments({rows,rules,month,manage,open,done}){return <><div className="whTop"><div><h2>Премии, штрафы и корректировки</h2><small>Проведённые документы не удаляются — только сторно.</small></div>{manage&&<button className="whPrimary" onClick={open}><Plus size={16}/>Добавить</button>}</div><div className="whTable">{rows.length?rows.map(x=><div className="whRow" key={x.id}><div><b>{x.user_name}</b><small>{x.reason}</small></div><span>{x.reversal_of?'СТОРНО':x.type}</span><b>{money(x.amount)}</b><span>{x.created_by_name||'—'}</span><div>{manage&&!x.reversal_of&&!x.reversed_by_name&&<button onClick={async()=>{const reason=prompt('Причина сторно');if(!reason)return;await c('/adjustments/'+x.id+'/reverse',{method:'POST',body:JSON.stringify({reason})});done()}}><RotateCcw size={15}/> Сторно</button>}</div></div>):<div className="whEmpty">Корректировок за месяц нет</div>}</div></>}
function AddAdjustment({rules,month,close,done}){const[f,setF]=useState({user_id:'',type:'BONUS',amount:'',reason:'',month}),[e,setE]=useState('');async function save(){try{await c('/adjustments',{method:'POST',body:JSON.stringify(f)});done()}catch(x){setE(x.message)}}return <Modal title="Корректировка зарплаты" close={close} error={e}><label>Сотрудник<select value={f.user_id} onChange={x=>setF({...f,user_id:+x.target.value})}><option value="">Выберите</option>{rules.filter(x=>x.active!==false).map(x=><option key={x.user_id} value={x.user_id}>{x.name} · {roleName(x.role)}</option>)}</select></label><label>Тип<select value={f.type} onChange={x=>setF({...f,type:x.target.value})}><option value="BONUS">Премия</option><option value="PENALTY">Штраф</option><option value="OTHER">Другое</option></select></label><label>Сумма<input type="number" min="0.01" step="0.01" value={f.amount} onChange={x=>setF({...f,amount:x.target.value})}/></label><label>Причина<textarea value={f.reason} onChange={x=>setF({...f,reason:x.target.value})}/></label><Buttons close={close} save={save}/></Modal>}
function PayModal({row,accounts,period,close,done}){const[f,setF]=useState({user_id:row.user_id,account_id:accounts[0]?.id||'',amount:row.due_amount,document_reference:'',occurred_at:new Date().toISOString().slice(0,10)}),[e,setE]=useState('');async function save(){try{done(await c(`/periods/${period.id}/payments`,{method:'POST',body:JSON.stringify(f)}))}catch(x){setE(x.message)}}return <Modal title={`Выплата — ${row.name}`} close={close} error={e}><label>К выплате<input type="number" min="0.01" step="0.01" max={row.due_amount} value={f.amount} onChange={x=>setF({...f,amount:x.target.value})}/></label><label>Счёт<select value={f.account_id} onChange={x=>setF({...f,account_id:+x.target.value})}><option value="">Выберите</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.balance)}</option>)}</select></label><label>Дата<input type="date" value={f.occurred_at} onChange={x=>setF({...f,occurred_at:x.target.value})}/></label><label>Документ<input value={f.document_reference} onChange={x=>setF({...f,document_reference:x.target.value})} placeholder="Ведомость / перевод / РКО"/></label><Buttons close={close} save={save}/></Modal>}
function ReversePayment({payment,close,done}){const[f,setF]=useState({reason:'',document_reference:'',occurred_at:new Date().toISOString().slice(0,10)}),[e,setE]=useState('');async function save(){try{done(await c(`/payments/${payment.id}/reverse`,{method:'POST',body:JSON.stringify(f)}))}catch(x){setE(x.message)}}return <Modal title="Сторно выплаты" close={close} error={e}><p>{payment.user_name} · {money(payment.amount)}</p><label>Причина<textarea value={f.reason} onChange={x=>setF({...f,reason:x.target.value})}/></label><label>Документ<input value={f.document_reference} onChange={x=>setF({...f,document_reference:x.target.value})}/></label><label>Дата<input type="date" value={f.occurred_at} onChange={x=>setF({...f,occurred_at:x.target.value})}/></label><Buttons close={close} save={save}/></Modal>}
function Modal({title,close,error,children}){return <div className="whOverlay"><div className="whModal small"><div className="whModalHead"><h2>{title}</h2><button onClick={close}><X/></button></div>{error&&<div className="whError">{error}</div>}<div className="whForm">{children}</div></div></div>}
function Buttons({close,save}){return <div className="whButtons"><button onClick={close}>Отмена</button><button className="whPrimary" onClick={save}>Провести</button></div>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);