import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Boxes,RefreshCw,X,ShoppingCart,AlertTriangle,TriangleAlert,Truck,History,CheckCircle2,Clock3,PackageSearch,WalletCards}from'lucide-react';
import'./procurement-planning.css';

const BASE='/procurement-api/v1',token=()=>localStorage.token;
const money=v=>new Intl.NumberFormat('ru-KZ',{maximumFractionDigits:0}).format(Number(v||0))+' ₸';
const qty=v=>new Intl.NumberFormat('ru-KZ',{maximumFractionDigits:3}).format(Number(v||0));
const date=v=>v?new Date(v).toLocaleDateString('ru-RU'):'—';
const dt=v=>v?new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
async function api(path,opt={}){const r=await fetch(BASE+path,{...opt,headers:{Authorization:`Bearer ${token()}`,...(opt.body!=null?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(j.error?.message||`Ошибка ${r.status}`);e.code=j.error?.code;e.details=j.error?.details;throw e}return j.data}
const priority={CRITICAL:'Критично',HIGH:'Высокий',MEDIUM:'Средний',NORMAL:'Норма'};

function App(){
 const[open,setOpen]=useState(false),[tab,setTab]=useState('plan'),[data,setData]=useState({summary:{},rows:[],attention_orders:[]}),[batches,setBatches]=useState([]),[selected,setSelected]=useState(new Set()),[quantities,setQuantities]=useState({}),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[notice,setNotice]=useState('');
 const user=(()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}})(),rbac=window.Profi24RBAC,P=rbac?.P||{},view=Boolean(P.PROCUREMENT_VIEW&&rbac?.can?.(P.PROCUREMENT_VIEW,user?.role)),manage=Boolean(P.PROCUREMENT_MANAGE&&rbac?.can?.(P.PROCUREMENT_MANAGE,user?.role));
 async function load(){if(!view)return;try{setBusy(true);setErr('');const[d,h]=await Promise.all([api('/replenishment'),api('/replenishment/batches?limit=30').catch(()=>[])]);setData(d||{summary:{},rows:[],attention_orders:[]});setBatches(h||[]);setSelected(prev=>new Set([...prev].filter(id=>(d?.rows||[]).some(x=>Number(x.id)===Number(id)&&x.best_supplier_id))));setQuantities(prev=>{const next={...prev};for(const row of d?.rows||[])if(next[row.id]==null)next[row.id]=Number(row.recommended_quantity||0);return next})}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open)load()},[open,view]);
 useEffect(()=>{if(!view)return;const register=()=>window.Profi24UI?.registerNav({id:'procurement-planning',label:'План закупок',group:'stock',permission:P.PROCUREMENT_VIEW,badge:(data.summary?.critical||data.summary?.positions)||null,onClick:()=>setOpen(true)});if(window.Profi24UI)register();else window.addEventListener('profi24:core-ui-ready',register,{once:true});return()=>{window.removeEventListener('profi24:core-ui-ready',register);window.Profi24UI?.removeNav?.('procurement-planning')}},[view]);
 useEffect(()=>{window.Profi24UI?.updateNav?.('procurement-planning',{badge:(data.summary?.critical||data.summary?.positions)||null})},[data.summary?.critical,data.summary?.positions]);
 const selectedRows=useMemo(()=>data.rows.filter(x=>selected.has(Number(x.id))),[data.rows,selected]);
 const selectedValue=selectedRows.reduce((s,x)=>s+Number(quantities[x.id]||0)*Number(x.best_unit_cost||0),0);
 function toggle(row){if(!row.best_supplier_id)return;setSelected(old=>{const next=new Set(old);const id=Number(row.id);next.has(id)?next.delete(id):next.add(id);return next})}
 function selectReady(){setSelected(new Set(data.rows.filter(x=>x.best_supplier_id&&Number(x.recommended_quantity)>0).map(x=>Number(x.id))))}
 async function order(){if(!selectedRows.length)return;const items=selectedRows.map(x=>({item_id:Number(x.id),quantity:Number(quantities[x.id]||x.recommended_quantity),supplier_id:Number(x.best_supplier_id)}));if(items.some(x=>!Number.isFinite(x.quantity)||x.quantity<=0)){setErr('Количество к заказу должно быть больше нуля');return}if(!window.confirm(`Создать заказы поставщикам по ${items.length} позициям на ориентировочную сумму ${money(selectedValue)}?`))return;try{setBusy(true);setErr('');setNotice('');const idempotency=globalThis.crypto?.randomUUID?.()||`rpl-${Date.now()}-${Math.random().toString(36).slice(2)}`;const batch=await api('/replenishment/orders',{method:'POST',body:JSON.stringify({idempotency_key:idempotency,items})});setNotice(`План ${batch.number} проведён. Создано заказов поставщикам: ${new Set((batch.lines||[]).map(x=>x.purchase_order_id)).size}.`);setSelected(new Set());setQuantities({});await load();setTab('history')}catch(e){setErr(e.message)}finally{setBusy(false)}}
 if(!view||!open)return null;
 const s=data.summary||{},attention=data.attention_orders||[];
 return <div className="ppScreen"><header className="ppTop"><div><h1><Boxes size={24}/> План закупок</h1><p>Автопополнение склада с учётом сервисных заказов, резервов и уже заказанных деталей</p></div><div className="ppActions"><button onClick={load} disabled={busy}><RefreshCw size={17}/> Обновить</button><button onClick={()=>setOpen(false)}><X size={19}/></button></div></header>{err&&<div className="ppError"><AlertTriangle size={16}/>{err}</div>}{notice&&<div className="ppNotice"><CheckCircle2 size={16}/>{notice}</div>}{!manage&&<div className="ppReadonly">Режим контроля: ваша роль может видеть потребность и историю, но не создавать заказы поставщикам.</div>}<div className="ppMetrics"><Metric icon={<PackageSearch/>} label="К заказу" value={s.positions||0}/><Metric icon={<TriangleAlert/>} label="Критично для ремонта" value={s.critical||0} hot={s.critical>0}/><Metric icon={<Boxes/>} label="Рекомендовано, ед." value={qty(s.recommended_units||0)}/><Metric icon={<WalletCards/>} label="Оценка закупки" value={money(s.estimated_value||0)}/><Metric icon={<AlertTriangle/>} label="Без поставщика" value={s.missing_supplier||0} hot={s.missing_supplier>0}/><Metric icon={<Clock3/>} label="Просрочено PO" value={s.overdue_orders||0} hot={s.overdue_orders>0}/></div><div className="ppTabs"><button className={tab==='plan'?'on':''} onClick={()=>setTab('plan')}><ShoppingCart/>Потребность <b>{s.positions||0}</b></button><button className={tab==='attention'?'on':''} onClick={()=>setTab('attention')}><Truck/>Контроль поставок <b>{attention.filter(x=>x.overdue||x.stale_without_eta).length}</b></button><button className={tab==='history'?'on':''} onClick={()=>setTab('history')}><History/>История планов <b>{batches.length}</b></button></div>{tab==='plan'&&<Plan rows={data.rows||[]} manage={manage} selected={selected} quantities={quantities} setQuantities={setQuantities} toggle={toggle} selectReady={selectReady} order={order} selectedValue={selectedValue} busy={busy}/>} {tab==='attention'&&<Attention rows={attention}/>} {tab==='history'&&<HistoryList rows={batches}/>}</div>
}
function Metric({icon,label,value,hot}){return <div className={'ppMetric '+(hot?'hot':'')}><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>}
function Plan({rows,manage,selected,quantities,setQuantities,toggle,selectReady,order,selectedValue,busy}){return <section className="ppCard"><div className="ppCardTop"><div><h2>Что нужно заказать сейчас</h2><p>Сервер пересчитает потребность ещё раз непосредственно перед созданием заказов.</p></div>{manage&&<div className="ppBulk"><button onClick={selectReady}>Выбрать все с поставщиком</button><button className="primary" disabled={!selected.size||busy} onClick={order}><ShoppingCart size={16}/> Создать PO · {money(selectedValue)}</button></div>}</div><div className="ppTable"><div className="ppHead"><span></span><span>Запчасть / филиал</span><span>Склад</span><span>Потребность</span><span>Уже заказано</span><span>Рекомендация</span><span>Поставщик</span><span>К заказу</span></div>{rows.map(row=><div className={'ppRow '+row.priority} key={row.id}><div>{manage?<input aria-label={'Выбрать '+row.name} type="checkbox" checked={selected.has(Number(row.id))} disabled={!row.best_supplier_id} onChange={()=>toggle(row)}/>:<span className="ppDot"/>}</div><div><b>{row.name}</b><small>{row.branch_name} · {[row.sku&&`SKU ${row.sku}`,row.oem_code&&`OEM ${row.oem_code}`].filter(Boolean).join(' · ')||'без артикула'}</small><em className={'ppPriority '+row.priority}>{priority[row.priority]||row.priority}</em></div><div><b>{qty(row.stock_quantity)}</b><small>свободно {qty(row.free_quantity)} · мин. {qty(row.min_quantity)}</small><small>{row.days_cover==null?'нет истории расхода':`покрытие ≈ ${Math.round(row.days_cover)} дн.`}</small></div><div><b>{qty(row.service_demand_quantity)}</b><small>сервис · резерв {qty(row.reserved_quantity)}</small><small>расход 30/90д: {qty(row.consumption_30d)}/{qty(row.consumption_90d)}</small></div><div><b>{qty(row.pending_order_quantity)}</b><small>в открытых PO</small></div><div><b>{qty(row.recommended_quantity)}</b><small>{money(row.estimated_value)}</small></div><div>{row.best_supplier_id?<><b>{row.best_supplier_name}</b><small>{money(row.best_unit_cost)}{row.lead_time_days!=null?` · ${row.lead_time_days} дн.`:''}</small><small>{row.supplier_available_qty==null?'остаток поставщика неизвестен':`у поставщика ${qty(row.supplier_available_qty)}`}</small></>:<><b className="ppMissing">Не назначен</b><small>Свяжите позицию с прайсом или поставщиком</small></>}</div><div>{manage&&row.best_supplier_id?<input aria-label={'К заказу '+row.name} type="number" min="0.001" step="0.001" max={row.recommended_quantity} value={quantities[row.id]??row.recommended_quantity} onChange={e=>setQuantities(x=>({...x,[row.id]:e.target.value}))}/>:<b>—</b>}</div></div>)}{!rows.length&&<div className="ppEmpty"><CheckCircle2 size={34}/><b>Текущая потребность закрыта</b><span>Минимальные остатки, резервы и сервисные заказы уже обеспечены складом или открытыми PO.</span></div>}</div></section>}
function Attention({rows}){return <section className="ppCard"><div className="ppCardTop"><div><h2>Контроль заказов поставщикам</h2><p>Просроченные поставки и PO без ожидаемой даты.</p></div></div><div className="ppAttention">{rows.map(x=><div key={x.id} className={'ppAttentionRow '+(x.overdue?'overdue':x.stale_without_eta?'stale':'')}><div><b>{x.number}</b><small>{x.branch_name} · {x.supplier_name}</small></div><div><b>{x.status}</b><small>{x.expected_at?`Ожидалось ${date(x.expected_at)}`:'Дата поставки не указана'}</small></div><div><b>{qty(x.remaining_qty)} ед.</b><small>{money(x.remaining_value)}</small></div><div>{x.overdue?<strong>Просрочено {x.overdue_days} дн.</strong>:x.stale_without_eta?<strong>Без ETA · {x.age_days} дн.</strong>:<span>В срок</span>}</div></div>)}{!rows.length&&<div className="ppEmpty">Открытых заказов поставщикам нет</div>}</div></section>}
function HistoryList({rows}){return <section className="ppCard"><div className="ppCardTop"><div><h2>Проведённые планы</h2><p>Неизменяемый аудит автоматического формирования заказов поставщикам.</p></div></div><div className="ppHistory">{rows.map(x=><div className="ppHistoryRow" key={x.id}><div><b>{x.number}</b><small>{dt(x.created_at)} · {x.created_by_name}</small></div><div><b>{x.lines_count} поз.</b><small>{x.orders_count||0} заказов поставщикам</small></div><strong>{money(x.total_value)}</strong><span className="ppPosted">Проведён</span></div>)}{!rows.length&&<div className="ppEmpty">Проведённых планов пока нет</div>}</div></section>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
