import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{CalendarClock,RefreshCw,X,Plus,FileText,Wrench,CheckCircle2,SkipForward,ExternalLink}from'lucide-react';
import'./service-contracts.css';
const BASE='/communications-api/v1/service-contracts',tok=()=>localStorage.token;
async function call(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${tok()}`,...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'Ошибка запроса');return j.data}
const api=(p='',o)=>call(BASE+p,o),core=(p,o)=>call('/api/v1'+p,o),branch=(p,o)=>call('/branch-api/v1'+p,o);
const user=()=>{try{return JSON.parse(localStorage.user||'null')}catch{return null}};
const d=v=>v?new Date(String(v).slice(0,10)+'T12:00:00Z').toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}):'—';
const today=()=>new Date().toISOString().slice(0,10);
const statusLabel={ACTIVE:'Активен',PAUSED:'Приостановлен',CLOSED:'Закрыт',DUE:'Ожидает ТО',PLANNED:'Заказ создан',COMPLETED:'Выполнено',SKIPPED:'Пропущено'};
function Metric({title,value,bad}){return <div className={'scMetric '+(bad?'bad':'')}><small>{title}</small><b>{value??0}</b></div>}
function App(){const u=user(),P=window.Profi24RBAC?.P||{},permission=P.OPERATIONS_MANAGE,allowed=Boolean(permission&&window.Profi24RBAC?.can?.(permission,u?.role));const[open,setOpen]=useState(false),[summary,setSummary]=useState({}),[contracts,setContracts]=useState([]),[detail,setDetail]=useState(null),[customers,setCustomers]=useState([]),[equipment,setEquipment]=useState([]),[branches,setBranches]=useState([]),[orders,setOrders]=useState([]),[status,setStatus]=useState('ACTIVE'),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[err,setErr]=useState('');const[form,setForm]=useState({customer_id:'',branch_id:'',start_date:today(),reminder_days_before:7,equipment_id:'',interval_months:6,next_service_date:today(),notes:''});
 async function load(keepDetail=true){try{setBusy(true);setErr('');const qs=status?`?status=${status}`:'';const[s,c,cu,eq,br,o]=await Promise.all([api('/summary'),api(qs),core('/customers'),core('/equipment'),branch('/branches'),core('/requests')]);setSummary(s||{});setContracts(c||[]);setCustomers(cu||[]);setEquipment(eq||[]);setBranches(br||[]);setOrders(o||[]);if(!form.branch_id&&br?.[0])setForm(x=>({...x,branch_id:String(br[0].id)}));if(keepDetail&&detail?.id){const fresh=await api('/'+detail.id);setDetail(fresh)}else if(!keepDetail)setDetail(null)}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(open&&allowed)load()},[open,allowed,status]);useEffect(()=>{if(!allowed)return;const register=()=>window.Profi24UI?.registerNav({id:'service-contracts',label:'Сервисные договоры',group:'operations',permission,onClick:()=>setOpen(true)});if(window.Profi24UI)register();else window.addEventListener('profi24:core-ui-ready',register,{once:true});return()=>{window.removeEventListener('profi24:core-ui-ready',register);window.Profi24UI?.removeNav?.('service-contracts')}},[allowed,u?.role,permission]);
 const customerEquipment=useMemo(()=>equipment.filter(x=>Number(x.customer_id)===Number(form.customer_id)),[equipment,form.customer_id]);const orderMap=useMemo(()=>Object.fromEntries(orders.map(x=>[Number(x.id),x])),[orders]);
 async function openContract(id){try{setBusy(true);setDetail(await api('/'+id))}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function createContract(e){e.preventDefault();try{setBusy(true);setErr('');const body={customer_id:Number(form.customer_id),branch_id:Number(form.branch_id),start_date:form.start_date,reminder_days_before:Number(form.reminder_days_before),notes:form.notes||null,assets:[{equipment_id:Number(form.equipment_id),interval_months:Number(form.interval_months),next_service_date:form.next_service_date}]};const sc=await api('',{method:'POST',body:JSON.stringify(body)});setCreating(false);await load(false);await openContract(sc.id)}catch(e2){setErr(e2.message)}finally{setBusy(false)}}
 async function sync(){try{setBusy(true);setErr('');await api('/sync',{method:'POST',body:'{}'});await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function createMaintenanceOrder(asset){try{setBusy(true);setErr('');const complaint=`Плановое техническое обслуживание по договору ${detail.number}: ${[asset.category,asset.brand,asset.model].filter(Boolean).join(' ')}`;const order=await core('/requests',{method:'POST',body:JSON.stringify({customer_id:Number(detail.customer_id),equipment_id:Number(asset.equipment_id),branch_id:Number(detail.branch_id),complaint,source:'OTHER'})});await api(`/cycles/${asset.cycle_id}/plan`,{method:'POST',body:JSON.stringify({request_id:Number(order.id)})});await load();window.dispatchEvent(new CustomEvent('profi24:orders-changed'));}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function complete(asset){try{setBusy(true);setErr('');await api(`/cycles/${asset.cycle_id}/complete`,{method:'POST',body:JSON.stringify({note:'ТО выполнено по связанному закрытому заказу'})});await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function skip(asset){const reason=window.prompt('Укажите причину пропуска планового ТО');if(!reason)return;try{setBusy(true);setErr('');await api(`/cycles/${asset.cycle_id}/skip`,{method:'POST',body:JSON.stringify({reason})});await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 if(!allowed||!open)return null;return <div className="scScreen"><header className="scTop"><div><h1>Сервисные договоры и плановое ТО</h1><p>Контроль регулярного обслуживания оборудования без пропущенных сроков</p></div><div className="scActions"><button onClick={sync} disabled={busy}><RefreshCw size={16}/> Синхронизировать</button><button className="primary" onClick={()=>setCreating(true)}><Plus size={16}/> Новый договор</button><button onClick={()=>setOpen(false)}><X size={19}/></button></div></header>{err&&<div className="scError">{err}</div>}<section className="scMetrics"><Metric title="Активные договоры" value={summary.active_contracts}/><Metric title="Просрочено ТО" value={summary.overdue} bad={summary.overdue>0}/><Metric title="На 7 дней" value={summary.due_7}/><Metric title="На 30 дней" value={summary.due_30}/><Metric title="Заказы ТО" value={summary.planned}/></section><div className="scToolbar"><label>Статус<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Активные</option><option value="PAUSED">Приостановленные</option><option value="CLOSED">Закрытые</option><option value="">Все</option></select></label><span>Менеджер получает задачу заранее, клиент — напоминание через очередь коммуникаций.</span></div><main className="scLayout"><section className="scList"><h2>Договоры</h2>{contracts.map(x=><button key={x.id} className={'scContract '+(detail?.id===x.id?'on':'')} onClick={()=>openContract(x.id)}><div><b>{x.number}</b><span>{x.customer_name}</span></div><div className="scContractMeta"><span className={'tag '+x.status}>{statusLabel[x.status]||x.status}</span><small>{x.assets_count} ед. · следующее ТО {d(x.next_service_date)}</small>{x.overdue_count>0&&<strong>Просрочено: {x.overdue_count}</strong>}</div></button>)}{!contracts.length&&<div className="scEmpty">Договоров с таким статусом пока нет</div>}</section><section className="scDetail">{detail?<ContractDetail detail={detail} orderMap={orderMap} busy={busy} createOrder={createMaintenanceOrder} complete={complete} skip={skip}/>:<div className="scEmpty big"><CalendarClock size={36}/><b>Выберите договор</b><span>Здесь будут техника, график ТО и действия менеджера.</span></div>}</section></main>{creating&&<CreateModal form={form} setForm={setForm} customers={customers} branches={branches} customerEquipment={customerEquipment} busy={busy} close={()=>setCreating(false)} submit={createContract}/>}</div>}
function ContractDetail({detail,orderMap,busy,createOrder,complete,skip}){return <><div className="scDetailHead"><div><FileText size={19}/><div><h2>{detail.number}</h2><p>{detail.customer_name} · {detail.branch_name}</p></div></div><span className={'tag '+detail.status}>{statusLabel[detail.status]||detail.status}</span></div><div className="scInfo"><div><small>Ответственный</small><b>{detail.responsible_name||'Не назначен'}</b></div><div><small>Период договора</small><b>{d(detail.start_date)} — {d(detail.end_date)||'без срока'}</b></div><div><small>Напоминание</small><b>за {detail.reminder_days_before} дн.</b></div></div>{detail.notes&&<div className="scNote">{detail.notes}</div>}<h3>Оборудование и ближайшее ТО</h3><div className="scAssets">{detail.assets.map(a=>{const order=orderMap[Number(a.request_id)],closed=order?.status==='CLOSED';return <article key={a.id} className="scAsset"><div className="scAssetTitle"><Wrench size={18}/><div><b>{[a.category,a.brand,a.model].filter(Boolean).join(' ')}</b><small>{a.serial_number?`S/N ${a.serial_number} · `:''}каждые {a.interval_months} мес.</small></div><span className={'tag '+a.cycle_status}>{statusLabel[a.cycle_status]||a.cycle_status||'—'}</span></div><div className="scDates"><span><small>Следующее ТО</small><b>{d(a.next_service_date)}</b></span><span><small>Последнее ТО</small><b>{d(a.last_service_date)}</b></span></div>{a.request_id&&<div className="scLinked"><ExternalLink size={14}/><span>Связанный заказ: <b>{order?.number||'#'+a.request_id}</b> · {order?.status||'статус загружается'}</span></div>}<div className="scAssetActions">{a.cycle_status==='DUE'&&<button className="primary" disabled={busy} onClick={()=>createOrder(a)}>Создать заказ ТО</button>}{a.cycle_status==='PLANNED'&&closed&&<button className="success" disabled={busy} onClick={()=>complete(a)}><CheckCircle2 size={15}/> Зафиксировать ТО</button>}{a.cycle_status==='PLANNED'&&!closed&&<span className="scHint">Завершите связанный заказ, затем зафиксируйте ТО.</span>}{['DUE','PLANNED'].includes(a.cycle_status)&&<button disabled={busy} onClick={()=>skip(a)}><SkipForward size={15}/> Пропустить</button>}</div></article>})}</div><details className="scAudit"><summary>Журнал изменений ({detail.audit?.length||0})</summary>{(detail.audit||[]).map(x=><div key={x.id}><b>{x.action}</b><span>{x.user_name||'Система'} · {new Date(x.created_at).toLocaleString('ru-RU')}</span></div>)}</details></>}
function CreateModal({form,setForm,customers,branches,customerEquipment,busy,close,submit}){return <div className="scModal"><form onSubmit={submit}><div className="scModalHead"><div><h2>Новый сервисный договор</h2><p>Сразу добавьте первую единицу оборудования и график ТО.</p></div><button type="button" onClick={close}><X size={18}/></button></div><label>Клиент<select required value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value,equipment_id:''})}><option value="">Выберите клиента</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.phone}</option>)}</select></label><div className="scFormRow"><label>Филиал<select required value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Дата начала<input required type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value,next_service_date:e.target.value})}/></label><label>Напомнить за<input required min="0" max="90" type="number" value={form.reminder_days_before} onChange={e=>setForm({...form,reminder_days_before:e.target.value})}/></label></div><label>Оборудование<select required value={form.equipment_id} onChange={e=>setForm({...form,equipment_id:e.target.value})}><option value="">Выберите оборудование клиента</option>{customerEquipment.map(x=><option key={x.id} value={x.id}>{[x.category,x.brand,x.model,x.serial_number].filter(Boolean).join(' · ')}</option>)}</select></label><div className="scFormRow two"><label>Периодичность, мес.<input required min="1" max="60" type="number" value={form.interval_months} onChange={e=>setForm({...form,interval_months:e.target.value})}/></label><label>Первое ТО<input required type="date" value={form.next_service_date} onChange={e=>setForm({...form,next_service_date:e.target.value})}/></label></div><label>Примечание<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Например: сезонное обслуживание перед летом"/></label><div className="scModalActions"><button type="button" onClick={close}>Отмена</button><button className="primary" disabled={busy} type="submit"><Plus size={15}/> Создать договор</button></div></form></div>}
const root=document.createElement('div');document.body.appendChild(root);createRoot(root).render(<App/>);
