import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import'./visit.css';

const token=decodeURIComponent(location.pathname.split('/').filter(Boolean).at(-1)||'');
const tm=v=>v?new Date(v).toLocaleString('ru-RU',{timeZone:'Asia/Qostanay',day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'}):'—';
async function api(method='GET',body){const r=await fetch('/visit-api/v1/visit/'+encodeURIComponent(token),{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined}),j=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(j.error?.message||'Не удалось открыть подтверждение');e.status=r.status;throw e}return j.data}
function App(){const[data,setData]=useState(null),[busy,setBusy]=useState(true),[err,setErr]=useState(''),[comment,setComment]=useState(''),[done,setDone]=useState(null);useEffect(()=>{api().then(d=>{setData(d);if(d.responded)setDone({status:d.status})}).catch(e=>setErr(e.message)).finally(()=>setBusy(false))},[]);async function respond(decision){try{setBusy(true);setErr('');const d=await api('POST',{decision,comment});setDone(d)}catch(e){setErr(e.message)}finally{setBusy(false)}}if(busy&&!data)return <main className="visitPortal"><section className="visitCard"><p>Загружаем данные визита…</p></section></main>;if(err&&!data)return <main className="visitPortal"><section className="visitCard"><div className="visitBrand">PROFI24KST</div><h1>Ссылка недоступна</h1><div className="visitError">{err}</div><p>Используйте последнее сообщение сервисного центра или свяжитесь с менеджером.</p></section></main>;return <main className="visitPortal"><section className="visitCard"><div className="visitBrand">PROFI24KST</div>{done?<Done status={done.status}/>:<><small>Подтверждение визита · версия {data?.version}</small><h1>Подтвердите время инженера</h1><div className="visitOrder"><b>Заявка {data?.request_number}</b><span>{data?.equipment}</span></div><div className="visitDetails"><div><small>Инженер</small><b>{data?.engineer_name}</b></div><div><small>Плановое время</small><b>{tm(data?.scheduled_at)}</b></div></div><p>Если время подходит — подтвердите. Если нет, сообщите об этом: менеджер получит отдельную срочную задачу и свяжется с вами.</p><textarea maxLength="500" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Комментарий или удобное время, если нужен перенос (необязательно)"/>{err&&<div className="visitError">{err}</div>}<button className="visitYes" disabled={busy} onClick={()=>respond('CONFIRM')}>{busy?'Сохраняем…':'Подтвердить визит'}</button><button className="visitNo" disabled={busy} onClick={()=>respond('RESCHEDULE')}>Нужно другое время</button><p className="visitPrivacy">Ответ относится только к времени визита по этой заявке. Стоимость ремонта здесь не согласовывается.</p></>}</section></main>}
function Done({status}){return <div className="visitDone">{status==='CONFIRMED'?<><strong>Время подтверждено</strong><p>Спасибо. Сервисный центр получил подтверждение визита.</p></>:<><strong>Запрос на перенос принят</strong><p>Менеджеру создана срочная задача. С вами свяжутся для согласования нового времени.</p></>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
