// Order 360 workflow: isolated overlay anchored before the left-column cards.
const W='/workflow-api/v1';
const tok=()=>localStorage.getItem('token')||'';
const names={NEW:'Принят',ASSIGNED:'Назначен',ACCEPTED:'Принят инженером',ON_ROUTE:'В пути',DIAGNOSTICS:'Диагностика',APPROVAL_REQUIRED:'Согласование',WAITING_PART:'Ожидание детали',REPAIR:'Ремонт',TESTING:'Проверка',PAYMENT_REQUIRED:'Оплата',CLOSED:'Закрыт'};
const steps=['NEW','ASSIGNED','ACCEPTED','ON_ROUTE','DIAGNOSTICS','APPROVAL_REQUIRED','REPAIR','TESTING','PAYMENT_REQUIRED','CLOSED'];
let panel=null,currentId='',loading=false,lastData=null;
async function api(p,o={}){const headers={Authorization:`Bearer ${tok()}`,...(o.body!=null?{'Content-Type':'application/json'}:{})};const r=await fetch(W+p,{...o,headers}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error?.message||`Ошибка ${r.status}`);return j.data}
const money=v=>Number(v||0).toLocaleString('ru-KZ')+' ₸';
function stateId(){return String(window.Profi24O360State?.id||document.querySelector('.o360')?.dataset?.currentRequestId||document.querySelector('.o360List button.on')?.dataset?.id||'')}
function ensure(){if(panel&&!document.body.contains(panel))panel=null;if(!panel){panel=document.createElement('section');panel.className='wf wfOverlay';document.body.appendChild(panel)}return panel}
function leftCol(){return document.querySelector('.o360Cols>div:first-child')}
function place(){const col=leftCol(),p=ensure();if(!document.querySelector('.o360')||!col){p.style.display='none';return false}const r=col.getBoundingClientRect();p.style.display='block';p.style.left=Math.round(r.left)+'px';p.style.top=Math.round(r.top)+'px';p.style.width=Math.round(r.width)+'px';return true}
function reserve(){const col=leftCol();if(!col||!panel)return;const h=Math.ceil(panel.getBoundingClientRect().height||0);col.style.paddingTop=h?`${h+14}px`:''}
function cleanup(){const col=leftCol();if(col)col.style.paddingTop='';if(panel)panel.style.display='none'}
function renderError(msg){const p=ensure();p.innerHTML=`<header><div><span class="wfClock">◷</span><b>Жизненный цикл заказа</b></div></header><p class="wfErr">${String(msg||'Ошибка')}</p>`;place();reserve()}
function render(x){lastData=x;const p=ensure(),cur=steps.indexOf(x.status),balance=Math.max(0,Number(x.balance??(Number(x.total||0)-Number(x.paid||0)))),closeBlocked=x.next?.event==='CLOSE'&&balance>0;const track=steps.map((s,i)=>`<div class="${i<cur?'done':i===cur?'now':''}"><i>${i<cur?'✓':i+1}</i><small>${names[s]||s}</small></div>`).join('');const times=(x.events||[]).slice(-5).reverse().map(e=>`<span><b>${names[e.stage]||e.stage}</b>${new Date(e.created_at).toLocaleString('ru-RU')} · ${e.user_name||'Система'}</span>`).join('');p.innerHTML=`<header><div><span class="wfClock">◷</span><b>Жизненный цикл заказа</b></div><span>${names[x.status]||x.status}</span></header><div class="wfTrack">${track}</div>${closeBlocked?`<div class="wfBlock"><b>Заказ нельзя закрыть</b><span>Необходимо принять оплату ${money(balance)}. После полной оплаты закрытие станет доступно автоматически.</span></div>`:''}${x.next&&!closeBlocked?`<button type="button" data-wf-go>${x.next.label}<span>→</span></button>`:''}<div class="wfTimes">${times}</div>`;p.querySelector('[data-wf-go]')?.addEventListener('click',go);place();requestAnimationFrame(reserve)}
async function load(force=false){const id=stateId();if(!id||loading||!document.querySelector('.o360'))return;if(!force&&id===currentId&&lastData){place();reserve();return}currentId=id;loading=true;try{const x=await api('/requests/'+id+'/workflow');if(id!==stateId())return;render(x)}catch(e){renderError(e.message)}finally{loading=false}}
async function go(){const id=stateId(),event=lastData?.next?.event;if(!id||!event||loading)return;loading=true;const btn=panel?.querySelector('[data-wf-go]');if(btn){btn.disabled=true;btn.textContent='Сохраняю…'}try{await api('/requests/'+id+'/workflow',{method:'POST',body:JSON.stringify({event})});currentId='';lastData=null;window.dispatchEvent(new CustomEvent('profi24:request-updated',{detail:{id:Number(id)}}));await load(true)}catch(e){renderError(e.message)}finally{loading=false}}
window.addEventListener('profi24:o360-current',()=>{currentId='';lastData=null;setTimeout(()=>load(true),20)});window.addEventListener('profi24:request-updated',e=>{if(!e.detail?.id||String(e.detail.id)===stateId()){currentId='';lastData=null;setTimeout(()=>load(true),60)}});window.addEventListener('resize',()=>{place();reserve()});document.addEventListener('scroll',()=>{if(document.querySelector('.o360'))place()},true);
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!document.querySelector('.o360')){cleanup();return}place();if(!currentId)load(true)},80)}).observe(document.body,{childList:true,subtree:true});setInterval(()=>{if(document.querySelector('.o360'))load()},3000);setTimeout(()=>load(true),600);